# -*- coding: utf-8 -*-
"""Hand-authored v2-style KB for CSQA qids 1120-1169 (no answerKey)."""

CHUNK = {
    1120: [
        ("A", "typical_location", "A workplace store room commonly holds stepladders and other equipment for reaching high shelves."),
        ("B", "typical_location", "A tool shed is outdoor home storage, not where an office worker borrows a stepladder at work."),
        ("C", "typical_location", "A hardware store sells stepladders; Billy is borrowing one at work, not shopping for a new ladder."),
        ("D", "typical_location", "A construction worker's vehicle carries job-site tools, not the office supply area Billy would use."),
        ("E", "typical_location", "A library may have a ladder, but Billy's boss at work would send him to the workplace storage room."),
    ],
    1121: [
        ("A", "effect", "Colliding is a crash hazard, not a benefit ships provide when no bridge is available."),
        ("B", "used_for", "Carrying people is one function of ships, but crossing water is the key benefit without a bridge."),
        ("C", "used_for", "Ships let people and cargo cross a river when no bridge spans the water."),
        ("D", "property", "Sailors are crew members who operate ships, not the benefit ships offer travelers."),
        ("E", "effect", "Bottoming out means running aground, a mishap rather than a benefit of using ships."),
    ],
    1122: [
        ("A", "typical_location", "A preschool has a playroom where very young children begin their formal education."),
        ("B", "typical_location", "A playground is outdoors for play, not the indoor playroom where toddlers start school."),
        ("C", "typical_location", "A big house is a residence, not specifically an early-education playroom for young children."),
        ("D", "typical_location", "A building is too vague; preschools specifically combine playrooms with early education."),
        ("E", "typical_location", "Grandma's house is a home visit, not the institution where young children start education."),
    ],
    1123: [
        ("A", "typical_location", "A math book contains numerical exercises, not someone's personal contact number on paper."),
        ("B", "property", "Mathematics is a subject of study, not a place where a person's number is written down."),
        ("C", "typical_location", "An office may keep contact lists, but a phonebook is the classic paper listing of numbers."),
        ("D", "typical_location", "A lottery ticket has ticket numbers, not someone's personal phone or address number."),
        ("E", "typical_location", "A phonebook lists people's telephone numbers printed on paper for lookup."),
    ],
    1124: [
        ("A", "typical_location", "A cabinet stores items at home, not a venue where one learns about someone's academic paper."),
        ("B", "typical_location", "A conference is where researchers present and discuss papers so others can learn about them."),
        ("C", "typical_location", "A front door is an entrance, not where one goes to learn about a written paper."),
        ("D", "typical_location", "A garden is outdoor landscaping, unrelated to learning about someone's paper."),
        ("E", "typical_location", "A suitcase holds travel belongings, not a place to learn about someone's paper."),
    ],
    1125: [
        ("A", "property", "Blue describes a color of water, not how choppy rapids are characteristically judged."),
        ("B", "property", "Choppy water rapids with turbulent currents are widely considered dangerous to navigate."),
        ("C", "property", "Surface of earth is a planetary feature, not a label for rough, choppy rapids."),
        ("D", "property", "Shaky describes trembling motion, but choppy rapids are more specifically called dangerous."),
        ("E", "property", "Important describes significance, not the safety judgment applied to choppy rapids."),
    ],
    1126: [
        ("A", "property", "Without solidity a building lacks structural stability and becomes unstable."),
        ("B", "property", "Hollowness suggests empty space inside, less direct than the instability from lacking solidity."),
        ("C", "property", "Weakness is vague; a building without solidity is structurally unstable."),
        ("D", "property", "Instability means the structure cannot reliably stand firm without solidity."),
        ("E", "property", "Openness describes access or transparency, not the structural failure from lacking solidity."),
    ],
    1127: [
        ("A", "motivation", "Recreational describes how sports feel, but the instinctual drive is to compete."),
        ("B", "motivation", "Man's instinctual competitive drive likely motivated the invention of sports."),
        ("C", "property", "Good looking describes appearance, not an instinctual need behind inventing sports."),
        ("D", "motivation", "Fun is a benefit of sports, but the deeper instinctual need is to be competitive."),
        ("E", "motivation", "Violent describes aggression, too negative as the primary instinct for inventing sports."),
    ],
    1128: [
        ("A", "used_for", "An atlas contains maps that help travelers figure out the best route."),
        ("B", "typical_location", "A post office handles mail, not tools for planning a travel route."),
        ("C", "used_for", "A map is the classic tool for figuring out the best route when travelling."),
        ("D", "used_for", "Getting to a specific place is the travel goal, not the tool used to plan the route."),
        ("E", "used_for", "A phone may have navigation apps, but a map is the direct tool for route planning."),
    ],
    1129: [
        ("A", "used_for", "Providing shelter is what a tree does for animals, not what light behind it causes."),
        ("B", "effect", "A light source behind a tree causes the tree to cast a shadow on the ground ahead."),
        ("C", "effect", "Branching out describes tree growth over time, not an immediate effect of backlighting."),
        ("D", "used_for", "Blocking wind is a tree function, unrelated to placing a light source behind it."),
        ("E", "effect", "Falling down is collapse, not the expected optical effect of light behind a tree."),
    ],
    1130: [
        ("A", "used_for", "A cup holds liquids and does not typically scratch a plate during a meal."),
        ("B", "used_for", "A spoon has a rounded bowl that slides on plates rather than scratching them."),
        ("C", "used_for", "A fork's tines scrape and scratch plate surfaces when a child misuses it."),
        ("D", "typical_location", "A saucer sits beneath a cup, not the utensil used to scratch a plate."),
        ("E", "typical_location", "A bowl is a separate serving dish, not what the child dragged across the plate."),
    ],
    1131: [
        ("A", "typical_location", "The internet delivers news and current events that people both read and watch online."),
        ("B", "typical_location", "Television broadcasts current events that viewers both hear and see in news programs."),
        ("C", "typical_location", "A newspaper reports current events in print, but you read rather than hear it."),
        ("D", "typical_location", "A book covers topics in depth but is not a timely source of current events."),
        ("E", "typical_location", "Radio broadcasts current events that listeners hear but cannot see."),
    ],
    1132: [
        ("A", "used_for", "Making tape records audio, not the teacher's main classroom role for student learning."),
        ("B", "used_for", "Memorizing is one step, but the teacher's main job is helping students learn new skills."),
        ("C", "effect", "Never forgetting is an ideal outcome, not the teacher's primary classroom activity."),
        ("D", "has_prerequisite", "Concentrating aids learning, but the teacher's main role is helping students learn."),
        ("E", "primary_function", "A teacher's main classroom job is helping students learn and commit skills to memory."),
    ],
    1133: [
        ("A", "effect", "Contemplating a concept can lead to revelations that deepen one's understanding."),
        ("B", "effect", "Contemplation may inspire action, but revelations are a direct cognitive outcome of deep thought."),
        ("C", "effect", "Understanding grows from contemplation, but revelations are the striking insight that can emerge."),
        ("D", "effect", "Discovery can follow contemplation, but revelations specifically describe sudden insight."),
        ("E", "effect", "Wisdom develops over time; revelations are the immediate insights contemplation can produce."),
    ],
    1134: [
        ("A", "effect", "Singing may accompany guitar playing but is not what playing guitar directly causes."),
        ("B", "used_for", "Listening to music is passive enjoyment, not an action caused by playing guitar."),
        ("C", "effect", "Arthritis is a medical condition, not a direct result of playing guitar."),
        ("D", "effect", "Playing guitar directly causes a person to make music with the instrument."),
        ("E", "used_for", "Writing a song is a creative follow-up, but playing guitar directly produces music."),
    ],
    1135: [
        ("A", "typical_location", "The realtor had to disclose that the former tenant used the houses to shoot pornography in them."),
        ("B", "typical_location", "A park is outdoor recreation, not what a tenant would shoot inside rented houses."),
        ("C", "property", "Very large is a size description, not what the former tenant shot inside the houses."),
        ("D", "typical_location", "A foundation is structural support, not something a tenant shoots inside houses."),
        ("E", "typical_location", "Walls are part of the house structure, not what the tenant used them to shoot."),
    ],
    1136: [
        ("A", "typical_location", "A phone book lists many contacts, not lodging options with only a few places to stay."),
        ("B", "typical_location", "A small town has only a few hotels or inns, offering limited places to stay."),
        ("C", "typical_location", "Mexico is a large country with many lodging options, not just a few places to stay."),
        ("D", "typical_location", "A holiday is a time period, not a location with limited lodging."),
        ("E", "typical_location", "A city typically has many hotels, far more than only a few places to stay."),
    ],
    1137: [
        ("A", "typical_location", "Finding a bone wrapped in cloth suggests you are at a tomb or burial site."),
        ("B", "typical_location", "A museum may display bones, but cloth-wrapped bones suggest a tomb discovery."),
        ("C", "part_whole", "An arm is a body part that contains bones, not where you find a wrapped bone artifact."),
        ("D", "part_whole", "The human body contains bones internally, not wrapped in cloth as a found object."),
        ("E", "typical_location", "A hospital treats patients but is not where one typically finds a cloth-wrapped bone."),
    ],
    1138: [
        ("A", "effect", "Boredom may occur while waiting in line, but locking knees causes a physical problem."),
        ("B", "property", "Order describes sequence in a line, not a bodily effect of locked knees."),
        ("C", "property", "Main is not a physical condition caused by locking your knees while standing."),
        ("D", "effect", "Locking your knees while standing in line restricts blood flow and can cause fainting."),
        ("E", "effect", "Agitation is restlessness, less specific than fainting from locked knees while standing."),
    ],
    1139: [
        ("A", "typical_location", "A cooking pot is kitchenware, not a shore location where live crabs are found."),
        ("B", "typical_location", "Beach sand may have crabs, but tidepools near shore are prime spots to look for them."),
        ("C", "typical_location", "Tidepools near the shore trap seawater where crabs are commonly found on vacation."),
        ("D", "typical_location", "Chesapeake Bay is a specific region, but tidepools are the classic shore crab-hunting spot."),
        ("E", "typical_location", "A fish market sells seafood already caught, not where you hunt for live crabs."),
    ],
    1140: [
        ("A", "typical_location", "A sporting event is athletic competition, not what a trade show spectator watches."),
        ("B", "typical_location", "Racing is a sport, not the product displays a trade show spectator observes."),
        ("C", "typical_location", "A trade show spectator typically watches product demonstrations at exhibitor booths."),
        ("D", "typical_location", "A show is generic; trade show spectators specifically watch product demonstrations."),
        ("E", "used_for", "Watch event describes the act of viewing, not the type of content at a trade show."),
    ],
    1141: [
        ("A", "typical_location", "Afternoon is before evening, not when party animals finish drinking that started at night."),
        ("B", "typical_location", "Dusk is early evening, before the drinking that started in the evening would end."),
        ("C", "typical_location", "Daytime is when the sun is up, not when late-night drinkers finally stop."),
        ("D", "typical_location", "Night covers the drinking period but dawn is when all-night partiers finally finish."),
        ("E", "typical_location", "Dawn marks early morning when party animals who started drinking in the evening finally stop."),
    ],
    1142: [
        ("A", "effect", "Restlessness is agitation, not what eye drops clear after getting up early."),
        ("B", "property", "Starting early describes her new habit, not a physical condition needing eye drops."),
        ("C", "effect", "Tiredness is fatigue, but bloodshot eyes specifically need drops after early rising."),
        ("D", "effect", "Feeling tired is general fatigue; eye drops target bloodshot eyes from lack of sleep."),
        ("E", "effect", "Bloodshot eyes from getting up early are what she needed eye drops to clear up."),
    ],
    1143: [
        ("A", "typical_location", "A cupboard in the kitchen is where people commonly store plastic cutlery at home."),
        ("B", "property", "Everything is too broad a word, not a storage place for plastic cutlery."),
        ("C", "typical_location", "Own home is where the cupboard is located, but the cupboard is the storage used."),
        ("D", "typical_location", "A clothes closet stores garments, not plastic eating utensils."),
        ("E", "typical_location", "A store sells cutlery; people store their plastic cutlery in a kitchen cupboard."),
    ],
    1144: [
        ("A", "typical_location", "A large city may host galleries, but most displayed features belong in an art museum."),
        ("B", "typical_location", "An art museum is where most displayed features of a particular gallery would be found."),
        ("C", "typical_location", "London is a city that contains museums, not the type of venue for gallery features."),
        ("D", "typical_location", "France is a country, not the specific venue where gallery features are displayed."),
        ("E", "typical_location", "New York City is a metropolis, but an art museum is the specific gallery venue."),
    ],
    1145: [
        ("A", "used_for", "A person who brings people to the table as a host probably makes delicious food for them."),
        ("B", "used_for", "Compliments are kind words, not what a successful dinner host primarily produces."),
        ("C", "motivation", "Acquiring wealth may follow success, but the host skill is making food people enjoy."),
        ("D", "used_for", "Bread is one food item, but a successful host makes a full delicious meal."),
        ("E", "effect", "Self esteem is an internal feeling, not what the host makes for guests at the table."),
    ],
    1146: [
        ("A", "typical_location", "A garage stores vehicles and tools, not where you obtain a new shopping bag."),
        ("B", "typical_location", "A retail store sells goods including new shopping bags for customers."),
        ("C", "typical_location", "A storage cabinet holds items at home, not where you buy a new shopping bag."),
        ("D", "typical_location", "A supermarket is a retail store where customers can get a new shopping bag."),
        ("E", "typical_location", "A car trunk stores items in a vehicle, not where you purchase a new bag."),
    ],
    1147: [
        ("A", "typical_location", "A city is an urban area, not a venue with lanes for throwing a ball down."),
        ("B", "typical_location", "A basketball court has hoops, not lanes designed for rolling a ball."),
        ("C", "typical_location", "Rural countryside is open land without bowling lanes for throwing a ball."),
        ("D", "typical_location", "A highway is for vehicle traffic, not a lane for throwing a ball."),
        ("E", "typical_location", "A bowling alley has lanes where players throw a ball down toward pins."),
    ],
    1148: [
        ("A", "typical_location", "A hockey game is an exciting sporting event where crowd excitement is expected."),
        ("B", "typical_location", "A boxing match is a lively event where excitement from the crowd is normal."),
        ("C", "typical_location", "A library requires quiet and does not allow loud excitement from visitors."),
        ("D", "typical_location", "A car show is an event where enthusiasts show excitement over vehicles."),
        ("E", "typical_location", "A dance is a lively social event where excitement and energy are welcome."),
    ],
    1149: [
        ("A", "capability", "Female ants lack wings and can only get around by crawling on the ground."),
        ("B", "used_for", "Following one another describes ant trail behavior, not their primary mode of locomotion."),
        ("C", "capability", "Running is faster movement, but wingless female ants primarily crawl to get around."),
        ("D", "used_for", "Circling food describes foraging behavior, not how wingless ants travel."),
        ("E", "capability", "Flying requires wings, which female ants do not have for getting around."),
    ],
    1150: [
        ("A", "typical_location", "A classroom is at school, not where you pack a vacation book for travel."),
        ("B", "typical_location", "A briefcase carries work documents, less typical than a suitcase for vacation packing."),
        ("C", "typical_location", "A suitcase is the standard luggage where you store a book for vacation travel."),
        ("D", "typical_location", "A book store sells books, not where you store one you are taking on vacation."),
        ("E", "typical_location", "A synagogue is a place of worship, not vacation luggage for a book."),
    ],
    1151: [
        ("A", "property", "Manual describes a handbook, not the thrilling experience of riding a bull."),
        ("B", "property", "A wild ride describes the exciting, bucking experience of a cowboy riding a bull."),
        ("C", "property", "Need for rest is fatigue, not what makes bull riding exciting despite the fun."),
        ("D", "property", "Playing marbles is a children's game, unrelated to riding a bucking bull."),
        ("E", "property", "A hug is an embrace, not the wild experience of a cowboy atop a bull."),
    ],
    1152: [
        ("A", "motivation", "Satisfaction is a feeling, not what Disney's ride is dedicated to spreading worldwide."),
        ("B", "motivation", "Disney theme park rides are dedicated to bringing fun and joy to the world."),
        ("C", "motivation", "Wanting more is a consumer desire, not the message of Disney's celebratory rides."),
        ("D", "motivation", "Joy is close, but Disney rides specifically aim to spread fun to the world."),
        ("E", "effect", "A new realization is an insight, not what a Disney ride delivers to the world."),
    ],
    1153: [
        ("A", "typical_location", "The arm has hair people sometimes remove, but the head is the primary upper-body target."),
        ("B", "property", "Mammals is an animal class, not a specific upper-body area for hair removal."),
        ("C", "typical_location", "A person's head is a common upper-body area where people remove unwanted hair."),
        ("D", "property", "A mammoth trunk is an extinct animal's nose, not a human hair-removal site."),
        ("E", "typical_location", "A sink is a fixture for washing, not where on the body people remove hair."),
    ],
    1154: [
        ("A", "effect", "Feeling pain is suffering, not what animals do at a river when they are not thirsty."),
        ("B", "capability", "Flying is for birds and insects, not what thirsty or non-thirsty land animals do at rivers."),
        ("C", "used_for", "Passing water is a euphemism for urination, what animals do at a river when not drinking."),
        ("D", "effect", "Dying of cancer is a disease outcome, unrelated to animals visiting a river."),
        ("E", "effect", "Feeling pleasure is enjoyment, not the typical activity of non-thirsty animals at a river."),
    ],
    1155: [
        ("A", "effect", "Being entertained is a benefit parents hope play gives their children."),
        ("B", "effect", "Spending money is a cost, not what parents hope results from children playing."),
        ("C", "effect", "Intermission is a break in activity, not an outcome parents encourage from play."),
        ("D", "effect", "Weight loss is a health benefit of exercise, not the typical hope for children playing."),
        ("E", "effect", "Sleepiness may follow active play, but parents encourage play hoping children are entertained."),
    ],
    1156: [
        ("A", "capability", "Going on vacation is leisure travel, not the ability AI threatens according to skeptics."),
        ("B", "capability", "Working is employment, but AI fears center on losing control over computers."),
        ("C", "capability", "Crossing a street is a simple task, not the core fear about artificial intelligence."),
        ("D", "capability", "People who fear AI worry that humans will lose the ability to control computers."),
        ("E", "capability", "Separating things is vague sorting, not the primary AI-related fear about human capability."),
    ],
    1157: [
        ("A", "typical_location", "The sky is overhead open air, not where bees congregate after drinking cider."),
        ("B", "typical_location", "A field of flowers attracts bees, but orchards specifically follow cider drinking contexts."),
        ("C", "typical_location", "A beehive houses bees, but orchards are where bees forage after cider from apples."),
        ("D", "typical_location", "An orchard has flowering fruit trees where bees are active after drinking apple cider."),
        ("E", "typical_location", "Countryside is broad rural land; orchards are the specific bee habitat near cider sources."),
    ],
    1158: [
        ("A", "used_for", "Making friends is a social goal, not what hired entertainers are paid to do."),
        ("B", "property", "Fatigue is exhaustion, not what Sally expected from the people she hired to entertain."),
        ("C", "property", "Envy is jealousy, not the performance quality Sally hired the people for."),
        ("D", "motivation", "Sally hired entertainers and expected them to perform because that is what they are paid for."),
        ("E", "motivation", "Appreciate more is vague gratitude, not the paid service Sally expected from entertainers."),
    ],
    1159: [
        ("A", "property", "In charge means holding authority, not what a paid servant would be."),
        ("B", "property", "A boss gives orders, the opposite role of a servant who serves others."),
        ("C", "property", "A paid servant who is compensated for work is a free person, not a slave."),
        ("D", "property", "A queen is royalty, not a paid servant who works for wages."),
        ("E", "property", "A lord is nobility who commands servants, not a paid worker himself."),
    ],
    1160: [
        ("A", "typical_location", "A skyscraper has elevators, not walk-up stairs to the tenth storey."),
        ("B", "property", "A book of stories is literature, not a building with walk-up stairs to the tenth floor."),
        ("C", "typical_location", "A tall building could have walk-up stairs, but an apartment building is more specific."),
        ("D", "typical_location", "An apartment building with walk-up stairs commonly has tenants on the tenth storey."),
        ("E", "typical_location", "A mall is a shopping center, not a residential walk-up with a tenth storey home."),
    ],
    1161: [
        ("A", "typical_location", "Big cities celebrate with confetti thrown from rooftops during major festivities."),
        ("B", "typical_location", "New Year's Eve is a celebration when confetti is thrown from rooftops in cities."),
        ("C", "typical_location", "Air is the medium confetti falls through, not where it is thrown from."),
        ("D", "typical_location", "A shredder destroys paper, not a place where celebratory confetti is thrown."),
        ("E", "typical_location", "Streets are at ground level; confetti is thrown from rooftops above them."),
    ],
    1162: [
        ("A", "property", "Exceptional means outstanding, matching the Queen's view when she knighted Dan despite his self-doubt."),
        ("B", "property", "Upright means honest and moral, less specific than exceptional for knighthood honor."),
        ("C", "property", "Choice means selected or fine quality, but exceptional better captures knighthood-worthy merit."),
        ("D", "property", "Sufficient means adequate, too modest for a Queen knighting someone she admired."),
        ("E", "property", "Worthy means deserving honor, close but exceptional captures the Queen's high regard for Dan."),
    ],
    1163: [
        ("A", "typical_location", "A theater has attendants at doors to block light during a premiere night show."),
        ("B", "typical_location", "A building is too generic; theaters specifically use door attendants during performances."),
        ("C", "typical_location", "An office is a workplace, not a venue with premiere-night door attendants blocking light."),
        ("D", "typical_location", "A neighbor's house is a residence, not a premiere venue with door attendants."),
        ("E", "typical_location", "A funeral is a solemn service, not a premiere with attendants blocking light at the door."),
    ],
    1164: [
        ("A", "used_for", "Eating food is unrelated to the purpose of a clock."),
        ("B", "primary_function", "A clock is used to tell time by displaying hours and minutes."),
        ("C", "used_for", "Winding down means relaxing, not the function of a clock."),
        ("D", "effect", "Stop working describes malfunction, not the intended use of a clock."),
        ("E", "property", "Working correctly describes proper function, not what you use a clock for."),
    ],
    1165: [
        ("A", "property", "A wall is a structural surface, not something a door would do that frightens Sean."),
        ("B", "property", "A window is a glass opening, not the motion Sean feared from his door at night."),
        ("C", "effect", "Sean stared at his door fearing he might see it opening on its own at night."),
        ("D", "typical_location", "A closet is a storage space behind a door, not the door's frightening motion."),
        ("E", "typical_location", "An exit is a way out, not the unsettling movement Sean feared from the door."),
    ],
    1166: [
        ("A", "used_for", "Believing in god is personal faith, not how people normally work on group projects."),
        ("B", "used_for", "People normally work on group projects by collaborating in teams."),
        ("C", "used_for", "Kissing each other is affection, not the standard method for completing group projects."),
        ("D", "used_for", "Receiving gifts is a social exchange, not how group project work is normally done."),
        ("E", "effect", "Arguing may occur in groups, but the normal approach is working together in teams."),
    ],
    1167: [
        ("A", "typical_location", "Floors are surfaces throughout a house, but the welcome mat sits specifically in the doorway."),
        ("B", "typical_location", "A desert is an arid landscape, not where a house welcome mat would be found."),
        ("C", "typical_location", "A school is an institution, not a location for a residential welcome mat."),
        ("D", "typical_location", "A welcome mat is placed in the doorway at the entrance of a house."),
        ("E", "typical_location", "A bathroom is for hygiene and does not typically have a welcome mat."),
    ],
    1168: [
        ("A", "effect", "Twins are a rare outcome of pregnancy, not more common than having children."),
        ("B", "effect", "Children born result from procreation, but pregnancy itself is even more common than kids."),
        ("C", "effect", "Venereal disease is a possible risk, not the most common consequence of sex."),
        ("D", "typical_location", "Used condoms are contraceptive waste, not a common consequence compared to pregnancy."),
        ("E", "effect", "Pregnancy is an even more common consequence of sex than the children it may produce."),
    ],
    1169: [
        ("A", "typical_location", "A car stand displays vehicles for sale, not where people wait to be picked up."),
        ("B", "typical_location", "A bus stop has a bench where people sit before the bus takes them away."),
        ("C", "typical_location", "A state park is for recreation, not a transit waiting area with benches."),
        ("D", "typical_location", "A bus depot handles buses but passengers typically wait at bus stop benches."),
        ("E", "typical_location", "A rest area is a highway stop, but bus stop benches are the classic waiting spot."),
    ],
}
