# -*- coding: utf-8 -*-
"""Hand-authored v2-style KB for CSQA qids 1441-1519 (no answerKey)."""

CHUNK = {
    1441: [
        ("A", "typical_location", "A hardware store sells tin and metal supplies, not where you store tin after purchase."),
        ("B", "typical_location", "An antique store sells vintage items, not where you keep tin once you have bought it."),
        ("C", "used_for", "A shopping bag holds newly purchased items like tin while you carry them home."),
        ("D", "typical_location", "A shed is long-term storage at home, not the first place tin goes right after buying."),
        ("E", "typical_location", "A landfill is for waste disposal, not where you put tin immediately after buying it."),
    ],
    1442: [
        ("A", "property", "A backpack carries belongings, not a retail store selling clothing and housewares."),
        ("B", "typical_location", "A house is a residence, not a shop where you buy clothing and sporting goods."),
        ("C", "typical_location", "A department store sells clothing, sporting goods, and housewares under one roof."),
        ("D", "typical_location", "A mall contains many shops but a department store specifically bundles those product lines."),
        ("E", "property", "A table is furniture, not a retail destination for clothing and sporting goods."),
    ],
    1443: [
        ("A", "typical_location", "Disneyland is an amusement park with rides, not primarily a place to buy toys for kids."),
        ("B", "typical_location", "A jungle is wild nature, not a shop where parents buy playthings for children."),
        ("C", "typical_location", "A swimming pool is for swimming, not where you take kids to buy things to play with."),
        ("D", "typical_location", "A toy store sells items designed for children to play with and enjoy."),
        ("E", "typical_location", "Home is where kids already have toys, not where you go to buy new playthings."),
    ],
    1444: [
        ("A", "property", "Four legs describes canine anatomy, not what the saying excludes from best-friend meaning."),
        ("B", "property", "Males refers to gender; the saying uses man generically, not only about male humans."),
        ("C", "property", "An electrical circuit is electronics jargon, unrelated to the dogs best friend saying."),
        ("D", "property", "Pet is what dogs are, but the saying is not limited to the pet relationship alone."),
        ("E", "capability", "Sniff is a dog behavior, not what the proverb contrasts when calling dogs best friends."),
    ],
    1445: [
        ("A", "effect", "Climbing a mountain and breathing fresh air often produces a feeling of exhilaration."),
        ("B", "effect", "Fresh mountain air can give a climber a clear head and mental sharpness."),
        ("C", "effect", "Breathing clean mountain air commonly makes a person feel better overall."),
        ("D", "effect", "Fresh alpine air can feel reviving after the exertion of climbing upward."),
        ("E", "effect", "Mountain climbing in fresh air frequently brings a sense of happiness and joy."),
    ],
    1446: [
        ("A", "effect", "An unsuccessful writing program may produce unexpected results instead of intended output."),
        ("B", "effect", "A failed writing program often introduces bugs and errors into the software."),
        ("C", "effect", "Satisfaction is a positive outcome, the opposite of what an unsuccessful program causes."),
        ("D", "effect", "An unsuccessful writing program commonly causes frustration for its users and developers."),
        ("E", "effect", "Aggrevation describes annoyance that a poorly working writing program can create."),
    ],
    1447: [
        ("A", "typical_location", "A party is a social gathering, not the musical pit where a flute is played."),
        ("B", "typical_location", "An orchestra pit is where a flute is likely positioned during a performance."),
        ("C", "typical_location", "A musical instrument store sells flutes but is not a performance pit."),
        ("D", "typical_location", "A marching band plays outdoors; a pit refers to an orchestra setting."),
        ("E", "typical_location", "A symphony performs on stage; the flute in a pit sits in the orchestra section."),
    ],
    1448: [
        ("A", "property", "Names identify people, not what the insult no brains implies about stupidity."),
        ("B", "property", "Dress refers to clothing, unrelated to calling someone stupid for lacking intelligence."),
        ("C", "property", "Brains refers to intelligence; saying someone has no brains means they are stupid."),
        ("D", "property", "Brown hair is a physical trait, not the mental quality the insult targets."),
        ("E", "property", "Two eyes are body parts, not what people mean when calling someone stupid."),
    ],
    1449: [
        ("A", "typical_location", "The ground outdoors keeps a potted ficus away from indoor carpet that could get dirty."),
        ("B", "typical_location", "An arboretum displays plants publicly, not a typical home spot to avoid dirty carpet."),
        ("C", "typical_location", "An apartment has carpet indoors; placing a ficus on the ground avoids that risk."),
        ("D", "typical_location", "A refrigerator is for food storage, not where you keep a living ficus plant."),
        ("E", "typical_location", "California is a state, not a specific indoor location to protect carpet from a ficus."),
    ],
    1450: [
        ("A", "property", "With someone suggests companionship, yet she still felt alone despite another person nearby."),
        ("B", "property", "Many people nearby can still leave someone feeling emotionally alone and isolated."),
        ("C", "property", "With others implies company, but she felt alone even when others were present."),
        ("D", "effect", "Being surrounded by people does not prevent feeling alone when emotionally disconnected."),
        ("E", "effect", "Sitting in a crowd can still leave a distracted person feeling profoundly alone."),
    ],
    1451: [
        ("A", "property", "Swiss cheese already has holes; punching it would not be making a new hole."),
        ("B", "typical_location", "A football ground is outdoor turf, less typical for punching a hole with a fist."),
        ("C", "typical_location", "The ground is earth or soil, but walls are more commonly punched to make holes."),
        ("D", "typical_location", "A golf course is open grassland, not where you would typically punch a hole."),
        ("E", "typical_location", "A wall is a solid surface where a fist can punch through and make a hole."),
    ],
    1452: [
        ("A", "typical_location", "New York has many courts, but red clay is not its most characteristic tennis surface."),
        ("B", "typical_location", "Wimbledon is famous for grass courts, not the red clay surface described."),
        ("C", "typical_location", "A town may have courts, but country clubs are known for red clay tennis surfaces."),
        ("D", "typical_location", "A country club often features tennis courts surfaced with distinctive red clay."),
        ("E", "typical_location", "A health club may have courts, but red clay is more typical at country clubs."),
    ],
    1453: [
        ("A", "used_for", "Sleep rests the whole body but is excessive when legs just need a brief pause."),
        ("B", "used_for", "Sitting down lets tired legs rest without the commitment of going fully to bed."),
        ("C", "used_for", "Going to bed is full rest, but sitting down suffices when legs simply need a break."),
        ("D", "used_for", "Running would further tire legs, the opposite of resting when they are exhausted."),
        ("E", "used_for", "Closing eyes aids relaxation but sitting down directly relieves tired legs."),
    ],
    1454: [
        ("A", "effect", "A championship is a competitive outcome, not what most people experience after all-day tennis."),
        ("B", "effect", "Playing tennis all day commonly leaves most people becoming tired and fatigued."),
        ("C", "effect", "Tennis elbow is an injury some develop, but general tiredness affects most players."),
        ("D", "effect", "Victory is winning a match, not the typical result of recreational all-day tennis."),
        ("E", "effect", "Friends may accompany you, but physical exhaustion is the usual aftermath of all-day play."),
    ],
    1455: [
        ("A", "typical_location", "A restaurant may show sports on screens, but televisions more often display sports at home."),
        ("B", "typical_location", "A living room television is where households commonly watch sports broadcasts."),
        ("C", "typical_location", "A bar shows sports on TV, but the living room is the most typical household location."),
        ("D", "typical_location", "An apartment contains a living area where a television often shows sports."),
        ("E", "typical_location", "A house has rooms where televisions frequently display live sports events."),
    ],
    1456: [
        ("A", "used_for", "Animals knowing fluids are important also know which liquids are safe to drink."),
        ("B", "effect", "Feeling pain is a sensation, not the safe activity animals associate with fluids."),
        ("C", "capability", "Biting uses teeth, unrelated to knowing which fluids are safe for consumption."),
        ("D", "capability", "Flying is an aerial ability, not connected to safe fluid consumption knowledge."),
        ("E", "property", "Gay describes orientation, irrelevant to animals knowing safe fluid consumption."),
    ],
    1457: [
        ("A", "used_for", "Love another describes a new romance, not a typical early-morning routine after staying over."),
        ("B", "used_for", "Making coffee is a common thoughtful gesture when someone stays over after intimacy."),
        ("C", "used_for", "Smoking is a personal habit, less universal than morning food or drink preparation."),
        ("D", "used_for", "Eating breakfast is a morning activity he might prepare after she spent the night."),
        ("E", "used_for", "Wait for is passive, not an active morning task like preparing food or drink."),
    ],
    1458: [
        ("A", "property", "Ominous means foreboding, fitting an assassination that turned a hopeful day dark."),
        ("B", "property", "Coincidental means chance occurrence, less pointed than the assassination's grim reversal."),
        ("C", "property", "Ruinous means causing ruin, but inauspicious specifically contrasts the king's hopeful speech."),
        ("D", "property", "Inauspicious means unlucky, the opposite of auspicious after the king was assassinated."),
        ("E", "property", "Disastrous means catastrophic, close but inauspicious directly negates the auspicious claim."),
    ],
    1459: [
        ("A", "used_for", "Drinking commonly accompanies eating as another act of consumption during a meal."),
        ("B", "used_for", "Playing poker is a card game, not a typical companion act while having food."),
        ("C", "used_for", "Sitting is posture during meals, not another consumption act alongside eating food."),
        ("D", "used_for", "Talking is social during meals, but drinking is the other consumption act paired with eating."),
        ("E", "property", "Being greedy describes excess appetite, not a routine companion act to eating."),
    ],
    1460: [
        ("A", "used_for", "Cleaning house can be a stress response, but substance use is a more common excess."),
        ("B", "effect", "Using drugs is something people under stress may do too much of as coping."),
        ("C", "effect", "Drinking alcohol is a frequent excess behavior when someone is experiencing stress."),
        ("D", "typical_location", "Hanging out at a bar involves drinking, a stress-related excess for some people."),
        ("E", "used_for", "Dreaming is sleep activity, not a harmful excess typically linked to stress."),
    ],
    1461: [
        ("A", "typical_location", "A root cellar is where small farmers traditionally store harvested potatoes after growing."),
        ("B", "typical_location", "An own kitchen holds food for cooking, not bulk potato storage after harvest."),
        ("C", "property", "Clam chowder is a soup dish, not where a farmer keeps stored potatoes."),
        ("D", "typical_location", "A desk drawer is office storage, not a farmer's potato keeping location."),
        ("E", "typical_location", "A kitchen cabinet stores some food but root cellars better preserve harvested potatoes."),
    ],
    1462: [
        ("A", "used_for", "Waste paper is discarded material, not a way people gain new perspectives."),
        ("B", "used_for", "Tickling tarantulas is absurd activity, unrelated to broadening one's worldview."),
        ("C", "used_for", "Paying bills is a financial chore, not a means of gaining new perspectives."),
        ("D", "used_for", "Changing direction alters course but travel abroad more directly exposes new perspectives."),
        ("E", "used_for", "Travel abroad exposes people to different cultures and helps them gain new perspectives."),
    ],
    1463: [
        ("A", "effect", "Remorse is guilt felt by the wrongdoer, not what grieving family members feel."),
        ("B", "effect", "Retaliation is a vengeful act, not the emotion family members feel while crying."),
        ("C", "property", "Terrible describes something awful, less precise than the deep grief family feels."),
        ("D", "effect", "Anguish is intense suffering that family members feel when crying over murdered relatives."),
        ("E", "property", "Wet describes moisture from tears, not the emotional state behind the crying."),
    ],
    1464: [
        ("A", "typical_location", "A cinema has seats arranged for audiences to watch movies on a large screen."),
        ("B", "property", "Movies are films themselves, not a physical venue with seats for viewing."),
        ("C", "typical_location", "A hockey game has seating but is for sports, not watching a movie."),
        ("D", "typical_location", "A theater has seats for performances; cinema specifically refers to film viewing."),
        ("E", "typical_location", "An opera has seated viewing but is for live music, not movies."),
    ],
    1465: [
        ("A", "typical_location", "The ocean is a body of water, not where an omnidisciplinary person finds success."),
        ("B", "used_for", "Working hard helps success, but an omnidisciplinary person succeeds across many fields."),
        ("C", "typical_location", "Various situations suit an omnidisciplinary person who can find success in many areas."),
        ("D", "typical_location", "Michigan is a state, not a domain where diverse skills lead to success."),
        ("E", "typical_location", "An awards ceremony recognizes achievement but is not where success is found."),
    ],
    1466: [
        ("A", "primary_function", "Keeping people out is a door's security role, not what you do to pass through."),
        ("B", "used_for", "Enclosing a cupboard describes cabinetry, not the action needed to use a closed door."),
        ("C", "capability", "Teleport is fantasy travel, not the realistic action for passing through a closed door."),
        ("D", "property", "Glass describes door material, not the action required to go through a closed door."),
        ("E", "primary_function", "You must open a closed door before you can walk through it."),
    ],
    1467: [
        ("A", "typical_location", "A Japanese restaurant serves food, not a book of animal pictures with rhymes."),
        ("B", "typical_location", "A lake is a body of water, not a collection of illustrated animals with rhymes."),
        ("C", "typical_location", "A zoo has live animals, but the child heard rhymes while viewing pictures."),
        ("D", "typical_location", "A book of animal pictures with accompanying rhymes is where a child finds favorites."),
        ("E", "property", "Current means flow or present time, not a book of animal illustrations."),
    ],
    1468: [
        ("A", "used_for", "A fan dries air but is not the primary tool for wet cleaning a floor."),
        ("B", "has_prerequisite", "Energy is needed for effort, but a mop is the specific tool for wet floor cleaning."),
        ("C", "used_for", "Vacuuming cleans dry debris, not the wet mopping described in the housework."),
        ("D", "used_for", "A mop is the tool needed for wet cleaning a floor during housework."),
        ("E", "used_for", "A broom sweeps dry messes, not for wet cleaning floors with water."),
    ],
    1469: [
        ("A", "property", "November is a calendar month, not the weather type associated with lightning strikes."),
        ("B", "property", "Rainy stormy days with moisture in the air produce beautiful lightning strikes."),
        ("C", "property", "Dull describes overcast gray weather less associated with dramatic lightning displays."),
        ("D", "property", "Wet means moisture is present, but rainy specifically pairs with thunderstorm lightning."),
        ("E", "property", "Average describes ordinary conditions, not the dramatic weather producing lightning."),
    ],
    1470: [
        ("A", "used_for", "Socialize means interacting with others, not something alcohol consumption causes you to lose."),
        ("B", "used_for", "Eating is consuming food, not a faculty that drinking alcohol typically diminishes."),
        ("C", "property", "Fool as a noun is vague; alcohol more commonly disrupts sleep at night."),
        ("D", "used_for", "Dance is movement, not the bodily function alcohol commonly causes people to lose."),
        ("E", "effect", "Drinking alcohol can interfere with your ability to sleep at night."),
    ],
    1471: [
        ("A", "typical_location", "A groundhog appears on Groundhog Day in February, not Independence Day in July."),
        ("B", "typical_location", "A construction site is ongoing work, not a typical Independence Day celebration sight."),
        ("C", "property", "A landmine is a weapon, not something commonly seen on Independence Day."),
        ("D", "typical_location", "An army may parade, but fireworks displays are the iconic Independence Day sight."),
        ("E", "typical_location", "A fireworks display is the classic spectacle people see on Independence Day."),
    ],
    1472: [
        ("A", "typical_location", "A closet in a hotel room commonly holds clothing including shirts on hangers."),
        ("B", "typical_location", "A drawer in a hotel room dresser is another place a shirt may be stored."),
        ("C", "typical_location", "A garderobe is an archaic wardrobe term for where clothing like shirts is kept."),
        ("D", "typical_location", "A shelf may hold folded items, but closets are the primary shirt location in hotels."),
        ("E", "typical_location", "A suitcase is luggage for travel, not the built-in storage for hotel room shirts."),
    ],
    1473: [
        ("A", "property", "A bad time is an unpleasant period, not an action to verify your memory."),
        ("B", "used_for", "Closing eyes aids focus but does not directly confirm you are remembering."),
        ("C", "used_for", "Answering a question tests recall and helps confirm you are remembering correctly."),
        ("D", "used_for", "Stopping to think pauses and reflects, a way to make sure you are remembering."),
        ("E", "effect", "Forgetting is memory failure, the opposite of making sure you are remembering."),
    ],
    1474: [
        ("A", "typical_location", "A bar is a licensed establishment where patrons drink beer and alcoholic beverages."),
        ("B", "typical_location", "A vending machine dispenses drinks but rarely serves beer in most places."),
        ("C", "property", "A bottle is a container, not a venue where you sit and drink beer."),
        ("D", "typical_location", "A refrigerator stores beer at home but is not a place to drink it socially."),
        ("E", "typical_location", "A hockey game is a sporting event, not a typical venue for drinking beer."),
    ],
    1475: [
        ("A", "effect", "A stomach ache is physical discomfort, not the emotional aftermath of killing in rage."),
        ("B", "effect", "Retaliation is a vengeful response, not a feeling someone has after their own violence."),
        ("C", "effect", "Sadness is grief, but remorse more specifically follows killing people in a rage."),
        ("D", "effect", "Remorse is guilt and regret someone likely feels after killing people in a rage."),
        ("E", "effect", "Going to jail is a legal consequence, not the immediate feeling after the killings."),
    ],
    1476: [
        ("A", "property", "A shaker is a container for salt, not an entity that uses salt in cooking."),
        ("B", "typical_location", "Fast food restaurants are known for using excessive amounts of salt in meals."),
        ("C", "typical_location", "A kitchen cupboard stores salt but does not actively use it in food preparation."),
        ("D", "capability", "People can use salt, but fast food restaurants are especially likely to use too much."),
        ("E", "property", "A table is furniture where salt sits, not an entity that applies salt to food."),
    ],
    1477: [
        ("A", "used_for", "Saying hello greets newcomers but smiling more visibly shows happiness when meeting people."),
        ("B", "used_for", "Starting a conversation engages others, but a smile immediately signals friendly happiness."),
        ("C", "used_for", "Introducing yourself shares identity, while smiling shows happiness upon meeting new people."),
        ("D", "used_for", "Shaking hands is a formal greeting gesture when meeting people for the first time."),
        ("E", "used_for", "Smiling is a facial expression that shows a friendly man is happy meeting new people."),
    ],
    1478: [
        ("A", "typical_location", "Outer space is beyond Earth, not the visible boundary where the sun appears to set."),
        ("B", "typical_location", "The horizon is where the sun appears to set as Earth rotates each evening."),
        ("C", "typical_location", "A beach offers a view of sunset, but the sun sets at the horizon everywhere."),
        ("D", "typical_location", "West is the general direction of sunset, but horizon is where it visually disappears."),
        ("E", "property", "Beans are legumes, unrelated to where the sun sets in the sky."),
    ],
    1479: [
        ("A", "effect", "Frostbite affects exposed skin in cold, less common than injuries from skiing collisions."),
        ("B", "effect", "Broken bones in multiple places are common injuries from serious skiing accidents."),
        ("C", "effect", "Chapped lips come from wind exposure, not typical multi-site skiing accident injuries."),
        ("D", "property", "A healthy body is the ideal state, opposite of skiing accident injury outcomes."),
        ("E", "effect", "Broken legs may occur, but broken bones in more than one place is broader."),
    ],
    1480: [
        ("A", "property", "Unfeeling describes lacking emotion, close but disregard better captures ignoring safety."),
        ("B", "property", "Disregard for her own safety is what John could not stand as Kate kept endangering herself."),
        ("C", "property", "Indifferent means unconcerned, but disregard specifically means ignoring safety warnings."),
        ("D", "property", "Neglect implies failing to care for something, less precise than disregard for safety."),
        ("E", "property", "Apathetic means showing no interest, similar but disregard fits the safety context."),
    ],
    1481: [
        ("A", "effect", "Recycled means processed again, not what a loathing agent plans for a hated king."),
        ("B", "property", "Inclined means tending toward, the opposite of what the agent wants for the king."),
        ("C", "effect", "Disposed means removed or gotten rid of, what the agent plans for the loathed king."),
        ("D", "property", "Avid means enthusiastic, the opposite of the agent's intent toward the king."),
        ("E", "property", "Enthusiastic means eager, contrary to the agent's loathing plan for the king."),
    ],
    1482: [
        ("A", "typical_location", "A classroom teaches students, but university offers deeper adult literary education."),
        ("B", "typical_location", "An English class covers language, but a poet seeking learning may attend university."),
        ("C", "typical_location", "A university provides advanced literary education that adult poets pursue for learning."),
        ("D", "typical_location", "A book store sells books, but formal learning as an adult often requires university."),
        ("E", "typical_location", "Home is for self-study, but poets often go to university for structured adult learning."),
    ],
    1483: [
        ("A", "typical_location", "A cupboard in the kitchen commonly stores towels for drying dishes and hands."),
        ("B", "typical_location", "A hotel has towels for guests, but kitchen towels belong in home cupboards."),
        ("C", "typical_location", "A linen closet holds household linens including kitchen towels in some homes."),
        ("D", "typical_location", "Under a rock is outdoors and absurd, not where kitchen towels are found."),
        ("E", "typical_location", "A locker room has athletic towels, not typical kitchen towels for cooking areas."),
    ],
    1484: [
        ("A", "property", "Irritation is annoyance, not what saying sir or ma'am after answers indicates."),
        ("B", "property", "Correct means accurate, but the honorifics indicate politeness rather than correctness."),
        ("C", "property", "Responding is the act of answering, but sir and ma'am signal respectful politeness."),
        ("D", "property", "Polite behavior is indicated when you answer questions and address someone as sir or ma'am."),
        ("E", "property", "Sadness is sorrow, unrelated to courteous sir or ma'am address after answering."),
    ],
    1485: [
        ("A", "effect", "Destroy enemy is extreme violence beyond what typical anger control issues produce."),
        ("B", "effect", "Punching is a common impulsive reaction when someone with anger issues is provoked."),
        ("C", "used_for", "Cooling off is healthy coping, not what Matt did when someone set off his anger."),
        ("D", "used_for", "Writing a letter is calm expression, opposite of Matt's reaction when anger was triggered."),
        ("E", "used_for", "Illustrating a point is reasoned argument, not Matt's impulsive anger response."),
    ],
    1486: [
        ("A", "used_for", "Reading stories is a quiet solo activity, not what two people doing the same thing tend toward."),
        ("B", "effect", "When two people do the same activity they often tend to compete with each other."),
        ("C", "used_for", "Helping is cooperative, but competition is more common when two people share an activity."),
        ("D", "used_for", "Solving problems is collaborative, less automatic than competing at the same task."),
        ("E", "used_for", "Giving orders is hierarchical, not the natural tendency of two equals doing the same thing."),
    ],
    1487: [
        ("A", "used_for", "Planning organizes an event, but Billy enjoyed mixing which means meeting people at parties."),
        ("B", "used_for", "Meeting new people is what Billy liked when he enjoyed mixing at the party."),
        ("C", "used_for", "Getting drunk is party behavior, but mixing specifically means socializing with new people."),
        ("D", "used_for", "Having fun is general enjoyment, but mixing at parties means meeting and mingling with others."),
        ("E", "used_for", "The watusi is a specific dance, less general than the social mixing Billy enjoyed."),
    ],
    1488: [
        ("A", "typical_location", "Movie theaters show films, not where a school prom is held after ticket check-in."),
        ("B", "property", "End of line is a queue position, not the venue where a school prom takes place."),
        ("C", "typical_location", "A football field is outdoor turf, not the typical indoor venue for a school prom."),
        ("D", "typical_location", "A school auditorium is where couples enter their prom after checking in at tickets."),
        ("E", "typical_location", "An opera house is a performance venue, not a typical high school prom location."),
    ],
    1489: [
        ("A", "property", "Courageous describes bravery, not what a person wanting no trouble would do."),
        ("B", "used_for", "Stepping up means intervening, which risks trouble the person wanted to avoid."),
        ("C", "used_for", "Keeping walking avoids confrontation when someone wants no trouble with a bully."),
        ("D", "used_for", "Crossing the street changes location but keeping walking more directly avoids the bully."),
        ("E", "used_for", "Doing nothing is passive, but continuing to walk away more actively avoids trouble."),
    ],
    1490: [
        ("A", "property", "Mainstream means widely accepted, the opposite approach that beat the kooky hipster cafe."),
        ("B", "property", "Straight means direct or conventional in style, contrasting the disingenuous kooky approach."),
        ("C", "property", "Right means correct, not a business approach contrasting kooky hipster branding."),
        ("D", "property", "Conventional means traditional and ordinary, what the successful competitor offered instead."),
        ("E", "property", "Uneccentric means not quirky, the practical approach that outlasted the kooky hipster cafe."),
    ],
    1491: [
        ("A", "typical_location", "A pocket keeps a ballpoint pen handy and accessible for everyday writing needs."),
        ("B", "typical_location", "A stationery store sells pens but is not where you store one you already own."),
        ("C", "typical_location", "A backpack carries supplies including pens, but a pocket is best for quick access."),
        ("D", "typical_location", "A desk drawer stores pens at a workstation, another good but less portable option."),
        ("E", "typical_location", "A bank is a financial institution, not storage for a personal ballpoint pen."),
    ],
    1492: [
        ("A", "typical_location", "An auditorium is a venue, not a punishment for cutting in the ticket line."),
        ("B", "property", "Humans are people, not a consequence for line-cutting at a ticket office."),
        ("C", "typical_location", "An opera house is a building, not the penalty for cutting in a queue."),
        ("D", "effect", "Death is an extreme punishment far beyond what line-cutting at tickets warrants."),
        ("E", "effect", "Being sent to the end of the line is the fitting punishment for cutting in queue."),
    ],
    1493: [
        ("A", "typical_location", "An awards ceremony celebrates achievement, not a factor producing success."),
        ("B", "typical_location", "Various situations are contexts, not the partner ingredient paired with preparation."),
        ("C", "property", "Vocation is a career calling, not the usual complement to preparation in success."),
        ("D", "motivation", "Working hard alongside preparation is what success is usually a product of."),
        ("E", "effect", "Promotion is a career advancement result, not the input paired with preparation."),
    ],
    1494: [
        ("A", "typical_location", "An office building is a professional workspace commonly equipped with air conditioning."),
        ("B", "typical_location", "Texas is a state with hot climate, not a professional space with air conditioning."),
        ("C", "typical_location", "A house may have AC, but office buildings are professional spaces that typically have it."),
        ("D", "property", "Humid describes moisture in air, not a professional space with climate control."),
        ("E", "property", "Warm climates are regions, not professional indoor spaces with air conditioning."),
    ],
    1495: [
        ("A", "motivation", "Existing means merely being alive, less than the active engagement key to happiness."),
        ("B", "property", "Happiness is the goal itself, not what you should do more of to achieve it."),
        ("C", "effect", "Early death ends life, the opposite of the active living that brings happiness."),
        ("D", "used_for", "Acquiring knowledge enriches life, but doing more than merely existing is the key."),
        ("E", "effect", "Being idle is passive inaction, less than the engaged living that creates happiness."),
    ],
    1496: [
        ("A", "property", "Hungry is a feeling, not a prerequisite step before cooking dinner for someone."),
        ("B", "has_prerequisite", "Buying a kitchen is excessive; he first needed ingredients to cook dinner."),
        ("C", "has_prerequisite", "Buying food is necessary before he can cook dinner as he had promised."),
        ("D", "has_prerequisite", "Buying groceries provides the ingredients he needed before cooking dinner."),
        ("E", "used_for", "Eating food is consumption, the opposite of the preparation step before cooking."),
    ],
    1497: [
        ("A", "effect", "Grief is sorrow over loss, but divorce can also bring positive new beginnings."),
        ("B", "effect", "Confusion follows major change, but relief is a common positive beginning after divorce."),
        ("C", "effect", "Relief can be a new beginning that ending an unhappy marriage sometimes brings."),
        ("D", "effect", "Depression is sadness, not the hopeful beginning divorce can sometimes provide."),
        ("E", "effect", "Happiness is possible, but relief more specifically captures freedom from a bad marriage."),
    ],
    1498: [
        ("A", "used_for", "Telling a story is something smart Jenny might do that James enjoys hearing."),
        ("B", "used_for", "Singing is musical, but James likely enjoys hearing smart Jenny tell stories."),
        ("C", "used_for", "Cleaning a room is a chore, not something James would especially like hearing."),
        ("D", "used_for", "Going out at night is an activity, not what James likes to hear Jenny do."),
        ("E", "used_for", "Jumping rope is physical play, not the intellectual sharing James enjoys from Jenny."),
    ],
    1499: [
        ("A", "typical_location", "A city is a large area, not the specific next stop for household items and food."),
        ("B", "typical_location", "A financial center has banks, not where you buy household items and groceries."),
        ("C", "typical_location", "Main street may have shops, but a grocery store specifically sells food and household items."),
        ("D", "typical_location", "A grocery store sells food and household items you need after visiting a bank."),
        ("E", "typical_location", "A salon provides hair services, not household items and food after banking."),
    ],
    1500: [
        ("A", "effect", "Peaceful sleep is a benefit someone free from guilt is likely to achieve."),
        ("B", "effect", "Freedom from want is economic security, less direct than guilt-free peaceful rest."),
        ("C", "effect", "A medal is an award, not an achievement tied to being free from guilt."),
        ("D", "effect", "A headache is discomfort, the opposite of what guilt-free peace brings."),
        ("E", "effect", "A new computer is a possession, unrelated to emotional freedom from guilt."),
    ],
    1501: [
        ("A", "property", "A space shuttle is a vehicle, not an essential human experience Danny lacks."),
        ("B", "typical_location", "A library provides knowledge, but love is a deeper human experience Danny may lack."),
        ("C", "typical_location", "School provides education, but love is a profound human experience Danny might miss."),
        ("D", "capability", "Love is a deep human connection and emotion Danny may not have experienced yet."),
        ("E", "property", "A wife is a marital partner, a specific form of love rather than the general missing experience."),
    ],
    1502: [
        ("A", "used_for", "Make love is physical intimacy, not the term for sharing the same point of view."),
        ("B", "used_for", "When they hug describes affection, not agreement on a shared viewpoint."),
        ("C", "used_for", "Shake hands is a greeting gesture, not what sharing the same viewpoint is called."),
        ("D", "property", "Agreeing with each other means two people share the same point of view on something."),
        ("E", "used_for", "Work together is collaboration, not specifically having the same perspective."),
    ],
    1503: [
        ("A", "effect", "Adventure may come on long hikes, but short hikes more commonly cause mild physical effects."),
        ("B", "effect", "Smiling is an expression, not a typical physical result of brief hiking."),
        ("C", "effect", "Cramps can occur, but sweating is more likely after even a short period of hiking."),
        ("D", "effect", "Sweating commonly happens after hiking for only a short time due to exertion."),
        ("E", "effect", "Giving up is quitting early, not a natural physical result of brief hiking."),
    ],
    1504: [
        ("A", "typical_location", "A wedding gathers people for ceremony, not typically while waiting for a ride across town."),
        ("B", "typical_location", "A bus stop is where people gather while waiting for a ride across town."),
        ("C", "typical_location", "A convention gathers attendees indoors, not for routine cross-town transportation waits."),
        ("D", "typical_location", "A pool is for swimming, not where people wait for a ride across town."),
        ("E", "typical_location", "An apartment is a residence, not a public gathering point for waiting rides."),
    ],
    1505: [
        ("A", "used_for", "Real estate is the field of study for someone who wants to make a fortune selling houses."),
        ("B", "property", "A treasure chest holds valuables, not a subject to study for selling houses."),
        ("C", "used_for", "The stock market involves securities trading, not specifically selling residential houses."),
        ("D", "used_for", "Business is broad; real estate more specifically prepares you for selling houses."),
        ("E", "typical_location", "A bank handles finances, not the field of study for a house-selling career."),
    ],
    1506: [
        ("A", "effect", "Health is wellness, the opposite of what excessive hand washing typically causes."),
        ("B", "effect", "Becoming wet is a surface effect, less serious than the skin damage from over-washing."),
        ("C", "effect", "Skin irritation commonly results from washing hands over one thousand times daily."),
        ("D", "effect", "Dry skin is a consequence of compulsive excessive hand washing over a thousand times."),
        ("E", "property", "Medium describes a size or channel, not a result of compulsive hand washing."),
    ],
    1507: [
        ("A", "used_for", "On trial is a legal proceeding, not what a priest does before a watching congregation."),
        ("B", "used_for", "Drinking coffee is a casual activity, not a priest's role before an observing audience."),
        ("C", "property", "Believing in God is faith, not the public ritual people watch a priest perform."),
        ("D", "used_for", "Baptising is a sacrament a priest may perform while people watch the ceremony."),
        ("E", "used_for", "Saying mass is the liturgical service a priest performs before a watching congregation."),
    ],
    1508: [
        ("A", "property", "Anger is an emotion, not a sound-related activity done while driving to work."),
        ("B", "used_for", "Listening to the radio involves sound and requires no mouth movement while driving to work."),
        ("C", "used_for", "Speeding is driving fast, not a sound activity that avoids moving your mouth."),
        ("D", "used_for", "Singing requires moving your mouth, contrary to the no-mouth-movement requirement."),
        ("E", "property", "A statue is an object, not an activity involving sound while commuting."),
    ],
    1509: [
        ("A", "typical_location", "A rainforest is the natural habitat where marmosets roam free in the wild."),
        ("B", "typical_location", "A kitchen is a human cooking space, not where a marmoset roams freely."),
        ("C", "typical_location", "The wilderness includes wild areas where marmosets can roam free outside captivity."),
        ("D", "property", "A dictionary is a reference book, not a habitat where marmosets roam."),
        ("E", "typical_location", "A burrow is underground shelter; marmosets roam freely in rainforest tree canopies."),
    ],
    1510: [
        ("A", "primary_function", "Monarchy is the form of government most associated with rule by a kingdom's monarch."),
        ("B", "property", "Ruled by government is vague; monarchy specifically pairs with kingdom governance."),
        ("C", "typical_location", "Europe is a continent, not a form of government associated with kingdoms."),
        ("D", "property", "A book is reading material, not a governmental system linked to kingdoms."),
        ("E", "part_whole", "A king is the ruler, but monarchy is the government form associated with kingdoms."),
    ],
    1511: [
        ("A", "effect", "Dishonor is loss of reputation, not the specific court charge for refusing respect."),
        ("B", "effect", "Contempt of court is the charge for refusing to give the court proper respect."),
        ("C", "effect", "Humiliate means to shame, not the legal charge Manny received for disrespect."),
        ("D", "property", "Disdain is scornful rejection, not the formal court charge for refusing respect."),
        ("E", "property", "Scorn is contemptuous feeling, not the specific legal charge in court."),
    ],
    1512: [
        ("A", "property", "Summer is a season, not where the Red Cross responds to storm disasters."),
        ("B", "typical_location", "The tropics are a climate zone, not the organization's primary storm response area."),
        ("C", "property", "Blue Shield is an insurance name, not where the Red Cross deploys for storms."),
        ("D", "property", "A weather report forecasts storms, not where the Red Cross responds to them."),
        ("E", "typical_location", "The Red Cross responds to storms and disasters across America."),
    ],
    1513: [
        ("A", "used_for", "A commercial is an advertisement, not court-ordered service for apathy-driven crime."),
        ("B", "property", "Three toed describes sloth anatomy, not the service a convicted apathetic man performs."),
        ("C", "used_for", "Civil service is community work a convicted slothful man might perform as punishment."),
        ("D", "typical_location", "Paraguay is a country, not the court-ordered activity for apathy-related crime."),
        ("E", "typical_location", "Costa Rica is a nation, not the mandated service for a slothful convicted man."),
    ],
    1514: [
        ("A", "part_whole", "Legs are body parts used for sitting, but a chair is not always required."),
        ("B", "part_whole", "A chair supports sitting, but getting comfortable while sitting does not always require one."),
        ("C", "property", "Laziness is unwillingness to act, not a physical requirement for sitting comfortably."),
        ("D", "typical_location", "The floor can support sitting, showing a chair is not always necessary for comfort."),
        ("E", "used_for", "Sit on describes the action, not a thing that is not always required for comfort."),
    ],
    1515: [
        ("A", "effect", "Getting tired is what the dog eventually does after chasing the ball repeatedly."),
        ("B", "effect", "The ball stopped is an object state, not what ends the dog's repeated chasing."),
        ("C", "effect", "Fall and hurt yourself is injury, not the typical end of a dog's ball chasing."),
        ("D", "capability", "Breathe is a constant body function, not what finally stops the repeated ball chasing."),
        ("E", "capability", "Catching the ball is the goal, but exhaustion eventually stops the repeated chasing."),
    ],
    1516: [
        ("A", "typical_location", "A workplace is for labor, not a place where humans typically go to relax."),
        ("B", "typical_location", "A park is a public green space where a human can relax outdoors."),
        ("C", "typical_location", "A church is for worship, which some find peaceful but parks are for relaxation."),
        ("D", "typical_location", "A war zone is dangerous conflict, the opposite of where a human would relax."),
        ("E", "typical_location", "A jail is confinement, not a place where a human can freely relax."),
    ],
    1517: [
        ("A", "typical_location", "A school has many people inside during class hours and school activities."),
        ("B", "typical_location", "A supermarket has many people standing inside while shopping for groceries."),
        ("C", "typical_location", "A street corner is outdoors, not where many people stand together inside."),
        ("D", "typical_location", "A public place is vague; supermarkets specifically have crowds standing inside."),
        ("E", "typical_location", "A space shuttle is a small vehicle, not where many people gather standing inside."),
    ],
    1518: [
        ("A", "property", "Room temperature describes mild heat, not what large water volumes do over long periods."),
        ("B", "effect", "Thin blood is a medical effect, unrelated to geological water erosion over time."),
        ("C", "effect", "Making parks is human landscaping, not a natural effect of water over long periods."),
        ("D", "effect", "Taking several forms describes phase changes, less iconic than erosion over long timescales."),
        ("E", "effect", "Large amounts of water over long periods can erode and move mountains."),
    ],
    1519: [
        ("A", "effect", "Getting drunk is a possible party outcome, not the specific opposite-sex social lead."),
        ("B", "effect", "Meeting new people happens at parties, but opposite-sex parties can lead further."),
        ("C", "effect", "Drinking beer is party behavior, not the distinctive outcome of opposite-sex socializing."),
        ("D", "effect", "Enjoying yourself is general fun, less specific than romantic outcomes with opposite sex."),
        ("E", "effect", "Going to a party with the opposite sex can lead to having sex afterward."),
    ],
}
