# -*- coding: utf-8 -*-
"""Hand-authored question-grounded commonsense knowledge for CSQA qids 920-1019.

Authored ONLY from each question's stem + options (never from answerKey).
Format:  CHUNK[qid] = [(option_label, dimension, fact), ...]
"""

CHUNK = {
    920: [
        ("A", "typical_location", "A hall is a broad passageway, not the specific business setting with a reception desk for meetings."),
        ("B", "typical_location", "A motel reception desk handles guest check-ins, not appointments with professionals in an office."),
        ("C", "typical_location", "Hotel lobbies serve travelers checking in, not visitors waiting for a scheduled business meeting."),
        ("D", "typical_location", "A law firm maintains a reception area where clients wait before seeing an attorney."),
        ("E", "typical_location", "An office building lobby has a reception area where visitors wait for scheduled meetings."),
    ],
    921: [
        ("A", "property", "Euphoria is an intense emotional high, not a basic physical skill taught in dance class."),
        ("B", "capability", "Rhythmic movement is the core bodily skill a dance instructor teaches struggling beginners."),
        ("C", "property", "Music is the accompaniment dancers move to, not the motor skill the instructor teaches."),
        ("D", "capability", "Moving the body is too general; instructors specifically drill timed, coordinated rhythmic steps."),
        ("E", "property", "Having fun is an attitude about dancing, not the foundational skill being taught."),
    ],
    922: [
        ("A", "typical_location", "A toy store is where toys are sold, not where a child leaves them at home."),
        ("B", "typical_location", "A home hallway is where scattered toys on the floor cause people to trip."),
        ("C", "typical_location", "A bathroom is for hygiene, not the usual place children leave stuffed animals lying about."),
        ("D", "typical_location", "An amusement park is a public venue, not where a mother trips over a child's toy at home."),
        ("E", "typical_location", "Fairgrounds are outdoor event spaces, not the indoor floor where a child left a stuffed animal."),
    ],
    923: [
        ("A", "used_for", "Gaining experience is a long-term outcome, not the immediate action needed to hear a lecture."),
        ("B", "used_for", "Taking notes records information but does not by itself ensure hearing what is said."),
        ("C", "used_for", "Listening carefully is the direct action a student takes to hear what the professor says."),
        ("D", "used_for", "Completing a test assesses knowledge after learning, not while trying to hear a lecture."),
        ("E", "capability", "Focus helps attention, but the question asks what the student actively does to hear speech."),
    ],
    924: [
        ("A", "property", "Working out describes the activity of running, not a feeling afterward."),
        ("B", "effect", "Muscles commonly feel sore after the exertion of a run."),
        ("C", "effect", "Getting tired describes fatigue, but soreness is the more specific post-run bodily feeling."),
        ("D", "effect", "Satisfaction is a possible emotion, but physical soreness is the typical sensation after running."),
        ("E", "property", "Falling down is an accident during a run, not a normal feeling after completing one."),
    ],
    925: [
        ("A", "typical_location", "Graduates may still visit a library; it is not what they stop attending upon graduation."),
        ("B", "typical_location", "Graduates can still attend parties; graduation does not end social gatherings."),
        ("C", "typical_location", "Kindergarten is early childhood education, not where a graduating student was enrolled."),
        ("D", "typical_location", "A bar is a social venue adults may still visit after graduating."),
        ("E", "typical_location", "A graduating student stops attending school because their formal enrollment ends."),
    ],
    926: [
        ("A", "used_for", "Shaking hands is a social greeting, not a universal adult obligation."),
        ("B", "has_prerequisite", "Owning property requires wealth many adults lack and is not universally expected."),
        ("C", "motivation", "Adults are routinely expected to pay bills for housing, utilities, and other expenses."),
        ("D", "property", "Smoking is a harmful habit, not something society expects of adults."),
        ("E", "used_for", "Talking to each other is casual social behavior, not a specific duty expected of all adults."),
    ],
    927: [
        ("A", "typical_location", "An antique store buys collectible old items, not broken appliances for disposal."),
        ("B", "typical_location", "A graveyard is for burying the dead, not for discarding broken household appliances."),
        ("C", "typical_location", "A kitchen is where an icebox is kept in use, not where a broken one is disposed of."),
        ("D", "typical_location", "A junk yard accepts broken appliances and other scrap for disposal or salvage."),
        ("E", "property", "Ice is frozen water, not a place or method for disposing of a broken refrigerator."),
    ],
    928: [
        ("A", "property", "Excellent describes high quality, not the trait of being open about one's flaws."),
        ("B", "property", "Fun describes enjoyment, not the honesty that made people appreciate her openness."),
        ("C", "property", "Honest means truthful and forthright, matching someone open about being badly behaved."),
        ("D", "property", "Worthy describes merit or value, not the transparency people found likable."),
        ("E", "property", "Choice is a selection or option, not a personality trait people admire."),
    ],
    929: [
        ("A", "typical_location", "The South Pacific is an ocean region, not a venue with a walk-through shark tunnel."),
        ("B", "typical_location", "SeaWorld aquariums feature clear underwater tunnels where visitors walk among sharks."),
        ("C", "typical_location", "The Pacific Ocean is open water, not an enclosed tunnel exhibit for viewing sharks."),
        ("D", "typical_location", "The Indian Ocean is a natural body of water without a built clear viewing tunnel."),
        ("E", "typical_location", "The Gulf of Mexico is a sea region, not an aquarium with a shark tunnel exhibit."),
    ],
    930: [
        ("A", "effect", "Being ordered describes receiving commands, not the benefit of choosing to queue up."),
        ("B", "effect", "Forming an orderly line reduces confusion about who goes next."),
        ("C", "effect", "Boredom is a possible downside of waiting, not the positive outcome of lining up."),
        ("D", "property", "Standing in line is the action itself, not the result that makes it the best choice."),
        ("E", "effect", "Having to wait is a cost of queuing, not the benefit Dan cited for getting in line."),
    ],
    931: [
        ("A", "typical_location", "Shopping mall theaters hire professional actors and charge admission."),
        ("B", "typical_location", "Hospitals do not typically host theaters with actors of any kind."),
        ("C", "property", "A populated area is a general description, not a venue known for unpaid theatrical performers."),
        ("D", "typical_location", "School theaters stage plays cast with unpaid student actors."),
        ("E", "typical_location", "A military base may have entertainment, but school plays are the classic unpaid-actor theater."),
    ],
    932: [
        ("A", "used_for", "Holding means keeping the object supported in an outstretched hand during the contest."),
        ("B", "used_for", "Lift up is an upward motion, not the sustained grip required with an arm extended."),
        ("C", "used_for", "Pick up is a one-time retrieval action, not maintaining an extended-arm grip on the object."),
        ("D", "used_for", "Lifting is raising something, not the steady grip needed while the arm stays straight out."),
        ("E", "used_for", "Hold onto is close in meaning but the contest phrasing pairs naturally with while holding."),
    ],
    933: [
        ("A", "motivation", "A guilty conscience drives some murderers to confess because the secret weighs on them."),
        ("B", "motivation", "Fear might coerce a confession under interrogation, but guilt is the internal reason to admit truth."),
        ("C", "effect", "Going free is the opposite of what confessing to murder typically brings."),
        ("D", "property", "Problems are vague difficulties, not the specific motive for admitting to murder."),
        ("E", "motivation", "Finding god is a spiritual turning point for some, but guilt is the more direct confession motive."),
    ],
    934: [
        ("A", "typical_location", "A concert is a live performance event, not something broadcast as tonight's TV program."),
        ("B", "typical_location", "An opera is staged live in a theater, not typically called a TV program saga."),
        ("C", "typical_location", "Theater refers to live stage performance, not a serialized show on television."),
        ("D", "used_for", "Take class describes attending instruction, not watching a long saga on a program."),
        ("E", "typical_location", "Television programs broadcast long-running serialized sagas viewers watch at home."),
    ],
    935: [
        ("A", "typical_location", "Grandma is a person who might own fabric, not a place to shop for quilting supplies."),
        ("B", "typical_location", "Clothing refers to finished garments, not raw velvet fabric for making a quilt."),
        ("C", "typical_location", "A jewelry store sells gems and accessories, not fabric for quilting."),
        ("D", "typical_location", "Clothes are finished wearable items, not the bolt of velvet needed for a quilt."),
        ("E", "typical_location", "A fabric store sells velvet and other textiles specifically for sewing and quilting projects."),
    ],
    936: [
        ("A", "property", "Maps show locations but are not themselves a convenient site for a bus station."),
        ("B", "typical_location", "A street is too vague; bus stops need a specific high-traffic central location."),
        ("C", "used_for", "Catch bus describes the rider's action, not a physical place for a bus station."),
        ("D", "typical_location", "A city centre concentrates commuters and transit routes, making it ideal for a bus station."),
        ("E", "typical_location", "A school may have a bus stop, but the city centre serves the widest ridership."),
    ],
    937: [
        ("A", "property", "A field is an open area of land, not a description of a modest number of people."),
        ("B", "property", "Alone means a single person, which contradicts the presence of any crowd at all."),
        ("C", "property", "A small group accurately describes a crowd that was not very large."),
        ("D", "property", "Solitude is the state of being alone, not a label for a modest gathering of people."),
        ("E", "property", "Solitary describes one isolated individual, not a group that was merely smaller than expected."),
    ],
    938: [
        ("A", "typical_location", "A table is where silverware is laid out for immediate use at a meal."),
        ("B", "typical_location", "A restaurant is a commercial dining venue, not where home silverware is stored."),
        ("C", "typical_location", "A cupboard stores clean dry silverware until it is needed for the next meal."),
        ("D", "typical_location", "A kitchen is the whole room; the cupboard within it is where dried silverware is kept."),
        ("E", "typical_location", "A sink is where dishes are washed and dried, not where clean silverware is stored afterward."),
    ],
    939: [
        ("A", "typical_location", "A chicken coop houses live hens that lay eggs, not store-bought eggs from a market."),
        ("B", "typical_location", "A supermarket is where eggs are purchased, not where they are kept after bringing them home."),
        ("C", "typical_location", "A box is a generic container; eggs from a store are specifically held in molded cartons."),
        ("D", "typical_location", "An egg carton is the molded container eggs are sold in and stored in at home."),
        ("E", "typical_location", "A henhouse shelters laying hens outdoors, not packaged eggs bought at a grocery store."),
    ],
    940: [
        ("A", "typical_location", "Kept at accountant is a phrase, not a standard place one leaves a personal account book."),
        ("B", "typical_location", "A purse is carried when leaving, so an account book there would travel with you."),
        ("C", "typical_location", "A desk drawer is where an account book is safely left when you depart without needing it."),
        ("D", "typical_location", "A bank holds money and records, not a personal ledger you leave behind when leaving."),
        ("E", "used_for", "Keeping track of expenses describes using the book, not where to leave it when departing."),
    ],
    941: [
        ("A", "used_for", "Hanging smelly clothes in a closet traps odors rather than removing them without washing."),
        ("B", "used_for", "Sniffing detects odor but does not freshen clothes that cannot be washed."),
        ("C", "effect", "Getting dirty makes clothes worse, the opposite of fixing an existing smell problem."),
        ("D", "effect", "Becoming soiled adds grime and odor rather than resolving a smell when washing is impossible."),
        ("E", "used_for", "Airing out clothes exposes them to fresh air to dissipate odor without washing."),
    ],
    942: [
        ("A", "effect", "Exhilaration is the thrilling rush of excitement commonly felt while playing football."),
        ("B", "effect", "Pain is a possible sensation, but exhilaration captures the primary feeling of active play."),
        ("C", "property", "Death is not a feeling experienced during a normal game of football."),
        ("D", "effect", "Getting hurt describes injury during play, not the overall feeling of participating in the sport."),
        ("E", "effect", "Get hurt is an injury outcome, not the emotional sensation of playing the game."),
    ],
    943: [
        ("A", "property", "Sanded describes smoothing wood with abrasive paper, not the fossilization process paleontologists name."),
        ("B", "property", "Composted means broken down into organic matter, the opposite of mineralized fossil wood."),
        ("C", "property", "Warp describes bent or twisted wood, not the term for wood turned to stone."),
        ("D", "property", "Hardened is vague; paleontologists use a specific term for wood replaced by minerals."),
        ("E", "property", "Petrify is the term paleontologists use for wood that has become fossilized stone."),
    ],
    944: [
        ("A", "typical_location", "A thrift store may sell used teddy bears but is not the primary retail destination for buying one new."),
        ("B", "typical_location", "A bed is furniture for sleeping, not a place to purchase a teddy bear."),
        ("C", "typical_location", "A shelf displays items already owned, not a shop where teddy bears are sold."),
        ("D", "typical_location", "A home is where a teddy bear is kept after purchase, not where it is bought."),
        ("E", "typical_location", "A toy store sells stuffed animals including teddy bears as its primary merchandise."),
    ],
    945: [
        ("A", "property", "Intelligence is a cognitive trait, not something caused by an inability to learn."),
        ("B", "property", "Education is an outcome of learning, not a consequence of being unable to learn."),
        ("C", "effect", "Effectiveness may decline, but emotional distress is the direct psychological result of failing to learn."),
        ("D", "effect", "Inability to learn commonly causes frustration and distress in the person struggling."),
        ("E", "property", "A stupid is a pejorative label for a person, not an effect caused by learning failure."),
    ],
    946: [
        ("A", "used_for", "School children are the primary beneficiaries when the government funds and supports public schools."),
        ("B", "used_for", "Parents benefit indirectly, but the government's school aid chiefly serves enrolled students."),
        ("C", "used_for", "Get money describes a financial action, not a group the government helps through schools."),
        ("D", "used_for", "Require to pay taxes describes citizen obligation, not who receives government school assistance."),
        ("E", "used_for", "Take money describes collecting revenue, not the population the government aids via schools."),
    ],
    947: [
        ("A", "typical_location", "A lost dog might eventually return home, but the question asks where it would likely be found regionally."),
        ("B", "typical_location", "Old England refers to Britain, a different region from New England in America."),
        ("C", "typical_location", "New Hampshire is a state within New England where a lost small dog would likely be found."),
        ("D", "typical_location", "A coffin holds the deceased, not a place a living lost dog would be discovered."),
        ("E", "typical_location", "Denmark is a European country, not part of the New England region where the dog was lost."),
    ],
    948: [
        ("A", "used_for", "Tighten means making something firmer, not the method for joining loose papers together."),
        ("B", "used_for", "Packaged means wrapped for shipping, not binding loose sheets into a single unit."),
        ("C", "used_for", "Bound means fastening loose papers together with staples, clips, or binding."),
        ("D", "property", "Faithful describes loyalty, unrelated to holding loose papers together."),
        ("E", "used_for", "Compact means compressing into a smaller form, not fastening separate sheets together."),
    ],
    949: [
        ("A", "used_for", "God is a deity, not the conversational partner for people chatting on a street corner."),
        ("B", "property", "Mix is not a noun describing who people talk with on a corner."),
        ("C", "used_for", "With people correctly identifies that corner conversations happen between people and other people."),
        ("D", "property", "Have friends describes a social state, not the immediate partners in a corner conversation."),
        ("E", "used_for", "See people describes visual contact, not the act of talking with someone on a corner."),
    ],
    950: [
        ("A", "property", "Gorgeous describes striking beauty, not the relief of no longer being the only ugly person."),
        ("B", "property", "Handsome describes attractive appearance, not blending in when someone equally plain is found."),
        ("C", "property", "Pleasing can describe the comfort of no longer being the one who stands out as ugly."),
        ("D", "property", "Glorious describes magnificence, unrelated to finding someone equally unattractive."),
        ("E", "property", "Pretty beautiful describes attractiveness, the opposite of the ugly appearance described."),
    ],
    951: [
        ("A", "motivation", "Bands love hearing the crowd go mad with excitement at the start of every concert."),
        ("B", "used_for", "Working hard describes effort, not the celebratory moment that opens a show."),
        ("C", "used_for", "Clapping is what the audience does, not what the band itself loves to do at the start."),
        ("D", "used_for", "Reproduce means copying or breeding, unrelated to opening a concert with fans."),
        ("E", "motivation", "Celebrate is close, but the band specifically feeds off the crowd's explosive reaction."),
    ],
    952: [
        ("A", "used_for", "Obtaining information is one-directional gathering, not the mutual back-and-forth of brainstorming."),
        ("B", "used_for", "Exchange of ideas is the defining activity of a brainstorming session alongside open talking."),
        ("C", "used_for", "Sharing information is close, but brainstorming emphasizes trading and building on each other's ideas."),
        ("D", "used_for", "Conversation is too general and does not capture the creative idea-trading purpose of brainstorming."),
        ("E", "used_for", "Gathering of information is passive collection, not the collaborative idea generation in brainstorming."),
    ],
    953: [
        ("A", "used_for", "Measure distance is what a ruler does, not a place where many rulers owned by different people exist."),
        ("B", "typical_location", "England is a country, not a location where multiple people's rulers are stored together."),
        ("C", "typical_location", "An office has many employees, each keeping their own ruler at their desk or drawer."),
        ("D", "typical_location", "A single drawer typically holds one person's ruler, not rulers belonging to many different owners."),
        ("E", "typical_location", "A desk usually belongs to one person, not a collection of rulers from different owners."),
    ],
    954: [
        ("A", "motivation", "Neatness is a benefit of grooming but cleanliness is the primary reason it is recommended to greasy teens."),
        ("B", "property", "Selfishness is unrelated to why grooming is advised for teenagers with oily skin and hair."),
        ("C", "property", "Mistakes are errors, not the reason grooming is recommended for greasy adolescents."),
        ("D", "motivation", "Cleanliness is the main reason grooming is recommended to greasy teens who need better hygiene."),
        ("E", "effect", "Satisfaction may follow grooming, but cleanliness is the reason it is recommended in the first place."),
    ],
    955: [
        ("A", "typical_location", "Detroit is a city, not a specific type of place to purchase barbecue sauce bottles."),
        ("B", "typical_location", "Australia is a country, not a retail destination for buying barbecue sauces."),
        ("C", "typical_location", "Michigan park is a recreational area, not a shop that sells condiments."),
        ("D", "typical_location", "A cafe serves prepared food and drinks, not bottled barbecue sauces for home use."),
        ("E", "typical_location", "A retail store sells packaged goods including bottles of barbecue sauce."),
    ],
    956: [
        ("A", "typical_location", "A refrigerator keeps food cold, not a place to view a mammoth skeleton in New York City."),
        ("B", "typical_location", "A museum exhibit could show a mammoth, but NYC's natural history museum is the specific answer."),
        ("C", "typical_location", "Prehistoric times is an era, not a place you can visit to see a mammoth in NYC today."),
        ("D", "typical_location", "The Museum of Natural History in NYC displays mammoth fossils in its permanent exhibits."),
        ("E", "typical_location", "A forest in NYC has no wild mammoths; they have been extinct for thousands of years."),
    ],
    957: [
        ("A", "used_for", "Eaten describes consuming food, not storing olives to keep them from wetting nearby items."),
        ("B", "property", "Glasses are eyewear, unrelated to storing olives away from other food."),
        ("C", "used_for", "A jar holds olives in brine, keeping their moisture contained and away from nearby food."),
        ("D", "typical_location", "Pizza is a dish olives may top, not a container that prevents them from wetting other food."),
        ("E", "typical_location", "A refrigerator stores food cold but a sealed jar specifically isolates olive brine from other items."),
    ],
    958: [
        ("A", "used_for", "Sit is the basic action expected of guests at a formal dining setting before eating."),
        ("B", "used_for", "Being sociable describes manner, not the primary physical action at a formal meal."),
        ("C", "used_for", "Talk may occur at dinner, but sitting down is the first expected action at a formal table."),
        ("D", "used_for", "Drinking may happen during a meal, but guests are first expected to sit at the table."),
        ("E", "property", "Medium is not an action performed when having food at a formal place."),
    ],
    959: [
        ("A", "property", "A lake can be very deep and is not characteristically shallow compared to smaller water bodies."),
        ("B", "typical_location", "Aquariums are artificial tanks, not natural bodies of water typically described as shallow."),
        ("C", "typical_location", "A swimming pool has a designed depth, not a natural shallow body of water."),
        ("D", "property", "A pond is a small natural body of water that is characteristically shallow."),
        ("E", "typical_location", "Children's pools are tiny artificial pools, not a natural body of water."),
    ],
    960: [
        ("A", "used_for", "Like more is a social-media action, not a universal gesture of agreement."),
        ("B", "used_for", "Nodding the head is a widely recognized nonverbal signal that you agree with someone."),
        ("C", "used_for", "Wearing rings is jewelry fashion, not a gesture indicating agreement with someone's statement."),
        ("D", "property", "Concordance is a noun meaning agreement, not an action you perform to show it."),
        ("E", "used_for", "Shaking hands seals greetings or deals, not the typical gesture for signaling agreement mid-conversation."),
    ],
    961: [
        ("A", "effect", "Pressure from constant competition can make someone want to stop competing altogether."),
        ("B", "property", "Death is not a feeling someone experiences when deciding to quit competing."),
        ("C", "used_for", "Trying harder is an intensified effort, the opposite of wanting to stop competing."),
        ("D", "property", "Quitting is the action of stopping, not the feeling that motivates the decision."),
        ("E", "property", "Winning or losing describes outcomes, not the internal feeling behind wanting to quit."),
    ],
    962: [
        ("A", "typical_location", "Water is a drink, not the body opening where food and germs enter during eating."),
        ("B", "typical_location", "A doctor is a medical professional, not the body part where germs enter with food."),
        ("C", "effect", "Spread disease is a consequence of germs, not the body opening where they enter."),
        ("D", "typical_location", "The mouth is where chewed food and accompanying germs enter the body during eating."),
        ("E", "typical_location", "The ear is not involved in eating food and does not receive germs from meals."),
    ],
    963: [
        ("A", "typical_location", "A public building is a broad category, not the ancient buried structure explorers seek via passages."),
        ("B", "typical_location", "Explorers following a central passage commonly discover an ancient buried tomb at its end."),
        ("C", "typical_location", "An arena is an open performance space, not typically reached through a secret central passage."),
        ("D", "typical_location", "A large building is too vague; explorers in passages specifically seek ancient burial sites."),
        ("E", "typical_location", "Treasure may lie inside, but the passage characteristically leads to an ancient buried tomb."),
    ],
    964: [
        ("A", "typical_location", "A park may contain rosebushes, but hedgerows are the linear feature they are planted along."),
        ("B", "typical_location", "In the ground is too generic; rosebushes specifically line certain landscape features."),
        ("C", "typical_location", "Rosebushes are commonly planted along a hedgerow that forms a living boundary."),
        ("D", "property", "Temperate climate describes a region's weather, not a physical feature along which rosebushes grow."),
        ("E", "typical_location", "Botanical gardens display rosebushes but hedgerows are the classic linear feature they border."),
    ],
    965: [
        ("A", "typical_location", "A closet stores clothes at home, not luggage being driven to the airport."),
        ("B", "typical_location", "At hotel is where luggage stays during a trip, not while driving oneself to the airport."),
        ("C", "typical_location", "A sidewalk is for pedestrians, not where luggage is placed during a drive to the airport."),
        ("D", "typical_location", "A bus stop is a transit waiting point, not where a driver stores luggage en route to the airport."),
        ("E", "typical_location", "The trunk of a car is where a driver puts luggage while driving to the airport."),
    ],
    966: [
        ("A", "effect", "Receiving an uncommon gift makes the recipient feel special and valued."),
        ("B", "property", "Personal describes the gift's nature, not the feeling the recipient experiences upon receiving it."),
        ("C", "effect", "Offended is the opposite reaction to getting a thoughtful uncommon gift."),
        ("D", "property", "Unique describes the gift itself, not the emotional feeling of the person who receives it."),
        ("E", "property", "Rare describes scarcity of the gift, not the warm feeling it inspires in the recipient."),
    ],
    967: [
        ("A", "typical_location", "A music shop sells instruments but is not where the banjo is most culturally famous."),
        ("B", "typical_location", "A music store sells instruments, not the region where the banjo gained its greatest fame."),
        ("C", "typical_location", "A jug band is a musical group, not the place where the banjo is most renowned."),
        ("D", "typical_location", "The banjo is most famously associated with American folk and bluegrass music in the United States."),
        ("E", "property", "Among nice people is a vague social phrase, not a region known for banjo music."),
    ],
    968: [
        ("A", "effect", "Reading extremely small print letter by letter causes eye strain from prolonged focusing effort."),
        ("B", "property", "Though is a conjunction, not a physical condition caused by reading tiny text."),
        ("C", "effect", "Happiness is a positive emotion unrelated to the discomfort of reading very small print."),
        ("D", "effect", "Realization is a mental insight, not the physical eye condition from reading tiny letters."),
        ("E", "effect", "Understanding is comprehension of content, not the ocular fatigue from small print."),
    ],
    969: [
        ("A", "effect", "A nice feeling is a surface emotion, not the hidden karmic force forgiveness may activate."),
        ("B", "effect", "Good karma is the hidden spiritual force believers say forgiveness releases into one's life."),
        ("C", "effect", "Respect from others is a social outcome, not the hidden force the question asks about."),
        ("D", "effect", "New freedom is a personal benefit, but good karma is the hidden force linked to forgiveness."),
        ("E", "property", "A good heart describes character, not a hidden force activated by forgiving others."),
    ],
    970: [
        ("A", "property", "Happiness is an emotion, not a baseball statistic tracking fielding mistakes."),
        ("B", "property", "Sore muscles result from exertion, not a stat recorded for defensive errors in baseball."),
        ("C", "property", "Injury is physical harm, not the name of the statistic for mistakes in the field."),
        ("D", "property", "Perfection means flawlessness, the opposite of the stat that counts mistakes."),
        ("E", "property", "Errors is the baseball statistic that records mistakes made by fielders during a game."),
    ],
    971: [
        ("A", "has_prerequisite", "Relaxing helps clear the mind, a common first step before beginning to create art."),
        ("B", "property", "Controversy is public dispute, not a prerequisite action for starting to make art."),
        ("C", "property", "Pleasure may follow creating art, but one must first settle in before beginning."),
        ("D", "property", "Frustration is a negative emotion, not what someone needs to do to start creating art."),
        ("E", "has_prerequisite", "Needs theater describes a venue requirement, not a universal step to begin creating art."),
    ],
    972: [
        ("A", "typical_location", "A grand casino hosts events but is not the generic space needed for a large reception."),
        ("B", "typical_location", "A large room provides the space needed to accommodate many people at a reception."),
        ("C", "typical_location", "A restaurant may host receptions but a large room is the essential requirement for capacity."),
        ("D", "typical_location", "A country club is one venue option, but any large room suffices for many attendees."),
        ("E", "typical_location", "A lobby is an entry area, often too small for a reception with many people attending."),
    ],
    973: [
        ("A", "used_for", "Inking in means refilling a dry pen with ink so it will write again."),
        ("B", "used_for", "Caps protect pen tips but removing a cap does not fix a pen that has run out of ink."),
        ("C", "used_for", "Ink cartridges belong to printers, not the ballpoint pens people use to take notes."),
        ("D", "used_for", "Take notes is what working pens are for, not the fix for pens that will not write."),
        ("E", "used_for", "Scribbling tests whether a pen writes, but refilling ink is what fixes a dry one."),
    ],
    974: [
        ("A", "primary_function", "Builders construct buildings from plans, but they do not design the structure itself."),
        ("B", "property", "A driver operates vehicles, not the professional who plans and designs buildings."),
        ("C", "primary_function", "An architect is the professional trained to design buildings and create their plans."),
        ("D", "property", "Fall down describes structural collapse, not a person who designs buildings."),
        ("E", "primary_function", "Tradesmen perform specialized construction tasks, not the overall design of a building."),
    ],
    975: [
        ("A", "typical_location", "A lake may contain a bay, but bays are found along shorelines of larger water bodies."),
        ("B", "typical_location", "Manhattan is an island borough, not the geographic feature where bays are always located."),
        ("C", "typical_location", "A bay is a coastal indentation always found along a shoreline where land meets water."),
        ("D", "typical_location", "A coastal area is the broader region, but a bay specifically lies along the shoreline itself."),
        ("E", "typical_location", "Los Angeles is a city, not the geographic feature along which bays are always found."),
    ],
    976: [
        ("A", "used_for", "Sailing boats is a pastime done while traveling along the surface of liquid water."),
        ("B", "used_for", "Question authority is a political act, not a leisure activity on water."),
        ("C", "used_for", "High fives are celebratory gestures, not a pastime associated with traveling on liquid."),
        ("D", "used_for", "Share things describes generosity, not a recreational activity done while moving on water."),
        ("E", "used_for", "Learn from each other is educational, not the pastime of traveling along a body of liquid."),
    ],
    977: [
        ("A", "typical_location", "A downtown area may have theaters, but malls specifically combine cinemas with many stores."),
        ("B", "typical_location", "An urban area is a broad region, not one place combining a theater and other shops."),
        ("C", "typical_location", "New York City is a metropolis, not a single location housing a theater alongside other stores."),
        ("D", "typical_location", "A shopping mall combines a movie theater with many retail stores under one roof."),
        ("E", "typical_location", "A military base has restricted facilities, not a public mall with a cinema and shops."),
    ],
    978: [
        ("A", "typical_location", "A jewelry store sells new watches, not where someone hocks a used watch for cash."),
        ("B", "property", "A case holds a watch, not the action of selling it for quick money."),
        ("C", "used_for", "To hock means to pawn an item, but pawn is the more standard verb in this context."),
        ("D", "typical_location", "A watch store sells timepieces, not where someone pawns a watch for drug money."),
        ("E", "used_for", "To pawn a wristwatch means selling it at a pawnshop for immediate cash."),
    ],
    979: [
        ("A", "typical_location", "Walmart sells some flooring, but it is not the primary destination for buying floor materials."),
        ("B", "typical_location", "A loft is an upper floor space, not a store where flooring is purchased."),
        ("C", "typical_location", "A house is where flooring is installed, not where it is bought."),
        ("D", "typical_location", "Home Depot is a home-improvement store that sells flooring materials."),
        ("E", "typical_location", "A kitchen is a room that may have flooring, not a place to shop for floor materials."),
    ],
    980: [
        ("A", "effect", "Tiredness is felt before sleep, not the physiological change occurring during the act of waking."),
        ("B", "effect", "Grogginess follows awakening, but the awakening process itself involves the eyes opening."),
        ("C", "effect", "Discomfort is a general unpleasant feeling, not the specific physiological sign of waking up."),
        ("D", "used_for", "Getting out of bed is a physical action after waking, not what happens during awakening itself."),
        ("E", "effect", "Eyes opening is the physiological change that occurs as a person is awakening from sleep."),
    ],
    981: [
        ("A", "effect", "Getting arrested is an unwanted legal consequence, not a reason someone buys beer."),
        ("B", "property", "Problems are difficulties, not the motivation for purchasing beer."),
        ("C", "property", "Sober describes abstaining from alcohol, the opposite of why someone buys beer."),
        ("D", "motivation", "Intoxication is the state of being drunk, a common reason people buy beer."),
        ("E", "motivation", "Pleasure from social drinking is a reason, but intoxication is the direct sought effect of beer."),
    ],
    982: [
        ("A", "property", "A vessel is a ship or container, not a type of radio used to contact a base."),
        ("B", "property", "A box is a container, not a radio device for reaching a base station."),
        ("C", "primary_function", "A transistor radio is a portable two-way radio used to communicate with a base station."),
        ("D", "property", "A submarine is an underwater craft, not the radio device used to reach base from it."),
        ("E", "property", "A lamp provides light, not radio communication with a base."),
    ],
    983: [
        ("A", "effect", "Smelling smoke may accompany burning, but the pizza itself becomes burnt after an hour in the oven."),
        ("B", "effect", "Catch cold is an illness unrelated to leaving a pizza in an oven for an hour."),
        ("C", "effect", "A pizza left in a hot oven for an hour becomes burnt and inedible."),
        ("D", "effect", "Looking angry is an emotional expression, not what happens to a pizza after an hour in the oven."),
        ("E", "property", "Bank savings are financial assets, unrelated to cooking a pizza in an oven."),
    ],
    984: [
        ("A", "capability", "Lie down is a resting posture wild animals may take, not a danger to humans who touch them."),
        ("B", "effect", "Run away is flight behavior, not the harm a wild animal could inflict on someone who touches it."),
        ("C", "capability", "Wild animals could bite a person who touches them, causing serious injury."),
        ("D", "effect", "Keep alive describes survival, not a threat posed to someone touching a wild animal."),
        ("E", "effect", "Feel pain is what the animal might feel, not the danger warned about for the person touching it."),
    ],
    985: [
        ("A", "effect", "Satisfaction is a positive outcome, opposite to what Danny's hatred of helping always brought."),
        ("B", "effect", "Good feelings are positive, but Danny's aversion to helping consistently produced negative outcomes."),
        ("C", "effect", "Complications are hassles, but stress better captures the persistent burden Danny experienced from helping."),
        ("D", "effect", "Feel good about yourself is positive self-regard, not what Danny's hated helping brought him."),
        ("E", "effect", "Stress and frustration consistently followed Danny's reluctant efforts to help other people."),
    ],
    986: [
        ("A", "has_prerequisite", "Owning a house requires capital and does not solve the problem of low pay at one's current job."),
        ("B", "motivation", "A better job is what someone needs when they cannot earn more at their current position."),
        ("C", "motivation", "Winning the lottery is unlikely and not a practical step for someone seeking higher income."),
        ("D", "used_for", "Saving money helps finances but does not increase earnings when the current job pays too little."),
        ("E", "effect", "Feeling safe is emotional security, not the solution to being unable to earn more at one's job."),
    ],
    987: [
        ("A", "property", "Plain describes flat terrain or bland taste, not what happens after seeing clouds overhead."),
        ("B", "effect", "Cold weather may follow certain clouds, but rain from overhead clouds makes you wet."),
        ("C", "property", "Dull describes boredom or lack of shine, not a consequence of clouds passing above."),
        ("D", "property", "Bad is too vague; beautiful clouds above commonly foreshadow rain that makes you wet."),
        ("E", "effect", "Beautiful clouds overhead often signal approaching rain that leaves you wet."),
    ],
    988: [
        ("A", "typical_location", "A zoo in a large northeastern city is the dedicated place to see many animal species."),
        ("B", "typical_location", "A workplace is for employment, not the primary place city residents go to see animals."),
        ("C", "typical_location", "The sky may have birds, but a zoo is where people go specifically to see animals."),
        ("D", "typical_location", "New York City is the city itself, not the specific venue within it for viewing animals."),
        ("E", "property", "Many places is too vague; a zoo is the standard destination for seeing animals in a big city."),
    ],
    989: [
        ("A", "used_for", "Make noise is disruptive behavior, not a typical activity performed inside a bank."),
        ("B", "used_for", "Have tea is a casual refreshment, not a standard banking activity."),
        ("C", "used_for", "Make time is an idiom for scheduling, not something people do as a banking service."),
        ("D", "used_for", "Make payments is a core banking activity such as paying bills or transferring funds."),
        ("E", "used_for", "Take time is an idiom for proceeding slowly, not an activity associated with visiting a bank."),
    ],
    990: [
        ("A", "typical_location", "Eyes can develop fungal infections, but the question asks about fungus on a milk product."),
        ("B", "typical_location", "A biology laboratory may culture fungus, not the everyday place it grows on milk products."),
        ("C", "typical_location", "A shower stall grows mold from moisture, not on products made from milk."),
        ("D", "typical_location", "Old cheese made from milk commonly develops surface fungus and mold as it ages."),
        ("E", "typical_location", "Decaying matter may host fungus, but old cheese is the classic milk product where it grows."),
    ],
    991: [
        ("A", "typical_location", "Pet shops sell snakes as pets, not the warm sunny habitat a snake would choose to live in."),
        ("B", "typical_location", "New Mexico has warm, sunny desert climate ideal for a snake preferring hot weather."),
        ("C", "typical_location", "The White House is a government building, not a natural habitat for a warmth-loving snake."),
        ("D", "typical_location", "The Arctic is bitterly cold, the opposite of the warm sunny climate a snake prefers."),
        ("E", "typical_location", "The Garden of Eden is a biblical setting, not a real warm habitat for snakes."),
    ],
    992: [
        ("A", "typical_location", "A cupboard stores kitchen items but John wants to leave the plastic-filled kitchen entirely."),
        ("B", "motivation", "Anywhere else expresses John's wish to be away from the kitchen full of plastic he dislikes."),
        ("C", "property", "Everything is too broad a word, not a place John would prefer to be instead."),
        ("D", "typical_location", "Own home is where John already is; he wishes to be somewhere other than this kitchen."),
        ("E", "typical_location", "A garbage dump is for waste disposal, not where someone would want to live instead."),
    ],
    993: [
        ("A", "used_for", "Eat cake is consuming dessert, not the consideration when examining an item in a shop."),
        ("B", "motivation", "Buy is what she is considering after examining the thing, deciding whether to purchase it."),
        ("C", "property", "Interests describes hobbies, not the purchasing decision under consideration."),
        ("D", "property", "Complex describes difficulty, not an action she considers when examining something."),
        ("E", "motivation", "Learn about applies to research, but examining an item in a shop usually precedes a buy decision."),
    ],
    994: [
        ("A", "part_whole", "An airplane has metal components, but cars are most people's preferred daily transportation."),
        ("B", "typical_location", "A construction site uses metal rods in building, not inside personal transportation."),
        ("C", "typical_location", "Shops sell goods, not the metal rods inside a person's preferred vehicle."),
        ("D", "part_whole", "A car engine contains metal connecting rods, found in most people's preferred transportation."),
        ("E", "property", "A broken bone is an injury, not a metal rod inside a method of transportation."),
    ],
    995: [
        ("A", "property", "Tenacity is persistence, not the physical means needed to balance a cup with nothing beneath it."),
        ("B", "capability", "Hands are what a person uses to steady and balance a cup when no surface supports it."),
        ("C", "used_for", "A coaster protects table surfaces, but he already placed the cup directly on the table."),
        ("D", "capability", "Skill in balancing might help, but lacking hands is the fundamental barrier to holding a cup steady."),
        ("E", "property", "Breaking is destruction, not the ability needed to keep a cup from tipping over."),
    ],
    996: [
        ("A", "typical_location", "An art show displays artwork, not the typical place to purchase a glass of wine."),
        ("B", "typical_location", "A basement is a lower level of a building, not where wine is sold by the glass."),
        ("C", "typical_location", "A bar sells alcoholic drinks including wine by the glass to customers."),
        ("D", "typical_location", "A church may serve communion wine, not sell a glass of wine as a commercial purchase."),
        ("E", "typical_location", "A basement is a room below ground, not a commercial venue for buying wine."),
    ],
    997: [
        ("A", "typical_location", "A place of work is for employment, not primarily for enjoying another person's company."),
        ("B", "typical_location", "An office is a professional setting, not the typical place for social companionship."),
        ("C", "typical_location", "A friend's house is a comfortable setting for enjoying another human's company."),
        ("D", "typical_location", "A workplace focuses on tasks, not on leisurely enjoyment of another person's company."),
        ("E", "typical_location", "Deep thought is solitary introspection, not a place to enjoy another person's company."),
    ],
    998: [
        ("A", "used_for", "Coffee is a common breakfast beverage paired with eggs and toast in the morning."),
        ("B", "effect", "Throw up is vomiting, not a normal drink choice alongside eggs and toast at breakfast."),
        ("C", "property", "Food is what you eat, not the beverage Brad would order to drink with breakfast."),
        ("D", "effect", "Getting drunk is intoxication, inappropriate for a breakfast meal of eggs and toast."),
        ("E", "used_for", "Wine is an alcoholic drink rarely chosen as a breakfast beverage with eggs and toast."),
    ],
    999: [
        ("A", "typical_location", "A health club serves green smoothies and has locker rooms where members change after workouts."),
        ("B", "property", "Jocks is a slang term for athletes, not a place with locker rooms and green drinks."),
        ("C", "typical_location", "A fitness centre serves health drinks and has locker rooms for members after exercising."),
        ("D", "typical_location", "A stadium hosts sports events but locker rooms with green health drinks are found at gyms."),
        ("E", "typical_location", "A gymnasium has locker rooms, and members may grab a green health drink before heading there."),
    ],
    1000: [
        ("A", "effect", "Live forever is impossible; motivated people needing money instead work to earn it."),
        ("B", "effect", "Getting sick is illness, not what motivated people do when they need money."),
        ("C", "used_for", "Work hard is what motivated people do when they need to earn money."),
        ("D", "effect", "Fall in love is a romantic outcome, not the action driven by needing money."),
        ("E", "effect", "Feel comfortable is a state of ease, not what financial need drives motivated people to do."),
    ],
    1001: [
        ("A", "property", "Family implies close kinship, more intimate than someone spoken to only occasionally."),
        ("B", "property", "A known person is someone familiar but not close, matching someone who is not a stranger yet rarely spoken to."),
        ("C", "property", "A friend implies regular contact and closeness beyond merely not being a stranger."),
        ("D", "property", "A relative is a family member, suggesting closer ties than someone rarely spoken to."),
        ("E", "property", "A crowd is a large group of people, not a description of one individual's relationship level."),
    ],
    1002: [
        ("A", "used_for", "Dance is a performing art, not the training needed to learn structural bridge engineering."),
        ("B", "used_for", "Talk is communication, not the educational path for learning how to build bridges."),
        ("C", "used_for", "Study engineering is the academic path a student follows to learn how to build bridges."),
        ("D", "used_for", "Play piano is a musical skill, unrelated to learning bridge construction."),
        ("E", "used_for", "Answer question responds to inquiry, not the learning process for bridge building."),
    ],
    1003: [
        ("A", "typical_location", "Commuters commonly read newspapers while riding the subway to work."),
        ("B", "typical_location", "A front door is an entrance, not where people ride and read during a commute."),
        ("C", "typical_location", "A lawn is outdoor grass, not a transit setting for reading on the way to work."),
        ("D", "typical_location", "A bookstore sells newspapers but is not where people read them while commuting."),
        ("E", "typical_location", "A library is for quiet reading on site, not reading while riding transit to work."),
    ],
    1004: [
        ("A", "typical_location", "A utility closet in a school stores janitorial supplies including buckets of sawdust."),
        ("B", "typical_location", "A well is a water source, not where a school janitor keeps cleanup supplies."),
        ("C", "typical_location", "A garden shed is outdoors at home, not inside a school cafeteria cleanup area."),
        ("D", "typical_location", "A pantry stores food, not janitorial sawdust buckets in a school building."),
        ("E", "typical_location", "A cupboard in a kitchen holds dishes, not a janitor's sawdust bucket in a cafeteria."),
    ],
    1005: [
        ("A", "effect", "Housework can leave you tired afterward without necessarily causing any pain."),
        ("B", "effect", "Stress is psychological strain, distinct from the physical pain the question excludes."),
        ("C", "used_for", "Put on shoes is a preparation step, not a result of completing housework."),
        ("D", "effect", "Backache is physical pain, which the question specifically says does not occur."),
        ("E", "property", "Low pay describes wages, not an outcome of doing housework at home."),
    ],
    1006: [
        ("A", "effect", "Rain would make a wet marmoset even wetter, not happy."),
        ("B", "typical_location", "France is a country, not a condition that would cheer up a wet marmoset."),
        ("C", "typical_location", "A shopping mall is an indoor retail space, not what a wet marmoset needs to dry off."),
        ("D", "effect", "A warm climate would help a wet marmoset dry off and feel comfortable again."),
        ("E", "typical_location", "The great outdoors is too broad; a warm climate specifically addresses being wet and cold."),
    ],
    1007: [
        ("A", "property", "Difficult for students describes a challenge, not why people join math competitions."),
        ("B", "motivation", "Fun is a reason people enter math competitions because they enjoy working on problems."),
        ("C", "property", "Class refers to a course or group, not the enjoyment that draws people to math competitions."),
        ("D", "property", "Class duplicated again refers to a course, not the appeal of math competitions."),
        ("E", "motivation", "Interesting captures appeal, but fun more directly describes why enthusiasts join competitions."),
    ],
    1008: [
        ("A", "effect", "People celebrating in a bar sometimes drink too much alcohol during the festivities."),
        ("B", "used_for", "Eat cake is party food, less typical of bar celebrations than excessive drinking."),
        ("C", "effect", "Getting drunk is similar, but drink too much is the common phrase for bar celebration excess."),
        ("D", "used_for", "Eat cake duplicated is dessert consumption, not the hallmark of bar celebrations."),
        ("E", "effect", "Having sex is private behavior, not the common public activity during bar celebrations."),
    ],
    1009: [
        ("A", "cause", "Direct sunlight comes from above outdoors, not from something encountered unexpectedly underground."),
        ("B", "cause", "Brightness is vague; underground one shields eyes from an unexpectedly bright artificial light source."),
        ("C", "cause", "Moonlight is faint and occurs outdoors at night, not underground where Sam needed shade."),
        ("D", "cause", "Full sunlight is outdoor daylight, not the surprising glare found in an underground space."),
        ("E", "cause", "Underground Sam shaded his eyes from an unexpectedly bright light he did not expect below ground."),
    ],
    1010: [
        ("A", "property", "Children are minors who are not legally or developmentally expected to engage in sexual activity."),
        ("B", "property", "Orgasm is a physiological response, not a category of person who has or avoids sex."),
        ("C", "property", "Pregnancy is a condition resulting from sex, not a person unlikely to have it."),
        ("D", "property", "Human is the species category; most adult humans are capable of sexual activity."),
        ("E", "property", "Herpes is a sexually transmitted disease, not a person unlikely to have sex."),
    ],
    1011: [
        ("A", "effect", "Committing murder induces fear of capture, guilt, and dread in the perpetrator."),
        ("B", "effect", "Go to jail is a legal consequence, not an emotion induced by committing murder."),
        ("C", "property", "Problems are difficulties, not the specific emotion murder induces in the person who commits it."),
        ("D", "property", "Cruel describes a personality trait, not the emotion experienced after committing murder."),
        ("E", "property", "Dead describes a state of being, not an emotion felt by someone who commits murder."),
    ],
    1012: [
        ("A", "used_for", "Watch television is sedentary entertainment, not a way tired children travel somewhere."),
        ("B", "used_for", "Riding a bike lets tired children reach a destination without the exertion of running."),
        ("C", "used_for", "Smell smoke detects fire, not a transportation method for tired children."),
        ("D", "used_for", "Walking still requires leg effort, less helpful than biking when children are tired from running."),
        ("E", "used_for", "Play tag involves running, which tired children would want to avoid to reach their destination."),
    ],
    1013: [
        ("A", "property", "History is the study of past events, not why a punctuation dot appears on a written page."),
        ("B", "used_for", "End of line is where a line break occurs, but a period specifically ends a sentence on the page."),
        ("C", "property", "Tracking of music is audio production, unrelated to a punctuation mark on a written page."),
        ("D", "typical_location", "School is an institution, not the reason a period character appears on a page of text."),
        ("E", "used_for", "A period on a page marks the finish of a sentence in written text."),
    ],
    1014: [
        ("A", "property", "An electrical circuit conducts electricity, not a place to order an old-fashioned cup of coffee."),
        ("B", "typical_location", "A coffee shop serves coffee but diners are especially known for old-fashioned brewed cups."),
        ("C", "typical_location", "A canteen is a cafeteria, not the classic spot for an old-fashioned cup of coffee."),
        ("D", "typical_location", "A diner is known for serving old-fashioned brewed coffee in a classic American setting."),
        ("E", "typical_location", "Mexico is a country, not a place to get an old-fashioned cup of coffee."),
    ],
    1015: [
        ("A", "effect", "Reviving describes restoration, but exhilaration captures the rush from breathing fresh country air."),
        ("B", "effect", "Silence may exist in the country, but the sensation sought is the thrill of clean fresh air."),
        ("C", "effect", "Exhilaration is the invigorating rush felt when breathing fresh country air after leaving a polluted city."),
        ("D", "effect", "A clear head is mental clarity, related but less vivid than the exhilaration of fresh air."),
        ("E", "effect", "Flatulence is intestinal gas, not the pleasant sensation sought from fresh country air."),
    ],
    1016: [
        ("A", "typical_location", "A classroom is the last place of study where a student likely left a writing instrument behind."),
        ("B", "typical_location", "A desk drawer at home is not the last place of study mentioned in the question."),
        ("C", "typical_location", "A bathroom is not typically a place of study where a student leaves a pen."),
        ("D", "typical_location", "A pocket travels with the student, so a pen there would not be left behind at school."),
        ("E", "typical_location", "A stationery store sells writing instruments but is not where the student studied last."),
    ],
    1017: [
        ("A", "used_for", "Talk is a verb describing speech, not the formal gathering employees hold for group discussion."),
        ("B", "property", "Company is an organization, not the event employees schedule for group discussion."),
        ("C", "property", "Corporation is a business entity, not the scheduled event for employee group discussion."),
        ("D", "used_for", "A meeting is the formal gathering employees hold when they want a group discussion."),
        ("E", "typical_location", "An office is where work happens, not the event itself for group discussion among employees."),
    ],
    1018: [
        ("A", "property", "Asthma is a respiratory condition, not a figurative label for the burden of housework."),
        ("B", "property", "Headache is the idiomatic expression for something lazy people consider one big nuisance chore."),
        ("C", "property", "Work is literal, but lazy people figuratively call housework one big headache."),
        ("D", "effect", "Arguments may arise over chores, but the idiom for lazy people is that housework is a headache."),
        ("E", "effect", "Boredom may result, but the classic complaint is that housework is one big headache."),
    ],
    1019: [
        ("A", "typical_location", "A bathroom scale for weighing yourself is commonly kept in the bathroom at home."),
        ("B", "typical_location", "A doctor's office has a medical scale, not the one kept at home for daily self-weighing."),
        ("C", "typical_location", "An assay office tests metals, not a room where a personal body scale is kept."),
        ("D", "typical_location", "A post office handles mail, not a home scale for weighing yourself."),
        ("E", "typical_location", "A study is a home office, but the bathroom is the standard room for a personal scale."),
    ],
}
