# -*- coding: utf-8 -*-
"""Hand-authored v2-style KB for CSQA qids 1270-1319 (no answerKey)."""

CHUNK = {
    1270: [
        ("A", "typical_location", "A system is abstract, not a venue where you hear a pipe organ played."),
        ("B", "typical_location", "A veterinarian treats animals, not a place to hear an organ being played."),
        ("C", "typical_location", "The human body contains internal organs, not the musical instrument in question."),
        ("D", "typical_location", "A cathedral is a classic place to hear a large pipe organ being played."),
        ("E", "typical_location", "A music store may sell organs, but cathedrals are where they are famously heard."),
    ],
    1271: [
        ("A", "property", "A support group is organized help, not what close family and friends naturally provide."),
        ("B", "property", "Getting enough sleep is rest, not the support from those closest to a person."),
        ("C", "property", "A person supported by those closest to them has a nice family backing them."),
        ("D", "property", "Strong bones describe physical health, not emotional support from loved ones."),
        ("E", "property", "Compliments are kind words, less central than having a nice supportive family."),
    ],
    1272: [
        ("A", "typical_location", "The bottom floor is a building level, not where pantry food is stored."),
        ("B", "typical_location", "A shop sells groceries rather than storing them on shelves in your pantry."),
        ("C", "typical_location", "The kitchen contains the pantry, but food inside is stored on shelves."),
        ("D", "typical_location", "Food in a pantry is usually stored on shelves for easy access."),
        ("E", "typical_location", "Refrigerators keep food cold; pantry dry goods sit on shelves."),
    ],
    1273: [
        ("A", "cause", "Cyanide is a poison, not a circumstance where death is unwanted by the victim."),
        ("B", "property", "Love is an emotion, not a situation where someone's death is against their will."),
        ("C", "property", "Burial follows death, not a case where the person did not want to die."),
        ("D", "effect", "Suicide is self-chosen death, so the person's death is wanted by them."),
        ("E", "effect", "Murder is death inflicted on someone who did not want to die."),
    ],
    1274: [
        ("A", "typical_location", "Breakfast food is what goes in the bowl, not where the bowl is stored."),
        ("B", "typical_location", "A china shop sells dishes, not where a child's cereal bowl is kept at home."),
        ("C", "typical_location", "A kitchen cabinet within reach holds cereal bowls children can access."),
        ("D", "typical_location", "A refrigerator keeps food cold, not where cereal bowls are normally stored."),
        ("E", "typical_location", "A cupboard in the kitchen commonly stores cereal bowls within a child's reach."),
    ],
    1275: [
        ("A", "typical_location", "A shelterbelt is a row of trees for wind protection, not a growing wooden structure."),
        ("B", "typical_location", "A tree is living wood, not the shelter James built and kept expanding."),
        ("C", "effect", "James kept adding wood until his handmade shelter became a full house."),
        ("D", "typical_location", "A home is where one lives, but the building process described ends as a house."),
        ("E", "typical_location", "A bus stop is a transit shelter, far smaller than what James built with axe and saw."),
    ],
    1276: [
        ("A", "used_for", "A phone lets you chat with friends who are not in the same place together."),
        ("B", "used_for", "A computer also enables remote chatting, but phones are the classic mobile tool."),
        ("C", "property", "Having friends is a relationship, not the device used for distant chatting."),
        ("D", "used_for", "Smoke signals are archaic, not how people chat with distant friends today."),
        ("E", "used_for", "A printer outputs documents, not a tool for chatting with remote friends."),
    ],
    1277: [
        ("A", "has_prerequisite", "Opening a business requires securing lots of funding to cover startup costs."),
        ("B", "has_prerequisite", "Capital is needed too, but funding broadly covers the financial backing required."),
        ("C", "motivation", "Determination helps entrepreneurs, but funding is the concrete resource to secure."),
        ("D", "property", "Llamas are animals, unrelated to what a new business must secure."),
        ("E", "motivation", "Creativity helps ideas, but securing funding is essential when opening a business."),
    ],
    1278: [
        ("A", "effect", "Armies and populations suffer when countries wage war against each other."),
        ("B", "effect", "Killing people is part of combat, but armies broadly suffer during wartime."),
        ("C", "effect", "Death and destruction result from war, but armies themselves endure suffering."),
        ("D", "effect", "People die in war, describing casualties rather than what armies must do."),
        ("E", "effect", "Crying is an emotional response, not the primary duty of armies at war."),
    ],
    1279: [
        ("A", "effect", "Head injuries are a risk of football, not a good thing about playing it."),
        ("B", "motivation", "Having fun is a good thing about playing football for participants."),
        ("C", "effect", "Death is a extreme outcome, not a positive aspect of playing football."),
        ("D", "effect", "Concussions are injuries, not a benefit of playing football."),
        ("E", "effect", "Getting hurt is negative, opposite of a good thing about playing football."),
    ],
    1280: [
        ("A", "typical_location", "Fields are land areas, not the northernmost country where apple trees grow."),
        ("B", "typical_location", "Brazil is in South America, not the northernmost apple-growing country in America."),
        ("C", "typical_location", "Canada is the northernmost country in North America where apple trees can grow."),
        ("D", "property", "Spring is a season, not a country where apple trees are cultivated."),
        ("E", "typical_location", "Outside is too vague to name the northernmost apple-growing country."),
    ],
    1281: [
        ("A", "used_for", "Learning is gaining knowledge, not the character trait forgiveness develops."),
        ("B", "used_for", "Giving a hug is a gesture, not how forgiveness makes someone act."),
        ("C", "effect", "Happiness may follow forgiveness, but being nice to others captures the trait."),
        ("D", "property", "Being able to forgive is a way to be nice to others despite wrongs."),
        ("E", "property", "Sex is unrelated to the character quality developed through forgiveness."),
    ],
    1282: [
        ("A", "motivation", "Love may grow from talks, but Sam chatted about important things seeking answers."),
        ("B", "motivation", "Happiness is a feeling, not what Sam sought from discussing important topics."),
        ("C", "motivation", "Sam chatted with friends about important things because he wanted to get answers."),
        ("D", "motivation", "Communication is the act itself, not the goal Sam hoped to achieve."),
        ("E", "motivation", "Money is financial gain, not what Sam sought from important conversations."),
    ],
    1283: [
        ("A", "part_whole", "Virginia is located in the southern region of the United States."),
        ("B", "part_whole", "Minnesota is a different state, not the region containing Virginia."),
        ("C", "part_whole", "The United States is the country, not the regional part Virginia occupies."),
        ("D", "part_whole", "South describes the region of the US where Virginia is located."),
        ("E", "part_whole", "Virginias is not a standard geographic term for US regional divisions."),
    ],
    1284: [
        ("A", "typical_location", "A house has rooms, but schools gather kids in entrance halls at teachers' request."),
        ("B", "typical_location", "A person is an individual, not a building with an entrance hall for students."),
        ("C", "typical_location", "A palace is a grand residence, not where teachers assemble students daily."),
        ("D", "typical_location", "Kids gather in the entrance hall at school when teachers request it."),
        ("E", "typical_location", "A hospital treats patients, not where kids gather at teachers' request."),
    ],
    1285: [
        ("A", "effect", "Going to jail may follow perjury, not the injustice committed through false testimony."),
        ("B", "property", "Falsehoods are lies told, but injustices result when perjury leads to wrongful convictions."),
        ("C", "effect", "A mistrial ends a case, different from convictions caused by perjured testimony."),
        ("D", "effect", "Injustices are committed when perjury leads to wrongful criminal convictions."),
        ("E", "effect", "Criminal prosecution is the legal process, not the wrong itself from perjury."),
    ],
    1286: [
        ("A", "effect", "Happiness may follow a payout, but cashing in means you get money."),
        ("B", "used_for", "Selling stock may precede cashing in, but the result is receiving money."),
        ("C", "effect", "Celebrating may follow, but cashing in directly means you get money."),
        ("D", "used_for", "Withdrawing is one way to cash in, but getting money states the outcome."),
        ("E", "effect", "When you cash in chips, bonds, or investments, you get money."),
    ],
    1287: [
        ("A", "used_for", "Recreation describes leisure activity broadly; poker is a specific card game."),
        ("B", "effect", "Losing money is a possible outcome, not what you are actively doing at the table."),
        ("C", "primary_function", "Playing poker means you are engaged in game playing with cards."),
        ("D", "primary_function", "Distributing cards is one dealer action, not what every poker player is doing."),
        ("E", "motivation", "Fun may motivate play, but game playing describes the activity itself."),
    ],
    1288: [
        ("A", "typical_location", "Outside describes location, not what they tried to capture with their phones."),
        ("B", "typical_location", "A hen house holds chickens, not a photo target at a park fox sighting."),
        ("C", "typical_location", "Indiana is a state, not something you snap with a phone at a fox sighting."),
        ("D", "used_for", "They hurried to get their phones out to take a picture of the fox."),
        ("E", "used_for", "Phone numbers are contacts, not what you capture when spotting a fox."),
    ],
    1289: [
        ("A", "typical_location", "A classroom holds students, but a university is where literary majors study."),
        ("B", "typical_location", "A book store sells books, less ideal than a university for reaching literary majors."),
        ("C", "typical_location", "The poet went to a university to promote literature to literary majors."),
        ("D", "typical_location", "A study is a room, not the institution where literary majors are found."),
        ("E", "typical_location", "Home is private, not where a poet promotes work to literary majors."),
    ],
    1290: [
        ("A", "effect", "Sweating occurs while hiking, but cramps and exertion better capture miles of strain."),
        ("B", "effect", "Hiking for miles commonly causes muscle cramps from prolonged effort."),
        ("C", "effect", "Physical exertion from hiking miles taxes the body and causes suffering."),
        ("D", "effect", "Smiling is positive expression, not suffering from miles of hiking."),
        ("E", "effect", "Deliriousness is extreme; cramps and exertion are typical hiking consequences."),
    ],
    1291: [
        ("A", "typical_location", "An incinerator burns waste briefly, not where refuse is stored long term."),
        ("B", "typical_location", "A wastebasket holds trash temporarily in a room, not for long-term storage."),
        ("C", "typical_location", "A waste basket is a small indoor bin, not long-term refuse storage."),
        ("D", "typical_location", "A dump or landfill is where refuse is stored for a long time."),
        ("E", "typical_location", "A garbage can is for short-term collection, not long-term refuse storage."),
    ],
    1292: [
        ("A", "effect", "A headache is pain, not what she accomplished by working hard on her tasks."),
        ("B", "effect", "Popularity is social status, not the result of completing her own evening tasks."),
        ("C", "effect", "Taking rest follows work, but she used evenings to accomplish her goals."),
        ("D", "effect", "Working hard for herself in the evenings let her accomplish her goals."),
        ("E", "effect", "Get laid is slang unrelated to completing personal tasks in the evening."),
    ],
    1293: [
        ("A", "motivation", "A doctor tells someone who gained fat to lose weight for their health."),
        ("B", "property", "Loosing is a misspelling of losing, not standard medical advice phrasing."),
        ("C", "property", "Loosing duplicates the misspelled option rather than clear medical guidance."),
        ("D", "property", "Loss is a noun, not the action a doctor recommends after weight gain."),
        ("E", "motivation", "Reduce is vague; lose weight is the direct advice after gaining fat."),
    ],
    1294: [
        ("A", "typical_location", "A labyrinth is a maze, not where you write down a passage of text."),
        ("B", "typical_location", "The Bible contains passages, but you write new passages in personal writing books."),
        ("C", "typical_location", "A hotel is lodging, not where you typically write down a passage."),
        ("D", "typical_location", "A diary is where people write down personal passages and reflections."),
        ("E", "typical_location", "A journal is also used to write down passages, similar to a diary."),
    ],
    1295: [
        ("A", "typical_location", "A studio records music, but audiences listen to musicians on a stage."),
        ("B", "typical_location", "A music store sells instruments, not performances with listening audiences."),
        ("C", "typical_location", "A stage is where many musicians perform while people listen to them."),
        ("D", "typical_location", "A symphony is an ensemble, not the venue with audience and many musicians."),
        ("E", "typical_location", "An orchestra performs music, but a stage hosts musicians with listening crowds."),
    ],
    1296: [
        ("A", "has_prerequisite", "Friends since childhood did not need a formal contract to agree with each other."),
        ("B", "property", "Friendship already existed; they did not need it anew to reach agreement."),
        ("C", "property", "Harmony describes getting along, not a document required for their agreement."),
        ("D", "property", "Compliance is following rules, not what Billy and Dan lacked for agreeing."),
        ("E", "property", "Death threats are coercion, not needed for two old friends to agree."),
    ],
    1297: [
        ("A", "typical_location", "A bathroom is for hygiene, not relaxing so long you miss a flight."),
        ("B", "typical_location", "A couch is for relaxing, but a bed is where people lose track of time sleeping."),
        ("C", "typical_location", "The airport is where Danny needed to be, not where he stayed too long."),
        ("D", "typical_location", "Homes is plural and vague; bed specifically fits staying too long before a flight."),
        ("E", "typical_location", "Danny stayed too long in bed, a object made for humans to relax, and missed his flight."),
    ],
    1298: [
        ("A", "effect", "Fall describes dropping, not the controlled action of putting something back down."),
        ("B", "effect", "Sun set is an astronomical event, unrelated to lowering a raised object."),
        ("C", "property", "Below is a position, not the action of returning something to a lower place."),
        ("D", "primary_function", "After raising something, you lower it to put it back down."),
        ("E", "used_for", "Place is general; lower specifically reverses raising an object."),
    ],
    1299: [
        ("A", "effect", "A grave injury from fighting an enemy leaves him dying or near death."),
        ("B", "effect", "Victory is winning, opposite of suffering a grave injury from fighting."),
        ("C", "effect", "Casualties are losses collectively, not his personal state after injury."),
        ("D", "used_for", "Protect yourself is defensive action, not his condition after grave injury."),
        ("E", "effect", "Death may result, but dying describes his immediate state from the grave injury."),
    ],
    1300: [
        ("A", "effect", "Hate is negative feeling, opposite of what correct answers bring the teacher's pet."),
        ("B", "effect", "Confusion follows mistakes, not the growing reward of each correct answer."),
        ("C", "effect", "Each correct answer brought the teacher's pet more satisfaction than the last."),
        ("D", "effect", "Teaching is instructing others, not the feeling she got from answering correctly."),
        ("E", "effect", "Panic is distress, not the pleasure of successive correct answers."),
    ],
    1301: [
        ("A", "motivation", "Peace is calm, but sunny days specifically contrast cold rain he was sick of."),
        ("B", "motivation", "Drinking water quenches thirst, not longing caused by cold rainy weather."),
        ("C", "motivation", "All kinds of things is too vague for weather-related longing."),
        ("D", "motivation", "Compliments are praise, unrelated to wanting relief from cold rain."),
        ("E", "motivation", "Sick of cold rain, he longed for sunny days instead."),
    ],
    1302: [
        ("A", "typical_location", "The Himalayas are mountains, but Swiss hotels famously overlook peaks with chocolate shops."),
        ("B", "typical_location", "Pennsylvania has hills, not the classic mountain-and-chocolate tourist pairing described."),
        ("C", "typical_location", "Switzerland is known for mountain views, hotels, and sampling chocolates."),
        ("D", "typical_location", "A picture is an image, not the destination of his mountain-view visit."),
        ("E", "typical_location", "Canada has mountains, but Switzerland fits the hotel, mountain, and chocolate scene."),
    ],
    1303: [
        ("A", "typical_location", "A cave commonly contains a long, dark passageway underground."),
        ("B", "typical_location", "A hotel has hallways, but caves are classic long dark passageways."),
        ("C", "typical_location", "A bathroom is small, not a long dark passageway."),
        ("D", "typical_location", "An airport has corridors, usually lit, unlike a cave's dark passageway."),
        ("E", "typical_location", "A house has hallways, but caves are the archetypal long dark passageway."),
    ],
    1304: [
        ("A", "typical_location", "Libraries keep magazines for long periods until they become old and dated."),
        ("B", "typical_location", "Markets sell fresh goods, not where magazines sit until they are old."),
        ("C", "typical_location", "A doctor's waiting room has magazines, but libraries hold them until old."),
        ("D", "typical_location", "A table holds magazines briefly, not where they usually grow old."),
        ("E", "typical_location", "Libraries archive periodicals, so magazines there are commonly old."),
    ],
    1305: [
        ("A", "property", "George wanted his salary supply to remain stable without unwanted changes."),
        ("B", "property", "Stagnant implies unhealthy lack of growth, not the neutral stability George wanted."),
        ("C", "property", "Constant pay without fluctuation is what George wanted for his money supply."),
        ("D", "property", "Unpleasant describes bad feelings, not the steady salary George preferred."),
        ("E", "property", "Permanent suggests unchanging forever; constant captures steady salary without changes."),
    ],
    1306: [
        ("A", "typical_location", "You send mail over the counter at a post office."),
        ("B", "typical_location", "A candy store sells sweets, not mail services over a counter."),
        ("C", "typical_location", "A butcher shop sells meat, not where you send mail over a counter."),
        ("D", "typical_location", "Animals are living creatures, not a place to send mail."),
        ("E", "typical_location", "A kitchen prepares food, not mail sent over a service counter."),
    ],
    1307: [
        ("A", "typical_location", "An internet cafe has computers, but James connected his new monitor to his desktop."),
        ("B", "used_for", "Display images is what a monitor does, not what James connected it to."),
        ("C", "typical_location", "The box was discarded packaging, not the device he plugged the monitor into."),
        ("D", "used_for", "View bluescreen is an error state, not the connection target for a new monitor."),
        ("E", "typical_location", "James connected his new monitor to his desktop computer."),
    ],
    1308: [
        ("A", "typical_location", "A table is furniture, not the vessel where fishermen clean their catch."),
        ("B", "typical_location", "A kitchen drawer stores utensils, not where anglers clean fish at sea."),
        ("C", "typical_location", "People use a knife to clean their catch on a fishing boat."),
        ("D", "typical_location", "A pocket holds small items, not where a catch is cleaned with a knife."),
        ("E", "typical_location", "A board may fillet fish ashore, but fishing boats are the classic cleaning vessel."),
    ],
    1309: [
        ("A", "used_for", "The pioneer sought baking soda as a baking supply at the general store."),
        ("B", "typical_location", "Barrels store goods in bulk, not the specific baking supply he sought."),
        ("C", "used_for", "Pepper is a spice, less central than baking soda for baking supplies."),
        ("D", "used_for", "Salt is a pantry staple, but baking soda is a key baking supply."),
        ("E", "typical_location", "A small town is a place, not the baking supply item he looked for."),
    ],
    1310: [
        ("A", "used_for", "Determining word definitions is why he used the dictionary, not what he wore it out on."),
        ("B", "used_for", "A thesaurus lists synonyms, a different reference book from a dictionary."),
        ("C", "used_for", "Eat cake is unrelated to wearing out a dictionary through word work."),
        ("D", "used_for", "He wore out his dictionary while working on his novel, looking up words."),
        ("E", "used_for", "An encyclopedia covers broad topics, not the word-by-word lookup of a novel draft."),
    ],
    1311: [
        ("A", "effect", "Making a person sick is illness, not the direct physical result of falling."),
        ("B", "effect", "Pain commonly results when a person is falling or hits the ground."),
        ("C", "effect", "Broken bones may result from a fall, but pain is the immediate common consequence."),
        ("D", "effect", "Going down describes the motion of falling, not the harm that happens to a person."),
        ("E", "effect", "Getting hurt encompasses pain and injury from falling to the ground."),
    ],
    1312: [
        ("A", "typical_location", "The Met is in New York City, so Sean took a subway stop there."),
        ("B", "typical_location", "Toronto is in Canada, not where the Metropolitan Museum of Art is located."),
        ("C", "typical_location", "Large city is vague; New York City specifically has the Met and its subway."),
        ("D", "typical_location", "Large city repeats without naming New York City where the Met is found."),
        ("E", "typical_location", "Metropolis is generic; the Met refers to the museum in New York City."),
    ],
    1313: [
        ("A", "used_for", "Dressing themselves is daily routine, not a cookout-specific social activity."),
        ("B", "used_for", "Driving a vehicle is transport, not what adults typically do at a cookout."),
        ("C", "used_for", "Adults at a cookout with friends commonly drink beer socially."),
        ("D", "used_for", "Playing games may happen, but drinking beer is a classic cookout adult activity."),
        ("E", "used_for", "Smoking cigarettes is a habit, less central than social drinking at cookouts."),
    ],
    1314: [
        ("A", "used_for", "Relax here offers rest, but stay here gives George a place when he had none."),
        ("B", "used_for", "I offered to let George stay here when he had no place to go away from home."),
        ("C", "used_for", "Come here invites arrival, but staying addresses his lack of any place to go."),
        ("D", "property", "Closer describes proximity, not lodging offered to George without a place to stay."),
        ("E", "property", "Available means free to use, less direct than offering to let him stay here."),
    ],
    1315: [
        ("A", "used_for", "Talking to a phone is odd phrasing; surfing the net relieves boredom on mobile."),
        ("B", "used_for", "Surfing the net on a mobile phone is a common cure for boredom."),
        ("C", "used_for", "Playing cards requires cards and partners, less convenient on a phone alone."),
        ("D", "used_for", "Playing chess on a phone is possible, but surfing the net is the classic mobile pastime."),
        ("E", "used_for", "See new is vague grammar, not a clear boredom activity on a mobile phone."),
    ],
    1316: [
        ("A", "typical_location", "The sea borders California, but sunshine and summer climate drive theme park planning."),
        ("B", "typical_location", "A windowsill is tiny indoor ledge, irrelevant to building Disneyland in California."),
        ("C", "typical_location", "Disneyland is the park itself, not the reason planners choose California as a site."),
        ("D", "typical_location", "Desert covers parts of California, not why a sunshine destination is chosen."),
        ("E", "property", "California's sunny summer weather is why planners would choose that state for Disneyland."),
    ],
    1317: [
        ("A", "effect", "A shy person often feels anxiety when meeting people for the first time."),
        ("B", "effect", "Stress may accompany new meetings, but anxiety specifically fits shy first encounters."),
        ("C", "effect", "Being bored is disinterest, not the typical shy reaction to new people."),
        ("D", "effect", "Smiling is a friendly expression, not the internal feeling of a shy newcomer."),
        ("E", "effect", "Making new friends is a hoped outcome, not the immediate feeling when shy."),
    ],
    1318: [
        ("A", "effect", "Starting to communicate with others may lead to engagement in conversation."),
        ("B", "effect", "People thinking is vague, less direct than engagement as a communication reaction."),
        ("C", "effect", "Exchanging ideas follows communication, but engagement is the immediate social reaction."),
        ("D", "effect", "Distributed information is one-way, not the reciprocal reaction to communicating."),
        ("E", "effect", "Sharing knowledge may result, but engagement captures others responding to communication."),
    ],
    1319: [
        ("A", "effect", "Turning up the thermostat raises heat; temperature does not drop to zero."),
        ("B", "effect", "Turning up the thermostat increases heat, not a rapid temperature drop."),
        ("C", "effect", "Turning up the thermostat makes it warmer, so temperature does not get colder."),
        ("D", "effect", "Turning up the thermostat causes the temperature to increase."),
        ("E", "effect", "Heat up describes warming, similar to increase when the thermostat is turned up."),
    ],
}
