# -*- coding: utf-8 -*-
"""Hand-authored v2-style KB for CSQA qids 1420-1440 (no answerKey)."""

CHUNK = {
    1420: [
        ("A", "property", "Icy cold describes a temperature, not a place where you purchase a freezer."),
        ("B", "typical_location", "Your own home is where you keep appliances, not where you go to buy one you lack."),
        ("C", "typical_location", "A garage may store a freezer but is not where you obtain one when you do not have it."),
        ("D", "primary_function", "Freezing food is what a freezer does, not a source for acquiring the appliance."),
        ("E", "typical_location", "An appliance store sells freezers to customers who need to buy one."),
    ],
    1421: [
        ("A", "effect", "Arguments may follow housework disputes but dust itself does not give you arguments."),
        ("B", "effect", "Dust poisoning is rare; ordinary household dust during chores does not cause it."),
        ("C", "effect", "Inhaling a lot of dust while doing housework commonly triggers a headache."),
        ("D", "effect", "Exhaustion comes from physical labor, less specifically from dust exposure alone."),
        ("E", "effect", "Boredom may occur during chores but breathing dust does not cause boredom."),
    ],
    1422: [
        ("A", "typical_location", "A house is too generic; hotels offer numbered floors for guests sleeping away from home."),
        ("B", "typical_location", "An office building is for work, not where people typically sleep overnight away from home."),
        ("C", "typical_location", "A parking space is for vehicles outdoors, not overnight lodging."),
        ("D", "typical_location", "A school is for classes, not the usual place to sleep when away from home."),
        ("E", "typical_location", "In a hotel, the first or second floor is considered safest for fire escape when sleeping away."),
    ],
    1423: [
        ("A", "typical_location", "Restaurants have restrooms but event-sized crowds point to a stadium venue."),
        ("B", "typical_location", "During an event break, crowds gather at toilets inside a stadium."),
        ("C", "typical_location", "A space shuttle has no public toilets for crowds during a terrestrial event break."),
        ("D", "typical_location", "Malls have restrooms but stadiums fit large event crowds lining up at toilets."),
        ("E", "property", "Bathroom names the room type; the question asks where the toilet was within the event venue."),
    ],
    1424: [
        ("A", "motivation", "When chatting with friends you admire, people hope to feel close to them."),
        ("B", "used_for", "Exchanging information is conversation but admiration seeks emotional closeness."),
        ("C", "effect", "Love is a strong outcome; feeling close to captures the hoped achievement with admired friends."),
        ("D", "motivation", "Social approval is external validation, not the closeness hoped when admiring friends."),
        ("E", "effect", "Exchanging smiles is friendly but feeling close to is the deeper hoped outcome."),
    ],
    1425: [
        ("A", "typical_location", "A kitchen holds food but Danny had none at his place and asked across the road."),
        ("B", "typical_location", "A military base is restricted and unlikely for casually borrowing food across a road."),
        ("C", "typical_location", "A shelf stores items but is not where you go to ask someone for food."),
        ("D", "typical_location", "Danny likely asked at a neighbor's house across the road for food."),
        ("E", "typical_location", "A restroom is for hygiene, not where you request food from others."),
    ],
    1426: [
        ("A", "typical_location", "Pool chemicals irritate skin but vaginal chemical burns suggest hazardous indoor chemical exposure."),
        ("B", "typical_location", "A beach has sun and sand, not the concentrated chemicals causing vaginal burns."),
        ("C", "typical_location", "An illegal crystal meth lab uses harsh chemicals that can cause severe chemical burns."),
        ("D", "typical_location", "A chemistry lab uses hazardous chemicals; ignored safety signs could cause serious burns."),
        ("E", "typical_location", "A laboratory handles chemicals but the severe burn context suggests an illicit meth lab."),
    ],
    1427: [
        ("A", "property", "Top piece is vague jargon; the winning game piece is what comes out on top."),
        ("B", "property", "Strong describes power but the game asks which piece ends up on top."),
        ("C", "property", "Win is an outcome verb, not the game piece that comes out on top."),
        ("D", "effect", "Total domination is a result, not the specific piece reaching the top."),
        ("E", "property", "Best is a quality judgment, not the game piece that comes out on top."),
    ],
    1428: [
        ("A", "effect", "Travel together is unrelated to jointly observing the same sight at the same moment."),
        ("B", "used_for", "Borrowing money is financial, not what happens when friends observe something together."),
        ("C", "effect", "Conspire implies secret plotting, not simply watching the same thing simultaneously."),
        ("D", "used_for", "Visiting each other is social contact, not the shared act of observing together."),
        ("E", "property", "See like is ungrammatical; friends observing together would see the same thing."),
    ],
    1429: [
        ("A", "effect", "Enjoy is pleasure, the opposite of how a disliked hamburger would make John feel."),
        ("B", "effect", "Satisfaction follows pleasant eating, not a burger John did not like."),
        ("C", "effect", "Sadness is emotional but nausea better captures physical revulsion from bad food."),
        ("D", "effect", "Death is extreme and unrelated to disliking a single hamburger."),
        ("E", "effect", "Eating a disliked hamburger commonly makes a person feel nauseated."),
    ],
    1430: [
        ("A", "typical_location", "Stop is vague; rest areas specifically serve groups of travellers on the road."),
        ("B", "typical_location", "A bus depot handles buses but highway rest areas gather road travellers together."),
        ("C", "typical_location", "Highway rest areas are where groups of travellers travelling by road stop together."),
        ("D", "typical_location", "Train stations serve rail passengers, not groups travelling by road."),
        ("E", "typical_location", "Airports serve air travellers, not groups moving along roads."),
    ],
    1431: [
        ("A", "property", "A human has muscles throughout the body, including the diaphragm mentioned."),
        ("B", "property", "A woman's body has muscles but human is the broader correct answer category."),
        ("C", "property", "A valve is a mechanical part, not a living thing possessing muscles."),
        ("D", "used_for", "Paying debts is an action, not something anatomically possessing muscles."),
        ("E", "typical_location", "A drugstore is a shop, not an organism with muscles."),
    ],
    1432: [
        ("A", "typical_location", "Homes have doors but castles are especially known for massive wooden doorways."),
        ("B", "typical_location", "Airports use modern glass and automatic doors, not large wooden ones."),
        ("C", "typical_location", "Skyscrapers use revolving or metal doors, not classic large wooden doorways."),
        ("D", "typical_location", "Castles characteristically feature large heavy wooden doors in their doorways."),
        ("E", "property", "Every building is too broad; castles specifically evoke large wooden doors."),
    ],
    1433: [
        ("A", "typical_location", "Africa has wild animals but the question humorously points to a drinking establishment."),
        ("B", "typical_location", "A bar is where patrons enjoy drinks, fitting the playful image of animals drinking."),
        ("C", "typical_location", "Amazon basin animals drink in nature, not at a social drinking venue."),
        ("D", "typical_location", "Research laboratories house animals for study, not for enjoying drinks."),
        ("E", "typical_location", "A friend's house may serve drinks but bar fits the animals-enjoying-drinks scenario."),
    ],
    1434: [
        ("A", "effect", "Buzzing is a sound insects make, not the locomotion done with legs and wings."),
        ("B", "capability", "Sensing vibrations uses specialized organs, not basic leg and wing motion."),
        ("C", "primary_function", "Insects use legs to walk and wings to fly, both forms of movement."),
        ("D", "primary_function", "Eating uses mouthparts, not the leg and wing motion described."),
        ("E", "capability", "Flying uses wings only; legs were mentioned separately for walking movement."),
    ],
    1435: [
        ("A", "has_prerequisite", "Going to bed early is the best preparation for being able to get up early."),
        ("B", "used_for", "Fixing an alarm helps waking but an early bedtime addresses the root schedule."),
        ("C", "has_prerequisite", "Going to sleep early parallels bedtime discipline needed to rise early."),
        ("D", "property", "Dawn is when day breaks, not an action you take to wake up early."),
        ("E", "used_for", "Asking a spouse to wake you is unreliable compared with going to bed early."),
    ],
    1436: [
        ("A", "typical_location", "A desk drawer stores pencils but you attend the physics speech in a lecture hall."),
        ("B", "typical_location", "Home is where you live, not where you sit through an advanced physics lecture."),
        ("C", "typical_location", "A university is the institution; the classroom is where you need a pencil during the speech."),
        ("D", "typical_location", "During an advanced theoretical physics speech in a classroom you may need a pencil for notes."),
        ("E", "typical_location", "A pocket carries a pencil but the question asks where you are when needing one during the speech."),
    ],
    1437: [
        ("A", "effect", "Fighting contradicts the creative self-expression art and music provide."),
        ("B", "primary_function", "Art, music, and hobbies are great forms of communication and self-expression."),
        ("C", "effect", "Fun accompanies hobbies but communication captures their expressive purpose."),
        ("D", "effect", "Being understood may follow expression but communication is the activity category asked."),
        ("E", "effect", "Suffering is negative and unrelated to expressive creative hobbies."),
    ],
    1438: [
        ("A", "typical_location", "Stores sell goods, not natural habitats hosting many bird species."),
        ("B", "typical_location", "Parks have some birds but forests host greater species variety."),
        ("C", "typical_location", "Forests provide diverse habitats where many bird species live together."),
        ("D", "typical_location", "Air is where birds fly through, not where you find a variety gathered on the ground."),
        ("E", "typical_location", "Countryside open areas host varied bird populations in natural settings."),
    ],
    1439: [
        ("A", "property", "Buildings with poor conditions remain barely adequate rather than being condemned."),
        ("B", "property", "Poormouth is slang for complaining about poverty, not a building condition status."),
        ("C", "property", "Rich contradicts the poor living conditions described in the question."),
        ("D", "property", "Enough is vague; adequate is the standard term for minimally acceptable habitable conditions."),
        ("E", "property", "Good overstates poor conditions; barely adequate fits not yet condemned."),
    ],
    1440: [
        ("A", "typical_location", "Delaware sits on the Atlantic coast, far from the Pacific Ocean."),
        ("B", "typical_location", "New Jersey is an Atlantic state, not near the Pacific coast."),
        ("C", "typical_location", "Toll roads on the eastern United States coast are not near the Pacific Ocean."),
        ("D", "typical_location", "Connecticut is on the Atlantic seaboard, not adjacent to the Pacific."),
        ("E", "property", "Good repair describes road maintenance, not a geographic coast."),
    ],
}
