# -*- coding: utf-8 -*-
"""Hand-authored question-grounded commonsense knowledge for CSQA qids 1020-1119.

Authored ONLY from each question's stem + options (never from answerKey).
Format:  CHUNK[qid] = [(option_label, dimension, fact), ...]
"""

CHUNK = {
    1020: [
        ("A", "typical_location", "A bathroom is the usual room where a household scale is kept for weighing yourself."),
        ("B", "typical_location", "A doctor's office is a medical clinic, not a room inside your house."),
        ("C", "typical_location", "An assay office tests precious metals and is not a room in a home."),
        ("D", "typical_location", "A post office handles mail and is not a room inside a house."),
        ("E", "typical_location", "A study is for reading and work, not the usual place for a body scale."),
    ],
    1021: [
        ("A", "effect", "An apple tree produces blossoms that become apples, so it makes flowers each spring."),
        ("B", "typical_location", "Ohio is a state where trees grow, not something an apple tree produces."),
        ("C", "property", "The Inuit are people, not a product that grows on an apple tree."),
        ("D", "typical_location", "Fields are open land, not fruit or flowers that an apple tree creates."),
        ("E", "typical_location", "Canada is a country, not something an apple tree makes."),
    ],
    1022: [
        ("A", "typical_location", "A neighbor's house is someone else's home, not where you put your own mail."),
        ("B", "typical_location", "The post office sends mail out; you do not store delivered mail there."),
        ("C", "typical_location", "A fridge keeps food cold and is not where incoming mail belongs."),
        ("D", "typical_location", "A table is a common flat surface where people set mail after bringing it inside."),
        ("E", "typical_location", "A bathroom is for hygiene and is not a sensible place to keep mail."),
    ],
    1023: [
        ("A", "effect", "A grain of sand in the eye causes sharp pain and can damage sight."),
        ("B", "property", "A clam is a shellfish, not a body part where sand threatens vision."),
        ("C", "property", "A bathing suit is clothing that may chafe with sand but does not endanger sight."),
        ("D", "property", "Shoes protect feet; sand inside them hurts the foot, not the eyes."),
        ("E", "typical_location", "A beach has sand everywhere, but the painful sight risk is in the eye itself."),
    ],
    1024: [
        ("A", "typical_location", "A market sells ingredients but is not where tomato sauce is enjoyed as a dish."),
        ("B", "typical_location", "A refrigerator stores sauce cold rather than being where it tastes delicious."),
        ("C", "typical_location", "A vegetable garden grows tomatoes but is not where cooked sauce is eaten."),
        ("D", "used_for", "Tomato sauce is a classic savory topping that tastes delicious on pizza."),
        ("E", "property", "Cake is a sweet dessert and is not a food where tomato sauce belongs."),
    ],
    1025: [
        ("A", "property", "Being happy is an inner feeling and is not a distinct visible feature on the face."),
        ("B", "property", "Pleasure is a sensation you feel, not something you can see on someone's face."),
        ("C", "effect", "Smiling is a visible facial expression that shows someone is having fun."),
        ("D", "property", "Injuries are harm to the body, not a sign of enjoyment on the face."),
        ("E", "property", "Inner joy is felt privately and is not something observers see on the face."),
    ],
    1026: [
        ("A", "property", "Brunch is a late-morning meal, not the evening meal served on a dish."),
        ("B", "typical_location", "Dinner is the evening meal that would appear on your serving dish at night."),
        ("C", "typical_location", "A fast food restaurant is a place to eat, not a meal on a serving dish."),
        ("D", "property", "Appear appetizing describes how food looks, not the name of a meal."),
        ("E", "property", "A plate is dinnerware that holds food, not the meal itself."),
    ],
    1027: [
        ("A", "capability", "Dogs can be trained to shake hands as a learned trick for their owners."),
        ("B", "property", "An accident is an unplanned mishap, not a skill taught to a dog."),
        ("C", "typical_location", "A guard house is a building, not an action a dog is taught to perform."),
        ("D", "property", "Drinking water is natural behavior and is not a special trick dogs are taught."),
        ("E", "property", "A stray is a homeless dog, not a trained behavior."),
    ],
    1028: [
        ("A", "property", "Alcohol in beer is a chemical fact, not a loving nickname like liquid gold."),
        ("B", "property", "Intoxicating describes an effect of beer, not the fond nickname beer lovers use."),
        ("C", "property", "Beer lovers often call their favorite drink liquid gold because they cherish it."),
        ("D", "property", "Hair of the dog is a hangover remedy phrase, not a term of affection for beer."),
        ("E", "property", "Harmful describes a danger of excess, not a loving name for beer."),
    ],
    1029: [
        ("A", "property", "Owning a house describes where someone lives, not why they burp with satisfaction."),
        ("B", "property", "Being rude is poor manners, not the satisfied state after a hearty meal."),
        ("C", "effect", "Being well fed means having eaten enough to feel full and burp with satisfaction."),
        ("D", "property", "Fairness is justice toward others, not a feeling after eating a big meal."),
        ("E", "property", "Candies are sweets and do not explain a loud satisfied burp after a full meal."),
    ],
    1030: [
        ("A", "typical_location", "Detroit is a major city in southern Michigan where apple trees can grow."),
        ("B", "typical_location", "Maryland is an eastern state far from southern Michigan."),
        ("C", "typical_location", "Oregon is on the Pacific coast, not in Michigan."),
        ("D", "typical_location", "Washington state is in the Pacific Northwest, not southern Michigan."),
        ("E", "typical_location", "Indiana borders Michigan but Bill is picking apples in Michigan itself."),
    ],
    1031: [
        ("A", "part_whole", "A refrigerator contains cooling coils that use refrigerant, not a freon coin."),
        ("B", "property", "A tub holds bathwater and has no refrigerant coil inside it."),
        ("C", "property", "A television plays video and does not contain a freon-filled cooling coil."),
        ("D", "property", "A circuit carries electrical current and does not need refrigerant coils."),
        ("E", "property", "A slinky is a toy spring and has nothing to do with refrigerant coils."),
    ],
    1032: [
        ("A", "property", "Feeling empowered is gaining strength, the opposite of guilt after hurting someone."),
        ("B", "property", "Luck is chance, not an emotion that follows harming another person."),
        ("C", "effect", "Regret is a common feeling after realizing you have hurt someone else."),
        ("D", "property", "Punishment is a penalty imposed by others, not an inner feeling after harm."),
        ("E", "property", "Despair is deep hopelessness, less specific than regret after hurting someone."),
    ],
    1033: [
        ("A", "used_for", "Demonstrating a lesson is one activity, not what a teacher does most all week."),
        ("B", "used_for", "Eating lunch is a daily break shared by many workers, not unique to teachers."),
        ("C", "used_for", "Timing a test is an occasional task, not the main weekly activity of a teacher."),
        ("D", "primary_function", "Working in school is the core job a teacher performs throughout the week."),
        ("E", "property", "School children are the students taught, not an action the teacher performs."),
    ],
    1034: [
        ("A", "typical_location", "An office often gives away promotional pens printed with a company logo."),
        ("B", "property", "On a pencil describes placement, not a place where logo pens are found."),
        ("C", "used_for", "Writing sentences on paper is an action, not a location for branded pens."),
        ("D", "typical_location", "A school may have pens, but company-logo pens are more common in offices."),
        ("E", "typical_location", "A backpack carries supplies but is not where you typically find logo pens."),
    ],
    1035: [
        ("A", "part_whole", "The world is full of many separate countries spanning continents."),
        ("B", "property", "Thought is an abstract mental activity, not what physically fills the world."),
        ("C", "part_whole", "Water covers much of Earth but the world is not literally full of only water."),
        ("D", "part_whole", "The universe contains the world; the world does not fill the universe."),
        ("E", "part_whole", "A galaxy is vastly larger than the world and is not what the world is full of."),
    ],
    1036: [
        ("A", "used_for", "Chewing has nothing to do with looking up books in a library card catalog."),
        ("B", "used_for", "Searching for a title or author is what you do in a card catalog."),
        ("C", "used_for", "Asking questions helps research but is not the card-catalog lookup itself."),
        ("D", "has_prerequisite", "Logic aids research but the catalog step itself requires searching entries."),
        ("E", "property", "Time passes during research but is not the action required in a card catalog."),
    ],
    1037: [
        ("A", "used_for", "A fishing rod is gear bought before heading to a fishing tournament."),
        ("B", "property", "A machine gun is military hardware unrelated to a corporate investor's tournament."),
        ("C", "property", "Hatred is an emotion and is not something Gary would buy at a store."),
        ("D", "property", "Artillery is heavy weaponry, not sporting equipment for a tournament."),
        ("E", "property", "Double in value describes stock gains, not a physical item Gary could purchase."),
    ],
    1038: [
        ("A", "used_for", "Fencing athletes wield a sword such as a foil, épée, or sabre."),
        ("B", "property", "A competition is the event itself, not the weapon fencers hold."),
        ("C", "property", "A fence post is a yard barrier, a homonym unrelated to the sport of fencing."),
        ("D", "property", "Protection is a goal in fencing but not the object participants use."),
        ("E", "property", "Dexterity is a skill fencers need, not the equipment used in the sport."),
    ],
    1039: [
        ("A", "property", "A trashcan holds garbage and is not a screen for watching television shows."),
        ("B", "typical_location", "The floor is where you stand, not a device for viewing reality TV."),
        ("C", "typical_location", "Toronto is a city and cannot display garbage reality shows."),
        ("D", "used_for", "A television is the screen people watch garbage reality shows on."),
        ("E", "property", "A microwave heats food and does not play television programs."),
    ],
    1040: [
        ("A", "typical_location", "A school computer lab usually requires enrollment, not casual visitor access."),
        ("B", "property", "Hell is a figurative place, not where a traveler finds a public computer."),
        ("C", "typical_location", "An internet cafe rents computer access to visitors who did not bring their own."),
        ("D", "typical_location", "An office building restricts computers to employees, not casual foreign visitors."),
        ("E", "property", "Despair is an emotion, not a place to find a computer while traveling."),
    ],
    1041: [
        ("A", "typical_location", "A school bus is a vehicle, not a storage spot inside a house."),
        ("B", "typical_location", "A car is too small to store an oversized fire extinguisher at home."),
        ("C", "typical_location", "A garage has floor space to store a very large fire extinguisher."),
        ("D", "typical_location", "A stairwell is a narrow passage, awkward for an oversized extinguisher."),
        ("E", "typical_location", "A hospital is a medical facility, not a room inside someone's house."),
    ],
    1042: [
        ("A", "property", "A basketball full of air is properly inflated and ready to bounce and play with."),
        ("B", "cause", "A punctured basketball loses air and becomes flat and unusable."),
        ("C", "property", "Being popular in America does not stop anyone from using a basketball."),
        ("D", "property", "Being round is the correct shape and does not prevent using a basketball."),
        ("E", "property", "Not being tall describes a player, not a reason the ball itself is unusable."),
    ],
    1043: [
        ("A", "typical_location", "The side of the road is for stopping, not driving quickly to a destination."),
        ("B", "typical_location", "A parking garage is where cars are stored, not where they drive faster."),
        ("C", "typical_location", "A street carries normal traffic at regular speeds, not the fastest route."),
        ("D", "typical_location", "A garage at home is for parking, not for driving somewhere quicker."),
        ("E", "typical_location", "The fast lane on a highway lets automobiles pass slower traffic and arrive sooner."),
    ],
    1044: [
        ("A", "used_for", "Watching TV is a common leisure activity roommates might prefer over reading books."),
        ("B", "used_for", "Listening could mean music, but it is less clearly the opposite of reading."),
        ("C", "used_for", "Sleeping is rest, not the active pastime contrasted with reading for pleasure."),
        ("D", "property", "Illiterate means unable to read, a condition rather than a preferred activity."),
        ("E", "property", "Illiteracy is the state of not reading, not an activity roommates choose instead."),
    ],
    1045: [
        ("A", "property", "Trouble is a problem or mischief, not a habitat where wild cats live."),
        ("B", "typical_location", "A dog's mouth is a dangerous spot, not where wild cats are found."),
        ("C", "typical_location", "Nature encompasses forests and grasslands where wild cats roam freely."),
        ("D", "typical_location", "A floor is an indoor surface where pet cats rest, not wild cats in nature."),
        ("E", "typical_location", "A warm place is vague; wild cats specifically inhabit natural outdoor habitats."),
    ],
    1046: [
        ("A", "used_for", "Reading a book is learning activity but does not officially make someone a student."),
        ("B", "effect", "Dropping out of school ends student status rather than creating it."),
        ("C", "used_for", "Washing dishes is a chore unrelated to becoming an enrolled student."),
        ("D", "has_prerequisite", "Entering school through enrollment is what officially makes a child a student."),
        ("E", "used_for", "Studying a book helps learning but enrollment is what grants official student status."),
    ],
    1047: [
        ("A", "typical_location", "A mart sells goods you carry out in bags, not mainly unfinished meals."),
        ("B", "typical_location", "At a restaurant you eat on site and only need a bag for unfinished leftovers."),
        ("C", "typical_location", "A relative's home is not a place where you shop and need a shopping bag."),
        ("D", "typical_location", "A supermarket gives bags for groceries you carry home, not half-eaten meals."),
        ("E", "typical_location", "A grocery store provides bags for purchased food, not for unfinished restaurant meals."),
    ],
    1048: [
        ("A", "effect", "A funeral follows a death but is not how killing itself is generally regarded."),
        ("B", "property", "Killing is widely regarded as a horrible act against another person's life."),
        ("C", "effect", "Remorse is a feeling afterward, not the usual moral judgment of killing itself."),
        ("D", "property", "Premeditated describes planned killing legally, not the general view of all killing."),
        ("E", "effect", "Going to jail is a legal consequence, not how killing is thought of in general."),
    ],
    1049: [
        ("A", "effect", "A headache can come from difficult study but is not a benefit of learning science."),
        ("B", "effect", "Seeing things differently is a shift in outlook, not the direct gain from science study."),
        ("C", "effect", "Learning about science increases a person's knowledge of how the world works."),
        ("D", "effect", "Accidents happen in labs but are risks, not what someone gets from learning science."),
        ("E", "effect", "Appreciation of nature may follow but increased knowledge is the direct science benefit."),
    ],
    1050: [
        ("A", "effect", "Industry helped cities grow but did not literally expand the concept of a big city."),
        ("B", "part_whole", "Factories are built by industry but are structures, not the human capacity expanded."),
        ("C", "part_whole", "Machinery is industrial equipment, not the broad human development industry expanded."),
        ("D", "effect", "Poverty increased in some places despite industry, not the main expansion it brought."),
        ("E", "effect", "Industry greatly expanded human civilization through manufacturing and technological progress."),
    ],
    1051: [
        ("A", "used_for", "Sleeping all day is idle rest, not a cat's response to approaching animal control."),
        ("B", "property", "Casting a shadow is a physical effect, not a decision the cat makes."),
        ("C", "motivation", "A cat threatened by animal control will run away to escape capture."),
        ("D", "capability", "Barking like a dog is something cats cannot do and would not choose."),
        ("E", "capability", "Seeing at night is a cat ability, not its reaction to animal control arriving."),
    ],
    1052: [
        ("A", "property", "Severe describes an extremely harsh punishment fit for unchecked over-indulgence."),
        ("B", "property", "Harsh means rough and punishing, similar in severity to severe discipline."),
        ("C", "property", "Hard can mean difficult but does not specifically describe punishment severity."),
        ("D", "property", "Strict means rigid rules, a form of discipline but not the harshest descriptor."),
        ("E", "property", "Self denying means abstaining from pleasure, the corrective opposite of over-indulgence."),
    ],
    1053: [
        ("A", "typical_location", "You bring towels to a swimming pool to dry off after swimming, not showering."),
        ("B", "typical_location", "A hotel provides its own towels, so guests rarely need to bring extras."),
        ("C", "typical_location", "A beach is another place people bring towels to dry off after swimming."),
        ("D", "typical_location", "A motel supplies towels like a hotel and rarely requires you to bring your own."),
        ("E", "typical_location", "Stored on a towel rack is where towels hang at home, not a place you bring them."),
    ],
    1054: [
        ("A", "used_for", "Writing stories is a creative hobby unrelated to being near the sea."),
        ("B", "used_for", "Talking to each other happens anywhere and is not specific to the seaside."),
        ("C", "used_for", "Going fishing is a common activity people do when they are near the sea."),
        ("D", "effect", "Dying of starvation is extreme deprivation, not what people typically do near the sea."),
        ("E", "used_for", "Eating fish is possible near the sea but fishing is the more distinct seaside activity."),
    ],
    1055: [
        ("A", "typical_location", "An airplane cabin has a captain, but that is an airline pilot, not an army captain."),
        ("B", "typical_location", "A basketball team has a captain, a sports role unrelated to the army."),
        ("C", "typical_location", "An army captain serves in the military and leads soldiers in the armed forces."),
        ("D", "typical_location", "A battleship is navy territory; an army captain is found in ground forces."),
        ("E", "typical_location", "A fleet is a naval group commanded by navy officers, not army captains."),
    ],
    1056: [
        ("A", "effect", "Being killed in war is a battlefield death, not the typical horror-movie fate."),
        ("B", "effect", "Characters who die in horror movies are usually murdered by a killer or monster."),
        ("C", "property", "Not being important dismisses a character but is not what happens when they die."),
        ("D", "effect", "Being sentenced to jail is a legal outcome, not how horror-movie victims die."),
        ("E", "effect", "Being cremated happens after death, not the moment horror-movie characters die."),
    ],
    1057: [
        ("A", "effect", "Aged cheese develops richer flavor, and old cheeses are prized because they age well."),
        ("B", "used_for", "Eating cake is unrelated to the qualities the man loves in old cheese."),
        ("C", "cause", "Benign bacteria help cheese ripen but are not what old cheese is said to do."),
        ("D", "effect", "Age to get better describes the ripening process, overlapping with aging well."),
        ("E", "used_for", "Salad dressing is a condiment and is not a property of aged cheese itself."),
    ],
    1058: [
        ("A", "used_for", "A saucer is a small dish too tiny to hold a full meal comfortably."),
        ("B", "used_for", "A fork is an eating utensil, not a container you eat a meal from."),
        ("C", "used_for", "A cup holds liquids and is too small to serve a complete meal."),
        ("D", "used_for", "A bowl is a deep dish often used to eat a meal when no clean plate is available."),
        ("E", "property", "Food is what you eat, not the vessel you eat it from."),
    ],
    1059: [
        ("A", "effect", "Garlic breakfast may taste strong but tasty is not the unpleasant consequence asked for."),
        ("B", "effect", "Garlic leaves a strong odor that causes bad breath after eating it."),
        ("C", "effect", "Dirty dishes result from any meal, not specifically from eating garlic."),
        ("D", "effect", "A better day is a positive outcome unrelated to garlic's side effects."),
        ("E", "effect", "Gaining energy is a benefit of eating, not a problem caused by garlic."),
    ],
    1060: [
        ("A", "typical_location", "Plains are flat lowlands that mountains can ring and surround from above."),
        ("B", "effect", "Creating a climbing challenge is what mountains do, not the land they surround."),
        ("C", "property", "A molehill is a tiny mound, the opposite scale of a surrounding mountain range."),
        ("D", "typical_location", "A field is open ground that mountains can encircle on the valley floor."),
        ("E", "typical_location", "A dale is a valley nestled below surrounding mountains."),
    ],
    1061: [
        ("A", "used_for", "Closing your eyes and meditating is a common self-improvement class exercise."),
        ("B", "used_for", "Celebrating is a festive activity that does not require closing your eyes."),
        ("C", "motivation", "Plotting a teacher's destruction contradicts the goal of a self-improvement class."),
        ("D", "used_for", "Eating better is healthy but does not require the instructor to say close your eyes."),
        ("E", "effect", "Feeling better about yourself is a hoped-for outcome, not the immediate instruction given."),
    ],
    1062: [
        ("A", "part_whole", "A jamb is the door frame, not a room where a hinged door might be absent."),
        ("B", "property", "Own house describes a dwelling, not a specific room lacking a hinged door."),
        ("C", "property", "A building is a general structure, not the particular room asked about."),
        ("D", "typical_location", "A kitchen may be open to other rooms and not always have a hinged door."),
        ("E", "property", "A washing machine is an appliance, not a room of the house."),
    ],
    1063: [
        ("A", "typical_location", "A palm tree grows on tropical land, not in the ocean where blowfish live."),
        ("B", "typical_location", "Books sit on shelves and are not a habitat for a living blowfish."),
        ("C", "typical_location", "A fish market displays dead seafood on ice, not a happy home for blowfish."),
        ("D", "typical_location", "A coral reef is a vibrant ocean habitat where a blowfish would be most at home."),
        ("E", "typical_location", "An aquarium can house blowfish but is a captive tank, not their natural home."),
    ],
    1064: [
        ("A", "typical_location", "A roof is high and rarely walked on, so footprints seldom appear there."),
        ("B", "typical_location", "A carpet is a man-made floor covering that shows footprints when walked on."),
        ("C", "typical_location", "The ground is natural earth, not a man-made item that holds footprints."),
        ("D", "typical_location", "The surface of the earth is natural terrain, not a manufactured object."),
        ("E", "typical_location", "A rug is a man-made floor covering that retains visible footprints."),
    ],
    1065: [
        ("A", "used_for", "A hug is a personal gesture that any individual, not just a country, can give."),
        ("B", "capability", "A jealous country can wage war, an act beyond what one person can do alone."),
        ("C", "used_for", "Competing is something both individuals and nations can do when jealous."),
        ("D", "used_for", "Judging is an action individuals perform as readily as institutions."),
        ("E", "motivation", "Loving someone else is a personal emotion, not exclusive to countries."),
    ],
    1066: [
        ("A", "effect", "Dropping out ends schooling and is the opposite of what attending school helps with."),
        ("B", "effect", "Getting paid is a work outcome, not the direct benefit of attending school."),
        ("C", "effect", "Catching a cold is an illness risk, not a benefit of going to school."),
        ("D", "effect", "Graduating is a milestone but employability is the broader long-term help school provides."),
        ("E", "effect", "Attending school builds skills and credentials that improve a person's employability."),
    ],
    1067: [
        ("A", "typical_location", "England has tens of millions of residential back gardens across its towns."),
        ("B", "typical_location", "A suburban neighborhood has many gardens but not tens of millions on its own."),
        ("C", "property", "A house has one back garden, not tens of millions by itself."),
        ("D", "typical_location", "A city has buildings but far fewer individual back gardens than a whole country."),
        ("E", "property", "Land is terrain in general, not a place counted in tens of millions of gardens."),
    ],
    1068: [
        ("A", "used_for", "Crying is an emotional reaction, not how children play-act as movie characters."),
        ("B", "used_for", "Going to a movie means watching it, not pretending to be the characters afterward."),
        ("C", "used_for", "Children pretend to be movie characters by acting out scenes from the film."),
        ("D", "used_for", "Standing in line is waiting at a theater, not playing as movie characters."),
        ("E", "used_for", "Waiting in line is queuing for tickets, not role-playing as film characters."),
    ],
    1069: [
        ("A", "effect", "Thick fur grows from the skin of furry mammals such as bears and rabbits."),
        ("B", "part_whole", "Nipples are present on all mammals but are organs, not hair growing from skin."),
        ("C", "effect", "Hair follicles across mammal skin produce the hair that covers their bodies."),
        ("D", "effect", "A dense fur coat grows outward from mammal skin as an insulating outer layer."),
        ("E", "part_whole", "The spinal cord runs inside the body, not as something growing from skin."),
    ],
    1070: [
        ("A", "used_for", "At a potluck each guest brings a dish and everyone shares the food together."),
        ("B", "used_for", "Cooking food may happen beforehand but sharing dishes is the potluck's main activity."),
        ("C", "motivation", "Believing in god is personal faith unrelated to a potluck gathering."),
        ("D", "motivation", "Demanding justice is a civic act, not what people do at a potluck meal."),
        ("E", "used_for", "Talking to each other is social but sharing food defines a potluck specifically."),
    ],
    1071: [
        ("A", "effect", "Losing money is the opposite of the profit the investor had promised to deliver."),
        ("B", "property", "Lost is a vague adjective and does not name the financial failure as clearly."),
        ("C", "effect", "Losses are the result of poor returns, similar to losing money on investments."),
        ("D", "property", "An expense is a cost paid out, not the failure to earn promised profit."),
        ("E", "effect", "Lose money describes the same financial failure as losing money in investments."),
    ],
    1072: [
        ("A", "capability", "A person can continue learning through life experience without staying in school."),
        ("B", "used_for", "Talking to himself is odd behavior, not something school is required to stop."),
        ("C", "property", "Casting a shadow is a physical fact unrelated to attending school."),
        ("D", "effect", "Going broke is financial ruin, not prevented solely by leaving school."),
        ("E", "used_for", "Crossing a street is a daily action that does not require ongoing schooling."),
    ],
    1073: [
        ("A", "used_for", "Mathematics is broad and includes many topics beyond shapes like triangles."),
        ("B", "used_for", "Geometry is the branch of math that specifically studies triangles and other shapes."),
        ("C", "used_for", "Math class is general and does not name the shape-focused course as precisely."),
        ("D", "property", "A math book is reading material, not the type of class that uses triangles."),
        ("E", "typical_location", "A university is an institution, not the specific class where triangles are studied."),
    ],
    1074: [
        ("A", "typical_location", "A building stays on the ground and cannot carry a person into space."),
        ("B", "used_for", "A space shuttle is a spacecraft designed to carry people into outer space."),
        ("C", "typical_location", "A car travels on roads and cannot reach space no matter how far it drives."),
        ("D", "property", "A fairy tale is fiction and not a real means of traveling to space."),
        ("E", "typical_location", "A street corner is a ground location with no path to outer space."),
    ],
    1075: [
        ("A", "capability", "Being able to hear is a physical sense, not the attentive skill of listening."),
        ("B", "property", "Being very quiet is the opposite of actively listening to someone speak."),
        ("C", "capability", "Paying attention is the listening skill you use when you hear someone speak."),
        ("D", "used_for", "Shut up means stop talking, not the skill of listening to another person."),
        ("E", "property", "Hatred is hostile emotion, not a skill demonstrated by listening to someone."),
    ],
    1076: [
        ("A", "typical_location", "A shelf is where products sit in stores, not the purpose of a non-sale item."),
        ("B", "property", "Costing one dollar is a price tag, not the reason a product is not for sale."),
        ("C", "effect", "Breaking a product destroys it rather than explaining its intended non-sale purpose."),
        ("D", "used_for", "A demonstration product is meant to be shown to customers, not sold to them."),
        ("E", "typical_location", "A store sells goods; a not-for-sale product serves a different purpose entirely."),
    ],
    1077: [
        ("A", "typical_location", "Every state has hospitals, but that phrase names a legal region, not an expected location."),
        ("B", "typical_location", "A military base has a medical clinic but is not where most people expect hospitals."),
        ("C", "property", "A doctor is a person who works in hospitals, not a place to find one."),
        ("D", "typical_location", "Detroit is one city with hospitals, not a general place you would expect them."),
        ("E", "typical_location", "Most cities of any size have at least one hospital serving their residents."),
    ],
    1078: [
        ("A", "property", "When you travel outside your home country you are in a foreign land."),
        ("B", "typical_location", "In space is beyond Earth entirely, not the usual meaning of being abroad."),
        ("C", "typical_location", "A tent is temporary shelter, not the status of being outside your country."),
        ("D", "typical_location", "Work is an activity or place of employment, not being away from your homeland."),
        ("E", "typical_location", "Outside is ambiguous and does not specifically mean outside your home country."),
    ],
    1079: [
        ("A", "typical_location", "Leaving a bicycle on the street is unsafe and risks theft or traffic damage."),
        ("B", "typical_location", "The Netherlands is a country known for cycling, not a place children leave bikes."),
        ("C", "typical_location", "Behind is a vague direction, not a secure spot to leave a bicycle."),
        ("D", "typical_location", "A university campus is for older students, not where children park bicycles."),
        ("E", "typical_location", "A schoolyard often has bike racks where children leave their bicycles during class."),
    ],
    1080: [
        ("A", "capability", "Processing information is exactly what computers are built to do well."),
        ("B", "property", "Casting a shadow is a physical property of objects; computers can cast shadows too."),
        ("C", "effect", "Crashing is a malfunction computers frequently experience, not something they are unable to do."),
        ("D", "capability", "Making decisions is something computers can do through programs and algorithms."),
        ("E", "capability", "Becoming sensible requires human judgment and empathy that computers cannot achieve."),
    ],
    1081: [
        ("A", "used_for", "You use your feet and legs to push off the ground and stand up."),
        ("B", "has_prerequisite", "Balance helps you stay upright but is not the body part you use to stand."),
        ("C", "has_prerequisite", "Effort is required but is abstract, not the physical part used to stand up."),
        ("D", "used_for", "Hands help you push off a chair but feet are what you stand on."),
        ("E", "motivation", "Courage is emotional strength, not the body part that lifts you to standing."),
    ],
    1082: [
        ("A", "typical_location", "A teaspoon in your mouth means you are using it, not storing it away."),
        ("B", "used_for", "Eating is an activity done with a spoon, not where an unused one is kept."),
        ("C", "typical_location", "A kitchen drawer is the usual place to store a teaspoon when not in use."),
        ("D", "typical_location", "A cup of coffee may hold a stirring spoon temporarily but is not storage."),
        ("E", "typical_location", "A coffee cup might hold a spoon briefly but drawers are the proper storage spot."),
    ],
    1083: [
        ("A", "effect", "A dimly lit room is the result of lighting a candle, not where you choose to place one."),
        ("B", "typical_location", "A synagogue uses candles for worship, not typically for a romantic atmosphere."),
        ("C", "typical_location", "A bedroom is a common place to light candles for a romantic atmosphere."),
        ("D", "used_for", "A birthday cake holds candles for celebration, not for setting a romantic mood."),
        ("E", "property", "Roses are flowers that complement romance but are not where you light a candle."),
    ],
    1084: [
        ("A", "typical_location", "A kitchen might have grapes in a bowl but often does not keep them on hand."),
        ("B", "typical_location", "A plate may hold grapes but is empty unless someone put grapes on it."),
        ("C", "typical_location", "A field is open farmland where grapevines grow, so grapes are commonly found there."),
        ("D", "typical_location", "A winery processes grapes and typically has plenty of them on the premises."),
        ("E", "typical_location", "A fruit stand sells fresh grapes and is a likely place to find them."),
    ],
    1085: [
        ("A", "typical_location", "A cloud is where snowflakes form in the sky, not a season you spend in a region."),
        ("B", "property", "December is a winter month but spending a December is not the usual seasonal phrase."),
        ("C", "typical_location", "Air is the medium snow falls through, not a season spent in a snowy region."),
        ("D", "typical_location", "Africa is mostly warm and rarely has the snow she excitedly caught on her tongue."),
        ("E", "typical_location", "Spending a winter in a snowy region lets you catch snowflakes on your tongue."),
    ],
    1086: [
        ("A", "typical_location", "A restroom needs privacy and usually has small or frosted windows, not a main window."),
        ("B", "property", "A building is a general structure, not the specific surface where a house window goes."),
        ("C", "part_whole", "A wall is the structural surface where a house window is installed to admit light."),
        ("D", "typical_location", "A classroom is in a school building, not a room in a house."),
        ("E", "typical_location", "A space shuttle is a spacecraft, not a place to install a house window."),
    ],
    1087: [
        ("A", "typical_location", "A backyard is where many home vegetable gardens are planted and tended daily."),
        ("B", "typical_location", "Outside is where a vegetable garden is located, exposed to sun and fresh air."),
        ("C", "typical_location", "An amusement park has rides and crowds, not a personal vegetable garden."),
        ("D", "used_for", "Eating is consuming produce, not the outdoor place where you tend a garden."),
        ("E", "typical_location", "A back yard is the outdoor area behind a house where gardens are commonly kept."),
    ],
    1088: [
        ("A", "used_for", "Boarding a bus is the action at a stop, not the destination imposing luggage limits."),
        ("B", "typical_location", "A city is a general area, not the specific destination with strict luggage rules."),
        ("C", "property", "Fast describes speed and does not explain why a bus stop restricts luggage size."),
        ("D", "typical_location", "An urban area is a broad region, not the destination with luggage restrictions."),
        ("E", "typical_location", "An airport bus stop enforces size limits because passengers carry large travel bags."),
    ],
    1089: [
        ("A", "cause", "A fight provokes anger and tension, not the laughter a surprising event causes."),
        ("B", "cause", "Accidents are mishaps that cause alarm or sadness, not amused laughter."),
        ("C", "cause", "Bad news brings sorrow and worry, not the laughter sparked by something surprising."),
        ("D", "cause", "Something funny and surprising catches people off guard and makes them laugh."),
        ("E", "effect", "Being frightened is a fear reaction, the opposite of laughing at a surprise."),
    ],
    1090: [
        ("A", "used_for", "Obeying orders is what subordinates do, not what a commanding officer chose to do."),
        ("B", "used_for", "Complying with rules is following authority, not leading a military command."),
        ("C", "motivation", "Choosing to serve in the military is what a career officer proudly commits to."),
        ("D", "used_for", "Following commands is a subordinate's role, not the leader's chosen path of service."),
        ("E", "used_for", "Asking questions seeks information and is not the proud choice of a commander."),
    ],
    1091: [
        ("A", "effect", "Fear is a negative reaction, not what someone feels in a positive new environment."),
        ("B", "effect", "Curiosity drives interest in new things but is quieter than the thrill of discovery."),
        ("C", "effect", "Wonder is awe at new sights, a thoughtful feeling in a positive setting."),
        ("D", "effect", "Anger is hostility, incompatible with a positive environment of new experiences."),
        ("E", "effect", "Excitement is the upbeat feeling when seeing new things in a positive environment."),
    ],
    1092: [
        ("A", "typical_location", "A restaurant uses dishes for serving food, not for storing empty ones long term."),
        ("B", "typical_location", "A pantry stores dry food goods, not the empty dishes used at meals."),
        ("C", "typical_location", "A table holds dishes during meals but is not where empty ones are stored."),
        ("D", "typical_location", "A kitchen cabinet is the usual place where clean empty dishes are kept."),
        ("E", "property", "Glass is a material dishes are made from, not a storage location."),
    ],
    1093: [
        ("A", "effect", "Anxiety is nervous worry, not a typical pleasant exchange before returning to work."),
        ("B", "effect", "Earning money is a goal of working, not something two people have before going back."),
        ("C", "used_for", "Two coworkers or friends often have a conversation before heading back to work."),
        ("D", "effect", "Depression is sadness, not a normal interaction before resuming the workday."),
        ("E", "effect", "A fight is a conflict, not the usual exchange before people return to their jobs."),
    ],
    1094: [
        ("A", "typical_location", "A house usually has enough rooms that a space-saving sofa bed is less necessary."),
        ("B", "typical_location", "An apartment has limited space, making a hide-a-bed sofa a practical choice."),
        ("C", "typical_location", "A village home tends to be spacious and rarely needs a convertible sofa bed."),
        ("D", "typical_location", "A beach condo may be small but an apartment better matches typical sofa-bed buyers."),
        ("E", "typical_location", "A hotel furnishes rooms temporarily; residents buy sofa beds for permanent small homes."),
    ],
    1095: [
        ("A", "typical_location", "A garage keeps a bicycle sheltered and locked away from theft and weather."),
        ("B", "typical_location", "A sidewalk is for walking and riding, not a secure place to leave a bicycle."),
        ("C", "typical_location", "A schoolyard is semi-public and bicycles left there can still be stolen."),
        ("D", "typical_location", "A toy store sells bicycles but is not where you safely store your own."),
        ("E", "typical_location", "A street exposes bicycles to traffic and theft, making it an unsafe place to leave one."),
    ],
    1096: [
        ("A", "property", "Time passes during any activity but is not itself a fun way to learn science."),
        ("B", "effect", "Frustration is a negative feeling, not a fun method for children to learn science."),
        ("C", "effect", "Becoming educated is an outcome of learning, not the fun method itself."),
        ("D", "used_for", "Doing hands-on experiments is a fun way for children to learn about science."),
        ("E", "effect", "Excitement is a feeling during learning, not the activity that teaches science."),
    ],
    1097: [
        ("A", "motivation", "Entertainment is why she watched the film, not what she did by closing her eyes."),
        ("B", "effect", "Dying is not what Sarah did; she simply missed most of the movie."),
        ("C", "effect", "Crying might happen during a film but does not explain missing the entire middle."),
        ("D", "effect", "Closing her eyes at the start and waking at the credits means she fell asleep."),
        ("E", "used_for", "Masturbating is unrelated to closing your eyes and missing a film's middle."),
    ],
    1098: [
        ("A", "effect", "Staring at a screen for hours commonly causes eyestrain and headaches."),
        ("B", "effect", "Addiction is a behavioral dependency, not a direct physical effect on the body."),
        ("C", "used_for", "Editing is a task done on a computer, not a bodily harm from prolonged use."),
        ("D", "effect", "Falling asleep can happen at the keyboard but is not a typical bodily injury."),
        ("E", "effect", "Repetitive typing over long sessions can cause carpal tunnel syndrome in the wrists."),
    ],
    1099: [
        ("A", "part_whole", "A cabinet has enclosed shelves behind doors that hide stored items from view."),
        ("B", "typical_location", "A mortuary stores bodies, not household items on enclosed shelves."),
        ("C", "typical_location", "A bookstore displays books on open shelves visible to browsing customers."),
        ("D", "typical_location", "A school building is too broad to specify enclosed shelf storage."),
        ("E", "typical_location", "A bedroom may have open shelves, but cabinets provide the enclosed type asked for."),
    ],
    1100: [
        ("A", "property", "Cloud vision is a product name, not an action dark clouds perform in the sky."),
        ("B", "property", "Weather is a general category, not the specific action dark clouds carry out."),
        ("C", "effect", "Being awe inspiring is an observer's reaction, not what dark clouds themselves do."),
        ("D", "effect", "Dark clouds gather moisture and are likely to bring rain to the ground below."),
        ("E", "effect", "Rain water is the result after clouds release precipitation, not the action itself."),
    ],
    1101: [
        ("A", "typical_location", "A lake is a natural body of water, not a chlorinated backyard summer feature."),
        ("B", "typical_location", "Children's pools are small but the question points to a backyard chlorinated pool."),
        ("C", "typical_location", "A pond is a natural water body without the chlorination described in the question."),
        ("D", "typical_location", "A backyard swimming pool is chlorinated and shallow, limiting summer swimming fun."),
        ("E", "typical_location", "A puddle is too small and temporary to be a backyard summer swimming spot."),
    ],
    1102: [
        ("A", "capability", "Dressing herself is a skill children learn early, not an adult-only privilege."),
        ("B", "capability", "Marrying without parental consent is a legal privilege reserved for adults."),
        ("C", "capability", "Drinking beer legally requires reaching adulthood in most countries."),
        ("D", "capability", "Working is something teenagers and adults both do, not exclusive to adulthood."),
        ("E", "capability", "Driving a train requires special licensing, not a common privilege of being an adult."),
    ],
    1103: [
        ("A", "typical_location", "A neighbor's house nearby is the closest place with a sofa outside your own home."),
        ("B", "typical_location", "A person's living room could be your own, not the closest outside your residence."),
        ("C", "typical_location", "A living room in your own home is your residence, not an outside location."),
        ("D", "typical_location", "The White House is far away and not the closest sofa to your own residence."),
        ("E", "typical_location", "Home usually means your own residence, which the question explicitly excludes."),
    ],
    1104: [
        ("A", "used_for", "Illustrating a point is a calm argument, not fueled by a charged anger bar."),
        ("B", "used_for", "Charging an anger bar in a game lets you more easily destroy an enemy."),
        ("C", "used_for", "Cooling off reduces anger, the opposite of what a filled anger bar enables."),
        ("D", "used_for", "Writing a letter is a calm activity unrelated to an anger power meter."),
        ("E", "used_for", "Getting drunk is reckless behavior, not what an anger bar helps you do in-game."),
    ],
    1105: [
        ("A", "effect", "Pain may follow a fall but broken bones are a more likely serious result from height."),
        ("B", "effect", "Falling from a height often causes broken bones from the impact on landing."),
        ("C", "property", "Going down describes the motion of falling, not the injury that results."),
        ("D", "used_for", "Diving is a controlled intentional jump into water, not an accidental fall."),
        ("E", "effect", "Injuries is a general term; broken bones is the specific likely result from a high fall."),
    ],
    1106: [
        ("A", "typical_location", "Suburbs surround cities and still have substantial populations, not smaller ones."),
        ("B", "typical_location", "A town has a smaller population than a bright bustling city."),
        ("C", "typical_location", "Wilderness has very few people, far less population than a bright city."),
        ("D", "typical_location", "Outside is too vague to name a place with a smaller population than a city."),
        ("E", "typical_location", "The countryside is rural with a much smaller population than a bright city."),
    ],
    1107: [
        ("A", "typical_location", "A farmers market sells fresh apples but is not the most typical everyday source."),
        ("B", "typical_location", "A table holds apples at home after you buy them, not where you purchase them."),
        ("C", "typical_location", "A grocery store is the typical place where people buy apples for everyday use."),
        ("D", "typical_location", "An apple tree grows apples for picking, not the usual place to buy them."),
        ("E", "typical_location", "A fridge stores apples after purchase, not where you typically buy them."),
    ],
    1108: [
        ("A", "effect", "Bankruptcy is financial ruin, not a method for finding the best product price."),
        ("B", "effect", "Loss of money is a bad outcome, not a strategy for getting the best price."),
        ("C", "used_for", "Comparison shopping means checking prices at different sellers to get the best deal."),
        ("D", "effect", "Overstocking means buying too much inventory, not a method to find lower prices."),
        ("E", "used_for", "Playing games is entertainment, not a method for finding the best product price."),
    ],
    1109: [
        ("A", "typical_location", "A historical novel casts knights as heroes in fictional medieval adventures."),
        ("B", "typical_location", "A castle employs knights as guards but they serve there rather than being celebrated heroes."),
        ("C", "typical_location", "A chess set has a knight piece, a game token rather than a storybook hero."),
        ("D", "typical_location", "A renaissance festival features costumed knights as entertainment, not heroic legend."),
        ("E", "typical_location", "The middle ages is the era when knights were celebrated as heroic figures."),
    ],
    1110: [
        ("A", "used_for", "Steel reinforces some houses but is not the primary material for building them."),
        ("B", "used_for", "Steel frames are essential for constructing modern tall buildings and skyscrapers."),
        ("C", "used_for", "Steel can build many structures but tall buildings most prominently rely on it."),
        ("D", "used_for", "Steel is widely used to build bridges that span rivers and valleys."),
        ("E", "used_for", "An automobile factory is built with steel but is a facility, not what steel builds."),
    ],
    1111: [
        ("A", "cause", "Sunset marks the transition into evening but daytime precedes the entire period."),
        ("B", "cause", "Evening follows daytime as the sun lowers and daylight fades into dusk."),
        ("C", "cause", "Dawn begins the morning, long before evening arrives at day's end."),
        ("D", "cause", "Night comes after evening, not before it in the daily cycle."),
        ("E", "cause", "Early morning is at the start of the day, many hours before evening begins."),
    ],
    1112: [
        ("A", "property", "Cramped means uncomfortably tight, the fit socks had before being stretched out."),
        ("B", "property", "Stretching socks loosens the fabric so they then have a loose, relaxed fit."),
        ("C", "effect", "Contract means shrink tighter, the opposite of what happens when socks are stretched."),
        ("D", "typical_location", "A park is an outdoor place unrelated to how stretched socks fit."),
        ("E", "effect", "Compressing means squeezing tighter, the opposite of stretching socks loose."),
    ],
    1113: [
        ("A", "used_for", "Meeting a friend over coffee usually means sitting together and talking."),
        ("B", "effect", "Excitement is a feeling you may have, not the activity you do over coffee."),
        ("C", "effect", "Joy is an emotion felt during the meeting, not the action performed over coffee."),
        ("D", "used_for", "Abuse is harm, not something people do when meeting a friend for coffee."),
        ("E", "effect", "Panic is distress, incompatible with a friendly coffee meeting."),
    ],
    1114: [
        ("A", "typical_location", "A drive-in movie has one screen and one audio channel, not many speakers."),
        ("B", "typical_location", "A shelf holds objects and is not a venue with many speakers presenting."),
        ("C", "typical_location", "A conference features many speakers each presenting to an audience in turn."),
        ("D", "typical_location", "A lecture hall typically has one professor speaking, not many equal speakers."),
        ("E", "typical_location", "A demonstration usually has one presenter showing how something works."),
    ],
    1115: [
        ("A", "property", "Toxic describes lead's health hazard, not why a child cannot lift the heavy box."),
        ("B", "property", "Light means easy to lift, the opposite of a box full of dense lead."),
        ("C", "property", "Isolated from sulphide is a chemical detail unrelated to the box being too heavy."),
        ("D", "property", "Lead is an extremely heavy metal, making its box too heavy for a child to lift."),
        ("E", "property", "Very dense means tightly packed mass, explaining weight but heavy is the direct reason."),
    ],
    1116: [
        ("A", "typical_location", "A sports arena sells tickets to games, not to a movie like The Greatest Showman."),
        ("B", "typical_location", "An auditorium hosts live performances but movie tickets come from a theatre."),
        ("C", "typical_location", "An opera house sells opera tickets, not tickets to a Hollywood musical film."),
        ("D", "typical_location", "A movie theatre sells tickets at the booth for films like The Greatest Showman."),
        ("E", "typical_location", "A metro station sells transit fares, not movie tickets at a ticket booth."),
    ],
    1117: [
        ("A", "used_for", "Swimming is a water sport unrelated to the legal phrase bringing suit."),
        ("B", "used_for", "Bringing suit against someone means filing a lawsuit and going to court."),
        ("C", "used_for", "Ruling is what a judge delivers, not what the plaintiff does when suing."),
        ("D", "property", "Randomness is chance, unrelated to the legal action of filing a suit."),
        ("E", "effect", "Laughter is amusement, not the legal process of suing another party."),
    ],
    1118: [
        ("A", "part_whole", "The end of the line is the hook where a caught fish hangs when reeling it in."),
        ("B", "typical_location", "The ocean is where fish live but you take them off the hook at the line's end."),
        ("C", "typical_location", "A pet shop sells aquarium fish, not where you land fish while angling."),
        ("D", "typical_location", "A boat is where you stand while fishing, not what you remove the fish from."),
        ("E", "typical_location", "A pond is where fish swim but the fish is taken off the fishing line hook."),
    ],
    1119: [
        ("A", "typical_location", "West Texas is a dry region but not the reason a lizard basks on a rock."),
        ("B", "typical_location", "Arid regions are habitats for lizards but do not explain sun-basking behavior."),
        ("C", "motivation", "Getting a sexy tan is a human joke and not why a cold-blooded lizard lies in sun."),
        ("D", "motivation", "A lizard lies on a warm rock in the sun to raise its body temperature."),
        ("E", "typical_location", "New Mexico is a sunny state but not the biological reason for basking behavior."),
    ],
}
