# -*- coding: utf-8 -*-
"""Hand-authored v2-style KB for CSQA qids 1220-1269 (no answerKey)."""

CHUNK = {
    1220: [
        ("A", "used_for", "A bouquet of flowers provides nectar and pollen that bees would appreciate as a gift."),
        ("B", "typical_location", "A trash can holds garbage, nothing a bee would want as a gift."),
        ("C", "typical_location", "Pizza is human food, not something a bee would like receiving."),
        ("D", "typical_location", "The sky is open air, not a tangible gift a bee would enjoy."),
        ("E", "typical_location", "The United States is a country, not a gift item a bee would appreciate."),
    ],
    1221: [
        ("A", "effect", "Compliments are kind words given to others, not what a good person is known for."),
        ("B", "property", "A green thumb is a gardening talent, too specific for what a good person is known for."),
        ("C", "used_for", "Riding horses is an activity, not the reputation of a person considered good."),
        ("D", "motivation", "A good person is known for making a positive contribution to society."),
        ("E", "property", "Wearing outrageous clothing is a fashion choice, not what defines a good person."),
    ],
    1222: [
        ("A", "motivation", "A retired person may have to return to work if they have debt to pay off."),
        ("B", "motivation", "Earning money is the purpose of returning, triggered by needing money in retirement."),
        ("C", "effect", "Leaving work is retirement itself, not a reason to return to employment."),
        ("D", "motivation", "Needing money is why a retired person may be forced to return to work."),
        ("E", "property", "A key opens locks, not a reason a retired person returns to employment."),
    ],
    1223: [
        ("A", "typical_location", "A Victorian style house has an attic; the nearest one is in your own home."),
        ("B", "typical_location", "A basement is below ground, the opposite direction from an attic above."),
        ("C", "typical_location", "Older houses may have attics, but your own home is the nearest attic location."),
        ("D", "typical_location", "Your own home contains the nearest attic accessible without travelling elsewhere."),
        ("E", "typical_location", "A Victorian house has an attic, but the nearest one is in your own home."),
    ],
    1224: [
        ("A", "used_for", "Win at Jenga is a board game, not what the undefeated opponent seemed able to do."),
        ("B", "property", "Victory is a win outcome, not the verb describing what the opponent could do to anyone."),
        ("C", "effect", "Losing is what opponents do, not what the dominant fighter could do to everyone."),
        ("D", "property", "Winning is a gerund, but conquer captures defeating anyone after the general's first loss."),
        ("E", "capability", "After the general's defeat, his opponent seemed able to conquer anybody."),
    ],
    1225: [
        ("A", "typical_location", "A friend's house is a domestic setting, not where wild monkeys live."),
        ("B", "typical_location", "A research laboratory holds captive monkeys, not wild ones in nature."),
        ("C", "typical_location", "The French government is an institution, not a wild monkey habitat."),
        ("D", "typical_location", "A beach is coastal sand, not the primary habitat for wild monkeys."),
        ("E", "typical_location", "Madagascar is an island where wild monkeys and lemurs live in nature."),
    ],
    1226: [
        ("A", "typical_location", "Michigan borders a Great Lake, so a steakhouse there can offer a Great Lake view."),
        ("B", "typical_location", "Florida borders the Atlantic and Gulf, not the Great Lakes region."),
        ("C", "typical_location", "Kansas City is inland with no Great Lake view for a steakhouse."),
        ("D", "typical_location", "Maine borders the Atlantic Ocean, not the Great Lakes."),
        ("E", "typical_location", "Georgia is in the Southeast, far from any Great Lake views."),
    ],
    1227: [
        ("A", "typical_location", "A community kitchen is indoors; butane fumes require outdoor use of the stove."),
        ("B", "typical_location", "The post office handles mail, not outdoor cooking with a butane stove."),
        ("C", "typical_location", "An apartment is indoors where butane fumes make stove use unsafe."),
        ("D", "typical_location", "A friend's house is indoors, unsuitable for butane stove use due to fumes."),
        ("E", "typical_location", "John would use his butane stove outside of a tent while camping outdoors."),
    ],
    1228: [
        ("A", "property", "Buttons are fasteners on shirts, not where she stores shirts at home."),
        ("B", "typical_location", "A suitcase is for travel packing, not where shirts are stored at home."),
        ("C", "typical_location", "A washing machine cleans clothes, not where clean shirts are stored."),
        ("D", "typical_location", "A sporting goods store sells athletic wear, not home shirt storage."),
        ("E", "typical_location", "She put her shirts away in the closet where clothing is normally stored."),
    ],
    1229: [
        ("A", "property", "First rate means excellent; Billy thought their odds were good, not bad as Sarah felt."),
        ("B", "property", "Adequate means sufficient; Billy disagreed with Sarah's pessimism about their odds."),
        ("C", "property", "Billy thought their odds were good despite Sarah feeling bad about them."),
        ("D", "property", "Propitious means favorable; Billy saw their odds positively unlike Sarah."),
        ("E", "property", "Sufficient means enough; Billy believed the odds were acceptable, not bad."),
    ],
    1230: [
        ("A", "typical_location", "A brother's house is one home, not the annual gathering for meeting a new niece."),
        ("B", "typical_location", "A family picture book holds photos, not the event where relatives meet."),
        ("C", "typical_location", "A family tree charts genealogy, not the annual gathering to meet relatives."),
        ("D", "typical_location", "A family reunion is the annual gathering where relatives meet a new niece."),
        ("E", "typical_location", "A book is reading material, not the annual event for family gatherings."),
    ],
    1231: [
        ("A", "motivation", "Listening with empathy is a reason someone pays attention to others speaking."),
        ("B", "property", "Thirsty describes needing drink, not a reason for listening to someone."),
        ("C", "used_for", "Hearing things is the sensory result of listening, not the reason for doing it."),
        ("D", "motivation", "Gaining knowledge motivates listening to learn from what is being said."),
        ("E", "motivation", "Learning is why someone listens carefully to absorb new information."),
    ],
    1232: [
        ("A", "typical_location", "A town is a community, not the source of traumatic mouth injury patients."),
        ("B", "typical_location", "Michigan is a state, not specifically where dental trauma patients originate."),
        ("C", "typical_location", "An office building may cause falls, but hospitals send trauma patients to dentists."),
        ("D", "typical_location", "Schools may have accidents, but hospitals refer traumatic mouth injuries to dentists."),
        ("E", "typical_location", "Hospital emergency rooms treat mouth trauma and refer patients to dental offices."),
    ],
    1233: [
        ("A", "used_for", "A music show is a performance, not what the upright piano helped sound better in."),
        ("B", "typical_location", "The upright piano helped the music room achieve a better, fuller sound."),
        ("C", "typical_location", "A house contains rooms, but the music room specifically benefits from a piano."),
        ("D", "used_for", "A band performs music, but the piano improved sound in the music room."),
        ("E", "typical_location", "A college has music facilities, but a music room is where the piano improved sound."),
    ],
    1234: [
        ("A", "typical_location", "Great oceans have sharks, but the question contrasts lake woods with outdoor dangers."),
        ("B", "typical_location", "The great outdoors around a woodland lake holds many natural dangers besides sharks."),
        ("C", "typical_location", "Tropical waters have sharks, not dangers found at a lake in the woods."),
        ("D", "typical_location", "The Pacific Ocean has sharks, irrelevant to a lake surrounded by woods."),
        ("E", "typical_location", "The Gulf of Mexico is saltwater; woodland lake dangers are in the great outdoors."),
    ],
    1235: [
        ("A", "typical_location", "A drawer stores items inside the home after mail is brought in from delivery."),
        ("B", "typical_location", "The health department distributes public health pamphlets, not home-delivered ones."),
        ("C", "typical_location", "A library lends books, not where home-delivered pamphlets are found."),
        ("D", "typical_location", "Pamphlets delivered to your home arrive in your mailbox first."),
        ("E", "typical_location", "The floor may hold dropped mail, but the mailbox is where delivered pamphlets arrive."),
    ],
    1236: [
        ("A", "typical_location", "Ohio is a state, not an outdoor merchant collection with a clothing store."),
        ("B", "used_for", "Buying clothing is an activity, not an outdoor merchant area with clothing stores."),
        ("C", "typical_location", "A park is for recreation, not a commercial area with clothing stores."),
        ("D", "typical_location", "A strip mall is an outdoor collection of merchants often including a clothing store."),
        ("E", "typical_location", "A city or town is broad; a strip mall specifically groups outdoor merchants."),
    ],
    1237: [
        ("A", "typical_location", "An office building contains many cubicles where corporate employees work."),
        ("B", "typical_location", "Work describes employment activity, not a physical location with cubicles."),
        ("C", "typical_location", "A bank handles finances, not the typical cubicle-filled corporate workspace."),
        ("D", "typical_location", "Office work is an activity, not the building housing corporate cubicles."),
        ("E", "typical_location", "A restroom is for hygiene, not where corporate cubicles are located."),
    ],
    1238: [
        ("A", "typical_location", "A show is a performance, not home equipment for watching movies."),
        ("B", "used_for", "People used a VCR at home to watch movies on videotape in their houses."),
        ("C", "used_for", "The duplicate VCR option also describes home movie playback equipment."),
        ("D", "used_for", "A television displays movies at home but the VCR was the playback device people used."),
        ("E", "typical_location", "A video store rented tapes; people watched movies at home on VCRs or televisions."),
    ],
    1239: [
        ("A", "effect", "A train behind schedule is likely to arrive late at its destination."),
        ("B", "effect", "Slowing down would worsen delays, not compensate for being behind schedule."),
        ("C", "effect", "Making up time is the goal, but being behind schedule means likely arriving late."),
        ("D", "effect", "Arriving early contradicts being behind schedule on a delayed train."),
        ("E", "effect", "Arriving on time is unlikely when a train is already behind schedule."),
    ],
    1240: [
        ("A", "effect", "Visiting relatives is a social activity, not what a person fearing failure expects."),
        ("B", "effect", "Scared describes fear itself, not the outcome someone who fears failure anticipates."),
        ("C", "effect", "Doctor himself is unclear phrasing, not the consequence feared from failure."),
        ("D", "effect", "Thank god is an exclamation, not what someone fearing failure thinks will happen."),
        ("E", "effect", "A person who fears failure worries they will amount to nothing."),
    ],
    1241: [
        ("A", "used_for", "Soft copy is a digital file format, not the paired shortcut after copying."),
        ("B", "used_for", "Copy and paste are paired keyboard shortcuts the efficient worker learned together."),
        ("C", "property", "Unique means one-of-a-kind, not the operation paired with copy shortcuts."),
        ("D", "property", "Ocean is a body of water, unrelated to copy shortcuts at work."),
        ("E", "property", "Creation is making something new, not the shortcut paired with copy."),
    ],
    1242: [
        ("A", "primary_function", "The main activity one does at an office is work on job tasks."),
        ("B", "typical_location", "A school building is for education, not a typical office workplace."),
        ("C", "typical_location", "A workplace is a general term; work is what you do at an office."),
        ("D", "typical_location", "A skyscraper is a tall building, not the activity performed in an office."),
        ("E", "typical_location", "A public building serves civic functions, not specifically office work activity."),
    ],
    1243: [
        ("A", "effect", "Depression is a mood disorder, not the direct physical result of prolonged hard thinking."),
        ("B", "effect", "Revelation is an insight, not the exhaustion caused by extended mental effort."),
        ("C", "effect", "A new thought is an idea, not the bodily effect of thinking hard and long."),
        ("D", "effect", "Thinking hard and long, like exercise on a treadmill, can cause mental fatigue."),
        ("E", "effect", "Knowledge is an outcome of thinking, not the tiring effect of prolonged mental effort."),
    ],
    1244: [
        ("A", "typical_location", "Air is what birds breathe, not how they reproduce by laying eggs."),
        ("B", "used_for", "Picking berries is foraging, not the reproductive method of laying eggs."),
        ("C", "typical_location", "The sky is where birds fly, not how they reproduce."),
        ("D", "used_for", "Breathing sustains life, not the reproductive act of laying eggs."),
        ("E", "effect", "Birds reproduce by laying eggs that hatch into offspring."),
    ],
    1245: [
        ("A", "motivation", "Staying alive is the goal when attacked, achieved by defending yourself."),
        ("B", "used_for", "Get rid of means eliminating something, not the immediate response to an attack."),
        ("C", "property", "Attacked describes the assault itself, not your defensive response."),
        ("D", "used_for", "If you are being attacked, you defend yourself to protect your safety."),
        ("E", "effect", "Falling down may result from an attack, not your intentional defensive action."),
    ],
    1246: [
        ("A", "typical_location", "A brownstone may have ground-floor units, but a hotel is standard for overnight stays."),
        ("B", "typical_location", "A highrise building is tall; hotels commonly offer ground-floor rooms for guests."),
        ("C", "typical_location", "A hotel provides ground-floor rooms where travellers spend the night away from home."),
        ("D", "typical_location", "A subway is transit underground, not where you spend the night."),
        ("E", "typical_location", "An office building is for work, not overnight accommodation away from home."),
    ],
    1247: [
        ("A", "property", "Just means fair or only, not the quality of everything a bad person said."),
        ("B", "property", "Sufficient means enough, not a description of a bad person's statements."),
        ("C", "property", "Even though the person was bad, everything he said was true."),
        ("D", "property", "Badarse is slang for tough, not what describes the truthfulness of his words."),
        ("E", "property", "Prime means best quality, not the accuracy of statements from a bad person."),
    ],
    1248: [
        ("A", "typical_location", "A backpack may carry a towel to the beach, but the beach is where towels are used."),
        ("B", "typical_location", "A beach towel is most likely found at the beach where it is used."),
        ("C", "typical_location", "A swimming pool area is where beach towels are commonly found and used."),
        ("D", "typical_location", "A locker room near pools stores towels including beach towels."),
        ("E", "typical_location", "At a hotel you may find beach towels provided for guest pool or beach use."),
    ],
    1249: [
        ("A", "used_for", "Spit was used to lubricate during copulation in the described scenario."),
        ("B", "used_for", "Mark territory is an animal behavior, not why spit is used during copulation."),
        ("C", "used_for", "Kiss is an affectionate act, different from using spit to lubricate."),
        ("D", "effect", "Procreation is the biological goal, not what spit was used to accomplish directly."),
        ("E", "effect", "Release tension is a relaxation outcome, not the purpose of using spit."),
    ],
    1250: [
        ("A", "effect", "Children may learn from mistakes, but embarrassment is the immediate feeling after wrong answers."),
        ("B", "effect", "Correct is the desired outcome, not what happens after answering incorrectly."),
        ("C", "effect", "Answering questions incorrectly commonly causes embarrassment for the person."),
        ("D", "effect", "Teaching follows instruction, not the result of giving wrong answers."),
        ("E", "effect", "A better grade comes from correct answers, not from answering incorrectly."),
    ],
    1251: [
        ("A", "typical_location", "An office building contains many computers across grouped work spaces."),
        ("B", "typical_location", "A canteen is a dining area, not where work computers are grouped."),
        ("C", "typical_location", "A backpack is portable carrying case, not a group of work space computers."),
        ("D", "typical_location", "A house may have a few computers, not many in grouped corporate workspaces."),
        ("E", "typical_location", "A box is a container, not a collection of computers in work spaces."),
    ],
    1252: [
        ("A", "used_for", "Singing songs is vocal communication, not how birds produce offspring."),
        ("B", "used_for", "Sleeping together is not how birds reproduce their young."),
        ("C", "effect", "Birds have babies by laying eggs that hatch into chicks."),
        ("D", "used_for", "Spreading wings is for flight, not the method of bird reproduction."),
        ("E", "effect", "Birds reproduce by laying eggs as their primary method of having babies."),
    ],
    1253: [
        ("A", "typical_location", "After using a rubber stamp, you put it back on or in your desk."),
        ("B", "typical_location", "An art class may use stamps, but a desk is where office stamps are stored."),
        ("C", "typical_location", "An office desk is where a rubber stamp is kept after use."),
        ("D", "typical_location", "A table is a flat surface, but a desk is the standard stamp storage spot."),
        ("E", "typical_location", "Indiana is a state, not where you put a rubber stamp after using it."),
    ],
    1254: [
        ("A", "typical_location", "A pantry stores food indoors, not where a potato is planted to grow."),
        ("B", "typical_location", "A paper bag holds potatoes temporarily, not where they grow."),
        ("C", "typical_location", "A potato should be placed underground in soil where it can sprout and grow."),
        ("D", "typical_location", "Boiling water cooks potatoes, it does not allow them to grow."),
        ("E", "typical_location", "A drawer is indoor storage, not a planting location for growing potatoes."),
    ],
    1255: [
        ("A", "effect", "Demands being met is a settlement outcome when a union ends its strike."),
        ("B", "effect", "Complaints being addressed follows settlement before workers return to their jobs."),
        ("C", "effect", "Being satisfied follows resolving the dispute that caused the strike."),
        ("D", "effect", "After settling, the union ends the strike and workers get back to work."),
        ("E", "effect", "More money may be part of the deal, but getting back to work follows ending the strike."),
    ],
    1256: [
        ("A", "has_prerequisite", "Mental concentration is needed to ready yourself before beginning detailed work."),
        ("B", "has_prerequisite", "Shoes are footwear, not a mental preparation for detailed work."),
        ("C", "has_prerequisite", "Applying for a job is employment seeking, not mental readiness for detailed tasks."),
        ("D", "has_prerequisite", "Shaving is grooming, not the mental preparation for detailed work."),
        ("E", "has_prerequisite", "Showering is hygiene, not the mental focus needed before detailed work."),
    ],
    1257: [
        ("A", "typical_location", "A swimming pool involves water, which the question excludes."),
        ("B", "typical_location", "An airport is for travel, not specifically a kid destination without water or shopping."),
        ("C", "typical_location", "An amusement park is fun for kids without requiring water or buying things."),
        ("D", "typical_location", "Disneyland involves buying tickets and merchandise, partially excluded by the question."),
        ("E", "typical_location", "A toy store requires buying something, which the question excludes."),
    ],
    1258: [
        ("A", "typical_location", "A cousin's house is a destination, not transportation for a ferret from the pet shop."),
        ("B", "used_for", "John called a taxi cab because he could not bring the ferret on the bus."),
        ("C", "typical_location", "Own home is where John was going, not what he called for transport."),
        ("D", "typical_location", "A friend is a person, not the vehicle service John called instead of the bus."),
        ("E", "typical_location", "A wood pile is stacked lumber, not transportation for a pet ferret."),
    ],
    1259: [
        ("A", "property", "Happy is an emotion, not what you do with a friend before playing."),
        ("B", "used_for", "Sitting is resting, not the prerequisite social step before going to play."),
        ("C", "used_for", "Competing happens during play, not the step before going to play together."),
        ("D", "has_prerequisite", "You need to meet your friend before going to play together."),
        ("E", "effect", "Being entertained results from play, not the prerequisite before going to play."),
    ],
    1260: [
        ("A", "effect", "Panic is distress, the opposite of what someone hopes for on a deserted island vacation."),
        ("B", "motivation", "Having fun is a goal, but relaxation is the primary hope for a deserted island trip."),
        ("C", "motivation", "Relaxation is what people hope to achieve on a peaceful deserted island vacation."),
        ("D", "motivation", "Solitude may come with the island, but relaxation is the hoped-for achievement."),
        ("E", "motivation", "Peace is a state of calm closely tied to the relaxation sought on a deserted island."),
    ],
    1261: [
        ("A", "typical_location", "A table is furniture, not where you go to send a piece of mail."),
        ("B", "typical_location", "You go to the post office to send a piece of mail."),
        ("C", "typical_location", "A neighbor's house is a residence, not a mail sending facility."),
        ("D", "typical_location", "A railway station handles trains, not routine mail sending for individuals."),
        ("E", "typical_location", "A fridge keeps food cold, not a place to send mail."),
    ],
    1262: [
        ("A", "used_for", "Smacking a face is aggression, not how dating couples greet each other."),
        ("B", "used_for", "Believing in god is faith, not a greeting between dating partners."),
        ("C", "used_for", "Working in teams is collaboration, not how dating couples greet each other."),
        ("D", "used_for", "Dating couples commonly greet each other by kissing one another."),
        ("E", "used_for", "Receiving gifts may happen on dates, but kissing is the typical greeting."),
    ],
    1263: [
        ("A", "typical_location", "Another place is vague, not a specific country lacking marmosets in South America."),
        ("B", "typical_location", "Venezuela is in South America where marmosets are found in the wild."),
        ("C", "typical_location", "Alabama is in North America, not the continent south of it where marmosets live."),
        ("D", "typical_location", "Rainforest is a habitat type, not a country where marmosets are absent."),
        ("E", "typical_location", "Foreign country is vague; Alabama in North America has no wild marmosets."),
    ],
    1264: [
        ("A", "used_for", "Work in school is general activity, not the specific disliked planned task."),
        ("B", "property", "School children are students, not the unpleasant activity the teacher planned."),
        ("C", "used_for", "Teach pupils is the teacher's job, not the activity students would dislike."),
        ("D", "used_for", "A timed test is an activity students probably would not enjoy as planned."),
        ("E", "used_for", "Demonstrate is showing something, less universally disliked than a timed test."),
    ],
    1265: [
        ("A", "property", "Many different colors describes stained glass windows expected in a church during Communion."),
        ("B", "used_for", "Hold water describes function, not the colorful appearance of church wall glass."),
        ("C", "property", "Break easily is a fragility trait, not the expected visual quality of church glass."),
        ("D", "property", "Dirty describes uncleanliness, not the stained glass seen during Sunday Communion."),
        ("E", "property", "Shattering is breaking apart, not the expected state of church wall glass."),
    ],
    1266: [
        ("A", "typical_location", "A skyscraper has many floors; Sally's office on the 8th top floor suggests one."),
        ("B", "typical_location", "A tall building could fit, but skyscraper specifically implies 8th floor as top floor."),
        ("C", "typical_location", "A public building serves civic functions, less likely for Sally's 8th-floor office."),
        ("D", "typical_location", "A school building is for education, not Sally's corporate-style top-floor office."),
        ("E", "typical_location", "A swimming pool is aquatic recreation, not where Sally's 8th-floor office is."),
    ],
    1267: [
        ("A", "effect", "Decline means refusing, not what couples do at the end of a sleigh ride."),
        ("B", "effect", "Going downhill describes the ride motion, not the romantic end-of-ride activity."),
        ("C", "effect", "Nausea is sickness, not a typical end-of-sleigh-ride activity for couples."),
        ("D", "effect", "Death is fatal, not what couples do when a sleighing ride ends."),
        ("E", "effect", "Couples often kiss at the end of a romantic sleighing ride."),
    ],
    1268: [
        ("A", "effect", "Asthma attacks are a breathing disorder, not what breathing does for living things."),
        ("B", "effect", "Breathing does not satisfy hunger; eating does that for living things."),
        ("C", "effect", "Breathing provides oxygen that is essential for sustaining life in living things."),
        ("D", "effect", "Warm air may be exhaled, but sustaining life is breathing's primary function."),
        ("E", "effect", "Giving life is broader; breathing specifically sustains life by supplying oxygen."),
    ],
    1269: [
        ("A", "property", "Discern means perceive, not the opposite of likening two things together."),
        ("B", "property", "Distinguish means tell apart, close but contrast is the direct opposite of likening."),
        ("C", "property", "Metaphor is a comparison device, not the opposite of likening something to another."),
        ("D", "property", "Discriminate means differentiate, not the opposite of drawing a likeness."),
        ("E", "property", "Contrast is the opposite of likening one thing to something else."),
    ],
}
