# -*- coding: utf-8 -*-
"""Hand-authored v2-style KB for CSQA qids 1470-1519 (no answerKey)."""

CHUNK = {
    1470: [
        ("A", "effect", "Socializing may increase with drinking but alcohol disrupts sleep at night."),
        ("B", "effect", "Eating is unrelated to what alcohol commonly makes you lose."),
        ("C", "effect", "Acting foolish may follow drinking but sleep loss is the direct effect asked."),
        ("D", "effect", "Dancing may happen while drinking but alcohol can cost you sleep at night."),
        ("E", "effect", "Drinking alcohol can make you lose sleep at night."),
    ],
    1471: [
        ("A", "typical_location", "A groundhog appears on Groundhog Day, not Independence Day celebrations."),
        ("B", "typical_location", "Construction sites are workplaces, not typical Independence Day sights."),
        ("C", "typical_location", "Landmines are weapons, not something seen at Independence Day festivities."),
        ("D", "typical_location", "Army units may appear in parades but fireworks displays are the iconic sight."),
        ("E", "typical_location", "Fireworks displays are commonly seen on Independence Day celebrations."),
    ],
    1472: [
        ("A", "typical_location", "A hotel room closet commonly holds shirts for guests."),
        ("B", "typical_location", "A drawer in hotel furniture may store a shirt but closets are primary."),
        ("C", "typical_location", "A garderobe is an archaic wardrobe term; closets are standard in hotel rooms."),
        ("D", "typical_location", "A shelf may hold items but closets are where shirts are typically found."),
        ("E", "typical_location", "A suitcase stores travel clothing but hotel rooms keep shirts in closets."),
    ],
    1473: [
        ("A", "effect", "A bad time is an outcome, not an action to ensure remembering."),
        ("B", "effect", "Closing eyes may aid focus but stopping to think confirms you are remembering."),
        ("C", "used_for", "Answering a question tests recall but stopping to think ensures you remember."),
        ("D", "used_for", "Stopping to think helps make sure you are remembering something."),
        ("E", "effect", "Forgetting is the opposite of what you do to ensure remembering."),
    ],
    1474: [
        ("A", "typical_location", "A bar is where you can drink beer and other alcoholic beverages."),
        ("B", "typical_location", "A vending machine dispenses drinks but bars serve alcoholic beverages socially."),
        ("C", "typical_location", "A bottle holds beer but is not where you go to drink it."),
        ("D", "typical_location", "A refrigerator stores beer but is not a drinking venue."),
        ("E", "typical_location", "A hockey game is a sport event, not primarily a place to drink alcohol."),
    ],
    1475: [
        ("A", "effect", "A stomach ache is physical, unrelated to emotional aftermath of killing in rage."),
        ("B", "effect", "Retaliation is others' response, not the killer's likely feeling afterward."),
        ("C", "effect", "Sadness may occur but remorse is the common feeling after killing in rage."),
        ("D", "effect", "After killing people in a rage someone is likely to feel remorse."),
        ("E", "effect", "Going to jail is a consequence, not the immediate feeling after the act."),
    ],
    1476: [
        ("A", "property", "A shaker dispenses salt but does not decide how much to use."),
        ("B", "primary_function", "Fast food restaurants commonly use too much salt in prepared meals."),
        ("C", "typical_location", "A kitchen cupboard stores salt but does not use it excessively."),
        ("D", "property", "People in general may oversalt food but fast food restaurants are notorious for it."),
        ("E", "typical_location", "A table holds condiments but is not an agent that uses too much salt."),
    ],
    1477: [
        ("A", "used_for", "Saying hello greets people but smiling visibly shows happiness when meeting them."),
        ("B", "used_for", "Starting a conversation engages people but smiling directly shows he was happy."),
        ("C", "used_for", "Introducing yourself is formal; smiling is a clear sign of happiness."),
        ("D", "used_for", "Shaking hands is polite but smiling best shows happiness when meeting new people."),
        ("E", "effect", "Smiling when meeting new people shows the friendly man was happy."),
    ],
    1478: [
        ("A", "typical_location", "Outer space is where the sun exists, not where it appears to set from Earth."),
        ("B", "typical_location", "The sun appears to set at the horizon as Earth rotates."),
        ("C", "typical_location", "A beach is where people watch sunsets but the sun sets at the horizon."),
        ("D", "typical_location", "West is a direction; the visible sunset occurs at the horizon line."),
        ("E", "property", "Beans are food, unrelated to where the sun sets in the sky."),
    ],
    1479: [
        ("A", "effect", "Frostbite affects extremities but skiing accidents more commonly break multiple bones."),
        ("B", "effect", "Someone in a skiing accident is likely to have broken bones in more than one place."),
        ("C", "effect", "Chapped lips are minor compared with multiple fractures from a skiing accident."),
        ("D", "effect", "A healthy body contradicts injuries from a serious skiing accident."),
        ("E", "effect", "Broken legs may occur but broken bones broadly covers multiple fracture sites."),
    ],
    1480: [
        ("A", "property", "Unfeeling describes lack of empathy, not Kate's reckless behavior toward danger."),
        ("B", "property", "John could not stand Kate's disregard for her own safety."),
        ("C", "property", "Indifferent is close but disregard specifically captures ignoring safety warnings."),
        ("D", "property", "Neglect implies failing to care for others, not self-endangering recklessness."),
        ("E", "property", "Apathetic is general; disregard for her own safety fits Kate's behavior."),
    ],
    1481: [
        ("A", "effect", "Recycled means processed again, not what a loathing agent plans for a king."),
        ("B", "property", "Inclined suggests willingness, opposite of the agent's hostile intent."),
        ("C", "effect", "Disposed can mean gotten rid of; the agent planned to have the king disposed of."),
        ("D", "property", "Avid means eager, contradicting the agent's loathing for the king."),
        ("E", "property", "Enthusiastic is positive, opposite of the agent's hostile plan against the king."),
    ],
    1482: [
        ("A", "typical_location", "A classroom teaches but university offers advanced adult learning for poets."),
        ("B", "typical_location", "English class is one subject; university provides broader adult literary education."),
        ("C", "typical_location", "A poet may go to university to achieve learning as an adult."),
        ("D", "typical_location", "A book store sells books but university provides structured adult learning."),
        ("E", "typical_location", "Home is informal; university is where adults pursue advanced learning."),
    ],
    1483: [
        ("A", "typical_location", "A kitchen towel is commonly found in a cupboard in the kitchen."),
        ("B", "typical_location", "Hotels have towels but kitchen towels belong in home kitchen cupboards."),
        ("C", "typical_location", "A linen closet may hold towels but kitchen cupboards store kitchen towels."),
        ("D", "typical_location", "Under a rock is outdoors, not where kitchen towels are kept."),
        ("E", "typical_location", "A locker room has athletic towels, not typical kitchen towels."),
    ],
    1484: [
        ("A", "property", "Irritation is a negative feeling, not indicated by polite sir or ma'am responses."),
        ("B", "property", "Correct describes accuracy, not the courtesy shown by sir or ma'am."),
        ("C", "property", "Responding is generic; saying sir or ma'am specifically indicates politeness."),
        ("D", "property", "Answering with sir or ma'am indicates that you are polite."),
        ("E", "property", "Sadness is unrelated to courteous sir or ma'am address forms."),
    ],
    1485: [
        ("A", "effect", "Destroy enemy is extreme violence beyond typical anger outbursts."),
        ("B", "effect", "When provoked, Matt with anger issues might punch someone."),
        ("C", "effect", "Cooling off is healthy but the question asks what he did when set off."),
        ("D", "effect", "Writing a letter is calm, unlikely for someone with uncontrolled anger when provoked."),
        ("E", "effect", "Illustrating a point is reasoned, not typical of an anger-driven reaction."),
    ],
    1486: [
        ("A", "effect", "Reading stories is unrelated to two people doing the same activity."),
        ("B", "effect", "When two people do the same thing they tend to compete with each other."),
        ("C", "effect", "Helping may occur but competition is common when doing the same activity."),
        ("D", "effect", "Solving problems is cooperative but rivalry often arises from shared activities."),
        ("E", "effect", "Giving orders implies hierarchy, not two peers doing the same thing."),
    ],
    1487: [
        ("A", "used_for", "Planning is preparation, not what Billy enjoyed while mixing at the party."),
        ("B", "used_for", "Meeting new people is social but the watusi is a dance he liked to do."),
        ("C", "used_for", "Getting drunk may happen but Billy enjoyed mixing and dancing at parties."),
        ("D", "used_for", "Having fun is general; the watusi names the specific dance he liked."),
        ("E", "used_for", "Billy enjoyed mixing at the party and liked to do the watusi dance."),
    ],
    1488: [
        ("A", "typical_location", "Movie theaters show films, not school proms after ticket office check-in."),
        ("B", "property", "End of line describes queue position, not the school venue for a prom."),
        ("C", "typical_location", "A football field is outdoors; proms are held in the school auditorium."),
        ("D", "typical_location", "After the ticket office the couple entered their prom in the school auditorium."),
        ("E", "typical_location", "An opera house is a performance venue, not a typical high school prom location."),
    ],
    1489: [
        ("A", "property", "Courageous is a trait, not an action for someone wanting no trouble."),
        ("B", "used_for", "Stepping up confronts the bully, conflicting with wanting no trouble."),
        ("C", "used_for", "Keep walking avoids confrontation when you want no trouble with a bully."),
        ("D", "used_for", "Crossing the street may avoid the scene but keep walking is the direct avoidance."),
        ("E", "used_for", "Doing nothing also avoids trouble but keep walking removes you from the situation."),
    ],
    1490: [
        ("A", "property", "A mainstream approach appeals broadly, defeating a disingenuous kooky cafe concept."),
        ("B", "property", "Straight describes direction or honesty, not a business approach opposite of kooky."),
        ("C", "property", "Right means correct, not a competitor's business strategy."),
        ("D", "property", "A conventional approach outlasted the hipsters' disingenuous kooky cafe."),
        ("E", "property", "Uneccentric is awkward phrasing; conventional captures the successful competitor's approach."),
    ],
    1491: [
        ("A", "typical_location", "A pocket carries a pen temporarily but desk drawer is best for storage."),
        ("B", "typical_location", "A stationery store sells pens but storage is at home or office."),
        ("C", "typical_location", "A backpack transports pens but desk drawer is the best storage spot."),
        ("D", "typical_location", "A desk drawer is the best place to store a ballpoint pen."),
        ("E", "typical_location", "A bank handles money, not storing personal ballpoint pens."),
    ],
    1492: [
        ("A", "typical_location", "An auditorium is a venue, not a punishment for cutting in line."),
        ("B", "property", "Humans are people, not a punishment for queue cutting."),
        ("C", "typical_location", "An opera house is a building, not a penalty for cutting at the ticket office."),
        ("D", "effect", "Death is extreme; going to the end of the line is the fitting punishment for cutting."),
        ("E", "property", "End of line is where you should be sent as punishment for cutting in queue."),
    ],
    1493: [
        ("A", "typical_location", "An awards ceremony recognizes success but does not produce it."),
        ("B", "typical_location", "Various situations are contexts, not the ingredient paired with preparation."),
        ("C", "property", "Vocation is a calling, less direct than hard work as success's partner."),
        ("D", "motivation", "Success is usually a product of preparation and working hard."),
        ("E", "effect", "Promotion may follow success but working hard is what combines with preparation."),
    ],
    1494: [
        ("A", "typical_location", "An office building is a professional space likely to have air conditioning."),
        ("B", "typical_location", "Texas is a state with hot climate, not a professional workspace itself."),
        ("C", "typical_location", "A house may have AC but the question asks about professional spaces."),
        ("D", "property", "Humid describes moisture, not a professional space with air conditioning."),
        ("E", "property", "Warm climates describe weather, not a professional building with AC."),
    ],
    1495: [
        ("A", "motivation", "The key to happiness is to do more than merely existing passively."),
        ("B", "property", "Happiness is the goal, not what you must do more than to achieve it."),
        ("C", "effect", "Early death ends life, not the baseline exceeded for happiness."),
        ("D", "motivation", "Acquiring knowledge helps but the key is doing more than just existing."),
        ("E", "motivation", "Being idle is passive existence; happiness requires doing more than that."),
    ],
    1496: [
        ("A", "property", "Hungry is a feeling, not what he needed to do before cooking dinner."),
        ("B", "has_prerequisite", "Buying a kitchen is unnecessary; he needed groceries to cook dinner."),
        ("C", "has_prerequisite", "Buy food is close but buy groceries is the standard prerequisite for cooking dinner."),
        ("D", "has_prerequisite", "Before cooking dinner he first needed to buy groceries."),
        ("E", "effect", "Eating food is the result, not the prerequisite step before cooking."),
    ],
    1497: [
        ("A", "effect", "Grief may precede divorce but relief can come from ending an unhappy marriage."),
        ("B", "effect", "Confusion may occur but relief captures the positive new beginning after divorce."),
        ("C", "effect", "Stopping being married can bring relief as a fresh beginning."),
        ("D", "effect", "Depression is negative; divorce can also bring relief and a new start."),
        ("E", "effect", "Happiness may follow but relief specifically contrasts the seeming negative end."),
    ],
    1498: [
        ("A", "used_for", "Telling a story is heard but James likes hearing Jenny sing."),
        ("B", "used_for", "James likes to hear Jenny sing because she is very smart and musical."),
        ("C", "used_for", "Cleaning a room is silent work, not something James would enjoy hearing."),
        ("D", "used_for", "Going out at night is an activity, not something James hears Jenny do."),
        ("E", "used_for", "Jump rope is play, less likely than singing for James to enjoy hearing."),
    ],
    1499: [
        ("A", "typical_location", "A city is broad; a grocery store specifically sells household items and food."),
        ("B", "typical_location", "A financial center has banks, not primarily household goods and food."),
        ("C", "typical_location", "Main street may have shops but grocery store directly provides food and household items."),
        ("D", "typical_location", "After the bank, a grocery store provides household items and food."),
        ("E", "typical_location", "A salon provides hair services, not household items and food."),
    ],
    1500: [
        ("A", "effect", "Being free from guilt allows a person to achieve peaceful sleep."),
        ("B", "effect", "Freedom from want is economic, less tied to freedom from guilt."),
        ("C", "effect", "A medal is an honor unrelated to clearing one's conscience."),
        ("D", "effect", "A headache is physical, not achieved when free from guilt."),
        ("E", "effect", "A new computer is material, not the peace guilt-free people achieve."),
    ],
    1501: [
        ("A", "typical_location", "A space shuttle is transport, not a core human experience Danny lacks."),
        ("B", "typical_location", "A library holds books, not the emotional depth of being fully human."),
        ("C", "typical_location", "School teaches academics but love is a profound human experience Danny may lack."),
        ("D", "property", "Love is an important human experience Danny may not yet have fully known."),
        ("E", "typical_location", "A wife is a relationship role, not the abstract human experience asked about."),
    ],
    1502: [
        ("A", "used_for", "Make love is intimacy, unrelated to sharing the same point of view."),
        ("B", "used_for", "When they hug is physical affection, not agreement on viewpoints."),
        ("C", "used_for", "Shake hands is greeting, not having the same point of view."),
        ("D", "property", "When two people have the same point of view they agree with each other."),
        ("E", "used_for", "Work together is collaboration, not necessarily sharing identical viewpoints."),
    ],
    1503: [
        ("A", "effect", "Adventure may come later but short hikes quickly cause sweating."),
        ("B", "effect", "Smiling is optional; sweating is a common immediate effect of hiking."),
        ("C", "effect", "Cramps may occur on long hikes but sweating happens even after short hiking."),
        ("D", "effect", "Even hiking for a short time can cause sweating from exertion."),
        ("E", "effect", "Give up is a choice, not a physical result of brief hiking."),
    ],
    1504: [
        ("A", "typical_location", "A wedding gathers people but not typically while waiting for a cross-town ride."),
        ("B", "typical_location", "People waiting for a ride across town gather at a bus stop."),
        ("C", "typical_location", "A convention draws crowds but bus stops fit waiting for cross-town rides."),
        ("D", "typical_location", "A pool is for swimming, not waiting for transportation across town."),
        ("E", "typical_location", "An apartment is private residence, not a public waiting area for rides."),
    ],
    1505: [
        ("A", "used_for", "Real estate is the field to study for making a fortune selling houses."),
        ("B", "used_for", "A treasure chest holds valuables, not a subject of academic study for selling houses."),
        ("C", "used_for", "Stock market investing differs from the profession of selling houses."),
        ("D", "used_for", "Business is broad; real estate specifically covers selling houses for profit."),
        ("E", "typical_location", "A bank handles finances but real estate is what you study to sell houses."),
    ],
    1506: [
        ("A", "effect", "Health may suffer but excessive hand washing causes skin irritation."),
        ("B", "effect", "Hands become wet during washing but skin irritation is the harmful result."),
        ("C", "effect", "Washing hands over a thousand times daily causes skin irritation."),
        ("D", "effect", "Dry skin may result but skin irritation broadly covers the damage from over-washing."),
        ("E", "property", "Medium is vague and unrelated to consequences of compulsive hand washing."),
    ],
    1507: [
        ("A", "typical_location", "On trial involves legal proceedings, not what a watched priest typically does."),
        ("B", "typical_location", "Drinking coffee is casual, not the formal role people watch a priest perform."),
        ("C", "property", "Believing in god is personal faith, not a public act people watch."),
        ("D", "primary_function", "Baptising is a sacrament but say mass is what congregations routinely watch."),
        ("E", "primary_function", "When people watch a priest he is likely saying mass."),
    ],
    1508: [
        ("A", "property", "Anger is an emotion, not a sound-related activity while driving."),
        ("B", "used_for", "Listening to the radio involves sound without moving your mouth while driving."),
        ("C", "used_for", "Speeding is silent driving behavior unrelated to sound without speaking."),
        ("D", "used_for", "Singing requires moving your mouth, contradicting the question's constraint."),
        ("E", "property", "A statue is motionless and unrelated to driving activities."),
    ],
    1509: [
        ("A", "typical_location", "Marmosets roam free in the rainforest of their native habitat."),
        ("B", "typical_location", "A kitchen is indoors, not where marmosets roam freely in nature."),
        ("C", "typical_location", "Wilderness is broad; rainforest specifically names marmoset habitat."),
        ("D", "typical_location", "A dictionary defines words, not a place where marmosets roam."),
        ("E", "typical_location", "A burrow is a hole in ground; marmosets live freely in rainforest trees."),
    ],
    1510: [
        ("A", "property", "Monarchy is the form of government most associated with kingdoms."),
        ("B", "property", "Ruled by government is vague; kingdoms specifically imply monarchical rule."),
        ("C", "typical_location", "Europe is a continent, not a form of government."),
        ("D", "typical_location", "A book is an object, not a system of government for kingdoms."),
        ("E", "property", "A king is the ruler, not the form of government itself."),
    ],
    1511: [
        ("A", "property", "Dishonor is a state, not the specific legal charge for refusing court respect."),
        ("B", "property", "Refusing to give the court respect leads to a charge of contempt."),
        ("C", "property", "Humiliate is a verb, not the legal charge Manny faced."),
        ("D", "property", "Disdain is an attitude, not the formal court charge for disrespect."),
        ("E", "property", "Scorn is contemptuous feeling, not the specific legal term for court disrespect."),
    ],
    1512: [
        ("A", "typical_location", "Summer is a season, not where the Red Cross responds to storms."),
        ("B", "typical_location", "The tropics have storms but the Red Cross responds across America broadly."),
        ("C", "property", "Blue Shield is an insurance name, unrelated to Red Cross storm response."),
        ("D", "typical_location", "A weather report forecasts storms but Red Cross responds in affected areas."),
        ("E", "typical_location", "The Red Cross responds to storms across America where disasters strike."),
    ],
    1513: [
        ("A", "property", "Commercial is an ad type, not community service from apathy conviction."),
        ("B", "property", "Three toed describes sloths anatomically, not court-ordered service hours."),
        ("C", "primary_function", "A slothful man convicted of apathy would serve civil service hours."),
        ("D", "typical_location", "Paraguay is a country, not the community service a court assigns."),
        ("E", "typical_location", "Costa Rica is a country, unrelated to court-ordered service for apathy."),
    ],
    1514: [
        ("A", "part_whole", "Legs are body parts used for sitting but not always required to sit comfortably."),
        ("B", "typical_location", "Sitting down comfortably does not always necessarily require a chair."),
        ("C", "property", "Laziness is a trait, not a physical requirement for sitting comfortably."),
        ("D", "typical_location", "The floor can suffice for sitting without needing a chair."),
        ("E", "property", "Sit on is the action itself, not something required beyond sitting down."),
    ],
    1515: [
        ("A", "effect", "The dog would run after the ball until it got tired."),
        ("B", "effect", "The ball stopping might pause play but the dog repeats until exhaustion."),
        ("C", "effect", "Fall and hurt yourself is an accident, not the usual end of repeated fetching."),
        ("D", "effect", "Breathing continues throughout; tiredness ends the repeated ball chasing."),
        ("E", "effect", "Catching the ball continues the game; the dog repeats until getting tired."),
    ],
    1516: [
        ("A", "typical_location", "A workplace is for labor, not where humans typically relax."),
        ("B", "typical_location", "A park provides open space where a human can relax."),
        ("C", "typical_location", "A church is for worship, less associated with general relaxation."),
        ("D", "typical_location", "A war zone is dangerous, not a place to relax."),
        ("E", "typical_location", "Jail is confinement, not a relaxing environment for humans."),
    ],
    1517: [
        ("A", "typical_location", "Schools have people inside but supermarkets commonly hold many standing shoppers."),
        ("B", "typical_location", "A supermarket often has many people standing inside shopping aisles."),
        ("C", "typical_location", "A street corner has people outdoors standing, not inside a building."),
        ("D", "typical_location", "A public place is vague; supermarket specifically has crowds standing inside."),
        ("E", "typical_location", "A space shuttle holds few people, not many standing inside."),
    ],
    1518: [
        ("A", "property", "Room temperature describes heat level, not geological effects of water over time."),
        ("B", "effect", "Thin blood is a medical effect, not what large water volumes do to landscapes."),
        ("C", "effect", "Making parks is human development, not natural long-term water erosion."),
        ("D", "property", "Taking several forms describes states of matter, not long-term geological change."),
        ("E", "effect", "Large amounts of water over long periods can move mountains through erosion."),
    ],
    1519: [
        ("A", "effect", "Getting drunk may happen at parties but is not what going with opposite sex leads to."),
        ("B", "effect", "Meeting new people is social but romantic parties may lead further."),
        ("C", "effect", "Drinking beer is one activity, not the typical lead of opposite-sex partygoing."),
        ("D", "effect", "Enjoying yourself is general; parties with the opposite sex may lead to intimacy."),
        ("E", "effect", "Going to a party with the opposite sex can lead to having sex."),
    ],
}
