# -*- coding: utf-8 -*-
"""Hand-authored v2-style KB for CSQA qids 1170-1219 (no answerKey)."""

CHUNK = {
    1170: [
        ("A", "property", "Hexachord is a musical term, not the firm quality paired with soft in a mattress."),
        ("B", "property", "Loud describes sound volume, not the mattress firmness contrasted with soft."),
        ("C", "property", "Hard is close, but firm is the standard mattress term paired with soft cushioning."),
        ("D", "property", "Harsh describes roughness or severity, not mattress firmness beside soft."),
        ("E", "property", "Firm describes a mattress that is soft yet supportive, the quality buyers seek."),
    ],
    1171: [
        ("A", "property", "You is a pronoun, not the state Sam wanted to avoid on Christmas."),
        ("B", "effect", "Sam did not care about company on Christmas; he just did not want to be alone."),
        ("C", "property", "Solitude is the condition of being alone, a noun rather than how Sam felt."),
        ("D", "property", "He want to marry is ungrammatical phrasing, not what Sam feared on Christmas."),
        ("E", "property", "Loneliness is a feeling, but alone is what Sam specifically did not want to be."),
    ],
    1172: [
        ("A", "has_prerequisite", "To buy something you must spend money to pay for the purchase."),
        ("B", "used_for", "Going shopping is one way to buy, but spending money is the required prerequisite."),
        ("C", "used_for", "Paying is the act of spending money required when you want to buy."),
        ("D", "motivation", "Having in mind describes intention, not the mandatory act of buying."),
        ("E", "typical_location", "A shop is where you buy, not what you must do to complete a purchase."),
    ],
    1173: [
        ("A", "typical_location", "A supermarket is one large store, not many separate merchants under one roof."),
        ("B", "typical_location", "A store is a single shop, not a collection of many merchants together."),
        ("C", "typical_location", "A mall houses many merchants with their stores all under one roof."),
        ("D", "typical_location", "A market may have vendors, but a mall specifically puts many stores under one roof."),
        ("E", "typical_location", "A shopping center groups many merchants' stores under one shared roof."),
    ],
    1174: [
        ("A", "typical_location", "A barn is farm storage, not a typical location for an office copy machine."),
        ("B", "typical_location", "An office commonly has a copy machine for duplicating documents."),
        ("C", "typical_location", "An assembly line manufactures products, not where copy machines are usually found."),
        ("D", "typical_location", "A museum displays artifacts, not a typical home for a copy machine."),
        ("E", "typical_location", "A kitchen is for cooking, not where a copy machine is likely placed."),
    ],
    1175: [
        ("A", "effect", "Feeling guilty is an emotion unrelated to overheating the body."),
        ("B", "effect", "Sleep may follow exhaustion, but getting too warm directly causes sweating."),
        ("C", "effect", "Getting too warm causes the body to sweat as it tries to cool down."),
        ("D", "effect", "Feeling more comfortable is the opposite of what happens when you get too warm."),
        ("E", "effect", "Cuddling is affectionate contact, not a physiological result of overheating."),
    ],
    1176: [
        ("A", "used_for", "Asking questions helps kids learn, but going to school is the primary way they learn new things."),
        ("B", "property", "Fun is enjoyment, not the action kids take to learn new things."),
        ("C", "used_for", "Studying helps learning, but attending school is how kids routinely learn new things."),
        ("D", "used_for", "Driving is an adult skill, not what kids do to learn new things."),
        ("E", "used_for", "Kids learn new things primarily by going to school as students."),
    ],
    1177: [
        ("A", "effect", "Relaxing follows mastery, but having fun is what you do once skateboard basics are learned."),
        ("B", "property", "Teenager is an age group, not an activity after mastering skateboard basics."),
        ("C", "property", "Freedom is a feeling, less direct than the fun of riding after mastering basics."),
        ("D", "effect", "Once skateboard basics are mastered, you can have fun riding freely."),
        ("E", "effect", "Giving up is quitting, the opposite of continuing after mastering the basics."),
    ],
    1178: [
        ("A", "typical_location", "A theatre is a venue where the public can enjoy live musical performances."),
        ("B", "typical_location", "An elevator plays occasional music but is not a public music enjoyment venue."),
        ("C", "typical_location", "An opera house offers public opera performances where audiences enjoy music."),
        ("D", "typical_location", "Cassettes are media formats, not public places to enjoy music."),
        ("E", "typical_location", "A store may play background music, but a theatre is a public music venue."),
    ],
    1179: [
        ("A", "typical_location", "A hotel already has guest rooms; James bought a sofa bed for his own residence."),
        ("B", "typical_location", "A guest room is one sleeping space; James added a sofa bed in his own home."),
        ("C", "typical_location", "An office is a workplace, not where James would add a hide-a-bed for guests."),
        ("D", "typical_location", "An apartment could work, but a house with a guest room and sofa bed fits the scenario."),
        ("E", "typical_location", "James bought a hide-a-bed sofa for his house to host an extra overnight guest."),
    ],
    1180: [
        ("A", "typical_location", "The Gulf of Mexico is open seawater, not where a crab would feel cold and stuck."),
        ("B", "typical_location", "A fridge freezer is cold enough that a crab stuck inside would feel freezing."),
        ("C", "typical_location", "A fish market displays crabs on ice, but a freezer is where one feels truly cold."),
        ("D", "typical_location", "A grocery store seafood section is cold, but a freezer is the coldest stuck location."),
        ("E", "typical_location", "The North Sea is cold ocean water, less specific than being stuck in a freezer."),
    ],
    1181: [
        ("A", "typical_location", "A sporting goods store sells sports equipment when you do not already have any."),
        ("B", "typical_location", "Sears is a department store that may sell some sports gear, less specialized."),
        ("C", "typical_location", "A pool is a swimming facility, not where you purchase sports equipment."),
        ("D", "typical_location", "A sporting event uses equipment but is not where you buy it."),
        ("E", "typical_location", "A school may lend equipment, but a sporting goods store is where you buy it."),
    ],
    1182: [
        ("A", "motivation", "Selling beer is a commercial goal unrelated to personal reasons for prolonged sex."),
        ("B", "property", "A wonderful thing is vague praise, not a specific goal for lasting longer during sex."),
        ("C", "effect", "Herpes is a disease, not a goal anyone seeks from prolonged sexual activity."),
        ("D", "property", "Cost money describes expense, not a goal for having sex for a long time."),
        ("E", "motivation", "Lasting an hour is a common goal people cite for having sex for a long time."),
    ],
    1183: [
        ("A", "typical_location", "Hoboken is a city in New Jersey, so a hitchhiker nearby is in New Jersey."),
        ("B", "typical_location", "Homes are residences, not a geographic location near Hoboken."),
        ("C", "typical_location", "A department store is a shop, not where a hitchhiker near Hoboken would be."),
        ("D", "typical_location", "Near Italy is across the Atlantic, not where someone hitchhikes near Hoboken."),
        ("E", "typical_location", "New Orleans is in Louisiana, far from Hoboken in the northeastern United States."),
    ],
    1184: [
        ("A", "typical_location", "England drives on the left side of the road, including on motorways."),
        ("B", "typical_location", "Europe is a continent where most countries drive on the right, not the left."),
        ("C", "typical_location", "New Jersey is an American state where people drive on the right side."),
        ("D", "typical_location", "A city is too vague; England specifically requires left-side motorway driving."),
        ("E", "typical_location", "A river is a waterway, not a road where people drive on the left."),
    ],
    1185: [
        ("A", "typical_location", "Colon is a punctuation mark, not a region where the centavo currency is used."),
        ("B", "typical_location", "Austral refers to southern regions, not specifically where centavos circulate."),
        ("C", "typical_location", "Cordoba is a city name, not the regional currency zone for centavos."),
        ("D", "typical_location", "Indian refers to India or indigenous peoples, not centavo-using regions."),
        ("E", "typical_location", "The centavo is a subdivision of the Mexican peso used in Mexico."),
    ],
    1186: [
        ("A", "typical_location", "Expensive clothing describes a price range, not a shop where you buy silk fabric."),
        ("B", "typical_location", "Garments are finished clothes, not a store where you purchase silk material."),
        ("C", "typical_location", "Chinatown shops commonly sell silk fabric and silk garments."),
        ("D", "typical_location", "Downtown is a general area; Chinatown specifically sells silk in many cities."),
        ("E", "typical_location", "A nightgown is sleepwear, not a place to go buy silk fabric."),
    ],
    1187: [
        ("A", "typical_location", "Outside of house is too vague; zoning rules come from urban area regulations."),
        ("B", "typical_location", "Urban areas have zoning rules that can prevent remodeling a front garden."),
        ("C", "typical_location", "Town hall is a building, not the type of area with restrictive zoning rules."),
        ("D", "typical_location", "Front yard is the garden itself, not the jurisdiction imposing zoning rules."),
        ("E", "typical_location", "Michigan is a state; urban zoning rules within cities restrict garden remodeling."),
    ],
    1188: [
        ("A", "typical_location", "A hen house holds chickens, not a dry region where fox hunting is pointless."),
        ("B", "typical_location", "Florida is humid subtropical, too wet and not dry enough for scarce foxes."),
        ("C", "typical_location", "New Hampshire has dry periods; Billy found fox hunting pointless in dry country."),
        ("D", "typical_location", "North Dakota's dry plains make fox hunting scarce and seem pointless to Billy."),
        ("E", "typical_location", "Arkansas has varied terrain but North Dakota's dryness better fits Billy's complaint."),
    ],
    1189: [
        ("A", "typical_location", "A shopping mall groups many shops together near a conveniently located general store."),
        ("B", "typical_location", "A barn is farm storage, not a cluster of shops near a general store."),
        ("C", "property", "Salt is a seasoning, not a commercial area grouping shops together."),
        ("D", "typical_location", "The old west is a historical setting, not a modern shop cluster near a store."),
        ("E", "property", "Checkers is a board game, not a commercial area with grouped shops."),
    ],
    1190: [
        ("A", "typical_location", "A hotel reception desk is located in the lobby where guests check in."),
        ("B", "typical_location", "A seated restaurant is for dining, not where the hotel reception desk sits."),
        ("C", "typical_location", "An office park is a business campus, not a hotel's reception area."),
        ("D", "typical_location", "A building is too generic; hotel reception desks are specifically in the lobby."),
        ("E", "typical_location", "A motel has a reception area, but the lobby is the standard hotel location."),
    ],
    1191: [
        ("A", "property", "Large is a clothing size Sarah might wear now that she is no longer a little girl."),
        ("B", "property", "Big is informal for large; both describe adult sizes rather than children's clothes."),
        ("C", "property", "See work is not a clothing size Sarah would shop for as a grown person."),
        ("D", "property", "Lot of is a quantity phrase, not a size label for new clothes."),
        ("E", "property", "Bog is a wetland, not a clothing size for someone no longer a little girl."),
    ],
    1192: [
        ("A", "property", "Brightness is light quality; the plant needed direct sunlight instead of shade."),
        ("B", "property", "Sunny delight is a drink brand, not the sunlight a shade-suffering plant needs."),
        ("C", "typical_location", "A plant suffering in shade needs to be planted in direct sunlight instead."),
        ("D", "property", "Bright light is close, but direct sunlight is what shade-bound plants specifically need."),
        ("E", "property", "Tanning is skin darkening in sun, not where a struggling plant should be planted."),
    ],
    1193: [
        ("A", "property", "Boattail describes a boat's stern shape, not a place requiring navigation skills."),
        ("B", "typical_location", "A river requires navigation skills to steer a boat through currents and bends."),
        ("C", "typical_location", "Indiana is a landlocked state, not where boat navigation skills are needed."),
        ("D", "typical_location", "A garage stores vehicles on land, not a waterway requiring navigation."),
        ("E", "typical_location", "The ocean requires advanced navigation skills for boating across open water."),
    ],
    1194: [
        ("A", "typical_location", "A drug store sells toothbrushes and some food items the man needed."),
        ("B", "part_whole", "The mouth is where a toothbrush is used, not where you buy one and food."),
        ("C", "typical_location", "A dentist office provides dental care, not routine toothbrush and food shopping."),
        ("D", "typical_location", "An attic is storage space at home, not a shop for toothbrushes and food."),
        ("E", "typical_location", "A grocery store sells food but toothbrushes are more commonly bought at drug stores."),
    ],
    1195: [
        ("A", "effect", "Rhythmic movement describes the motion of dancing, not the feeling it gives Janet."),
        ("B", "effect", "Moving body describes physical action, not the emotional sensation Janet experiences."),
        ("C", "effect", "The swaying and music of dancing gives Janet a feeling of euphoria."),
        ("D", "effect", "Sore feet may follow dancing, not the positive feeling the swaying music gives."),
        ("E", "effect", "Fatigue is exhaustion, not the uplifting feeling Janet gets from dancing."),
    ],
    1196: [
        ("A", "used_for", "A supermarket box holds products for transport and display on shelves."),
        ("B", "used_for", "Storing food is one use, but holding stuff is the general purpose of a supermarket box."),
        ("C", "used_for", "Organizing is a benefit, but the primary purpose of a box is to hold items."),
        ("D", "used_for", "Holding things is the basic purpose of a box used in a supermarket."),
        ("E", "used_for", "Store clothes is incorrect; supermarket boxes hold groceries and merchandise."),
    ],
    1197: [
        ("A", "property", "From the ceiling describes placement, not the type of structure with a foyer chandelier."),
        ("B", "typical_location", "A building is generic; a mansion specifically has a grand foyer with a chandelier."),
        ("C", "typical_location", "An apartment may have an entry, but mansions feature large foyer chandeliers."),
        ("D", "typical_location", "A mansion typically has a large chandelier hanging in its grand foyer."),
        ("E", "typical_location", "A spacious house may have a foyer, but mansion specifically implies grand chandeliers."),
    ],
    1198: [
        ("A", "typical_location", "James feared neighbors using his hot tub would turn his house into a country club."),
        ("B", "typical_location", "A health centre is a medical facility, not what excessive neighbor hot tub use creates."),
        ("C", "typical_location", "A hospital treats patients, not a social destination from shared hot tub access."),
        ("D", "typical_location", "A backyard is where the tub sits, not what the house would become socially."),
        ("E", "typical_location", "A resort welcomes many guests; James feared his house becoming like a country club."),
    ],
    1199: [
        ("A", "part_whole", "Torso is a body part, not the winding mountain feature with a shoulder to pull off to."),
        ("B", "property", "Garment is clothing, not a mountain route with a shoulder for pulling over."),
        ("C", "property", "A cello is a musical instrument, unrelated to a mountain road shoulder."),
        ("D", "typical_location", "They pulled off to the shoulder of the winding mountain road."),
        ("E", "part_whole", "Body refers to a physical form, not the paved shoulder of a mountain road."),
    ],
    1200: [
        ("A", "property", "Terrorists hands are a threat scenario, not where you keep your plane ticket."),
        ("B", "typical_location", "A shirt pocket is a common place to keep a plane ticket while travelling."),
        ("C", "typical_location", "An airport is where you use a ticket, not where it is kept in your shirt."),
        ("D", "typical_location", "A back pocket could hold a ticket, but a shirt pocket is the question's target."),
        ("E", "typical_location", "A briefcase carries documents but the question asks about keeping it in your shirt."),
    ],
    1201: [
        ("A", "property", "Medium describes a format or size, not where people view pictures with a story."),
        ("B", "typical_location", "An art show displays visual works but not typically narrative picture stories."),
        ("C", "typical_location", "A newspaper publishes pictures alongside stories for readers to view."),
        ("D", "typical_location", "A suitcase stores belongings, not where people look at pictures with stories."),
        ("E", "typical_location", "Books contain pictures with stories that readers look at page by page."),
    ],
    1202: [
        ("A", "typical_location", "A synagogue is a place of worship, not where James would get a floor blanket."),
        ("B", "typical_location", "A table holds items but is not the source of a blanket for the floor."),
        ("C", "typical_location", "Carpet covers floors permanently, not a blanket James would pull to cover burn marks."),
        ("D", "typical_location", "A general store sells blankets James might buy to cover floor burn marks."),
        ("E", "typical_location", "A bed has blankets James could take to cover burn marks on the floor."),
    ],
    1203: [
        ("A", "effect", "A smart decision is wise choice, the opposite of what using a fake ID turned out to be."),
        ("B", "used_for", "Spend money is a transaction, not the disastrous outcome of her fake ID plan."),
        ("C", "effect", "Buying beer with a fake ID can get you arrested, which is what happened to Sarah."),
        ("D", "effect", "Stupidity describes foolishness, but getting arrested was the actual bad outcome."),
        ("E", "effect", "Have fun was her goal, but the fake ID attempt turned into anything but enjoyment."),
    ],
    1204: [
        ("A", "typical_location", "An aquarium displays fish, not the people a company chief oversees."),
        ("B", "property", "Peon is a subordinate worker, not the group a chief manages in a company."),
        ("C", "property", "Indian refers to a person or culture, not employees overseen by a company chief."),
        ("D", "primary_function", "A company chief oversees employees and manages the organization's workforce."),
        ("E", "property", "A follower is a subordinate, but employees is the standard term for company staff."),
    ],
    1205: [
        ("A", "effect", "Joyfulness is happiness, but sexual attraction specifically describes her response to his mustache."),
        ("B", "effect", "A smile is a facial expression, less specific than the attraction his mustache elicited."),
        ("C", "effect", "Getting excited is general arousal; his mustache elicited sexual attraction in her."),
        ("D", "effect", "Enthusiasm is eager interest, not the romantic attraction his mustache sparked."),
        ("E", "effect", "His mustache elicited sexual attraction as she giggled and flirted with him."),
    ],
    1206: [
        ("A", "typical_location", "Books are references, not what you check for to solve a math problem properly."),
        ("B", "property", "Incomplete means unfinished work, which you should check for when solving math properly."),
        ("C", "property", "Incorrect describes wrong answers, which you should verify when doing math properly."),
        ("D", "property", "Impolite describes rude behavior, irrelevant to solving a math problem properly."),
        ("E", "property", "Inappropriate means unsuitable, not a math error to check when working properly."),
    ],
    1207: [
        ("A", "typical_location", "The sky is where meteors appear, not how they travel around galactic objects."),
        ("B", "typical_location", "Outer space is the environment, but meteors travel in orbit around galactic objects."),
        ("C", "part_whole", "The universe contains everything, not the specific path meteors follow."),
        ("D", "typical_location", "A vacuum is empty space, not the orbital path of a meteor."),
        ("E", "effect", "Meteors travel around galactic objects by moving in orbit under gravitational influence."),
    ],
    1208: [
        ("A", "property", "An old person is elderly, the opposite starting point before becoming a baby boy."),
        ("B", "used_for", "Learn to speak is a developmental milestone, not the starting identity in the story."),
        ("C", "property", "An old man is aged, not the beginning form before the character became a baby boy."),
        ("D", "property", "The character started as an adult before the story transformed him into a baby boy."),
        ("E", "effect", "Died is an ending, not the starting identity before becoming a baby boy."),
    ],
    1209: [
        ("A", "typical_location", "A seaside town is generic; California is the US state east of Bob's Pacific position."),
        ("B", "typical_location", "Florida is on the Atlantic coast, not east of a Pacific Ocean location near the US."),
        ("C", "typical_location", "Ocean is where Bob was tossed, not the shore he swam toward to the east."),
        ("D", "property", "Picture of sea side is an image, not the landmass Bob swam toward."),
        ("E", "typical_location", "Bob was in the Pacific near the US; swimming east toward shore means California."),
    ],
    1210: [
        ("A", "effect", "Finally discovering the truth after lifelong weight was a great relief."),
        ("B", "effect", "Satisfaction follows relief, but the release of lifelong burden feels most like relief."),
        ("C", "effect", "Hurt is pain, the opposite of the positive feeling from finally discovering truth."),
        ("D", "effect", "Happiness is joy, but relief specifically captures shedding a lifelong heavy burden."),
        ("E", "effect", "A conclusion is an ending point, not the emotional feeling of discovering truth."),
    ],
    1211: [
        ("A", "typical_location", "The South Pole is frozen tundra where apple trees cannot grow in abundance."),
        ("B", "typical_location", "A park may have a few trees, but farmland has apple trees in abundance."),
        ("C", "typical_location", "A vineyard grows grapes, not apple trees in large numbers."),
        ("D", "typical_location", "Farmland commonly has apple orchards with apple trees growing in abundance."),
        ("E", "typical_location", "An orchid is a flower, not a place where apple trees grow abundantly."),
    ],
    1212: [
        ("A", "typical_location", "A clarinet case stores the instrument, not where a listener hears a student play."),
        ("B", "typical_location", "A jazz band performs with clarinets, but beginners try instruments in music stores."),
        ("C", "property", "Spongebob is a cartoon character, not where one hears a student trying clarinet."),
        ("D", "typical_location", "A music store is where listeners hear new students trying out a clarinet."),
        ("E", "typical_location", "An orchestra has skilled players, not beginners first trying a clarinet."),
    ],
    1213: [
        ("A", "typical_location", "Movies are films; Billy was at a meeting or conference with slides and a presenter."),
        ("B", "typical_location", "A meeting with slides and a presenter talking to an audience fits Billy's event."),
        ("C", "typical_location", "A conference features projectors, slides, and presenters addressing an audience."),
        ("D", "typical_location", "A theatre shows performances, not typically slide presentations with a speaker."),
        ("E", "used_for", "Show films is a cinema activity, not Billy's slide presentation event."),
    ],
    1214: [
        ("A", "property", "Stagnation resists change, not something that demands a person change."),
        ("B", "property", "Tradition preserves old ways, less likely to demand change than a spouse."),
        ("C", "property", "Paper money is currency, not an agent that demands personal change."),
        ("D", "motivation", "A wife's expectations often demand that a person change their habits or behavior."),
        ("E", "property", "Unpleasant describes discomfort, not the force that demanded the person change."),
    ],
    1215: [
        ("A", "property", "North is the opposite direction, not the name for a wind blowing from the east."),
        ("B", "property", "Westward means toward the west, not a wind coming from the eastern direction."),
        ("C", "property", "Western describes a region or direction, not an east-origin wind's name."),
        ("D", "property", "Westerly describes winds from the west, not from the east as the question states."),
        ("E", "property", "Eastside is a location, not the meteorological term for a wind from the east."),
    ],
    1216: [
        ("A", "primary_function", "A motorboat is a powered leisure vessel steered using a helm control."),
        ("B", "typical_location", "South Tyrol is a region in Italy, not a powered leisure vessel with a helm."),
        ("C", "primary_function", "A tugboat is a work vessel, not typically classified as a powered leisure craft."),
        ("D", "primary_function", "A brig is a sailing ship, not a powered leisure vessel with a helm."),
        ("E", "primary_function", "A sailing vessel uses wind power, not motor power for leisure steering."),
    ],
    1217: [
        ("A", "has_prerequisite", "Concentrating helps reading but written material is what you must have before starting."),
        ("B", "has_prerequisite", "You need written material such as a book or text before you can begin reading."),
        ("C", "has_prerequisite", "Acculturation is cultural learning, not a prerequisite for starting to read."),
        ("D", "has_prerequisite", "Memory aids comprehension but written material is required before reading begins."),
        ("E", "has_prerequisite", "Concentration helps focus but you first need written material to read."),
    ],
    1218: [
        ("A", "used_for", "You should reply to email received while at work in a timely manner."),
        ("B", "property", "Mute means silent, not a workplace message requiring a reply."),
        ("C", "used_for", "A fax may arrive at work and require a reply from the recipient."),
        ("D", "used_for", "Send is an outgoing action, not an incoming item you should reply to."),
        ("E", "used_for", "Answer is close, but email is the specific workplace communication needing replies."),
    ],
    1219: [
        ("A", "effect", "A deep dive is plunging underwater, not what happens at the end of a day after sunrise."),
        ("B", "effect", "Fall describes dropping, not the daily event following the sun's rise."),
        ("C", "effect", "Lower means reducing height, not the end-of-day solar event."),
        ("D", "property", "Below is a position, not what happens at day's end after the sun rises."),
        ("E", "effect", "After the sun rises, it sets at the end of the day in a sunset."),
    ],
}
