# -*- coding: utf-8 -*-
"""Hand-authored v2-style KB for CSQA qids 1441-1469 (no answerKey)."""

CHUNK = {
    1441: [
        ("A", "typical_location", "A hardware store sells tin but is not where you put it after purchasing."),
        ("B", "typical_location", "An antique store sells collectibles, not where you store newly bought tin."),
        ("C", "typical_location", "You put tin in a shopping bag to carry it home after you buy it."),
        ("D", "typical_location", "A shed stores items long-term but you first carry tin home in a bag."),
        ("E", "typical_location", "A landfill receives waste, not newly purchased tin you intend to keep."),
    ],
    1442: [
        ("A", "typical_location", "A backpack carries items but is not where you buy clothing and housewares."),
        ("B", "typical_location", "A house is where you live, not a retail venue for sporting goods."),
        ("C", "typical_location", "A department store sells clothing, sporting goods, and housewares under one roof."),
        ("D", "typical_location", "A mall contains many shops but department store directly names the combined retail type."),
        ("E", "typical_location", "A table is furniture, not a place to purchase clothing and housewares."),
    ],
    1443: [
        ("A", "typical_location", "Disneyland is an amusement park, not primarily where you buy toys to take home."),
        ("B", "typical_location", "A jungle is wild habitat, not a shop for children's playthings."),
        ("C", "typical_location", "A swimming pool is for swimming, not buying toys for kids."),
        ("D", "typical_location", "A toy store sells things for children to play with."),
        ("E", "typical_location", "Home is where toys end up, not where you take kids to buy them."),
    ],
    1444: [
        ("A", "property", "Four legs describes anatomy but the saying refers to companionship beyond physical traits."),
        ("B", "property", "Males is too narrow; the phrase means loyal companionship, not just male humans."),
        ("C", "property", "An electrical circuit is unrelated to the proverb about dogs as best friends."),
        ("D", "property", "Pet is close but the saying is not talking about just any pet category."),
        ("E", "property", "Sniff describes a dog action, not the friendship bond the proverb emphasizes."),
    ],
    1445: [
        ("A", "effect", "Climbing a mountain and breathing fresh air commonly produces a feeling of exhilaration."),
        ("B", "effect", "A clear head may follow fresh air but exhilaration captures the mountain-climbing high."),
        ("C", "effect", "Feeling better is vague; exhilaration describes the peak experience of mountain air."),
        ("D", "effect", "Reviving suggests recovery, less than the thrill of fresh air on a mountain climb."),
        ("E", "effect", "Happiness is general; exhilaration fits the intense feeling of mountain fresh air."),
    ],
    1446: [
        ("A", "effect", "Unexpected results may occur but bugs are the classic failure of an unsuccessful program."),
        ("B", "effect", "An unsuccessful writing program commonly causes software bugs and errors."),
        ("C", "effect", "Satisfaction contradicts an unsuccessful program outcome."),
        ("D", "effect", "Frustration is felt by the user but bugs are what the broken program causes."),
        ("E", "effect", "Aggravation is an emotional response; bugs are the concrete program failure."),
    ],
    1447: [
        ("A", "typical_location", "A party is social gathering, not where orchestral musicians sit in a pit."),
        ("B", "typical_location", "An orchestra performs from an orchestra pit where a flute is likely placed."),
        ("C", "typical_location", "A musical instrument store sells flutes but does not have a performance pit."),
        ("D", "typical_location", "A marching band performs outdoors, not from a seated orchestra pit."),
        ("E", "typical_location", "A symphony uses an orchestra pit where flutes are positioned during performance."),
    ],
    1448: [
        ("A", "property", "Names identify people; stupidity is not described as having no names."),
        ("B", "property", "Dress is clothing, unrelated to the insult about lacking intelligence."),
        ("C", "property", "People say someone stupid has no brains, meaning no intelligence."),
        ("D", "property", "Brown hair is a physical trait, not what the stupidity insult refers to."),
        ("E", "property", "Two eyes is anatomy, not the mental capacity implied by the insult."),
    ],
    1449: [
        ("A", "typical_location", "Putting a ficus on the ground indoors can spill soil and dirty the carpet."),
        ("B", "typical_location", "An arboretum is outdoors for trees, not indoor carpet protection."),
        ("C", "typical_location", "An apartment has carpets; placing the ficus on the ground risks dirtying them."),
        ("D", "typical_location", "A refrigerator is for food storage, not keeping a ficus plant."),
        ("E", "typical_location", "California is a state, not a placement strategy to protect carpets."),
    ],
    1450: [
        ("A", "property", "With someone implies company, yet she still felt alone despite someone's presence."),
        ("B", "property", "Many people nearby can still leave someone feeling alone inside."),
        ("C", "property", "With others suggests company but she felt alone even among other people."),
        ("D", "property", "Surrounded by people can still feel lonely when emotionally disconnected in class."),
        ("E", "property", "In crowd describes many people present while she still felt alone."),
    ],
    1451: [
        ("A", "typical_location", "Swiss cheese already has holes; punching it is not the typical fist-hole scenario."),
        ("B", "typical_location", "A football ground is turf outdoors, not where you punch holes with a fist."),
        ("C", "typical_location", "Ground is too vague; a wall is the classic surface for making a fist hole."),
        ("D", "typical_location", "A golf course is maintained turf, not where you make holes with your fist."),
        ("E", "typical_location", "You could make a hole with your fist by punching through a wall."),
    ],
    1452: [
        ("A", "typical_location", "New York has courts but red clay tennis is iconic at European tournaments."),
        ("B", "typical_location", "Wimbledon uses grass; red clay courts are famous at the French Open in Europe."),
        ("C", "typical_location", "Town is too vague; country clubs specifically may feature red clay courts."),
        ("D", "typical_location", "A country club may have a red clay tennis court for members."),
        ("E", "typical_location", "A health club may have courts but red clay is classic at country clubs."),
    ],
    1453: [
        ("A", "effect", "Sleep is restful but sitting down immediately addresses tired legs without full sleep."),
        ("B", "used_for", "If your legs are tired and you need rest, you should sit down."),
        ("C", "effect", "Going to bed is longer rest; sitting down is the immediate action for tired legs."),
        ("D", "effect", "Running would further tire legs, opposite of resting them."),
        ("E", "effect", "Closing eyes may accompany rest but sitting down directly relieves tired legs."),
    ],
    1454: [
        ("A", "effect", "A championship is a rare outcome, not what most people get after tennis all day."),
        ("B", "effect", "Most people become tired after playing tennis all day."),
        ("C", "effect", "Tennis elbow is possible but becoming tired is what most people experience."),
        ("D", "effect", "Victory is not guaranteed; fatigue is the common result of all-day tennis."),
        ("E", "effect", "Friends may accompany play but tiredness is the typical physical outcome."),
    ],
    1455: [
        ("A", "typical_location", "Restaurants may show sports but living rooms are where TVs commonly display them."),
        ("B", "typical_location", "A living room television often displays sports for household viewing."),
        ("C", "typical_location", "Bars show sports but the question asks where a television often displays them at home."),
        ("D", "typical_location", "An apartment contains rooms; the living room TV commonly shows sports."),
        ("E", "typical_location", "A house has many rooms; sports often play on the living room television."),
    ],
    1456: [
        ("A", "primary_function", "Animals knew fluids were important and that drinking them was safe."),
        ("B", "effect", "Feeling pain is unrelated to knowing which fluids are safe to consume."),
        ("C", "primary_function", "Biting is aggression, not the safe fluid-related action animals knew."),
        ("D", "capability", "Flying is locomotion, not the safe consumption of fluids."),
        ("E", "property", "Gay is unrelated to animals knowing safe ways to consume fluids."),
    ],
    1457: [
        ("A", "effect", "Love another is unrelated to morning hospitality after spending the night."),
        ("B", "primary_function", "He got up early to make coffee as a hospitable morning gesture."),
        ("C", "effect", "Smoke is a habit, less typical than making coffee for an overnight guest."),
        ("D", "primary_function", "Eat breakfast is possible but making coffee is the common early-morning offer."),
        ("E", "effect", "Wait for is vague; making coffee is the concrete hospitable morning action."),
    ],
    1458: [
        ("A", "property", "Ominous foreshadows danger; assassination mid-speech makes the day inauspicious."),
        ("B", "property", "Coincidental downplays the assassination's reversal of the auspicious claim."),
        ("C", "property", "Ruinous is severe but inauspicious directly opposes the king's auspicious declaration."),
        ("D", "property", "Inauspicious is the opposite of auspicious after the king was assassinated mid-speech."),
        ("E", "property", "Disastrous is close but inauspicious precisely negates the claimed auspicious day."),
    ],
    1459: [
        ("A", "used_for", "When having food it is common to drink as a paired act of consumption."),
        ("B", "used_for", "Playing poker is a game, not a consumption act paired with eating."),
        ("C", "used_for", "Sitting may accompany meals but drinking is the other consumption act asked."),
        ("D", "used_for", "Talking is social, not the consumption counterpart to eating food."),
        ("E", "property", "Being greedy describes excess, not the common paired consumption with food."),
    ],
    1460: [
        ("A", "effect", "Cleaning house may increase under stress but drinking alcohol is a common excess."),
        ("B", "effect", "Using drugs is possible under stress but drinking alcohol is a widely cited excess."),
        ("C", "effect", "People experiencing stress may drink alcohol too much as a coping behavior."),
        ("D", "effect", "Hanging out at a bar involves drinking, a common stress response."),
        ("E", "effect", "Dreaming is sleep-related, not a stressed excess behavior."),
    ],
    1461: [
        ("A", "typical_location", "A small farmer keeps harvested potatoes in a root cellar for storage."),
        ("B", "typical_location", "An own kitchen uses potatoes but bulk storage is in a root cellar."),
        ("C", "typical_location", "Clam chowder is a dish, not where a farmer stores harvested potatoes."),
        ("D", "typical_location", "A desk drawer is too small for storing a farmer's potato harvest."),
        ("E", "typical_location", "A kitchen cabinet holds some potatoes but farmers store harvests in root cellars."),
    ],
    1462: [
        ("A", "used_for", "Waste paper is trash, not a way to gain new perspectives."),
        ("B", "used_for", "Tickling tarantulas is absurd and unrelated to gaining new perspectives."),
        ("C", "used_for", "Paying bills is a chore, not a path to new perspectives."),
        ("D", "used_for", "Change direction is vague; travel abroad exposes people to new viewpoints."),
        ("E", "used_for", "Travel abroad lets people encounter different cultures and gain new perspectives."),
    ],
    1463: [
        ("A", "effect", "Remorse is felt by wrongdoers, not family members mourning murdered relatives."),
        ("B", "effect", "Retaliation is an action urge, not the feeling while crying over murdered kin."),
        ("C", "effect", "Terrible is vague; anguish captures deep grief when family members are murdered."),
        ("D", "effect", "Family members crying over murdered relatives would feel anguish."),
        ("E", "effect", "Wet describes tears physically, not the emotional feeling while crying."),
    ],
    1464: [
        ("A", "typical_location", "Seats in a cinema are used to watch a movie."),
        ("B", "typical_location", "Movies are the content, not the venue with seats for viewing."),
        ("C", "typical_location", "A hockey game uses seats but the question asks about watching a movie."),
        ("D", "typical_location", "A theater has seats for films but cinema specifically denotes movie viewing."),
        ("E", "typical_location", "An opera has seats but is for live performance, not movie watching."),
    ],
    1465: [
        ("A", "typical_location", "The ocean is a place, not how an omnidisciplinarian finds success."),
        ("B", "motivation", "Working hard helps success but an omnidisciplinarian thrives across many fields."),
        ("C", "typical_location", "An omnidisciplinarian finds success in various situations across disciplines."),
        ("D", "typical_location", "Michigan is a state, not the breadth of success an omnidisciplinarian seeks."),
        ("E", "typical_location", "An awards ceremony recognizes success but various situations is where it is found."),
    ],
    1466: [
        ("A", "primary_function", "Keeping people out is a door's security role, not passing through a closed one."),
        ("B", "primary_function", "Enclosing a cupboard is unrelated to going through a closed door."),
        ("C", "capability", "Teleport is fantasy, not what you do to a closed door you want to pass."),
        ("D", "property", "Glass describes material, not the action needed to pass through a closed door."),
        ("E", "primary_function", "To go through a closed door you have to open it first."),
    ],
    1467: [
        ("A", "typical_location", "A Japanese restaurant serves food, not picture books of animals with rhymes."),
        ("B", "typical_location", "A lake has real animals but the child looked at pictures with rhymes."),
        ("C", "typical_location", "A zoo has live animals but the rhyming pictures suggest a book."),
        ("D", "typical_location", "A book contains animal pictures and rhymes the child heard his mom read."),
        ("E", "typical_location", "A current is water flow, not a collection of illustrated animal rhymes."),
    ],
    1468: [
        ("A", "used_for", "A fan dries floors but wet cleaning specifically requires a mop."),
        ("B", "property", "Energy is needed generally but a mop is the tool for wet floor cleaning."),
        ("C", "used_for", "Vacuuming cleans dry surfaces, not wet mopping floors."),
        ("D", "used_for", "Wet cleaning a floor while doing housework requires a mop."),
        ("E", "used_for", "A broom sweeps dry debris, not wet mopping of floors."),
    ],
    1469: [
        ("A", "property", "November is a month, not the weather type producing lightning strikes."),
        ("B", "property", "Beautiful lightning strikes commonly happen on rainy stormy days."),
        ("C", "property", "Dull days lack the atmospheric drama that produces lightning."),
        ("D", "property", "Wet describes moisture but rainy specifically pairs with thunderstorm lightning."),
        ("E", "property", "Average is vague; rainy storm conditions produce visible lightning strikes."),
    ],
}
