# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7120-7219 (1 fact each)."""

KNOWLEDGE_REST_7120_7219 = {
    7120: [("B", "effect", "High temperatures commonly cause physical discomfort that can disrupt sleep.")],
    7121: [("A", "typical_location", "Comic books often feature animals with exaggerated special abilities beyond real ones.")],
    7122: [("B", "typical_location", "A kennel gives a dog a designated sleeping area that can aid house training.")],
    7123: [("B", "effect", "Drivers commonly slow down when they see a police car nearby.")],
    7124: [("E", "motivation", "Curiosity about another place motivates a person to go there.")],
    7125: [("B", "part_whole", "The sun sits at the center of the solar system.")],
    7126: [("B", "property", "A hunter may hang a painting or mounted fox on the wall as decoration.")],
    7127: [("A", "typical_location", "An art show displays original paintings that can inspire viewers.")],
    7128: [("C", "typical_location", "On hot days children commonly walk to a swimming pool to cool off.")],
    7129: [("E", "typical_location", "Heifers are commonly exhibited and judged at county fairs.")],
    7130: [("C", "primary_function", "Paying attention in a lecture enables a student to learn from it.")],
    7131: [("B", "effect", "Cleaning a house thoroughly commonly leaves a person feeling tiredness.")],
    7132: [("A", "effect", "Drinking too much liquor commonly causes a person to stumble.")],
    7133: [("B", "typical_location", "Jellyfish are commonly found in the Mediterranean Sea.")],
    7134: [("A", "typical_location", "A labyrinth is a maze where someone trying to leave may run into a wall.")],
    7135: [("D", "effect", "Ice that is no longer ice has melted into liquid water.")],
    7136: [("D", "property", "A devastating facial injury can leave a face looking hideous.")],
    7137: [("E", "part_whole", "Dogs run around all day using their four legs for locomotion.")],
    7138: [("C", "effect", "Running twenty-six miles commonly causes nearly everyone to feel exhaustion.")],
    7139: [("B", "typical_location", "Train stations often have automated ticket booths.")],
    7140: [("E", "typical_location", "A loft is typically an open upper space without a dedicated bed.")],
    7141: [("E", "property", "Despite being old, a vigorous bull is not feeble.")],
    7142: [("D", "part_whole", "The Indian Ocean is named after the Indian subcontinent landmass.")],
    7143: [("B", "typical_location", "Grapes are commonly purchased at a food store.")],
    7144: [("A", "effect", "Drinking too much alcohol causes a person to become drunk.")],
    7145: [("A", "property", "Upgrading office computers with new equipment is typically expensive.")],
    7146: [("C", "used_for", "Excited babies may clap their hands even though they cannot applaud like adults.")],
    7147: [("B", "typical_location", "White rats are commonly kept in a laboratory for research.")],
    7148: [("D", "property", "Oceans are very deep, providing diverse habitats for many different creatures.")],
    7149: [("C", "primary_function", "Adding taco meat to a hot pan is done to brown the meat.")],
    7150: [("D", "typical_location", "A recording studio often has a booth with a window where musicians play with headphones.")],
    7151: [("B", "motivation", "Students in school sessions are expected to pass their course.")],
    7152: [("B", "used_for", "People commonly crumple a sheet of paper before throwing it away.")],
    7153: [("C", "typical_location", "A shopping center can be so packed with people that aisles are hard to navigate.")],
    7154: [("B", "used_for", "Hot tired dogs commonly sloppily drink water to cool down.")],
    7155: [("B", "typical_location", "An uncaptured jellyfish is likely found near the shore in the ocean.")],
    7156: [("E", "typical_location", "A household vacuum is commonly stored in a closet when not in use.")],
    7157: [("D", "typical_location", "A stool is commonly found at a bar for seating.")],
    7158: [("C", "property", "After conservation efforts, buffalo populations became plentiful again.")],
    7159: [("B", "property", "Material confirmed for an upcoming test is treated as very important.")],
    7160: [("B", "effect", "A father whose child's killer goes free commonly feels anguish when justice is not served.")],
    7161: [("C", "typical_location", "Teenagers often dislike high school but attend because they must to graduate.")],
    7162: [("D", "property", "Dog breeds were developed with many colours and varied physical traits.")],
    7163: [("B", "typical_location", "An agricultural specialist walking row to row is likely in a farmer's field.")],
    7164: [("A", "typical_location", "The Kentucky Derby in Kentucky is among the world's most famous horse races.")],
    7165: [("A", "property", "The opposite of ambiguous meaning is clear or unambiguous.")],
    7166: [("A", "property", "Kissing is often described as expressing strong feelings between people.")],
    7167: [("A", "effect", "Monopoly ends when one player wins the game by bankrupting all opponents.")],
    7168: [("E", "used_for", "Children commonly like to play games during car rides.")],
    7169: [("A", "typical_location", "Moving into a new apartment commonly prompts buying new cups for the kitchen.")],
    7170: [("E", "used_for", "A father who does not abandon his son will embrace and support him.")],
    7171: [("B", "typical_location", "A collection of many cottages where residents know each other is called a village.")],
    7172: [("D", "cause", "Running out of money commonly forces a person to stop buying products.")],
    7173: [("A", "typical_location", "A semi-truck traveling on a superhighway can move largely unrestricted on open stretches.")],
    7174: [("B", "typical_location", "Someone who owns the only dentist office in an area likely lives in a small town.")],
    7175: [("A", "property", "Many children do not want to eat vegetables.")],
    7176: [("D", "used_for", "A cup can be filled with water to give a thirsty dog a drink.")],
    7177: [("E", "property", "A roundabout slows traffic compared with a long straight road leading to a stop.")],
    7178: [("C", "effect", "Some believe that constant assistance to those in need builds dependence rather than self-reliance.")],
    7179: [("A", "effect", "Overwhelming difficulty in life can drive a person to consider suicide.")],
    7180: [("C", "used_for", "Sex can be an enjoyable physical activity that helps a person get in shape.")],
    7181: [("A", "property", "Monsters that appear while sleeping are called nightmares.")],
    7182: [("B", "typical_location", "Canned vegetables are commonly stored in a cellar over the winter.")],
    7183: [("B", "typical_location", "A furniture store is the typical place to purchase furniture.")],
    7184: [("D", "typical_location", "A fork belongs on a table alongside other place settings during a meal.")],
    7185: [("E", "effect", "Drinking water produces hydration in most humans.")],
    7186: [("E", "effect", "Presidents are often said to always get in trouble with critics and scandals.")],
    7187: [("E", "typical_location", "A fiddle can be purchased or rented at a music store.")],
    7188: [("A", "typical_location", "Sloths live in the wilderness and could be taken from there.")],
    7189: [("D", "effect", "Getting drunk commonly leads to stumbling and falling down.")],
    7190: [("C", "motivation", "A desire to change society may stem from aiming for a cultural revolution.")],
    7191: [("B", "property", "An illogically spelled word in text might be something like though with silent letters.")],
    7192: [("E", "effect", "Using a computer commonly increases efficiency for work tasks.")],
    7193: [("A", "typical_location", "A music store lets customers try out keyboard instruments before buying.")],
    7194: [("C", "used_for", "People in a library are likely studying books or reading quietly.")],
    7195: [("A", "motivation", "People usually play games for entertainment and enjoyment.")],
    7196: [("B", "effect", "The women were tired of staying quiet and decided to speak about the issue.")],
    7197: [("C", "typical_location", "Dressing rooms commonly have long mirrors for trying on clothes.")],
    7198: [("E", "typical_location", "A bald eagle commonly lands in a tall pine tree.")],
    7199: [("B", "effect", "While contemplating a problem, a student may make a discovery that leads to the answer.")],
    7200: [("E", "typical_location", "The United States lies in the northern hemisphere, so an astronaut aims there from space.")],
    7201: [("D", "typical_location", "Devil's food cake is a prize commonly won at a church cakewalk fundraising game.")],
    7202: [("A", "effect", "If auditors are worried about your practices, you should care because the company could be liquidated.")],
    7203: [("C", "typical_location", "At a buffet you fill a salad bowl with as much as you want to eat.")],
    7204: [("B", "property", "Ocean water is a liquid that contains naturally occurring salt.")],
    7205: [("A", "effect", "A person convicted of murder is sent to go to jail.")],
    7206: [("E", "property", "PG-13 ratings allow only partial nudity rather than full nudity.")],
    7207: [("E", "effect", "Repeated failure to beat a friend at chess commonly causes frustration.")],
    7208: [("A", "primary_function", "A boss commonly signs checks at the end of the week to pay employees.")],
    7209: [("A", "typical_location", "A maternity ward waiting room may contain fathers awaiting news of a birth.")],
    7210: [("D", "typical_location", "A dead weasel specimen may be displayed at a natural history museum.")],
    7211: [("E", "typical_location", "Students need to use pens most frequently at school.")],
    7212: [("B", "typical_location", "South America is one of the largest regions with diverse lizard populations.")],
    7213: [("A", "property", "Two people agreeing with each other exist in accord with one another.")],
    7214: [("B", "typical_location", "Rock in a desert is found on the surface of earth.")],
    7215: [("B", "effect", "If a movie seems vapid, one might appreciate the book version more.")],
    7216: [("C", "typical_location", "A fortune can be made through investments in the stock market.")],
    7217: [("E", "part_whole", "Townships are a form of local government common in certain states.")],
    7218: [("D", "capability", "Climbing requires the use of very particular dexterity in hands and feet.")],
    7219: [("E", "typical_location", "Raked leaves are commonly added to a compost pile for decomposition.")],
}
