# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7420-7519 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_7420_7519 = {
    7420: [("A", "typical_location", "A large dog might live in a guard house where it can patrol and protect property.")],
    7421: [("B", "property", "Items can fall out of a bundle that is tied too loosely.")],
    7422: [("B", "motivation", "Mistrust may lead a person to check up on someone while they are working.")],
    7423: [("E", "motivation", "A pathological shopping habit reflects a compulsive need to keep possessing more things.")],
    7424: [("E", "primary_function", "Cats mark territory by excreting a scented spray.")],
    7425: [("D", "typical_location", "A percussion instrument can be purchased at a music store.")],
    7426: [("D", "effect", "Waiting in traffic for a long time commonly causes a person to be late arriving to work.")],
    7427: [("B", "typical_location", "People sit outside on bleachers at a sporting event.")],
    7428: [("E", "typical_location", "A soccer field at a school is commonly located next to the school yard.")],
    7429: [("B", "used_for", "Children on a ranch often enjoy riding horses.")],
    7430: [("D", "property", "Something that is not divine and not terrible may be described as humdrum.")],
    7431: [("C", "effect", "Using the wrong words by accident commonly causes misunderstandings.")],
    7432: [("B", "typical_location", "Workers who pass through a lobby are often in an office building.")],
    7433: [("A", "used_for", "When gathering weapons, people commonly stockpile them for future use.")],
    7434: [("C", "effect", "A better solution can make a person's earlier effort seem insignificant.")],
    7435: [("A", "primary_function", "Contemplating research results is a form of thinking.")],
    7436: [("D", "effect", "Applying for a job while already employed can cause anxiety and fear.")],
    7437: [("B", "effect", "Lowered inhibitions from drinking alcohol can lead to having sex.")],
    7438: [("D", "typical_location", "A drill that is not being used is likely stored in a tool shed.")],
    7439: [("E", "typical_location", "Someone who urgently needs a toilet would go to the bathroom.")],
    7440: [("A", "motivation", "A knight returning to the castle after a quest would go to see the king.")],
    7441: [("B", "used_for", "Someone with a passion for music could listen to music all day.")],
    7442: [("D", "has_prerequisite", "Hungry plants need photosynthesis to produce the energy they require.")],
    7443: [("B", "cause", "Sam may think James is a native because Lane introduced him that way.")],
    7444: [("B", "property", "Art with very little originality is often described as derivative.")],
    7445: [("E", "property", "Making up questions for others can be an enjoyable task.")],
    7446: [("B", "typical_location", "People commonly play with a frisbee at a park.")],
    7447: [("C", "used_for", "A drink ordered on the rocks is served over ice, as with scotch.")],
    7448: [("D", "typical_location", "Olives that you want to cook can be placed in an oven.")],
    7449: [("C", "typical_location", "A European red fox roaming in the wild is likely in the northern hemisphere.")],
    7450: [("E", "property", "Felt is a material commonly used to make a man's hat.")],
    7451: [("A", "typical_location", "If you do not have a marker, you can get one at an office supply store.")],
    7452: [("E", "used_for", "When fishing, a person is trying to catch fish.")],
    7453: [("A", "typical_location", "Civilians may stand in line inside at a bus stop waiting area.")],
    7454: [("E", "used_for", "A weather report is used to find out whether clouds will appear in the sky.")],
    7455: [("C", "typical_location", "A small house is likely to have a table in the kitchen.")],
    7456: [("D", "typical_location", "Grapes used for wine production ultimately end up at a winery.")],
    7457: [("C", "typical_location", "A traveler who distrusts unfamiliar lighting may not trust the lights at a hotel.")],
    7458: [("C", "property", "California is the largest coastal state among common U.S. state options with a seacoast.")],
    7459: [("A", "has_prerequisite", "A rosebush grows best in a temperate climate.")],
    7460: [("D", "typical_location", "Animals commonly frolic in a meadow.")],
    7461: [("E", "typical_location", "Basketball dribbles echo loudly in an empty gymnasium.")],
    7462: [("D", "typical_location", "People go to a classroom to gain knowledge.")],
    7463: [("C", "typical_location", "A crossroads with deserted traffic is likely located in the countryside.")],
    7464: [("C", "typical_location", "Children often love visiting their grandmother's house for treats and affection.")],
    7465: [("E", "used_for", "Jim offered the homeless person advice he remembered, even though he was not religious.")],
    7466: [("E", "typical_location", "In a kitchen, a cup is commonly kept on a table.")],
    7467: [("C", "used_for", "A movie performance can be viewed on a DVD.")],
    7468: [("E", "typical_location", "People buy gum, candy, and popcorn before watching movies.")],
    7469: [("E", "motivation", "Socialising is a way to begin forming friendships.")],
    7470: [("B", "typical_location", "A cardboard box full of car parts is commonly kept in a garage.")],
    7471: [("B", "effect", "After someone lives a life, death eventually occurs.")],
    7472: [("E", "typical_location", "Workers in suits and ties are commonly found on the ground floor of an office building.")],
    7473: [("B", "typical_location", "Containers holding hydrogen are commonly found in a chemistry lab.")],
    7474: [("C", "motivation", "An archaeologist searching for ancient civilization may enjoy the adventure of discovery.")],
    7475: [("E", "effect", "Watching television when one has much to do may be wasting time.")],
    7476: [("E", "has_prerequisite", "Waiting in line for a long time requires patience.")],
    7477: [("A", "effect", "Going for a run can cause leg cramps that are likely to hurt.")],
    7478: [("E", "has_prerequisite", "To join a poker hand, a player must ante up.")],
    7479: [("A", "capability", "A marmot is likely to be good at finding food.")],
    7480: [("D", "typical_location", "After the final boarding group is seated, an airplane can depart.")],
    7481: [("C", "typical_location", "An out-of-the-way spot for a floor lamp is often a corner of a room.")],
    7482: [("A", "typical_location", "A man who wants to carry a writing instrument with him may put it in a pocket.")],
    7483: [("D", "part_whole", "Two bookends on a shelf support a line of library books.")],
    7484: [("D", "typical_location", "People worshipping together when the lights go out are likely in a church.")],
    7485: [("E", "has_prerequisite", "Birds kept in a sealed jar without air holes need to breathe to survive.")],
    7486: [("E", "used_for", "Charlie was treating his pet dog for fleas while Snoopy watched.")],
    7487: [("B", "used_for", "Volunteering is a great way for teens to build character and pad their resume.")],
    7488: [("D", "motivation", "Someone without happiness may need to live life more fully.")],
    7489: [("E", "typical_location", "When Billy needed his hammer, he looked in his tool box.")],
    7490: [("E", "effect", "A boy scared to dance may spend the evening sitting still in a corner.")],
    7491: [("C", "property", "A prisoner is likely to have chains or restraints.")],
    7492: [("C", "effect", "At age fifteen, a student may go to high school for the first time.")],
    7493: [("A", "effect", "Someone having fun is likely to experience enjoyment.")],
    7494: [("C", "used_for", "Before going on vacation, you pack the things you want to take with you.")],
    7495: [("D", "typical_location", "To see a meteor, you look up at the sky.")],
    7496: [("C", "used_for", "A plastic model kit can be used when you want to create something new.")],
    7497: [("C", "typical_location", "People using public transportation are often found waiting at a train station.")],
    7498: [("D", "typical_location", "A toilet filthy from overuse and drunken use is likely at a stadium.")],
    7499: [("B", "used_for", "A container can is generally used to store liquid.")],
    7500: [("C", "motivation", "A single person at a singles party likely wants to be meeting people.")],
    7501: [("A", "typical_location", "Chocolate cake from a dessert tray is commonly chosen at a buffet.")],
    7502: [("A", "motivation", "It is a good idea to wait for a sale before buying an item.")],
    7503: [("E", "effect", "Playing through an injury requires a person to ignore the pain.")],
    7504: [("C", "typical_location", "Friends sleeping in loft beds at a remote crude building may be at a hunting lodge.")],
    7505: [("A", "effect", "Shopping can become dangerous when a person keeps overspending beyond their means.")],
    7506: [("B", "used_for", "When talking to someone, you should maintain eye contact.")],
    7507: [("A", "effect", "Rocks flung by large trucks on the highway can crack a car's windows.")],
    7508: [("C", "motivation", "After a deer eats a rosebush, a person may begin planting again.")],
    7509: [("B", "used_for", "A knob on a control panel is used to change settings.")],
    7510: [("B", "effect", "Sunlight shining inside commonly makes a room warm.")],
    7511: [("E", "motivation", "People often eat fruit because it tastes sweet.")],
    7512: [("D", "used_for", "A company delivers things to customers by shipping goods.")],
    7513: [("D", "property", "A perfunctory examination is not thorough enough to catch the real cause of death.")],
    7514: [("B", "effect", "Drinking a lot of water causes the bladder to become full.")],
    7515: [("A", "effect", "Someone who dislikes communicating by mail may dislike waiting for a response.")],
    7516: [("C", "effect", "Buying products can be impossible if you experience bankruptcy.")],
    7517: [("B", "used_for", "Produce such as potatoes and bananas is commonly carried home in shopping bags.")],
    7518: [("E", "motivation", "Public recreational areas in a condominium serve the community.")],
    7519: [("E", "typical_location", "Wild bald eagles can still be found in Utah.")],
}
