# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 6120-6219 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6120_6219 = {
    6120: [("B", "typical_location", "Prince Edward Island in Canada is famous for potato farming.")],
    6121: [("E", "typical_location", "Professional photographs are commonly displayed at an art show.")],
    6122: [("C", "typical_location", "Loose ball bearings are often collected and stored in a can.")],
    6123: [("A", "effect", "Surfing the internet on a computer at night can cause eye strain.")],
    6124: [("C", "effect", "Someone constantly on a cell phone may talk about themselves frequently.")],
    6125: [("A", "part_whole", "A pawn is a minor piece used in someone else's larger scheme.")],
    6126: [("A", "typical_location", "If smoking is barred inside a building, smokers must go outside.")],
    6127: [("D", "motivation", "A lazy person typically wants an easy life with minimal effort.")],
    6128: [("D", "typical_location", "Boats are often stored in a warehouse during harsh winter months.")],
    6129: [("A", "effect", "Feeling that everything is spinning while climbing is called vertigo.")],
    6130: [("D", "property", "Someone committing perjury is knowingly telling lies under oath.")],
    6131: [("B", "typical_location", "Theaters are typically located in a downtown area of a city.")],
    6132: [("A", "typical_location", "An elected official in public office may be labelled a weasel.")],
    6133: [("B", "primary_function", "An adult engineer is likely to work at an engineering job.")],
    6134: [("A", "effect", "A person whose dog ran away may become depressed.")],
    6135: [("D", "property", "Despite dismal prospects, a person may still act very cheerful.")],
    6136: [("C", "part_whole", "Elaborate joinery and paneling are commonly used for the walls of a saloon.")],
    6137: [("E", "effect", "Despite lifelong mental illness, a person may still have managed to cope.")],
    6138: [("B", "typical_location", "Summer in Texas is notoriously hot without air conditioning.")],
    6139: [("D", "effect", "Chatting with friends helps people feel relaxed.")],
    6140: [("E", "typical_location", "People looking to save for retirement often invest in the stock market.")],
    6141: [("E", "typical_location", "A referee blows his whistle and cites rules during a football game.")],
    6142: [("B", "used_for", "People employ searching for information when they need to find answers.")],
    6143: [("D", "typical_location", "After buying vegetables at a market, you can also buy magazines there.")],
    6144: [("A", "effect", "Going into a trance can leave a person feeling disoriented afterward.")],
    6145: [("E", "primary_function", "A train must slow down before reaching the station.")],
    6146: [("C", "effect", "Sleeping in late commonly leaves a person feeling tired all day.")],
    6147: [("B", "effect", "A boy good at making friends will end up having friends.")],
    6148: [("E", "typical_location", "An engineer on the job commonly works out in the field.")],
    6149: [("C", "typical_location", "A pocket is a common place to keep personal money.")],
    6150: [("A", "typical_location", "A football field is a common gathering place on a college campus.")],
    6151: [("B", "primary_function", "A child pretending to be in space uses imagining to turn ordinary items into spaceship parts.")],
    6152: [("E", "used_for", "Speculation about alien communication often involves choosing a medium of exchange.")],
    6153: [("E", "property", "Dogs are valued for their pack mentality and for being faithful companions.")],
    6154: [("C", "part_whole", "When someone is talking, you can hear their voice.")],
    6155: [("D", "part_whole", "Hub caps found during highway cleanup usually came off a car wheel.")],
    6156: [("D", "part_whole", "A newly delivered computer is opened by unboxing it from its box.")],
    6157: [("A", "property", "A wedding servant is hired staff rather than a free person of high status.")],
    6158: [("E", "typical_location", "Making loud noise and commentary while watching something is rude in a movie theatre.")],
    6159: [("D", "typical_location", "Families commonly watch television in the living room.")],
    6160: [("C", "effect", "Moving toward a predetermined goal means you have made progress.")],
    6161: [("D", "typical_location", "Too much snow accumulating on a roof is likely to cause damage.")],
    6162: [("B", "part_whole", "Birds have feathers that can molt and fall off.")],
    6163: [("B", "typical_location", "Bread is commonly put in the pantry immediately after buying it.")],
    6164: [("A", "typical_location", "When suffering, you wait in a hospital reception area.")],
    6165: [("C", "typical_location", "You can stand in line at a post office indoors without needing a coat.")],
    6166: [("B", "effect", "Students who work hard are expected to do well in school.")],
    6167: [("B", "typical_location", "People are generally not allowed to live inside a state park.")],
    6168: [("D", "effect", "Eye drops are used so that eyes do not dry out.")],
    6169: [("A", "motivation", "After years away from his hometown, a person would love to meet a friend.")],
    6170: [("E", "typical_location", "Raked leaves are commonly gathered into a compost pile.")],
    6171: [("C", "part_whole", "A mid-ranking military officer leads a company of soldiers.")],
    6172: [("E", "typical_location", "A brand new bookshelf can be purchased at a furniture store.")],
    6173: [("B", "used_for", "A parent whose child never goes outside may choose to homeschool.")],
    6174: [("C", "typical_location", "Drivers change lanes while traveling on a highway.")],
    6175: [("E", "typical_location", "Being away for the first time, Mario was excited when he met his family.")],
    6176: [("A", "effect", "Visiting a museum always involves seeing artifacts on display.")],
    6177: [("B", "typical_location", "Gasoline is produced at oil refineries.")],
    6178: [("E", "typical_location", "Millions of apple trees can be found together in an orchard.")],
    6179: [("E", "typical_location", "New clothes before starting high school are commonly bought at a mall.")],
    6180: [("B", "primary_function", "A teacher is required to state facts and teach students.")],
    6181: [("C", "used_for", "Playing chess is a good game activity for two children to do together.")],
    6182: [("B", "effect", "A rich student might try to pay a professor to let him pass a course.")],
    6183: [("E", "typical_location", "A musician playing a snare drum in a theater is likely in an orchestra.")],
    6184: [("E", "property", "A person from the western part of a region is not from the east.")],
    6185: [("B", "typical_location", "A brass drum player asked to join a friend's concert likely joins a marching band.")],
    6186: [("E", "motivation", "A minimalist hopes to achieve freedom from want through simpler living.")],
    6187: [("C", "used_for", "A person who is not being honest is practicing deception.")],
    6188: [("B", "typical_location", "Sunshine on a crew at sea also beats up from below by reflecting off the sea.")],
    6189: [("C", "used_for", "A follow-up email after no reply is sent to ask for a response.")],
    6190: [("D", "typical_location", "A bowl of whipped cream is commonly kept in the refrigerator.")],
    6191: [("B", "effect", "Receiving acknowledgment from others commonly makes a person feel good.")],
    6192: [("D", "property", "People drinking alcohol are often in a state of disorientation.")],
    6193: [("A", "typical_location", "Any tearoom will be located inside a building.")],
    6194: [("E", "typical_location", "A grocery store sells food but does not usually sell suntan lotion.")],
    6195: [("D", "primary_function", "Learning to ride a bike requires mastering pedaling.")],
    6196: [("E", "motivation", "A special interest group may mobilize young people primarily to secure their vote.")],
    6197: [("C", "part_whole", "A new copy of an original sculpture is called a replica.")],
    6198: [("A", "typical_location", "A bee shipped south to avoid cold winters was likely originally from Michigan.")],
    6199: [("B", "has_prerequisite", "An apple tree has unripe apples that are not yet ready to eat in summer.")],
    6200: [("C", "motivation", "Most people who take dance classes do so because they like dancing.")],
    6201: [("B", "used_for", "Someone who values privacy may ask others to turn away so he can act unseen.")],
    6202: [("B", "typical_location", "You can find a fast food restaurant in every town in America.")],
    6203: [("B", "used_for", "To get something from a store you must purchase it.")],
    6204: [("C", "typical_location", "One might obtain an injury from a skate during a hockey game.")],
    6205: [("B", "effect", "Some celebrities find going public useful after being caught getting high.")],
    6206: [("B", "effect", "People having fun in a big way commonly experience glee.")],
    6207: [("E", "typical_location", "A teacher would store an upright piano in a music room.")],
    6208: [("B", "typical_location", "Random kitchen items with no obvious place are often put in a cupboard.")],
    6209: [("C", "effect", "If the temperature is too low for cooking turkey, it needs to heat up.")],
    6210: [("C", "cause", "A company can get in trouble if it commits a crime.")],
    6211: [("A", "typical_location", "An orchestra pit is found in an opera house where players come on stage.")],
    6212: [("A", "typical_location", "A wire shelf is commonly found inside a refrigerator.")],
    6213: [("D", "typical_location", "Most people keep utensils in a kitchen drawer.")],
    6214: [("A", "cause", "Only close friends laugh at a fox joke because it is an inside joke.")],
    6215: [("B", "effect", "A prisoner can get into more trouble by attempting to escape.")],
    6216: [("E", "effect", "Densely packed trees in a forest grow tall to reach sunlight.")],
    6217: [("D", "typical_location", "Old cowboy and Indian movies with horses usually take place in the American southwest.")],
    6218: [("B", "typical_location", "A privately owned sporting goods shop may sit right in a small town.")],
    6219: [("B", "effect", "Committing perjury creates tension between a witness and the prosecutor.")],
}
