# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 8520-8619 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8520_8619 = {
    8520: [("C", "typical_location", "A jeweller commonly repairs watches and other fine timepieces.")],
    8521: [("B", "effect", "Being distracted makes it harder to focus and win games.")],
    8522: [("A", "effect", "Seeing an idea become reality commonly brings a fulfilling sense of accomplishment.")],
    8523: [("A", "typical_location", "Pet flea infestations commonly require treating carpets and furniture as well as the animals.")],
    8524: [("C", "typical_location", "A hotel reception desk is where guests ring a bell and check in with a reservation.")],
    8525: [("B", "effect", "Someone can feel alone even while mingling with many people at a crowded gathering.")],
    8526: [("B", "typical_location", "The sun is visible from Earth in the daytime sky.")],
    8527: [("C", "property", "Something seems odd when it differs from what was expected.")],
    8528: [("C", "effect", "After running, a person needs a period of rest before having energy to run again.")],
    8529: [("A", "property", "Someone who enjoys hearing violin performances typically likes music.")],
    8530: [("C", "typical_location", "Building inside city limits commonly means constructing a house in a residential area.")],
    8531: [("E", "used_for", "Wealthy people commonly own property such as real estate.")],
    8532: [("E", "capability", "A concierge can help guests by getting or expressing the information they need.")],
    8533: [("C", "typical_location", "The Piedmont region of the United States is largely located in North Carolina.")],
    8534: [("A", "typical_location", "Elevators sometimes play music while passengers travel between floors.")],
    8535: [("B", "used_for", "People at a beach commonly sun themselves on the sand.")],
    8536: [("E", "property", "Being away means you cannot currently be present at a location.")],
    8537: [("E", "effect", "A very happy person commonly experiences joy.")],
    8538: [("E", "effect", "Injuries can prevent football players from enjoying the game.")],
    8539: [("E", "typical_location", "Classical music is typically performed by an orchestra, unlike rap.")],
    8540: [("A", "typical_location", "People commonly buy pills and other medicines at a pharmacy.")],
    8541: [("B", "effect", "Contemplating ideas can lead to revelations or new insights.")],
    8542: [("B", "typical_location", "Istanbul is a historic city whose name changed from Constantinople.")],
    8543: [("D", "property", "Montana is nicknamed Big Sky Country for its vast open landscapes.")],
    8544: [("C", "typical_location", "Supermarkets sell shampoo alongside food and other nourishment items.")],
    8545: [("B", "used_for", "Winning an auction can let you obtain valuable items for little or no money.")],
    8546: [("A", "typical_location", "Disneyland sells themed snack food and treats shaped like Mickey Mouse.")],
    8547: [("D", "property", "Indiana is known for its racing heritage including the Indianapolis 500.")],
    8548: [("D", "typical_location", "A local radio station can sometimes pick up signals from far away transmitters.")],
    8549: [("A", "effect", "Drinking milk provides calcium that helps build strong bones.")],
    8550: [("B", "typical_location", "Africa has regions where commercial trophy hunting of wildlife is common.")],
    8551: [("E", "effect", "Eating at a favorite restaurant commonly brings satisfaction.")],
    8552: [("E", "effect", "Cats are known to knock over cups and other objects set on tables.")],
    8553: [("B", "typical_location", "Victoria is a large state in Australia where the city of Melbourne is located.")],
    8554: [("D", "property", "Someone who never leaves the city remains a city dweller their whole life.")],
    8555: [("E", "typical_location", "Taking off socks and lying down commonly indicates being in bed.")],
    8556: [("A", "typical_location", "Paperwork is commonly left on a desk when someone leaves work abruptly.")],
    8557: [("A", "cause", "Upset feelings during friendly chats often come from misunderstanding.")],
    8558: [("A", "cause", "Bright full sunlight commonly makes people seek shade.")],
    8559: [("B", "part_whole", "The neck and bridge are parts of a stringed instrument such as a guitar or violin.")],
    8560: [("E", "effect", "Smoking commonly irritates the lungs and causes coughing.")],
    8561: [("A", "motivation", "Being tired commonly makes people decide to go to bed.")],
    8562: [("B", "typical_location", "North America spans a vast area with many climates and diverse wildlife.")],
    8563: [("B", "property", "Someone not attractive in appearance may be described as homely.")],
    8564: [("E", "typical_location", "A leg razor is commonly stored in a bathroom medicine cabinet.")],
    8565: [("A", "typical_location", "Peas are often freshest when bought directly at a farmer's market.")],
    8566: [("B", "effect", "Messing up a home after housework commonly provokes anger.")],
    8567: [("C", "typical_location", "Lettuce is found in the produce section of a grocery store.")],
    8568: [("B", "used_for", "A guide leading children in line at a museum commonly takes them to see exhibits.")],
    8569: [("A", "effect", "When something does not personally concern people, they often care less about the outcome.")],
    8570: [("D", "typical_location", "Animal tracks are often clearly visible in soft mud.")],
    8571: [("E", "typical_location", "People on a highway commonly pull off to find a restaurant when hungry.")],
    8572: [("D", "typical_location", "The Gadsden flag with a snake and motto is a symbol associated with North America.")],
    8573: [("A", "typical_location", "People commonly keep keys in a jeans pocket.")],
    8574: [("E", "typical_location", "Sugar is commonly stored in a kitchen cupboard at home.")],
    8575: [("A", "property", "A gentleman dressed stylishly for a formal show often wears a tuxedo.")],
    8576: [("A", "has_prerequisite", "Conception and childbirth in humans require sexual reproduction between a man and a woman.")],
    8577: [("D", "property", "A producer avoiding live performance typically wants a recorded show.")],
    8578: [("A", "effect", "Not watching your footing while running commonly causes a person to fall down.")],
    8579: [("E", "effect", "Failing to recycle packing materials leads to more paper waste.")],
    8580: [("B", "effect", "A child running too fast who hits a foot on a rock commonly falls down.")],
    8581: [("E", "typical_location", "People often keep a chair in the bedroom to toss clothes on before going to sleep.")],
    8582: [("C", "used_for", "Soldiers use weapons to defend themselves when under attack.")],
    8583: [("A", "effect", "Waging war on a large scale generally results in death and destruction.")],
    8584: [("E", "cause", "Furniture that falls apart soon after purchase often results from poor workmanship.")],
    8585: [("D", "typical_location", "Clothing for a vacation is commonly packed and found in a suitcase.")],
    8586: [("D", "property", "On a sunny day the sky commonly appears blue.")],
    8587: [("C", "used_for", "Singing lets a person express themselves and be heard by others.")],
    8588: [("A", "typical_location", "Many sea anemones live in the intertidal zone among other tiny marine animals.")],
    8589: [("E", "effect", "Drinking too much alcohol commonly causes headaches the next morning.")],
    8590: [("B", "effect", "Running out of steam during a competition suggests the contestant is quitting.")],
    8591: [("C", "effect", "In religious belief, committing murder can lead to damnation.")],
    8592: [("A", "property", "Dreaming of being awake while actually sleeping means being in deep sleep.")],
    8593: [("B", "typical_location", "Large cities commonly have many bookstores.")],
    8594: [("B", "part_whole", "A government exercises control over the country it governs.")],
    8595: [("E", "effect", "Eating high-calorie food without exercising commonly leads to weight gain.")],
    8596: [("C", "typical_location", "People visit graveyards to be near the resting place of deceased ancestors.")],
    8597: [("C", "cause", "Corrupt politicians may improperly accept bribes.")],
    8598: [("B", "typical_location", "People commonly find taxis waiting at street corners.")],
    8599: [("B", "property", "Offering help when someone lacks change is an act of kindness.")],
    8600: [("B", "motivation", "Meeting new people typically requires going out to social settings.")],
    8601: [("B", "typical_location", "Small apartments in cities like Manhattan suit keeping only a small dog.")],
    8602: [("E", "part_whole", "An airplane has metal wings used for flight.")],
    8603: [("B", "part_whole", "A cathode ray tube was the display component inside older television sets.")],
    8604: [("A", "effect", "Difficulty reading aloud from a teleprompter commonly leads to stammering.")],
    8605: [("D", "capability", "Dogs reproduce, so two dogs can quickly produce many puppies.")],
    8606: [("B", "typical_location", "In urban areas people commonly live in an apartment dwelling.")],
    8607: [("A", "typical_location", "Photo boxes for long-term storage are commonly kept in a closet.")],
    8608: [("C", "effect", "Struggling to understand a complex program commonly leads to frustration.")],
    8609: [("D", "used_for", "Drivers commonly turn the dial to listen to the radio during monotonous drives.")],
    8610: [("E", "effect", "A first kiss often marks when two people begin to fall in love.")],
    8611: [("C", "used_for", "A cruise puts travelers near strangers and speeds up meeting new people.")],
    8612: [("D", "used_for", "Someone not present at a live performance may listen via broadcast.")],
    8613: [("A", "typical_location", "Retirement communities house elderly residents who may need wheelchair-accessible facilities.")],
    8614: [("E", "used_for", "Mission workers commonly spread religious teachings to many people.")],
    8615: [("A", "typical_location", "A clavichord is a historical keyboard instrument heard in music halls or concert settings.")],
    8616: [("E", "effect", "A car crash can cause smoke from damage to the engine or overheating.")],
    8617: [("C", "typical_location", "Preserved or mounted shark specimens are displayed in maritime museums.")],
    8618: [("D", "effect", "Children laughing while playing are having fun.")],
    8619: [("E", "typical_location", "A toilet is located in a bathroom.")],
}
