# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7820-7919 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_7820_7919 = {
    7820: [("A", "typical_location", "A city with a courthouse is commonly considered the county seat of local government.")],
    7821: [("A", "part_whole", "Plants are living organisms made up of millions of cells.")],
    7822: [("A", "typical_location", "A roof is an elevated surface where bugs are unlikely compared with gardens or fields.")],
    7823: [("A", "typical_location", "A bird that flies upward is commonly seen moving through the sky.")],
    7824: [("A", "effect", "Skiing without warm clothes commonly causes a person to get cold.")],
    7825: [("C", "typical_location", "Personal soap is commonly kept at a person's own home.")],
    7826: [("B", "typical_location", "Humans visit clerks and businesses in places such as an office block.")],
    7827: [("A", "motivation", "Someone wanting a seafood dinner may decide to fish at a lake.")],
    7828: [("C", "typical_location", "A teenager playing a trumpet is commonly part of a high school band.")],
    7829: [("E", "typical_location", "A lantern that is not for sale is likely kept in someone's house.")],
    7830: [("B", "cause", "A car crash may cause someone to stop driving immediately.")],
    7831: [("A", "capability", "Someone who can string a bass instrument likely knows how to play a bass guitar.")],
    7832: [("C", "typical_location", "Chlorinated dihydrogen monoxide is water treated with chlorine in a swimming pool.")],
    7833: [("C", "effect", "A dishonest real estate agent may misrepresent a house's quality to close a sale.")],
    7834: [("D", "typical_location", "A vacation package with hotel and meals included is commonly offered at a resort.")],
    7835: [("A", "effect", "Giving assistance commonly brings relief to the person receiving help.")],
    7836: [("C", "typical_location", "A bank may use a security lock on a revolving door because it holds large amounts of money.")],
    7837: [("B", "property", "Needing to rest often is commonly a sign that someone is weak or fatigued.")],
    7838: [("C", "typical_location", "The freshest green beans are commonly found at a farmer's market.")],
    7839: [("E", "typical_location", "The Pacific Ocean lies to the west of Nevada.")],
    7840: [("B", "property", "Someone who is very slow at work may be expected to become more fast.")],
    7841: [("A", "effect", "Someone eating a hamburger comfortably and appearing fine looks like they are enjoying the meal.")],
    7842: [("B", "effect", "Talking to people about their feelings commonly gives a person increased understanding of them.")],
    7843: [("A", "motivation", "Brothers punching angrily often do so to cause pain to each other.")],
    7844: [("C", "property", "A school cafeteria is typically a large room sized to seat many students.")],
    7845: [("C", "effect", "Eating too much cabbage and broccoli commonly causes a person to suffer from gas.")],
    7846: [("A", "typical_location", "A balcony in a theatre is a common place to watch a show from above.")],
    7847: [("A", "effect", "Someone suffering heatstroke must cool off immediately to stay alive.")],
    7848: [("E", "typical_location", "After a pencil falls from a desk cup, someone puts it back in the cup.")],
    7849: [("A", "typical_location", "A town or city may contain hundreds or thousands of apartments.")],
    7850: [("B", "effect", "Using a cleaning agent while doing housework can trigger allergies and sneezing.")],
    7851: [("D", "used_for", "The telephone is a device used to connect people who may be strangers to each other.")],
    7852: [("C", "typical_location", "A weasel cursed by a witch would be found in a fairytale story.")],
    7853: [("C", "capability", "A living person can experience pain, unlike a stuffed dummy.")],
    7854: [("E", "typical_location", "A business leader is commonly in charge of an organization.")],
    7855: [("B", "typical_location", "Shoppers try on clothes and check themselves in a mirror inside a dressing room.")],
    7856: [("A", "part_whole", "A leaf is commonly pulled off of a plant growing in a forest.")],
    7857: [("E", "typical_location", "Many prison movies are set at the famous Alcatraz prison.")],
    7858: [("B", "typical_location", "Fresh wood is obtained from a living tree before it is processed.")],
    7859: [("C", "part_whole", "Horseradish is a spicy sauce commonly served with roast beef sandwiches.")],
    7860: [("B", "typical_location", "Everything is bigger at a steak house in Texas, according to a common saying.")],
    7861: [("D", "property", "A builder who is blocked may protest that the proposed construction should be permitted.")],
    7862: [("D", "typical_location", "People who are not morning people often do not get going until the afternoon.")],
    7863: [("C", "effect", "A person in a comfortable relationship may let himself go and neglect personal upkeep.")],
    7864: [("A", "typical_location", "Plastic silverware at a cheap restaurant can feel like a turnoff to some diners.")],
    7865: [("E", "typical_location", "A weasel kept behind glass for children to view may rest comfortably in a terrarium.")],
    7866: [("D", "effect", "Giving assistance to family members in need commonly brings a feeling of satisfaction.")],
    7867: [("D", "typical_location", "People who throw bottles in the grass leave broken glass scattered in a field.")],
    7868: [("A", "property", "Mercury building up in fish can make them toxic to eat.")],
    7869: [("A", "effect", "Sam may be getting headaches, something unwanted that causes discomfort.")],
    7870: [("B", "typical_location", "Cheese on a mouse trap is dangerous for mice and other small creatures.")],
    7871: [("B", "effect", "Someone may try to stop violin playing because it produces loud noises.")],
    7872: [("B", "typical_location", "Congress is colloquially said to contain human weasels, meaning cunning people.")],
    7873: [("C", "typical_location", "The prosecution's job is to explain why a defendant is guilty of obstructing justice.")],
    7874: [("E", "typical_location", "If you do not have a washcloth, you can buy one at Walmart.")],
    7875: [("B", "used_for", "A party host at the front door stays there to welcome guests as they arrive.")],
    7876: [("B", "typical_location", "A truck driver on a long haul who gets lost may buy a map at a truck stop.")],
    7877: [("D", "property", "Adequate light is crucial when trying to read text clearly.")],
    7878: [("C", "effect", "Driving drunk is extremely dangerous and can end up deadly.")],
    7879: [("A", "typical_location", "Sourdough bread dough commonly begins to rise inside a bread pan.")],
    7880: [("E", "effect", "A foreman may tell a worker to move away from dangerous equipment instead of standing in the way.")],
    7881: [("E", "effect", "Meeting a friend you have not seen in a long time commonly brings excitement.")],
    7882: [("A", "cause", "A company may have low manufacturing costs if it uses slave labor instead of fair wages.")],
    7883: [("B", "used_for", "To confirm information you already have, you would ask someone about it.")],
    7884: [("D", "part_whole", "The cover bounds and protects the pages of a book.")],
    7885: [("A", "effect", "Listening to a boring talk for a long time commonly leads to fatigue.")],
    7886: [("A", "effect", "An airplane may stall in the air before it starts falling down.")],
    7887: [("C", "property", "America is called a melting pot because its people come from many different backgrounds.")],
    7888: [("E", "capability", "Running in the Olympics requires competitive speed beyond ordinary outdoor jogging.")],
    7889: [("B", "part_whole", "Veins carry blood toward the heart throughout the body.")],
    7890: [("E", "typical_location", "Cracker crumbs from children playing on the floor end up on the rug needing vacuuming.")],
    7891: [("C", "typical_location", "To add more light sources for nighttime wakefulness, install them throughout the house.")],
    7892: [("A", "used_for", "Coffee beans are processed to make coffee, a popular drink.")],
    7893: [("D", "typical_location", "A hospital usually has more than one telephone for different departments and stations.")],
    7894: [("D", "effect", "Someone wading in water while fishing commonly ends up with wet clothes.")],
    7895: [("C", "typical_location", "A busy landing where people socialize is commonly found in a stairwell.")],
    7896: [("C", "motivation", "A person may take drugs to not feel pain during illness or injury.")],
    7897: [("A", "typical_location", "A movie is entertainment commonly watched on a screen.")],
    7898: [("D", "typical_location", "You order a cup of coffee at a coffee shop.")],
    7899: [("E", "typical_location", "Cows being judged for prizes are commonly found at fairgrounds.")],
    7900: [("A", "typical_location", "After finishing a meal, a used spoon is commonly placed in the dishwasher.")],
    7901: [("B", "effect", "Performing many physical tasks commonly leads to tiredness.")],
    7902: [("D", "typical_location", "A fox that wants to hide may go into its burrow underground.")],
    7903: [("B", "effect", "Eating without exercising commonly leads to gaining weight.")],
    7904: [("D", "property", "A black and white photograph that is not recent is likely old.")],
    7905: [("E", "typical_location", "Stories about a talking beaver are commonly found in children's books.")],
    7906: [("C", "effect", "A person planning to stop being married to their spouse is probably feeling sad.")],
    7907: [("D", "typical_location", "Old pictures are commonly kept stored in an attic.")],
    7908: [("D", "typical_location", "Someone might fall on ice during a hockey game on a rink.")],
    7909: [("D", "typical_location", "While cleaning an old house, forgotten items are often found in the cellar.")],
    7910: [("A", "typical_location", "A man commonly carries a dollar bill in his wallet.")],
    7911: [("C", "typical_location", "In Michigan and other rural states, a blanket is useful to cover a horse in cold weather.")],
    7912: [("A", "has_prerequisite", "The best things for your health are to exercise and eat well.")],
    7913: [("A", "typical_location", "Garbage waste poured on a road commonly washes away into the sewer.")],
    7914: [("D", "part_whole", "A state is smaller than a country but larger than a city.")],
    7915: [("C", "property", "A laconic speaker avoids verbose language and keeps remarks brief.")],
    7916: [("A", "effect", "Someone stabbed to death may collapse covered with knife wounds.")],
    7917: [("C", "typical_location", "A frying pan is commonly stored in a kitchen cabinet.")],
    7918: [("D", "property", "In the film Lady and the Tramp, a girl who likes Lady may have a brother who likes the Tramp.")],
    7919: [("A", "effect", "People who touch a hot stove commonly burn themselves.")],
}
