# -*- coding: utf-8 -*-
"""Batch 4: hand-authored rest KB for qids 320-519."""

KNOWLEDGE_REST_320_519 = {
    320: [("B", "effect", "Reproduction begins and ends with giving birth to new life.")],
    321: [("B", "typical_location", "The North Pole is known to always have snow.")],
    322: [("A", "motivation", "Someone having fun with friends and trying to fit in wants to be understood.")],
    323: [("B", "motivation", "Parents who want children to learn teamwork often sign them up to play sports.")],
    324: [("D", "effect", "A sleepy person can drink coffee to feel more alert.")],
    325: [("B", "typical_location", "A large city could contain hundreds of sporting goods stores.")],
    326: [("C", "property", "A selfish child may not even care when being mean to others.")],
    327: [("C", "primary_function", "People explore space by using a space shuttle.")],
    328: [("A", "typical_location", "Unusual varieties of roses are commonly found in a botanic garden.")],
    329: [("B", "typical_location", "A desk is a sensible place to put a light for reading or work.")],
    330: [("E", "effect", "Eating a hamburger from an unknown source can cause food poisoning.")],
    331: [("B", "effect", "Touching an exposed wire commonly causes a person to get shocked.")],
    332: [("E", "typical_location", "Arkansas is a landlocked southern state where a fox might be seen.")],
    333: [("A", "property", "A priest pushing for orthodox behavior is trying to stop liberal behavior.")],
    334: [("E", "primary_function", "Breathing deeply helps a person enjoy fresh mountain air more.")],
    335: [("E", "typical_location", "A cow that comes outside after a storm still stays in the green field.")],
    336: [("A", "typical_location", "A health center is where one can obtain a contraceptive.")],
    337: [("E", "typical_location", "A Martian would find the Indian Ocean on Earth.")],
    338: [("E", "typical_location", "A ficus plant can brighten up a room in an apartment.")],
    339: [("A", "primary_function", "A refrigerator keeps turkey from spoiling.")],
    340: [("B", "property", "A giant hole in a plain might be called a gorge.")],
    341: [("D", "typical_location", "Tracking oxygen levels is necessary aboard a space shuttle.")],
    342: [("C", "primary_function", "Putting on headphones to relax commonly leads to listening to music.")],
    343: [("C", "motivation", "Someone who knows the police are after him may prepare to go on the run.")],
    344: [("A", "effect", "After going for a run, a person often feels a sense of satisfaction.")],
    345: [("D", "has_prerequisite", "Fiddling through a music book instead of playing suggests a lack of knowledge of music.")],
    346: [("C", "property", "A fragile man may hope to find someone indestructible as his opposite.")],
    347: [("C", "typical_location", "A bass clarinet to take home is bought at a music store.")],
    348: [("C", "has_prerequisite", "Deciding whether to see artifacts requires careful thinking.")],
    349: [("A", "property", "Someone unfamiliar with another person may come off as cold.")],
    350: [("C", "typical_location", "A launch pad is one part of a vast space center complex.")],
    351: [("C", "typical_location", "Rain-damaged electronics from a store should be stored inside a building.")],
    352: [("E", "motivation", "A lonely person may commit suicide to end pain.")],
    353: [("A", "motivation", "Someone who is thick may want to become slender.")],
    354: [("D", "effect", "Walking all day in the wrong shoes commonly causes blisters on heels and toes.")],
    355: [("B", "primary_function", "Thinking releases mental energy without mainly using the muscles.")],
    356: [("A", "primary_function", "Doing a crossword puzzle with a dictionary helps relieve boredom.")],
    357: [("B", "property", "A chess game is played with pieces, though the board itself is one solid piece.")],
    358: [("A", "typical_location", "A fond childhood memory of a giraffe mascot may come from a toy store.")],
    359: [("A", "typical_location", "A student can get lost finding a second-floor room in a very large school.")],
    360: [("E", "primary_function", "Whether popped, grilled, or canned, people like to eat corn.")],
    361: [("E", "effect", "Someone caught committing murder may experience a feeling of guilt.")],
    362: [("D", "typical_location", "After commuting by car in a city, one still walks to and from the parking garage.")],
    363: [("B", "motivation", "Telling many people about a new organization helps them learn about it.")],
    364: [("C", "typical_location", "The legs of a stool can be built in a blacksmith's shop.")],
    365: [("C", "property", "People scared of someone may perceive that person as dangerous.")],
    366: [("A", "typical_location", "A ticket at a train station can help one travel to a different country.")],
    367: [("C", "effect", "Playing too aggressively commonly leads to injury.")],
    368: [("D", "motivation", "Students are generally trying to further their education.")],
    369: [("A", "typical_location", "Farmers keep toothpicks in their mouth for use after meals.")],
    370: [("A", "primary_function", "A detective analysing clues must look at every detail at the scene.")],
    371: [("C", "property", "A person with brown skin may share that trait with their own family.")],
    372: [("E", "primary_function", "Screwing a chain ring onto something is part of fixing a motorcycle.")],
    373: [("C", "typical_location", "A dictionary being used is commonly placed on a table.")],
    374: [("C", "property", "A common saying paired with go forth is back and forth.")],
    375: [("E", "property", "Someone who is awake and conscious is likely to know what is going on.")],
    376: [("C", "typical_location", "Decorative swords in a house may be kept in a collection.")],
    377: [("E", "primary_function", "Not abandoning a fight means choosing to engage the enemy.")],
    378: [("B", "typical_location", "A shower is an expected amenity when one reserves a motel room.")],
    379: [("D", "primary_function", "Humans in a race compete with each other.")],
    380: [("A", "property", "A garage with light sensors and automatic doors belongs to a modern house.")],
    381: [("A", "typical_location", "In a workplace, people gather near liquid at the water cooler.")],
    382: [("E", "typical_location", "A tent can be stored in a backpack and carried on your person.")],
    383: [("B", "effect", "People playing games commonly experience entertainment.")],
    384: [("C", "typical_location", "A child who leaves fighting parents does not want to stay at home.")],
    385: [("E", "typical_location", "Fox hunting when not in a forest is associated with England.")],
    386: [("B", "typical_location", "A senior who lives with his children may refuse to go to an old people's home.")],
    387: [("B", "effect", "Ground getting wet near you may be caused by snow or ice melting.")],
    388: [("D", "typical_location", "Most people keep magazines at home.")],
    389: [("C", "property", "Chinese food is stereotypically joked about in relation to small dogs.")],
    390: [("C", "motivation", "A person may seek counseling to understand themselves better.")],
    391: [("A", "typical_location", "A water spout in the ocean off the coast is commonly seen near Florida.")],
    392: [("E", "property", "Buildings like the Empire State Building are described as tall.")],
    393: [("B", "motivation", "Rowdy frat boys shouting about having fun tonight may plan to get laid.")],
    394: [("E", "effect", "Someone having fun may laugh.")],
    395: [("D", "motivation", "A common goal of going jogging is to lose weight.")],
    396: [("C", "cause", "A person may be stuck in his house during a winter storm.")],
    397: [("B", "typical_location", "The master control for the Tardis is at the center of the main room.")],
    398: [("D", "has_prerequisite", "An old barn beyond repair must be destroyed before one can build a new one.")],
    399: [("A", "typical_location", "Shopping bags for packing groceries are found at a supermarket.")],
    400: [("E", "property", "A dismissive view of accident statistics is that accidents happen anywhere.")],
    401: [("B", "property", "A television show with different episodes about a ranger and a gardener is an anthology.")],
    402: [("E", "motivation", "When cupboards are barren, a household must go get food.")],
    403: [("E", "primary_function", "A flea locomotes primarily by jumping.")],
    404: [("B", "typical_location", "A professional prostitute is likely found in a whorehouse.")],
    405: [("E", "typical_location", "A vintage decorative light source in a home is likely a lamp.")],
    406: [("E", "primary_function", "Someone curious who cannot leave the house may surf the net.")],
    407: [("A", "property", "If Sam was against a decision, Joe being the opposite was for it.")],
    408: [("A", "effect", "Working with wood can cause blisters on the hands.")],
    409: [("B", "typical_location", "History studies are a favorite subject within social science.")],
    410: [("B", "typical_location", "A wealthy gentleman who flaunts his riches likely lives in a big house.")],
    411: [("C", "typical_location", "A bookstore is commonly found in a city.")],
    412: [("C", "effect", "Someone respected by few may face a lot of disparagement.")],
    413: [("E", "effect", "Trouble beginning work is a symptom of procrastination.")],
    414: [("D", "property", "Waiting for the doctor is difficult for busy workers because it is time consuming.")],
    415: [("E", "motivation", "Without curiosity, watching a favorite show can still ensure viewing enjoyment.")],
    416: [("B", "motivation", "A gambler on a winning streak may wisely decide to cash in.")],
    417: [("C", "motivation", "A lover is likely to want to make love with their partner.")],
    418: [("A", "typical_location", "After clothes are filled into it, a bag may be placed in a shopping cart.")],
    419: [("D", "effect", "A lab sample that needed to be pure may become contaminated.")],
    420: [("E", "primary_function", "An old-time doctor used leeches to let blood from a patient.")],
    421: [("B", "motivation", "Someone looking for new things in life welcomes change.")],
    422: [("A", "typical_location", "A handle on a briefcase lets you bring the case with you.")],
    423: [("C", "has_prerequisite", "One needs money before buying products.")],
    424: [("E", "motivation", "In basketball, the goal is to score points.")],
    425: [("E", "effect", "Fatigue often follows a long day of traveling.")],
    426: [("D", "has_prerequisite", "Great skill at something requires focus and dedication.")],
    427: [("B", "effect", "When humans are exposed to noises, they hear sounds.")],
    428: [("A", "motivation", "When listening to an expert speak, one hopes to gain learning.")],
    429: [("B", "typical_location", "An old copy machine is likely to be viewed in a museum.")],
    430: [("D", "primary_function", "A child may wash dishes after breakfast before getting on the bus.")],
    431: [("E", "typical_location", "Hundreds of rows of large containers fill a warehouse.")],
    432: [("A", "typical_location", "A cottonmouth snake is an American species found in Georgia.")],
    433: [("C", "typical_location", "Furniture is placed on top of the floor.")],
    434: [("B", "typical_location", "A county highway appears as a line on a map.")],
    435: [("B", "effect", "Heart attacks from stress can cause death if not treated immediately.")],
    436: [("A", "typical_location", "A person who takes a seat to watch a movie is in a cinema.")],
    437: [("A", "typical_location", "One can read a magazine at a train station while waiting for rail transport.")],
    438: [("D", "primary_function", "A farmer planting seed crops can reuse them and make bird feed.")],
    439: [("C", "typical_location", "Cake with ice cream is commonly served at a party.")],
    440: [("E", "typical_location", "Living at the top of a tall tower where clouds pass the window suggests a medieval castle.")],
    441: [("B", "primary_function", "Policemen clearing an accident scene direct traffic.")],
    442: [("D", "typical_location", "Betting with a shark commonly takes place in a pool hall.")],
    443: [("B", "typical_location", "Louisiana is a coastal gulf state where a fox might be seen.")],
    444: [("A", "typical_location", "A clerk puts checks received from customers into the cash register area.")],
    445: [("D", "typical_location", "Performers on a platform in public may appear in a concert hall.")],
    446: [("A", "typical_location", "An old box of clothes and holiday decorations is often found in the attic.")],
    447: [("C", "property", "A yard is likely to be tiny in a city.")],
    448: [("A", "property", "Love felt by everyone can be described as contagious.")],
    449: [("A", "typical_location", "Balloons are a staple decoration at a birthday party.")],
    450: [("B", "typical_location", "Potatoes bought at a store are carried home in a grocery bag.")],
    451: [("A", "typical_location", "A paper program is commonly found at a theater.")],
    452: [("C", "typical_location", "Bouncing a ball against a wall target indoors suggests a playroom.")],
    453: [("D", "primary_function", "An artist can commemorate a horse forever with a painting.")],
    454: [("C", "typical_location", "Almost all people live on the surface of Earth.")],
    455: [("C", "property", "A human is a living thing that has lips.")],
    456: [("E", "motivation", "Before going to a party, one may meet new people.")],
    457: [("D", "property", "Yellow is associated with cowardice, the opposite of being brave.")],
    458: [("E", "primary_function", "Instituting civil action is another way of describing protests.")],
    459: [("D", "effect", "A celebrated occasion is commonly described with happiness.")],
    460: [("E", "typical_location", "A crate of shampoo delivered in bulk is used heavily at a hair salon.")],
    461: [("B", "typical_location", "Georgia is a state where one can find balls of cotton.")],
    462: [("A", "typical_location", "Without containers, a rosebush is planted directly in a flower garden.")],
    463: [("E", "typical_location", "Large pieces of paper not for sale may be found in an artist's studio.")],
    464: [("B", "effect", "Pushing a relationship further might destroy something good.")],
    465: [("C", "primary_function", "Brakes to help stop are important when driving fast and approaching a light.")],
    466: [("D", "typical_location", "A level for hanging a shelf can be obtained at a carpenter's shop.")],
    467: [("D", "effect", "Professionals may be unable to compete because of injuries.")],
    468: [("B", "typical_location", "A clarinet concerto is most likely performed with an orchestra.")],
    469: [("B", "effect", "When a newborn opens its eyes for the first time, it sees light.")],
    470: [("C", "typical_location", "In a town, a shed is commonly placed in the backyard.")],
    471: [("B", "property", "Rubber balls at rest in the morning are put in motion again to play.")],
    472: [("C", "primary_function", "A cat normally communicates by saying meow.")],
    473: [("A", "typical_location", "People find bills alongside bread at a restaurant.")],
    474: [("B", "typical_location", "An atlas made of paper helps one find the way while traveling on a highway.")],
    475: [("A", "motivation", "Someone comfortable at home may have a crippling fear of going outside.")],
    476: [("E", "typical_location", "A native lemur is found in the rain forest.")],
    477: [("C", "typical_location", "One can eat fruit on the red Golden Gate Bridge in San Francisco.")],
    478: [("D", "typical_location", "Head wear in an entrance hall is kept on a hat rack.")],
    479: [("D", "typical_location", "An RV driver needing electricity to cook may plug in at a rest area.")],
    480: [("B", "typical_location", "Turkey as a nation is located in Asia Minor.")],
    481: [("A", "effect", "A surprising and unexpected joke makes people happy.")],
    482: [("E", "typical_location", "New Mexico is an English-speaking place to see a lizard in its natural habitat.")],
    483: [("A", "property", "Carrying jewelry in a suitcase is not a safe way to transport it on vacation.")],
    484: [("B", "motivation", "To end a fight over money, Johnny might choose to settle everything.")],
    485: [("A", "effect", "Spending three hours grooming each morning may lead to tardiness at work.")],
    486: [("D", "property", "Finding a second heart in a chest means the patient might not be a human being.")],
    487: [("D", "effect", "A surprise attack can end a cease fire.")],
    488: [("E", "typical_location", "Ireland is a European country famous for its potato industry.")],
    489: [("C", "effect", "Dancing for a long time leads to fatigue.")],
    490: [("A", "typical_location", "Most people keep a curling iron stored in the bathroom.")],
    491: [("A", "typical_location", "A shore that was once a bustling fishing industry is part of a seaside town.")],
    492: [("D", "effect", "After becoming inebriated, a person's speech may devolve into talking nonsense.")],
    493: [("E", "effect", "Something new helps get rid of a mundane routine.")],
    494: [("A", "primary_function", "A master carpenter uses a drill to put holes in objects.")],
    495: [("C", "effect", "Falling from a mountain can lead to death.")],
    496: [("C", "cause", "Deafness is a reason someone might not listen to music.")],
    497: [("B", "effect", "Extreme tiredness, shaking, and pain suggest suffering from fatigue.")],
    498: [("C", "typical_location", "Moistener such as hand lotion is sold at a drug store.")],
    499: [("C", "typical_location", "A saucepan used only for marinara is kept in a kitchen cupboard.")],
    500: [("E", "primary_function", "Vegetarians eat plants more often than meat eaters do.")],
    501: [("C", "property", "A movie with many songs and dances is a musical.")],
    502: [("C", "effect", "A student having fun singing in front of class shows a lot of glee.")],
    503: [("C", "typical_location", "A system of electronic devices is used in computer science classes at school.")],
    504: [("B", "primary_function", "Humans reproduce by having sex.")],
    505: [("E", "property", "A judge may tell a convicted murderer that he is pure evil.")],
    506: [("E", "primary_function", "Changing society through violent conflict is known as a revolution.")],
    507: [("A", "property", "After New Coke was discontinued, the original formula was used again.")],
    508: [("A", "typical_location", "A monkey in the rainforest is likely found in the tree tops.")],
    509: [("E", "typical_location", "A college donation for science commonly funds a new science building.")],
    510: [("B", "primary_function", "Humans take in oxygen while breathing.")],
    511: [("C", "property", "Someone who wishes another to fail feels antipathy toward them.")],
    512: [("A", "effect", "Reckless driving can lead to injuries for a person.")],
    513: [("A", "typical_location", "Containers of goods are unloaded at a port after a long sea journey.")],
    514: [("C", "typical_location", "A lion is likely to live on the savannah.")],
    515: [("B", "typical_location", "Rollercoasters and ferris wheels are found at fairgrounds.")],
    516: [("D", "typical_location", "A ferret getting lots of attention is likely at a petting zoo.")],
    517: [("E", "effect", "Confirming a reference fails if the reference refuses to cooperate.")],
    518: [("B", "primary_function", "Raising a drink and cheering together is called toasting.")],
    519: [("C", "primary_function", "Someone watching a person play guitar is listening to music.")],
}
