# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 9520-9619 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_9520_9619 = {
    9520: [("E", "motivation", "People who try new things commonly want to experience life.")],
    9521: [("A", "effect", "When domestic violence becomes known, a neighborhood often responds with public outcry.")],
    9522: [("E", "typical_location", "Fungus commonly grows in damp caves and other underground geological features.")],
    9523: [("D", "typical_location", "A large block of salt is commonly stored in a kitchen cupboard among cooking supplies.")],
    9524: [("D", "typical_location", "A t-shirt is commonly kept in a closet with other clothing.")],
    9525: [("C", "part_whole", "Secondary items typically follow the main item on a list.")],
    9526: [("D", "typical_location", "The Space Needle is a landmark tower with restaurants located in Seattle.")],
    9527: [("D", "typical_location", "Tabby cats are domesticated cats that usually live at home with people.")],
    9528: [("D", "effect", "Smoking commonly causes bad breath that can ruin an intimate moment like a first kiss.")],
    9529: [("B", "typical_location", "New York City is famous for towering skyscrapers and grand buildings that inspire awe.")],
    9530: [("B", "typical_location", "An exposed catwalk five stories up with required helmets and harnesses describes a construction site.")],
    9531: [("B", "used_for", "Doctors often emotionally distance themselves to cope with patient suffering and death.")],
    9532: [("A", "motivation", "Writers who love nature often express it by writing poems about the natural world.")],
    9533: [("E", "effect", "Children who leave home in clean clothes commonly get dirty while playing outdoors.")],
    9534: [("C", "effect", "Buying alcohol for minors is illegal and can result in arrest.")],
    9535: [("A", "part_whole", "A loose window often means the windowsill needs frequent repainting from weather exposure.")],
    9536: [("A", "used_for", "Yeast is added to bread dough to make it rise during baking.")],
    9537: [("B", "effect", "A person with a tumor may die of cancer if the condition is not successfully treated.")],
    9538: [("B", "typical_location", "Michigan is nicknamed the Great Lake State and is shaped somewhat like a mitten or glove.")],
    9539: [("E", "typical_location", "Bank statements commonly arrive at a person's house through the mail.")],
    9540: [("C", "used_for", "A vacuum baggie removes air from around food to help keep it fresh longer.")],
    9541: [("B", "typical_location", "Helium balloons with no visible support appear to float overhead in the sky.")],
    9542: [("C", "effect", "When someone is no longer living, they have died.")],
    9543: [("A", "used_for", "A person in a dirty kitchen commonly washes dishes to clean it up.")],
    9544: [("A", "typical_location", "A big match with ticketed spectators takes place at a football stadium.")],
    9545: [("E", "effect", "Stabbing someone to death leaves behind a gruesome mess at the scene.")],
    9546: [("A", "effect", "A reaching advantage at the finish line commonly leads to victory in a race.")],
    9547: [("C", "property", "A hurricane is a large rotating wind storm similar in nature to tornadoes.")],
    9548: [("A", "used_for", "Clear tape on glasses is meant to repair them without obscuring the wearer's field of vision.")],
    9549: [("B", "typical_location", "A person standing next to a net is commonly seen at a soccer game by the goal.")],
    9550: [("C", "effect", "After an accident, a judge may rule that the injured party receives money as compensation.")],
    9551: [("D", "typical_location", "A mall offers many types of goods from different stores in one location.")],
    9552: [("B", "typical_location", "A building commonly has a large entrance door to admit people and goods.")],
    9553: [("D", "typical_location", "A mother commonly puts a stray toy ball in the toy box where children can easily find it.")],
    9554: [("C", "property", "Someone not allowed in when capacity is full is unfortunately a reject.")],
    9555: [("E", "effect", "Someone who enjoys answering questions may feel sadness when all the questioners go home.")],
    9556: [("D", "used_for", "Someone trying to ruin a parade might construct a barrier in the middle of the street.")],
    9557: [("E", "typical_location", "Excavation workers in hot, dry landscapes like deserts need extra care to stay hydrated.")],
    9558: [("B", "typical_location", "A researcher who cuts a hand commonly washes it at a sink in a chemistry lab.")],
    9559: [("A", "primary_function", "Ice is commonly used to cool water and drinks.")],
    9560: [("A", "effect", "Getting very drunk commonly leads to vomiting and making a mess with bodily fluids.")],
    9561: [("D", "typical_location", "A pie is commonly stored in a refrigerator to keep it fresh.")],
    9562: [("A", "typical_location", "Cars are parked in a parking lot.")],
    9563: [("E", "used_for", "Many people at festivals enjoy listening to live music.")],
    9564: [("C", "typical_location", "A bookstore typically has endless shelves filled with books.")],
    9565: [("A", "typical_location", "The De Soto Bridge crosses the Mississippi near Memphis, Tennessee, about an hour from Jackson.")],
    9566: [("D", "property", "When cold air makes your breath visible, it appears as mist or vapor.")],
    9567: [("B", "capability", "Computers in an office are often useless for collaborative work if they are not networked.")],
    9568: [("C", "typical_location", "A bed is placed on the floor of a bedroom in a new house.")],
    9569: [("C", "effect", "People sometimes fight each other over a good deal to secure it for themselves.")],
    9570: [("A", "used_for", "A spider builds a web to trap and capture its prey.")],
    9571: [("B", "typical_location", "A beauty parlor is commonly found in a city among other businesses.")],
    9572: [("B", "effect", "Someone who commits suicide would die.")],
    9573: [("E", "typical_location", "Birth control pills are available at a pharmacy with a prescription.")],
    9574: [("A", "effect", "Rambunctious children may break things while playing roughly.")],
    9575: [("C", "has_prerequisite", "Growing grapes in a vineyard requires plenty of sunshine.")],
    9576: [("A", "typical_location", "A student ID would not grant admission to a bar that restricts entry by age.")],
    9577: [("D", "typical_location", "A potato and other recipe ingredients can be bought at a food market.")],
    9578: [("C", "used_for", "Soldiers may call reinforcements when opponents gain the upper hand in battle.")],
    9579: [("E", "typical_location", "A dress shirt is commonly kept in a closet with other formal wear.")],
    9580: [("E", "typical_location", "Programs seen by millions of people are commonly broadcast on television.")],
    9581: [("D", "typical_location", "A keg holds gallons of beer in a single large container.")],
    9582: [("A", "typical_location", "Many zoo monkeys come from natural rainforest habitats unlike their enclosures.")],
    9583: [("A", "typical_location", "Someone crossing the country with online tickets might drive to a train station.")],
    9584: [("B", "property", "Joy as a name pairs with sadness as its emotional opposite for a husband's name.")],
    9585: [("C", "property", "A billionaire's personal entertainment venue that accommodates many people is a large building.")],
    9586: [("E", "typical_location", "Dinosaur bones are commonly displayed in a museum.")],
    9587: [("B", "part_whole", "A garage is a type of building attached to or near a home.")],
    9588: [("B", "typical_location", "A walkout basement accessed from a back courtyard is typically attached to a large house.")],
    9589: [("D", "used_for", "Bored young people commonly play outside for recreation.")],
    9590: [("C", "used_for", "An atlas or road map helps someone find their way on a turnpike without GPS.")],
    9591: [("B", "typical_location", "If you lose track of a pet monkey at home, a friend's house is a nearby place it might have gone.")],
    9592: [("A", "cause", "People close a door to keep unwanted people out of a room.")],
    9593: [("E", "typical_location", "People commonly run along a hallway floor to move between rooms.")],
    9594: [("E", "typical_location", "After shopping at the mall, people commonly take new clothing home to their house.")],
    9595: [("D", "typical_location", "Locker rooms at a stadium are frequently visited by reporters covering sports teams.")],
    9596: [("B", "used_for", "The piano lets people sit while expressing themselves artistically through music.")],
    9597: [("E", "property", "Some people believe there is no inherent conflict between religion and science.")],
    9598: [("C", "effect", "Couples who disagree while planning a vacation may end up in arguments.")],
    9599: [("B", "used_for", "To tell many people something, you need to speak so they can hear you.")],
    9600: [("A", "property", "Because humans are not immortal, people should expect to die someday.")],
    9601: [("D", "typical_location", "Travelers planning intercontinental trips are commonly found at an airport.")],
    9602: [("A", "typical_location", "A liquor store sells beer and wine in addition to spirits.")],
    9603: [("B", "capability", "A computer with an audio card can produce sound through speakers or headphones.")],
    9604: [("C", "typical_location", "A complex computer system can be purchased at a computer store.")],
    9605: [("C", "part_whole", "All the women in an office might collectively file a complaint against a crass male coworker.")],
    9606: [("B", "typical_location", "Spiders are often found in a house cellar where it is dark and undisturbed.")],
    9607: [("E", "motivation", "Someone who signs up for a dating website is commonly looking for a good relationship.")],
    9608: [("E", "cause", "Nuclear weapons can cause mass death on a catastrophic scale.")],
    9609: [("D", "used_for", "Collectivist people tend to share things rather than prioritize individual ownership.")],
    9610: [("A", "typical_location", "Flowers grow all over the surface of the earth in many climates and regions.")],
    9611: [("E", "typical_location", "A student who plays tennis frequently may use the tennis court on a college campus.")],
    9612: [("B", "property", "Food described as hot is by definition not cold at the moment it is served.")],
    9613: [("B", "motivation", "Exercise helps an overweight person get in shape and improve health.")],
    9614: [("D", "effect", "Listening to music and taking a cool bath after a hard day commonly makes a person feel better.")],
    9615: [("C", "effect", "A stressed-out mother often finds a baby cutest when it sleeps soundly and is peaceful.")],
    9616: [("C", "typical_location", "Driftwood accumulates in large quantities along beaches where waves deposit washed-up wood.")],
    9617: [("E", "used_for", "A soccer game is played by kicking a black-and-white patterned ball with the feet.")],
    9618: [("A", "effect", "Seasickness is a common side effect of traveling on the water.")],
    9619: [("D", "typical_location", "People attend a conference annually to review offered programs and presentations.")],
}
