# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 9120-9219 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_9120_9219 = {
    9120: [("C", "typical_location", "A personal ficus tree is commonly kept in one's own home as a houseplant.")],
    9121: [("E", "used_for", "A lawyer handling marriage proposals helps a couple prepare to get married.")],
    9122: [("E", "motivation", "People on vacation commonly seek relaxation from everyday routines.")],
    9123: [("E", "property", "Compared with nature, living in a city often feels artificial and man-made.")],
    9124: [("B", "effect", "When someone wakes but is not yet ready to get up, they often yawn.")],
    9125: [("D", "motivation", "Many people prefer simplicity in life over a hectic mess.")],
    9126: [("C", "used_for", "Newspaper laid on the floor can temporarily take the place of a rug.")],
    9127: [("A", "effect", "A hoarse voice makes it difficult or impossible to sing normally.")],
    9128: [("A", "typical_location", "Emergency dental office services are commonly found at a hospital.")],
    9129: [("D", "typical_location", "A department store commonly sells both children's clothing and televisions.")],
    9130: [("B", "typical_location", "Louisiana is a southern delta state where foxes may be seen.")],
    9131: [("D", "typical_location", "People commonly procure magazines and other items at a market.")],
    9132: [("D", "effect", "Seeing the desired results of housework commonly leaves a person feeling satisfied.")],
    9133: [("D", "used_for", "To get a drink for yourself, you normally take out a cup.")],
    9134: [("B", "effect", "If someone commits murder, their victim would be dying.")],
    9135: [("E", "typical_location", "Seeing skyscrapers outside a hotel window indicates you are in a city.")],
    9136: [("E", "effect", "Getting only a small taste of something often leaves you wanting more.")],
    9137: [("A", "typical_location", "An American hiking north would eventually reach Canada.")],
    9138: [("A", "effect", "A fan who meets their idol might go crazy with excitement.")],
    9139: [("E", "used_for", "To comfort a friend, someone might give them a big hug.")],
    9140: [("D", "typical_location", "Treasure in pirate lore is often hidden on a single body of water.")],
    9141: [("E", "primary_function", "A telescope with a lens is used to see distant stars and planets.")],
    9142: [("C", "typical_location", "When candy is gone, people go to a store to pick up more.")],
    9143: [("A", "typical_location", "A phone bill is commonly delivered through a mail slot.")],
    9144: [("D", "effect", "In Texas, stabbing someone to death can lead to capital punishment.")],
    9145: [("A", "motivation", "Someone driven by greed hoping for quick money might try gambling such as playing poker.")],
    9146: [("C", "motivation", "The Bible teaches that people should care for one another.")],
    9147: [("C", "effect", "Someone can feel happy about an accident when they were not harmed.")],
    9148: [("D", "effect", "A driver with an open sunroof during a rainstorm is likely to get wet.")],
    9149: [("B", "used_for", "A soldier who rose through the ranks may ultimately lead troops to fight the enemy.")],
    9150: [("E", "capability", "Online videos commonly allow viewers to fast forward through advertisements.")],
    9151: [("D", "cause", "Playing sports causes the body to lose water through sweating.")],
    9152: [("B", "used_for", "People often wait in line to acquire items they desire at a store.")],
    9153: [("A", "has_prerequisite", "Washing clothes in a washer requires adding soap.")],
    9154: [("E", "typical_location", "Items made of fabric that adorn the body are found at a clothing store.")],
    9155: [("E", "effect", "Seeing one's idea become reality commonly fills a person with pride.")],
    9156: [("C", "cause", "Fear while skating often comes from worrying you might fall.")],
    9157: [("E", "typical_location", "A zoo is an animal park among other attractions.")],
    9158: [("A", "typical_location", "Popular books are commonly sold at a shopping center rather than a specialty bookshop.")],
    9159: [("C", "typical_location", "A map you plan to use soon is conveniently kept in a backpack.")],
    9160: [("C", "typical_location", "An electric razor is often stored in a medicine cabinet to keep it dry.")],
    9161: [("D", "typical_location", "Bats commonly live inside dark caves.")],
    9162: [("D", "used_for", "People watch documentaries to learn information about lizards.")],
    9163: [("E", "typical_location", "A monkey jumping in trees never leaves the treetops.")],
    9164: [("C", "effect", "Ending a marriage to someone you no longer love may bring relief.")],
    9165: [("E", "used_for", "Companies inform clients about upcoming deals and offers by mail.")],
    9166: [("A", "typical_location", "A bass fish might move closer in a river.")],
    9167: [("E", "has_prerequisite", "To wage war, a leader must first raise armies.")],
    9168: [("B", "used_for", "After enjoying a show, people show appreciation by clapping.")],
    9169: [("A", "motivation", "People go to bed in order to get rest.")],
    9170: [("D", "typical_location", "Nurses work with older people at a nursing home.")],
    9171: [("E", "typical_location", "Bacteria are commonly contained in a petri dish for study.")],
    9172: [("A", "has_prerequisite", "To read a book, you must first open it up.")],
    9173: [("A", "typical_location", "A small dog might spend a nice day in a backyard.")],
    9174: [("C", "effect", "Understanding a subject better commonly leads to increased knowledge.")],
    9175: [("D", "property", "After a hard negotiation, both sides may find an agreeable solution.")],
    9176: [("E", "part_whole", "The middle of a trip comes after the beginning.")],
    9177: [("B", "effect", "When a punctual friend fails to show up, the waiting person may begin to panic.")],
    9178: [("D", "effect", "Someone who hurts others without regret may face punishment.")],
    9179: [("B", "typical_location", "A large city is the most likely place to have more than one stadium.")],
    9180: [("B", "used_for", "Someone without respect for another may speak to them with disparagement.")],
    9181: [("C", "typical_location", "A deli seeking high traffic might open in a shopping center.")],
    9182: [("B", "capability", "Children can jump rope outside but not in a small room.")],
    9183: [("C", "effect", "Some believe eating a heavy meal before sleep causes nightmares.")],
    9184: [("C", "part_whole", "Alaska has more coastline than any other state in the United States.")],
    9185: [("D", "typical_location", "The Everglades is a large marsh in Florida.")],
    9186: [("A", "property", "Someone who is underage is not legally allowed to buy alcohol.")],
    9187: [("E", "typical_location", "A ficus is protected from rain when kept inside a home.")],
    9188: [("B", "typical_location", "A veterinarian commonly sees blood coming from animals.")],
    9189: [("C", "effect", "Driving a car for a long time commonly causes tire wear.")],
    9190: [("B", "typical_location", "A new chess set can be purchased at a toy store.")],
    9191: [("A", "used_for", "Children often sing to express happiness.")],
    9192: [("B", "part_whole", "The helm on a tugboat is used to steer it as it pulls barges.")],
    9193: [("E", "typical_location", "A grocery store sells snacks, cake, and sometimes balloons.")],
    9194: [("D", "effect", "After getting drunk the night before, someone may experience forgetfulness the next morning.")],
    9195: [("B", "effect", "A negative external consequence of taking part in a killing is being imprisoned.")],
    9196: [("B", "capability", "Canadian players are commonly known for puck hitting in hockey.")],
    9197: [("A", "motivation", "A cold snake seeks a warm place.")],
    9198: [("D", "effect", "People who sneeze often also cough.")],
    9199: [("C", "capability", "Musicians who cannot learn others' pieces often cannot read music.")],
    9200: [("E", "used_for", "Finishing a test while watching the clock frantically means racing against time.")],
    9201: [("B", "typical_location", "Getting in a fight after drinking may land someone in jail.")],
    9202: [("E", "effect", "Unexpectedly discovering the truth may startle a person.")],
    9203: [("A", "effect", "People with no contact with others commonly feel lonely.")],
    9204: [("A", "cause", "Someone afraid of falling asleep may refuse to sit down.")],
    9205: [("A", "motivation", "When bored with life, a person might try all kinds of things.")],
    9206: [("B", "capability", "Learning needlepoint is a goal competency related to sewing.")],
    9207: [("B", "used_for", "A construction foreman who supervises others spends the day watching work.")],
    9208: [("D", "capability", "A person might drive a car to go somewhere.")],
    9209: [("A", "property", "A super ball is a popular toy that children enjoy.")],
    9210: [("B", "part_whole", "An island is a piece of land surrounded by a body of water.")],
    9211: [("D", "effect", "A toddler trying breakfast in bed commonly creates a mess.")],
    9212: [("D", "used_for", "Someone learning to socialize may call a friend asking for input.")],
    9213: [("C", "typical_location", "Personal books are commonly found on a shelf.")],
    9214: [("A", "effect", "A sleigh ride commonly goes only one way: downhill.")],
    9215: [("C", "typical_location", "Balls and bats are sold at a sporting goods store.")],
    9216: [("C", "effect", "Going to bed helps someone fall asleep.")],
    9217: [("E", "typical_location", "Couples looking to adopt commonly review profiles of orphans.")],
    9218: [("A", "motivation", "People groom before a party in order to look pretty.")],
    9219: [("E", "used_for", "Before lighting a log, crumpled paper is often used as kindling to start a fire.")],
}
