# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 5620-5719 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_5620_5719 = {
    5620: [("E", "typical_location", "A bookstore invites customers to spend time reading and browsing books.")],
    5621: [("E", "typical_location", "A bored student in class often stares at the ceiling.")],
    5622: [("C", "typical_location", "Prepared mushrooms are commonly purchased at a grocery store.")],
    5623: [("A", "typical_location", "A bear may take trash from a dumpster while foraging.")],
    5624: [("D", "typical_location", "A severed gazelle head displayed indoors suggests a trophy room.")],
    5625: [("A", "used_for", "Someone with a great love of music often sings in the car.")],
    5626: [("A", "effect", "A formerly lonely man chatting with friends for hours would feel happiness.")],
    5627: [("A", "typical_location", "A fluffy comfortable chair is commonly found in a living room.")],
    5628: [("E", "effect", "Starting a fire near oxygen can cause an explosion.")],
    5629: [("B", "effect", "After killing an animal, the animal would be in the process of dying.")],
    5630: [("C", "typical_location", "Trash is emptied from a dumpster on a regular schedule.")],
    5631: [("A", "property", "Someone whose attitudes are regressive might be described as backward.")],
    5632: [("D", "typical_location", "People store their cars in a parking lot while running errands.")],
    5633: [("B", "typical_location", "A large quantity of steel pens would be stored in a warehouse.")],
    5634: [("A", "property", "Teachers explaining when mammoths lived may use the term Pleistocene.")],
    5635: [("E", "used_for", "The yellow pages is where people commonly look up business hours.")],
    5636: [("C", "typical_location", "A back courtyard is a common feature of houses in suburbs.")],
    5637: [("E", "typical_location", "Beef cattle are commonly raised on a ranch in the countryside.")],
    5638: [("A", "effect", "Bringing a lawsuit against someone is likely to increase tensions between the parties.")],
    5639: [("D", "effect", "Getting a birthday gift you wanted commonly causes a person to feel happy.")],
    5640: [("C", "cause", "Arthritis can debilitate a person and make activities like playing chess painful.")],
    5641: [("D", "property", "Glass walls let more light into a room because glass is clear.")],
    5642: [("C", "effect", "An overcast sky tends to make colors appear dull rather than vibrant.")],
    5643: [("E", "has_prerequisite", "A prisoner of war who treasures freedom would try to escape from captivity.")],
    5644: [("A", "part_whole", "Fish use gills to aid in oxygen exchange in water.")],
    5645: [("C", "effect", "After procreating, some people struggle with added responsibilities and seek government help.")],
    5646: [("A", "typical_location", "A company-sponsored business trip may place workers in a hotel room near a convention center.")],
    5647: [("D", "part_whole", "An entrance hall used by a single family is commonly found in a house.")],
    5648: [("C", "typical_location", "Cookies for arriving guests are commonly arranged on a plate.")],
    5649: [("E", "motivation", "A mistake that was not an accident was made on purpose.")],
    5650: [("E", "used_for", "Typing requires a person to press keys on a keyboard.")],
    5651: [("B", "part_whole", "Human nerves are found throughout a person's body.")],
    5652: [("D", "property", "A human contemplating something is in a state of deep thought.")],
    5653: [("A", "used_for", "People commonly swim in waters where jellyfish live.")],
    5654: [("A", "typical_location", "Toothpaste is most likely to be found in the bathroom.")],
    5655: [("C", "typical_location", "A coffee shop often offers free refills on the first cup of hot brew.")],
    5656: [("E", "typical_location", "People who use a puck for a living work at a hockey rink.")],
    5657: [("C", "typical_location", "After sealing a box and writing an address, a person takes it to the post office.")],
    5658: [("B", "property", "Someone who never stopped talking would talk at a constantly high rate.")],
    5659: [("C", "typical_location", "Young people commonly read about weasels in children's stories.")],
    5660: [("C", "used_for", "Vinegar is often spritzed on salad as a lighter alternative to adding more salt.")],
    5661: [("E", "typical_location", "Lizards commonly climb up rock walls and similar rough vertical surfaces.")],
    5662: [("E", "typical_location", "After picking food to buy in a store, people go to the end of the line to pay.")],
    5663: [("A", "effect", "Children playing in the rain are getting wet and will need their clothes washed again.")],
    5664: [("D", "typical_location", "An amusement park map often shows locations that can only be reached on foot.")],
    5665: [("E", "typical_location", "A marching band member plays a trumpet while walking the entire time.")],
    5666: [("B", "effect", "After getting drunk, people often cannot be understood because of slurred speech.")],
    5667: [("B", "effect", "Jumping rope is aerobic exercise that can cause sweating in the upper body.")],
    5668: [("A", "effect", "People commonly feel anxious when they see large guard dogs.")],
    5669: [("C", "effect", "Dreaming scary things is likely to lead to waking up with a sense of fear.")],
    5670: [("D", "effect", "A negative effect of creating art can be generating controversy.")],
    5671: [("D", "part_whole", "A board game with chance spaces may also include community chest spaces.")],
    5672: [("E", "property", "When someone does not have beauty, they may be described as having ugliness.")],
    5673: [("C", "used_for", "A string quartet uses classical stringed instruments in performance.")],
    5674: [("B", "has_prerequisite", "To listen to a movie, a person needs to pay attention to the audio.")],
    5675: [("B", "effect", "A mother getting a whole new house to decorate would likely feel excitement.")],
    5676: [("A", "typical_location", "Most banks in a town are commonly located on main street.")],
    5677: [("B", "effect", "If you yell when a person starts to go in another direction, they are likely to turn around.")],
    5678: [("C", "typical_location", "A mixer working with a band commonly operates in a recording studio.")],
    5679: [("B", "effect", "If someone is not playing basketball carefully, they could suffer a knee injury.")],
    5680: [("B", "typical_location", "The Library of Congress in Washington D.C. holds a vast collection of books.")],
    5681: [("C", "effect", "Doing housework is hard and can lead to exhaustion.")],
    5682: [("B", "capability", "Most birds have the ability to fly.")],
    5683: [("E", "property", "A lawyer might explain committing perjury as simply telling lies under oath.")],
    5684: [("C", "property", "An atheist might respond that after dying a person no longer exists.")],
    5685: [("A", "effect", "After an extended amount of living, a person is getting old.")],
    5686: [("B", "motivation", "A child commonly dreads fall because it means having to go to school.")],
    5687: [("D", "typical_location", "Cow farms tend to be located in a remote rural area due to their strong smell.")],
    5688: [("B", "primary_function", "Someone starts playing guitar in order to make music.")],
    5689: [("A", "property", "A hand is a body part at the end of an arm.")],
    5690: [("A", "motivation", "To accomplish something in a short amount of time, you would make haste.")],
    5691: [("A", "used_for", "When two people feel attraction to each other, they often flirt first.")],
    5692: [("C", "typical_location", "A child stuck in the middle seat never gets the window of a bench seat.")],
    5693: [("C", "typical_location", "Red Lobster restaurants across the U.S. sell crab, shrimp, and fish dinners.")],
    5694: [("E", "effect", "The likely end of bringing a lawsuit is receiving a ruling from the court.")],
    5695: [("B", "typical_location", "You are unlikely to see clouds inside of a house.")],
    5696: [("B", "typical_location", "A freeway with signs in miles instead of kilometers is likely located in America.")],
    5697: [("A", "effect", "After a ten hour interrogation, a person would be getting tired.")],
    5698: [("C", "typical_location", "A musician would go to a music store to buy a replacement cymbal before practice.")],
    5699: [("D", "has_prerequisite", "James did not wear his suit when he heard he was going to court.")],
    5700: [("C", "typical_location", "You can get a needle for a routine checkup at a doctor's office.")],
    5701: [("B", "typical_location", "A bald eagle nest in a tree surrounded by others sits in a vast forest.")],
    5702: [("C", "part_whole", "The core and seeds inside are often left behind after eating an apple.")],
    5703: [("C", "used_for", "When you just met someone, you might say hello to greet them.")],
    5704: [("B", "typical_location", "You can buy eggs along with many other types of food at a supermarket.")],
    5705: [("A", "capability", "A person skilled at expressing thoughts may still need to study literature formally.")],
    5706: [("B", "property", "The opposite of an odd number is an even number.")],
    5707: [("D", "typical_location", "A stick a dog brings from a small nearby area was likely from the yard.")],
    5708: [("A", "typical_location", "An old newspaper is likely to be found in a library archive.")],
    5709: [("A", "typical_location", "Travellers can pull off the road at a rest area to stretch their legs.")],
    5710: [("C", "typical_location", "A person described as a weasel tends to work at a used car lot.")],
    5711: [("B", "motivation", "A person's main goal when learning about a subject is to gain knowledge.")],
    5712: [("C", "part_whole", "A wall is usually positioned next to a door in a building.")],
    5713: [("E", "cause", "A fish might avoid a boat for safety from fishermen and propellers.")],
    5714: [("C", "has_prerequisite", "City zoning may require a neighborhood barbershop to be in a commercial area.")],
    5715: [("E", "typical_location", "If he left camp following the river down below, his partner remained above.")],
    5716: [("A", "property", "Someone who is killing another person would be committing a crime.")],
    5717: [("A", "typical_location", "A supermarket is a place where you could go to spend money on goods.")],
    5718: [("D", "used_for", "Executives walking through a lobby talking strategy are likely discussing a business plan.")],
    5719: [("B", "typical_location", "The last place food is before being eaten is commonly on a plate.")],
}
