# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 9620-9719 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_9620_9719 = {
    9620: [("D", "typical_location", "New Jersey is known for toll roads on its highways and interstates.")],
    9621: [("A", "property", "Someone without work is described as unemployed.")],
    9622: [("C", "typical_location", "An astronaut in orbit around Earth can see virtually anywhere on the planet below.")],
    9623: [("C", "property", "Someone talking a lot and being lively is said to be blabbering.")],
    9624: [("E", "typical_location", "Broken glass is commonly found on beaches where bottles may have been discarded.")],
    9625: [("B", "property", "Eating too much can lead to obesity, which doctors commonly warn against.")],
    9626: [("B", "effect", "Digesting a meal can cause gas that leads to farting, affecting people nearby.")],
    9627: [("C", "capability", "Unlike humans, robots often cannot think and reason when faced with entirely new situations.")],
    9628: [("D", "effect", "Decades ago, unprotected sex among gay men carried a major risk of contracting AIDS.")],
    9629: [("B", "effect", "Drinking alcohol faster than the body can process it commonly causes a person to throw up.")],
    9630: [("A", "part_whole", "Lateral movement in tennis primarily works the muscles of the legs.")],
    9631: [("D", "used_for", "A cold snake will sun itself to absorb heat and warm its body.")],
    9632: [("B", "used_for", "Lying back is a common way to relax and unwind.")],
    9633: [("D", "typical_location", "Many people find peace and spiritual calm in a church.")],
    9634: [("A", "typical_location", "A garage typically contains tools and oil cans for car maintenance.")],
    9635: [("A", "cause", "Police commonly pull over drivers who are going too fast.")],
    9636: [("A", "property", "Movies are widely considered entertaining, which is why people watch them to escape.")],
    9637: [("A", "typical_location", "A satchel is commonly stored in a room at home when not in use.")],
    9638: [("C", "part_whole", "A house may have an iron in the laundry room but not in every other room.")],
    9639: [("B", "motivation", "When you love something, you typically want to get it.")],
    9640: [("C", "used_for", "Ignoring someone is a way of showing you do not respect or acknowledge them.")],
    9641: [("A", "part_whole", "Asia contains China, a country famous for its historical Great Wall.")],
    9642: [("E", "effect", "Over time, new ways of doing things gradually gain acceptance despite initial resistance.")],
    9643: [("C", "used_for", "People who remember leaving the oven on commonly hurry home to turn it off.")],
    9644: [("A", "typical_location", "Drug stores that specialize in prescriptions often charge higher prices on non-pharmacy goods.")],
    9645: [("D", "used_for", "In poker without blinds, players typically put in an ante before each hand.")],
    9646: [("D", "typical_location", "Kentucky, a state north of Alabama, has many rivers and streams where beavers live.")],
    9647: [("D", "typical_location", "Hospitals use lasers in medical procedures to alleviate suffering and treat patients.")],
    9648: [("A", "motivation", "Cars cost money to buy, maintain, and insure, which is why some people choose not to own one.")],
    9649: [("A", "used_for", "Many drivers sing along with their favorite music during a monotonous commute to work.")],
    9650: [("B", "effect", "Intimate physical contact commonly produces intense pleasure.")],
    9651: [("E", "typical_location", "Jellyfish in the warm Pacific Ocean stay in temperate tropical waters.")],
    9652: [("B", "typical_location", "Circuses are well known for featuring elephants that perform tricks.")],
    9653: [("E", "property", "Basketball rebounds are hard to predict because both the ball and rim are round.")],
    9654: [("B", "typical_location", "The beaver is a national symbol of Canada and is commonly associated with Ontario.")],
    9655: [("D", "typical_location", "A symphonic group commonly performs as part of a musical program lineup.")],
    9656: [("E", "typical_location", "A furniture store is where you can purchase a dining room table.")],
    9657: [("D", "effect", "Being tired can cause a person to snore while sleeping.")],
    9658: [("C", "effect", "Financial issues can lead to disagreements when a couple spends money on products.")],
    9659: [("B", "used_for", "If something was not fully destroyed, one might still be able to repair it afterward.")],
    9660: [("B", "typical_location", "Putting a furnace in an encampment would be highly unusual compared to a home basement.")],
    9661: [("D", "used_for", "A ring binder is commonly used to store and organize notebook pages.")],
    9662: [("B", "motivation", "Grooming requires careful consideration because people want to achieve neatness in their appearance.")],
    9663: [("B", "typical_location", "Most people put junk mail directly into the trash.")],
    9664: [("C", "typical_location", "Budget motels often have on-site dumpsters and limited housekeeping services.")],
    9665: [("B", "property", "A proper sentence must be grammatically complete and cannot be incomplete.")],
    9666: [("A", "has_prerequisite", "Before holding your breath, you typically inhale to fill your lungs with air.")],
    9667: [("B", "typical_location", "Providence is the capital of Rhode Island, where an apple tree would be planted nearby.")],
    9668: [("B", "effect", "Standing in line all day and having someone cut in front of you commonly causes agitation.")],
    9669: [("B", "typical_location", "Antique plates are commonly found for sale at a flea market.")],
    9670: [("D", "typical_location", "Humans and mammoths both lived during the Stone Age before mammoths went extinct.")],
    9671: [("A", "property", "Intoxication is another word for the state of getting drunk.")],
    9672: [("E", "used_for", "Dogs typically go outside to pee rather than urinating indoors.")],
    9673: [("A", "typical_location", "Highway rest areas provide public restrooms for travelers on the road.")],
    9674: [("B", "typical_location", "A city council meeting is a public event where a committee of elected officials conducts business.")],
    9675: [("D", "effect", "Having a good time while chatting with friends commonly brings happiness.")],
    9676: [("C", "property", "A bolt that does not fit a standard-sized tool likely has nonstandard threading or sizing.")],
    9677: [("A", "typical_location", "After landing at an airport, travelers can claim luggage and catch a bus nearby.")],
    9678: [("A", "part_whole", "A king's back courtyard is typically adjacent to or part of a palace.")],
    9679: [("C", "typical_location", "A toy store salesperson must be especially good at interacting with children.")],
    9680: [("B", "typical_location", "Pebbles on playground surfaces are commonly walked on by children and adults.")],
    9681: [("E", "effect", "After escaping a collapsed mine, a person may develop a fear of being trapped in enclosed spaces.")],
    9682: [("C", "typical_location", "Onions for cooking stew are commonly stored in the refrigerator or kitchen.")],
    9683: [("B", "property", "An atheist in a room full of religious people is sometimes ironically the most vocal about their views.")],
    9684: [("A", "property", "Television differs from radio primarily because it provides a visual component in addition to sound.")],
    9685: [("A", "effect", "Taking a corner at too high a velocity can cause a car to roll over.")],
    9686: [("E", "property", "Stockholders commonly review a company's earnings reports to assess how well it is performing.")],
    9687: [("D", "used_for", "When told something controversial, people typically form opinions about the issue.")],
    9688: [("D", "typical_location", "Parents gather at school cafeterias to watch children perform in the school band.")],
    9689: [("A", "typical_location", "People in large northeastern cities can find food at grocery stores and markets.")],
    9690: [("E", "motivation", "Many people hope to achieve orgasm as a primary goal during sex.")],
    9691: [("E", "has_prerequisite", "People typically go shopping for souvenirs while they are traveling.")],
    9692: [("D", "typical_location", "Resorts often offer specialty hair salons as amenities for their guests.")],
    9693: [("A", "typical_location", "A sloth climbs slowly but can eventually reach the forest canopy at the tops of trees.")],
    9694: [("E", "effect", "Learning about science helps a person become educated.")],
    9695: [("C", "typical_location", "Dos Equis is a Mexican beer, and Mexico lies south of the United States.")],
    9696: [("D", "effect", "When a singer's foot gets caught on a wire on stage, they may have a small stumble.")],
    9697: [("A", "effect", "Taking ibuprofen for a headache commonly makes a person feel relieved as the pain subsides.")],
    9698: [("C", "typical_location", "Montana is known as Big Sky Country and is home to beavers in its rivers and streams.")],
    9699: [("C", "property", "A loving couple typically provides the stable home environment that makes for the happiest child.")],
    9700: [("A", "effect", "When economic forces fail to match a changing society, it often leads to a change in leadership.")],
    9701: [("D", "motivation", "Someone who does not care about making friends or drinking at a party may simply want to have fun.")],
    9702: [("A", "effect", "Finishing stressful Christmas shopping commonly brings a sense of relief.")],
    9703: [("B", "effect", "Joining friends outside while they smoke exposes you to secondhand smoke, which is bad for your health.")],
    9704: [("A", "typical_location", "It is important to spend time in nature and sometimes get out of the city.")],
    9705: [("D", "effect", "Kissing can transmit oral herpes between partners.")],
    9706: [("D", "effect", "One's chest may swell with pride at the prospect of gaining more land or territory.")],
    9707: [("B", "effect", "Washing hands too frequently can strip natural oils and cause dry skin.")],
    9708: [("E", "typical_location", "After being used, a bowl is commonly placed in the dishwasher to be cleaned.")],
    9709: [("E", "effect", "Chatting with friends usually leaves people feeling relaxed.")],
    9710: [("D", "typical_location", "The history of a kingdom is commonly recorded and found in a book.")],
    9711: [("E", "typical_location", "Traveling an expressway toward the Atlantic Ocean from inland North America heads toward the eastern United States.")],
    9712: [("B", "used_for", "People in a band perform music for an audience.")],
    9713: [("D", "has_prerequisite", "To reach the sky, one must pass through the atmosphere.")],
    9714: [("E", "typical_location", "Travelers commonly stop at a gas station for a quick bite to eat before a long trip.")],
    9715: [("D", "typical_location", "A tourniquet is commonly kept in a first-aid or emergency kit.")],
    9716: [("B", "used_for", "Starting a fire is a practical method of getting warm when stranded naked in snow.")],
    9717: [("B", "typical_location", "Garlic bread is commonly served as a side during dinner.")],
    9718: [("A", "property", "Writing is a form of communication that conveys ideas through text.")],
    9719: [("D", "motivation", "Most people get up and live life because they feel they have no other choice.")],
}
