# -*- coding: utf-8 -*-
"""Early 1-fact rest KB for qids 8720-8819 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8720_8819 = {
    8720: [("C", "part_whole", "Flour is the main ingredient used to make bread dough.")],
    8721: [("E", "used_for", "A rowboat is a vessel used to move across the surface of water.")],
    8722: [("D", "effect", "Participating in sports such as fencing carries a risk of injury.")],
    8723: [("E", "property", "An afternoon of fun can seem to pass in a blink until it becomes evening.")],
    8724: [("C", "property", "People who reach the finals of a competition are participants in that event.")],
    8725: [("B", "typical_location", "Big cities with large populations commonly have many fast food restaurants.")],
    8726: [("D", "motivation", "On the first day of school students often want to meet friends.")],
    8727: [("B", "motivation", "Many people take up running as a way to pursue weight loss.")],
    8728: [("B", "typical_location", "Tupperware containers are commonly found in kitchens for food storage.")],
    8729: [("D", "typical_location", "The host of a meal commonly takes a seat at the head table.")],
    8730: [("D", "typical_location", "Holes made by burrowing animals are commonly found in the ground.")],
    8731: [("E", "typical_location", "A museum is a place with pictures where small dogs are typically not allowed.")],
    8732: [("C", "typical_location", "A conference often requires tables when many different thoughts need to be discussed.")],
    8733: [("C", "property", "Nearly every building is a structure that people enter through a doorway.")],
    8734: [("B", "typical_location", "Lights needed for an office are installed inside a building.")],
    8735: [("A", "property", "Ideas described as corporeal are physical, so their opposite seems intangible.")],
    8736: [("D", "effect", "Pets in the back of a van may get hurt during travel over rough roads.")],
    8737: [("D", "typical_location", "A fire extinguisher in a single-floor home is commonly kept in the kitchen.")],
    8738: [("B", "property", "Food that tastes good commonly makes someone want to eat more of it.")],
    8739: [("C", "typical_location", "Beavers are aquatic mammals commonly found at lakes and rivers.")],
    8740: [("E", "effect", "A serious car crash is an event that may cause someone to get rid of their car.")],
    8741: [("A", "used_for", "Eating cake is a well-known way for couples to celebrate a marriage.")],
    8742: [("B", "property", "Refreshment is another term for a drink meant to quench thirst.")],
    8743: [("A", "typical_location", "Boats that are not on the ocean commonly travel across the surface of a lake.")],
    8744: [("D", "effect", "Climbing a hill while hiking can deepen one's appreciation of the great outdoors.")],
    8745: [("D", "used_for", "Police may draw guns and park vehicles to create a roadblock blocking the only exit.")],
    8746: [("B", "has_prerequisite", "A library card must be renewed on a renewal form before it stops working.")],
    8747: [("A", "motivation", "Seeking more information about things in general is done to gain increased knowledge.")],
    8748: [("E", "typical_location", "Union membership is often required to advance in the construction business.")],
    8749: [("A", "property", "Bread that you make yourself is commonly fresher than store-bought bread.")],
    8750: [("C", "typical_location", "A marmoset that is not in the wild is likely to be at the zoo.")],
    8751: [("B", "used_for", "Members of ISIS are associated with practicing terrorism.")],
    8752: [("D", "typical_location", "New York on the East Coast is a city known for its pizzerias.")],
    8753: [("A", "motivation", "Weapons may be preserved because they could have use in the future.")],
    8754: [("B", "typical_location", "A canteen is a portable container used to carry a drink on a hike.")],
    8755: [("C", "typical_location", "A garage across the street from a house is located at a neighbor's house.")],
    8756: [("C", "effect", "Eating rotten food for breakfast in bed is likely to cause vomiting.")],
    8757: [("E", "used_for", "A concert hall can also be used as a theater for staged performances.")],
    8758: [("C", "typical_location", "A newly built banjo bound for retail sale is commonly sent to a music store.")],
    8759: [("A", "effect", "A child who cannot be trusted around food will eat food whenever it is available.")],
    8760: [("D", "typical_location", "A garage is a common place to store boxes of spare automobile parts.")],
    8761: [("A", "typical_location", "Cape Cod is a coastal region where catching crabs is relatively easy.")],
    8762: [("C", "effect", "No matter how life is lived, it commonly ends the same way with death.")],
    8763: [("B", "effect", "Traveling to a new time zone commonly causes jet lag.")],
    8764: [("D", "used_for", "Someone who uses hand sanitizer frequently may use hand lotion to moisturize dry skin.")],
    8765: [("E", "typical_location", "Temples in India may contain monks or priests with shaved heads.")],
    8766: [("B", "effect", "A person found guilty of committing murder is likely going to prison.")],
    8767: [("E", "property", "A student who never gets in trouble may receive a certificate for good behavior.")],
    8768: [("C", "typical_location", "New Mexico is a dry state where lizards can be found.")],
    8769: [("E", "has_prerequisite", "A doctor must study medicine before being allowed to take the exam for an MD.")],
    8770: [("B", "has_prerequisite", "The first person to arrive at work commonly needs a key to get in the door.")],
    8771: [("C", "typical_location", "A house in a normal residential location is commonly found in a subdivision.")],
    8772: [("B", "used_for", "Young adult friends commonly have fun by going out at night.")],
    8773: [("B", "used_for", "Someone told to stop fidgeting is expected to stay still.")],
    8774: [("B", "property", "An atheist who praises secular thought is likely opposing religious ideas.")],
    8775: [("C", "effect", "Surprising someone rather than prepping beforehand helps minimize what was planned.")],
    8776: [("D", "typical_location", "An encyclopedia is a reference work where one might enjoy reading about a sloth.")],
    8777: [("D", "has_prerequisite", "A doctor may tell a patient that medicine alone is not enough without a proper diet.")],
    8778: [("B", "used_for", "To make your voice heard by everyone you should speak loud.")],
    8779: [("E", "typical_location", "Cargo is commonly stored in a ship's hold during transport.")],
    8780: [("D", "effect", "Playing a game commonly results in having fun.")],
    8781: [("C", "property", "After treatment a patient who returns to work pain-free is completely painless.")],
    8782: [("D", "typical_location", "A container cup for kitchen use is commonly found in a kitchen cupboard.")],
    8783: [("C", "used_for", "People going somewhere beyond walking distance commonly take a car.")],
    8784: [("C", "effect", "Resting when you have other things to do can help you feel more energetic afterward.")],
    8785: [("C", "part_whole", "A person accused of murder must face prosecution in court.")],
    8786: [("E", "typical_location", "An expressway in a large city is likely to be crowded with traffic.")],
    8787: [("B", "typical_location", "A garden oasis in the middle of a wasteland is a striking sight to an explorer.")],
    8788: [("C", "typical_location", "A cat commonly sits on a window sill to soak up sunlight.")],
    8789: [("E", "used_for", "Calling a brother for money means finding yourself asking for money.")],
    8790: [("C", "typical_location", "New York City is a destination with many art galleries to visit in one trip.")],
    8791: [("A", "property", "Laser light that hurts the eyes can be described as forceful and intense.")],
    8792: [("E", "part_whole", "Cadets learning about a stock may disassemble and reassemble a machine gun.")],
    8793: [("E", "effect", "Drinking alcohol can cause forgetfulness that takes a long time to finish clearing.")],
    8794: [("E", "primary_function", "A windmill uses moving air to turn blades and provide power.")],
    8795: [("E", "typical_location", "A caught monkey is likely to live at least initially in a pet store.")],
    8796: [("C", "part_whole", "Hearing a bugle in the mornings suggests membership in a military band.")],
    8797: [("E", "effect", "Sadness commonly leads immediately afterward to crying.")],
    8798: [("D", "typical_location", "A farmer worried about foxes commonly makes the chicken coop fox proof.")],
    8799: [("A", "used_for", "A restaurant customer who is seated early is likely to order dinner next.")],
    8800: [("D", "effect", "Someone who hates killing people does not like seeing people die.")],
    8801: [("D", "typical_location", "A court is commonly located inside a public building.")],
    8802: [("A", "typical_location", "A king who needs to feel safe commonly retreats to a castle.")],
    8803: [("D", "typical_location", "Staying at a bar in Las Vegas can mean losing less money than drinking elsewhere.")],
    8804: [("B", "typical_location", "Someone unhappy with their hair commonly goes to a barber shop.")],
    8805: [("B", "typical_location", "A pot that is not needed for immediate use is commonly stored in a cupboard.")],
    8806: [("A", "effect", "Kissing outdoors when it starts to snow is likely to make you get cold.")],
    8807: [("A", "typical_location", "In the United States a monkey is likely to be found nearby in a research laboratory.")],
    8808: [("E", "part_whole", "The armed forces are an organization that contains a company of people.")],
    8809: [("B", "typical_location", "A towel mounted above a shower is commonly found in a gym.")],
    8810: [("D", "typical_location", "Folded clothes are best kept stored in a closet.")],
    8811: [("A", "capability", "People who lift a car by hand to save a child display extraordinary strength.")],
    8812: [("B", "capability", "Thinking for a long time requires the ability to concentrate.")],
    8813: [("C", "effect", "A snowman that is getting wet is likely to begin shrinking.")],
    8814: [("E", "used_for", "The purpose of a remote control is to use a television.")],
    8815: [("D", "typical_location", "The most famous cartoon mouse is associated with Disneyland.")],
    8816: [("B", "used_for", "Cooks who are almost finished cooking commonly season with salt.")],
    8817: [("D", "effect", "As things get colder the temperature is dropping quickly.")],
    8818: [("C", "part_whole", "Nature includes both living things such as a person and a jellyfish.")],
    8819: [("E", "effect", "A sudden burst of inspiration commonly makes someone grab pen and paper.")],
}
