# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 6420-6519 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6420_6519 = {
    6420: [("A", "motivation", "When feeling excited at home, people often go somewhere else.")],
    6421: [("C", "effect", "Cashing in casino winnings commonly brings a smile of contentment.")],
    6422: [("E", "effect", "Having fun with someone you enjoy can bring feelings of happiness.")],
    6423: [("D", "typical_location", "Big Sky is a nickname for Montana, so Big Sky Excavation would likely be found there.")],
    6424: [("D", "effect", "Setting a cup carelessly on a table can cause spillage.")],
    6425: [("E", "used_for", "Skating lets a person move fast while feeling the wind.")],
    6426: [("E", "part_whole", "Food passes through the alimentary canal starting from the mouth.")],
    6427: [("D", "typical_location", "Pens are commonly purchased at an office supply store.")],
    6428: [("D", "used_for", "Children in uniforms and helmets are typically about to play sports.")],
    6429: [("A", "typical_location", "An outdoor chess set could freeze in a cold climate like Michigan.")],
    6430: [("A", "typical_location", "Hair clippers are used on women at a salon.")],
    6431: [("C", "typical_location", "Fishing boats in Alaska search for crab in coastal waters.")],
    6432: [("B", "typical_location", "Someone with sudden illness should reasonably visit a hospital.")],
    6433: [("E", "used_for", "After a printer jam, one may need to clear the print queue.")],
    6434: [("D", "property", "Gender reveal bouquets for a daughter are commonly colored pink.")],
    6435: [("A", "typical_location", "Visitors stop at a ticket booth before rides at an amusement park.")],
    6436: [("B", "effect", "Watching a favorite comedy show is likely to make someone laugh.")],
    6437: [("B", "typical_location", "Toiletries packed in a small bag are commonly stuffed into a suitcase.")],
    6438: [("A", "typical_location", "A sit-down restaurant is an unlikely place to get popcorn.")],
    6439: [("C", "typical_location", "A crab separated from others may be stranded in a tide pool.")],
    6440: [("E", "effect", "An opponent who is too skilled may prevent you from achieving victory.")],
    6441: [("D", "effect", "Discovering the truth about one's father can bring a feeling of relief.")],
    6442: [("D", "typical_location", "Without a wallet, people often carry a dollar bill in a pocket.")],
    6443: [("A", "motivation", "Putting belongings in a drawstring bag, people want their things to stay safe.")],
    6444: [("E", "typical_location", "A bald eagle at the northern extreme of the continental United States may fly over Maine.")],
    6445: [("E", "typical_location", "Wet leaves on a street are likely to cause a vehicle accident.")],
    6446: [("A", "effect", "Eating a lot of food commonly makes someone feel full.")],
    6447: [("E", "property", "Even a devastating oil spill may be described as entirely accidental.")],
    6448: [("E", "used_for", "Many people hike as a form of exercise.")],
    6449: [("E", "effect", "Expecting a job but never receiving the offer leaves someone feeling let down.")],
    6450: [("B", "typical_location", "Real knights historically existed during the Middle Ages.")],
    6451: [("E", "typical_location", "A fox emerging from woods is a common sight near a cabin's back yard.")],
    6452: [("B", "effect", "Children given ice cream commonly enjoyed the treat.")],
    6453: [("D", "typical_location", "Air to fill balloons is freely available in and around a house.")],
    6454: [("A", "effect", "Even habitual killers may eventually feel remorse for their actions.")],
    6455: [("C", "motivation", "Someone with many friends may keep socialising to become more popular.")],
    6456: [("D", "primary_function", "Professors commonly state facts and present evidence to prove their points.")],
    6457: [("D", "effect", "Tripping while playing basketball commonly causes a person to fall down.")],
    6458: [("A", "property", "Difficult negotiations about intimacy can proceed with surprising calmness.")],
    6459: [("D", "effect", "A witness afraid of perjury fears being found out and going to jail.")],
    6460: [("D", "effect", "Not receiving expected pay commonly makes a person feel sorrow.")],
    6461: [("C", "effect", "A senator going public about a governor's office commonly creates controversy.")],
    6462: [("D", "effect", "Starting a fire on purpose and getting caught can result in going to jail.")],
    6463: [("B", "effect", "Staying healthy helps contribute to a long life.")],
    6464: [("D", "used_for", "People sometimes use clothing as a form of communication.")],
    6465: [("B", "typical_location", "A harbor provides a safe protected space for a boat.")],
    6466: [("A", "has_prerequisite", "Warnings near printers caution against carelessly drinking coffee beside the equipment.")],
    6467: [("C", "typical_location", "A single bee is commonly seen in the countryside among flowers.")],
    6468: [("D", "typical_location", "A ticket booth announcing a late train is located at a metro station.")],
    6469: [("B", "motivation", "When resting, people are trying to achieve relaxation.")],
    6470: [("E", "used_for", "People require a large amount of thinking to figure out complex problems.")],
    6471: [("C", "typical_location", "Snakes at a zoological park are commonly displayed in a terrarium.")],
    6472: [("E", "effect", "Not drinking enough water leads to thirst.")],
    6473: [("B", "cause", "Jealousy is not uncommon when two people compete with each other.")],
    6474: [("C", "primary_function", "An ornate artfully laid out terrace is commonly created by an architecture firm.")],
    6475: [("C", "effect", "Everyone eventually faces their own death, even an uncaught murderer.")],
    6476: [("C", "used_for", "Personal items for travel are often packed together into a single box.")],
    6477: [("A", "typical_location", "A soprano commonly sings live for money at an opera house.")],
    6478: [("D", "effect", "Driving someone on errands for the day can help people in the community.")],
    6479: [("E", "has_prerequisite", "Bringing a wallet to shop means you intend to spend money on products.")],
    6480: [("A", "effect", "Breaking a leg commonly results in needing to get a cast.")],
    6481: [("C", "typical_location", "When a water spout barely dribbles, someone may look for another water fountain.")],
    6482: [("D", "effect", "Watching sports you dislike commonly fills a person with boredom.")],
    6483: [("E", "cause", "Getting drunk commonly causes forgetfulness about where one left belongings.")],
    6484: [("B", "effect", "Someone accused of murder faces potential jail time.")],
    6485: [("A", "used_for", "When you buy something new, you often read the manual for product information.")],
    6486: [("E", "cause", "Being sick with a cough commonly causes hard breathing.")],
    6487: [("A", "effect", "A child heading out to play commonly reacts with happiness.")],
    6488: [("E", "typical_location", "A cardboard box damaged beyond use belongs in the trash.")],
    6489: [("A", "capability", "Being omnipotent means God can do anything.")],
    6490: [("E", "typical_location", "A reception held near a golf course is likely at a country club.")],
    6491: [("B", "property", "Southern is the opposite of northern.")],
    6492: [("D", "typical_location", "Someone shopping locally for peas may go to a farmer's market.")],
    6493: [("C", "typical_location", "Store employees retrieve cans of paint from a shelf for customers.")],
    6494: [("B", "typical_location", "A place using gallons of deep-fryer oil weekly is likely the busiest restaurant in town.")],
    6495: [("B", "effect", "Learning science without religious moral constraints may lead to new ideas.")],
    6496: [("B", "has_prerequisite", "Surrounded by gnats, a person refuses to open mouth to avoid swallowing insects.")],
    6497: [("D", "part_whole", "A head attaches to the body at the neck.")],
    6498: [("B", "primary_function", "Meeting people for the first time involves introducing yourself.")],
    6499: [("E", "typical_location", "An image of a blowfish can be found in books about marine life.")],
    6500: [("C", "typical_location", "Spare change not needed soon is often kept in a jar at home.")],
    6501: [("C", "property", "Live band performances may use sound that was previously recorded.")],
    6502: [("A", "motivation", "Most people chat with friends for fun.")],
    6503: [("D", "typical_location", "A graveyard is usually found on the outskirts of every town.")],
    6504: [("D", "effect", "Learning more about your weakest subjects helps improve yourself.")],
    6505: [("B", "has_prerequisite", "Before running, a person first needs to know how to walk.")],
    6506: [("B", "motivation", "A shady investor may insist a client must spend money to make money.")],
    6507: [("C", "effect", "A talented person who dislikes performing may suffer from anxiety.")],
    6508: [("E", "used_for", "Crushed ice is commonly used to make a cup of water colder.")],
    6509: [("B", "typical_location", "A bald eagle at a zoological park is housed in an aviary.")],
    6510: [("A", "has_prerequisite", "Understanding each other better in a serious relationship requires effort.")],
    6511: [("C", "typical_location", "A shark bumping piers unable to reach open water may be stuck in San Francisco Bay.")],
    6512: [("B", "used_for", "A brass player in a marching band must carry the instrument while playing.")],
    6513: [("D", "property", "Someone with poor job references needs to work on being more reputable.")],
    6514: [("B", "typical_location", "Lying on one's back, a familiar ceiling lamp can be a blinding light overhead.")],
    6515: [("D", "has_prerequisite", "Meeting someone in the afternoon means a project should be finished by morning.")],
    6516: [("D", "property", "A well-known adage warns against mixing business with pleasure.")],
    6517: [("E", "typical_location", "To save money, coffee may be had at a friend's house instead of going out.")],
    6518: [("E", "used_for", "Silo homes are often insulated with packed earth and recycled tires.")],
    6519: [("C", "typical_location", "A space shuttle is a place humans do not often go compared with everyday locations.")],
}
