# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 9420-9519 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_9420_9519 = {
    9420: [("D", "typical_location", "The Trevi Fountain is a famous landmark located in Rome, Italy.")],
    9421: [("D", "effect", "Successfully completing a difficult climb commonly brings a sense of accomplishment.")],
    9422: [("E", "typical_location", "When a sword is not in use it is typically stored in its sheath.")],
    9423: [("C", "cause", "A dentist may work late when a patient requires extended treatment.")],
    9424: [("C", "effect", "Studying a subject over time commonly leads to greater understanding.")],
    9425: [("E", "typical_location", "Bald eagles are wild birds that naturally live in protected nature reserves.")],
    9426: [("E", "typical_location", "The United States Congress meets in the Capitol Building.")],
    9427: [("D", "used_for", "People often seal a deal by shaking hands after reaching agreement.")],
    9428: [("D", "property", "A clock that is ticking is generally working correctly.")],
    9429: [("A", "property", "Yellow is a very common color found in many types of flowers.")],
    9430: [("D", "typical_location", "Student graduation ceremonies are commonly held on a stage in an auditorium.")],
    9431: [("E", "typical_location", "Someone might buy a puppy from a person's house during a road trip.")],
    9432: [("A", "effect", "A person who helps return a lost wallet may receive a reward from the owner.")],
    9433: [("A", "effect", "A sleeping child can still sense movement when being transported in a vehicle.")],
    9434: [("C", "property", "Cutting-edge computer technology typically costs a significant amount of money.")],
    9435: [("C", "typical_location", "A desk drawer is convenient furniture for storing stamps you need to access often.")],
    9436: [("D", "typical_location", "Fraternity houses are stereotypically associated with heavy drinking and rowdy young men.")],
    9437: [("E", "typical_location", "Restaurants commonly serve steak and alcohol to diners at the table.")],
    9438: [("C", "effect", "Learning about the world can broaden a person's worldview.")],
    9439: [("B", "effect", "A person may feel remorse after taking a life.")],
    9440: [("E", "cause", "Settlers sometimes justified displacement by claiming indigenous people lacked formal land ownership systems.")],
    9441: [("C", "used_for", "When someone has questions they typically need to find solutions.")],
    9442: [("E", "typical_location", "A peace treaty can end fighting so no blood is shed on the battlefield that day.")],
    9443: [("E", "effect", "When feeling a little fatigue, resting can help restore energy.")],
    9444: [("A", "effect", "A silly but exciting film commonly gives a viewer a great deal of enjoyment.")],
    9445: [("C", "motivation", "James wanted Sarah to be happy at her birthday party despite his grief.")],
    9446: [("C", "used_for", "Attending lectures is a traditional way of learning from an expert speaker.")],
    9447: [("B", "effect", "Citizens commonly experience suffering when their country is at war.")],
    9448: [("B", "effect", "Someone who cannot stand the idea of food may have an upset stomach.")],
    9449: [("B", "effect", "Spending time at a museum listening to lectures leads to learning about artifacts.")],
    9450: [("C", "motivation", "Serial killers are sometimes motivated by deriving pleasure from killing.")],
    9451: [("B", "effect", "An injured animal typically signals harm by feeling and showing pain.")],
    9452: [("B", "motivation", "After a difficult work day people often buy beer seeking relaxation.")],
    9453: [("A", "used_for", "Police officers arm themselves with equipment before going on duty.")],
    9454: [("D", "effect", "A released balloon rises upward into the sky.")],
    9455: [("A", "typical_location", "A prisoner in jail may rely on a newspaper as a connection to the outside world.")],
    9456: [("C", "effect", "Eating asparagus commonly causes urine to produce unpleasant odors.")],
    9457: [("C", "used_for", "Someone who spends all day at their job is likely working hard.")],
    9458: [("D", "used_for", "A shorthand typist takes notes by rapidly typing while hearing testimony.")],
    9459: [("C", "typical_location", "A grand entrance hall with royalty present is characteristic of a palace.")],
    9460: [("D", "typical_location", "Many people store extra toilet paper in a bathroom cabinet.")],
    9461: [("B", "capability", "A professional gardener is not expected to burn plants as part of the job.")],
    9462: [("D", "has_prerequisite", "Waiting for someone requires having patience.")],
    9463: [("C", "used_for", "Dancing is a great way to express yourself through movement.")],
    9464: [("C", "typical_location", "A book someone is currently reading is often kept on a bedside table.")],
    9465: [("A", "typical_location", "A delicatessen is a type of shop that sells prepared foods.")],
    9466: [("E", "typical_location", "A maze of underground burrows is characteristic of a rabbit warren.")],
    9467: [("B", "property", "A man calling a woman too thin suggests she is slimmer than he prefers.")],
    9468: [("D", "effect", "Fighters who disrespected each other personally held each other in contempt.")],
    9469: [("A", "typical_location", "Restaurants commonly place decorative vases on dining tables.")],
    9470: [("E", "effect", "A poor loser often shows a lot of anger when defeated in a game.")],
    9471: [("A", "typical_location", "A clock can be stored on a shelf when not displayed on a wall.")],
    9472: [("D", "typical_location", "A performer seeking a new accordion would go to a music store.")],
    9473: [("E", "property", "Honey that is not thick flows freely rather than sticking together.")],
    9474: [("C", "motivation", "A stressed person breathing fresh air is often trying to relax.")],
    9475: [("C", "used_for", "People write in a diary to express themselves and record personal thoughts.")],
    9476: [("B", "typical_location", "A bug seeking wildflowers without human interruption would go to a meadow.")],
    9477: [("B", "typical_location", "Buildings in the classical tradition such as the Pantheon prominently feature columns.")],
    9478: [("C", "typical_location", "If you lack chairs you might borrow some from a friend's house.")],
    9479: [("B", "primary_function", "According to tradition God rested after creating everything.")],
    9480: [("E", "property", "Cold is the direct opposite of hot in temperature.")],
    9481: [("B", "primary_function", "A helper monkey works around the home assisting a disabled person with tasks.")],
    9482: [("B", "property", "Diamonds are difficult for prospectors to find because they are rare.")],
    9483: [("C", "property", "A cat that seems calm but is ready to claw is actually quite agitated.")],
    9484: [("B", "cause", "Fear of heights can prevent someone from climbing.")],
    9485: [("A", "typical_location", "A choker necklace might also be found for sale at a boutique.")],
    9486: [("D", "typical_location", "A can of soda is commonly purchased at a general store alongside many other items.")],
    9487: [("D", "motivation", "Hot weather often makes people crave something cold like ice cream.")],
    9488: [("E", "typical_location", "Scissors used frequently are often kept on a desk for easy access.")],
    9489: [("C", "typical_location", "A missing comforter means the couple's bed in the bedroom lacked its usual warmth.")],
    9490: [("E", "typical_location", "Picnic sandwich meat is often purchased from a deli counter.")],
    9491: [("C", "motivation", "Searching for a place to have lunch is an effort to satiate one's appetite.")],
    9492: [("A", "property", "In Hollywood beautiful appearances are so common that they seem average.")],
    9493: [("A", "used_for", "A solicitor may write a formal letter to warn of upcoming litigation.")],
    9494: [("E", "used_for", "Creativity is one of the best ways to express yourself.")],
    9495: [("A", "typical_location", "A brutal killing scene is likely to involve a bloody mess.")],
    9496: [("E", "typical_location", "You can see a jellyfish without approaching one by visiting a zoo.")],
    9497: [("C", "effect", "The long-term consequence of regularly overeating is weight gain.")],
    9498: [("B", "used_for", "After making contact a spy may need to go somewhere to meet an informant.")],
    9499: [("D", "used_for", "Sliding into the outside lane while driving away from work suggests an upcoming right turn.")],
    9500: [("A", "motivation", "A person who witnesses an accident generally wonders what happened.")],
    9501: [("B", "typical_location", "Driving through a turnpike from a rural area often leads toward an urban region.")],
    9502: [("C", "effect", "Drinking heavily to the point of hitting the bottle is a sign of alcoholism.")],
    9503: [("C", "used_for", "Nodding is a common way to show agreement with someone.")],
    9504: [("E", "effect", "Over-indulging when eating food can lead to getting fat over time.")],
    9505: [("C", "used_for", "When competing someone is typically competing against an opponent.")],
    9506: [("A", "effect", "A lunch of onions, sardines, and garlic commonly results in bad breath.")],
    9507: [("D", "typical_location", "A person who breaks the law may be placed in jail.")],
    9508: [("B", "primary_function", "Cooks are hired primarily to prepare meals.")],
    9509: [("E", "used_for", "Birds often sing as part of seeking and attracting a mate.")],
    9510: [("D", "motivation", "When talking people are generally attempting to communicate with others.")],
    9511: [("E", "effect", "Prolonged kissing can lead to sexual excitement between partners.")],
    9512: [("B", "effect", "After running twenty-six miles the weight loss sensation comes largely from sweat.")],
    9513: [("E", "effect", "Analysing something new helps a person learn more about it.")],
    9514: [("C", "typical_location", "A box office may sell tickets for outdoor sporting events at a ballpark.")],
    9515: [("B", "property", "Events that are typical and expected rather than divine are often humdrum.")],
    9516: [("B", "typical_location", "Someone celebrating success by giving a speech is likely at an awards ceremony.")],
    9517: [("C", "used_for", "A steel cable called a wire rope is primarily used with a winch for lifting.")],
    9518: [("C", "typical_location", "A beginner wanting a harmonica would find one at a music shop.")],
    9519: [("B", "has_prerequisite", "An open mind leads someone toward learning about the world.")],
}
