# -*- coding: utf-8 -*-
"""Hand-authored rest KB for qids 5520-5619 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_5520_5619 = {
    5520: [("E", "part_whole", "The Mississippi River is the largest river in North America, a continent.")],
    5521: [("C", "effect", "Someone who is not good at playing poker will likely begin losing money when they play.")],
    5522: [("A", "effect", "Taking illegal drugs long term commonly causes illness and harm to the body.")],
    5523: [("A", "used_for", "A mother tells a sick child to stay in bed until they are well enough to go to school again.")],
    5524: [("A", "typical_location", "A special wild rosebush is commonly found in a botanic garden.")],
    5525: [("C", "typical_location", "A runway is the path models walk on at a fashion show.")],
    5526: [("E", "typical_location", "Mines are typically located underneath mountains where valuable minerals are extracted.")],
    5527: [("E", "part_whole", "Hardware such as door knobs can have a knob to turn but no electronic display.")],
    5528: [("E", "typical_location", "An office building contains several businesses in the same location.")],
    5529: [("A", "effect", "A writer who contemplates the purpose of a lost story may finally begin to get ideas.")],
    5530: [("A", "part_whole", "The trombone fits in well on the field as a member of a marching band.")],
    5531: [("E", "effect", "Listening to music while working can help a person achieve a quiet mind for focus.")],
    5532: [("E", "typical_location", "A snake in a meadow would hide in high grass for cover.")],
    5533: [("B", "effect", "While driving to work, a person may feel the pressure of important decisions to be made that day.")],
    5534: [("C", "motivation", "Someone who went to relax in nature did not go fishing just to catch fish.")],
    5535: [("D", "typical_location", "A quite old clavichord is commonly found in a museum.")],
    5536: [("B", "used_for", "An airplane must accelerate along the runway before takeoff.")],
    5537: [("E", "cause", "Travellers who buy food from a stand are often suffering from hunger.")],
    5538: [("D", "typical_location", "Rocks form in nature above the treeline on mountains.")],
    5539: [("C", "used_for", "A farmer wanting to make a maze commonly grows corn in a field pattern.")],
    5540: [("C", "property", "If a chicken crossed a busy road, you might say it was stupid or being brave.")],
    5541: [("D", "effect", "Fans often watch players lose teeth during a hockey game.")],
    5542: [("D", "primary_function", "Making friends is a good thing for people to do with other people.")],
    5543: [("E", "motivation", "A student who did not drop out like neighbors still had the ambition to go to school.")],
    5544: [("E", "typical_location", "Dust in a room usually ends up collecting in the corner.")],
    5545: [("A", "typical_location", "You need to use a fan in a hot room to stay cool.")],
    5546: [("D", "typical_location", "You buy ketchup at a grocery store.")],
    5547: [("B", "typical_location", "The mailbox that residents of an apartment complex use is located on the property.")],
    5548: [("C", "typical_location", "A dynamite expert checking fuses at a profitable mining operation prepares controlled blasting.")],
    5549: [("A", "used_for", "After someone attacks you, you would defend yourself.")],
    5550: [("B", "property", "Milk is white in color.")],
    5551: [("A", "typical_location", "Sheep commonly graze in a meadow.")],
    5552: [("E", "typical_location", "The Ann Arbor Expressway is located in Michigan.")],
    5553: [("E", "primary_function", "Teachers encourage a child to ask many questions to learn.")],
    5554: [("E", "typical_location", "Jelly that needs to be preserved should be put in a refrigerator.")],
    5555: [("C", "part_whole", "A human has two arms on their upper body.")],
    5556: [("D", "typical_location", "A ficus grows vigorously when it gets plenty of humidity and warm weather like in a tropical rainforest.")],
    5557: [("B", "capability", "Concentration is required to be good at driving cars.")],
    5558: [("D", "typical_location", "Someone working in a ticket booth near a livestock competition is likely at the fairgrounds.")],
    5559: [("E", "typical_location", "A roadway leading away from town typically heads toward the countryside.")],
    5560: [("C", "typical_location", "You can likely buy many poems at a book store.")],
    5561: [("C", "typical_location", "Concord is in New Hampshire, where an apple tree might be planted outside the city.")],
    5562: [("E", "property", "Wrestling involves constant physical contact between opponents.")],
    5563: [("E", "typical_location", "A student who forgot a book may not realize it until already in the classroom.")],
    5564: [("E", "effect", "A parent tells a wild active child they will eventually run out of steam and need rest.")],
    5565: [("C", "used_for", "When a baby is thirsty, its mother may allow it to nurse.")],
    5566: [("D", "typical_location", "A lady can store a writing instrument in her purse while away from home.")],
    5567: [("C", "typical_location", "Your favorite eatery is contained within a commercial building.")],
    5568: [("C", "typical_location", "Opera glasses are used at a theater to see performances clearly.")],
    5569: [("C", "typical_location", "You can find a bar at an airport before traveling a long distance.")],
    5570: [("D", "typical_location", "Someone on the 30th floor during a fire would find it difficult to escape the building.")],
    5571: [("E", "typical_location", "An employee with personal items on their desk may be required to turn off a loud fan in the office.")],
    5572: [("A", "typical_location", "A razor is likely to be found in a suitcase when on vacation.")],
    5573: [("E", "typical_location", "Someone might find a very nice flat in London.")],
    5574: [("C", "effect", "A woman told she could not procreate may be extremely surprised to learn she is having twins.")],
    5575: [("C", "typical_location", "A steakhouse near one of the largest cattle ranches in America could be in Florida.")],
    5576: [("A", "motivation", "A father teaching his daughter to throw a football might seem like he wanted a son.")],
    5577: [("C", "typical_location", "A Bulldog school in the humid south is likely in Georgia.")],
    5578: [("C", "typical_location", "Large speakers playing music are found at a concert.")],
    5579: [("A", "typical_location", "A bean bag chair sits on the floor.")],
    5580: [("D", "typical_location", "A machine used often to help with studies is commonly found in a laboratory.")],
    5581: [("E", "property", "Note-taking on information that seems important may turn out to be useless for an upcoming quiz.")],
    5582: [("A", "typical_location", "A collector of literature might go to a public library to find books.")],
    5583: [("E", "typical_location", "A policeman is most likely to stop a car on the street.")],
    5584: [("A", "typical_location", "Conversation is likely to get loud at a party.")],
    5585: [("C", "effect", "If you slap a horse's butt while off of it, the horse will likely go away.")],
    5586: [("A", "typical_location", "An American horse that finds its home too hot might live in Arizona.")],
    5587: [("C", "used_for", "Someone will tell the truth in court for a person they love.")],
    5588: [("A", "typical_location", "A wall faucet spraying water into the air would be annoying to people in a restroom.")],
    5589: [("E", "primary_function", "A mail service will drop packages off and also pick them up for delivery.")],
    5590: [("C", "typical_location", "Marmosets are found in the warm environments of South and Central America.")],
    5591: [("B", "typical_location", "A computer user can learn geography, math, or history at school.")],
    5592: [("B", "typical_location", "New York is a city known for its disco era and nightlife.")],
    5593: [("A", "effect", "A tense person listening to soft music may do so for relaxation.")],
    5594: [("E", "typical_location", "A person who needs a new trumpet might visit a music shop.")],
    5595: [("B", "used_for", "Deodorant should be applied to the armpits.")],
    5596: [("D", "primary_function", "A clerk is likely to check you into a beauty salon.")],
    5597: [("B", "part_whole", "An office desk used during your occupation usually has a drawer.")],
    5598: [("B", "typical_location", "Illinois has largely flat farmland where uneven land rarely prevents apple trees from growing.")],
    5599: [("E", "typical_location", "Someone fumbling through magazines hearing whirring machines in the next room is likely at the dentist.")],
    5600: [("A", "typical_location", "Plants are happiest in the spring in a garden with fresh soil and rain.")],
    5601: [("B", "typical_location", "An unused hat is commonly kept in a closet.")],
    5602: [("B", "effect", "Lawyers who are not treated well at a restaurant may press charges or take legal action.")],
    5603: [("A", "typical_location", "A cat that paws at the couch and walks in front of the TV is in the family room.")],
    5604: [("D", "used_for", "A real estate agent showing a house with problems may try to cover up the defects.")],
    5605: [("A", "typical_location", "Tires are found on all vehicles at an airport where you can travel long distances.")],
    5606: [("A", "cause", "Catching a cold could temporarily prevent you from attending school.")],
    5607: [("C", "typical_location", "Someone at a field hospital is likely to be at a military base.")],
    5608: [("C", "used_for", "One uses energy when exercising the body.")],
    5609: [("E", "used_for", "People often take a photo when they see a pretty sky.")],
    5610: [("D", "typical_location", "Bacteria on hands is relatively easy to wash off with soap and water.")],
    5611: [("B", "effect", "The consequence of a long day of doing housework is becoming tired.")],
    5612: [("C", "typical_location", "A large city hall is usually located in the downtown area.")],
    5613: [("E", "effect", "A judge taking away a child after a neglect verdict is a serious consideration for the parent.")],
    5614: [("D", "typical_location", "Leather jackets are typically bought at department stores.")],
    5615: [("D", "effect", "Passing out from drinking alcohol means the brain suffered from alcohol toxicity.")],
    5616: [("E", "property", "Two parties who can neither confirm nor compromise on anything are in a dispute.")],
    5617: [("D", "used_for", "Dividing positive integers produces a smaller result than the original numbers.")],
    5618: [("E", "effect", "If you break someone's nose while wrestling, blood will come out of it.")],
    5619: [("D", "property", "Someone who neither reveres nor disdains a holy man has respect for him.")],
}
