# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 9020-9119 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_9020_9119 = {
    9020: [("C", "used_for", "A bridge is commonly built to span over water across a river or valley.")],
    9021: [("B", "typical_location", "Tyson chicken products are found in a grocery store when you need more.")],
    9022: [("D", "motivation", "Pet owners usually prefer their own animal over other people's pets.")],
    9023: [("A", "typical_location", "If no plants exist on another planet, you might look for them on the surface of Earth.")],
    9024: [("B", "used_for", "Children commonly gather around a campfire to hear stories.")],
    9025: [("D", "typical_location", "Utah has scenic canyons where a steakhouse might offer a canyon view.")],
    9026: [("B", "typical_location", "A coffee cup ring stain commonly appears on the table beneath the cup.")],
    9027: [("C", "effect", "When division profits skyrocket, overall company margins typically get higher.")],
    9028: [("E", "typical_location", "Engineers testing an automaton are likely doing so in a lab.")],
    9029: [("A", "property", "An illusionist's practiced lying is part of performing deception.")],
    9030: [("A", "motivation", "A nervous first-time job applicant may worry about taking on employment.")],
    9031: [("E", "cause", "A caregiver absorbed in a cell phone shows negligence that can harm a patient.")],
    9032: [("C", "typical_location", "Controlling aircraft takeoff and landing is done from an airbase control room.")],
    9033: [("C", "typical_location", "A porch is a good outdoor place to put a lawn chair.")],
    9034: [("B", "has_prerequisite", "Athletes commonly need to rest their bodies after a game.")],
    9035: [("C", "motivation", "Bored people are often told to go somewhere to find activity.")],
    9036: [("E", "part_whole", "The ceiling is the surface directly above the floor inside a building.")],
    9037: [("E", "typical_location", "A ficus not kept in a pot may be planted in a flower garden.")],
    9038: [("E", "property", "An office chair with one uneven leg wobbles and sounds wrong on the floor.")],
    9039: [("D", "typical_location", "Cheap linoleum and boxy rooms characterize many mobile homes.")],
    9040: [("A", "typical_location", "A village might have only one churchyard for the whole community.")],
    9041: [("E", "typical_location", "The small screen refers to performing on television.")],
    9042: [("A", "used_for", "Surfing the net is a quick way to read the latest news.")],
    9043: [("D", "typical_location", "Submarines are transport used underwater in the Atlantic Ocean.")],
    9044: [("C", "used_for", "Emptying closet racks into a cardboard box stores clothes.")],
    9045: [("D", "typical_location", "You catch a ball at a sporting event during play.")],
    9046: [("E", "typical_location", "An old well is often found on a farm yard when property is purchased.")],
    9047: [("C", "motivation", "A teacher wanting each student to feel individual wants them to feel special.")],
    9048: [("A", "effect", "A person standing in line often fidgets to pass the time.")],
    9049: [("D", "effect", "Hurting someone else can result in punishment.")],
    9050: [("B", "typical_location", "Living in a remote area makes getting local news difficult.")],
    9051: [("D", "property", "A migraine is a type of headache that causes severe head pain.")],
    9052: [("A", "effect", "Hikers suffering fatigue on a steep trail commonly stop to sit down.")],
    9053: [("B", "typical_location", "A subway underground may not allow riders to see daylight.")],
    9054: [("A", "used_for", "A jury judges matters of responsibility in a legal case.")],
    9055: [("B", "typical_location", "Apartments are small dwellings grouped together in one building.")],
    9056: [("B", "used_for", "Leather is primarily used for car seats in automobiles.")],
    9057: [("E", "property", "Pewter is known for its softness unlike most harder metal alloys.")],
    9058: [("E", "typical_location", "A hospital next to the Sears Tower is located at Ross Tower.")],
    9059: [("E", "motivation", "People play cards because they want the satisfaction of winning.")],
    9060: [("C", "typical_location", "The aroma of food simmering in a pan commonly fills the entire kitchen.")],
    9061: [("B", "effect", "Hikers feeling exhaustion commonly sit on a log to have rest.")],
    9062: [("A", "typical_location", "Baltimore Maryland is known for areas of brick row houses.")],
    9063: [("D", "typical_location", "A weasel belongs out of doors rather than inside a home.")],
    9064: [("C", "property", "God sparing people in the flood suggests he has compassion.")],
    9065: [("C", "motivation", "A person getting married makes a promise to commit to their partner.")],
    9066: [("C", "typical_location", "An audience at intermission buying popcorn is likely watching theatre.")],
    9067: [("B", "effect", "Trees receiving lots of water and sunlight commonly produce more fruit.")],
    9068: [("A", "typical_location", "A racetrack allows automobiles to reach the highest legal driving speed.")],
    9069: [("E", "effect", "Dancing vigorously until you smell bad means you have begun to sweat.")],
    9070: [("C", "effect", "A boy who kissed girls at school might stay home a week fearing cooties.")],
    9071: [("D", "typical_location", "Many mailboxes in a foyer suggest living in an apartment building.")],
    9072: [("E", "property", "A person with lots of friends ranks high in popularity.")],
    9073: [("A", "typical_location", "A fiddle is commonly stored in a violin case when not being played.")],
    9074: [("A", "typical_location", "Peanuts sealed for freshness are commonly placed in a jar.")],
    9075: [("D", "effect", "When someone finishes going somewhere, they have arrived and are being there.")],
    9076: [("E", "motivation", "A person's conscience may tell them that they should not do wrong.")],
    9077: [("B", "used_for", "A person making a withdrawal is looking for bank money.")],
    9078: [("E", "motivation", "People typically work for money in order to have food to eat.")],
    9079: [("B", "effect", "Someone who has been killing people should be arrested by the police.")],
    9080: [("D", "property", "A bomb is an explosive device that commonly has a fuse or timer.")],
    9081: [("E", "typical_location", "Storms fueled by warm waters commonly begin over tropical seas.")],
    9082: [("B", "used_for", "Grabbing a handle tightly to work out knots means she began to brush hair.")],
    9083: [("D", "has_prerequisite", "At a crowded fast food restaurant you must get in line before ordering.")],
    9084: [("C", "used_for", "Chewing food is part of the broader activity of eating.")],
    9085: [("D", "typical_location", "From groups having fun to falling pins, you hear a lot of noise at a bowling alley.")],
    9086: [("A", "effect", "Learning about science can lead a person to develop new ideas.")],
    9087: [("C", "typical_location", "A highlighter you rarely use is commonly stored in a desk drawer.")],
    9088: [("E", "typical_location", "A car is commonly parked in a driveway near your house.")],
    9089: [("B", "typical_location", "A family might go to a park on a nice day.")],
    9090: [("E", "effect", "James stopped standing in the mud and began to move further into the pit.")],
    9091: [("B", "effect", "A person reunited with a significant other after a long absence may expect passionate kisses.")],
    9092: [("D", "effect", "A runner may collapse before finishing a twenty-six mile marathon.")],
    9093: [("B", "motivation", "Takeout with too many vegetables may leave someone wanting more rice.")],
    9094: [("C", "typical_location", "Men commonly keep a wallet in their pockets.")],
    9095: [("E", "typical_location", "Groceries put in a room that is not the main kitchen commonly go in the pantry.")],
    9096: [("A", "typical_location", "A potato is commonly stored in a kitchen cabinet at home.")],
    9097: [("C", "used_for", "To pass class and stay on the team, a student and tutor begin to study hard.")],
    9098: [("E", "motivation", "A person may move to the suburbs seeking neighborhoods with low crime.")],
    9099: [("C", "has_prerequisite", "With a test tomorrow, a student needs to study for the subject.")],
    9100: [("A", "typical_location", "A single heifer is commonly kept most of the time in a dairy barn.")],
    9101: [("E", "typical_location", "A computer mouse that jumps when moved is likely on the desktop.")],
    9102: [("B", "property", "Given dietary salt restrictions, he added just a little bit of salt.")],
    9103: [("A", "used_for", "People use airplanes to travel quickly through the sky over long distances.")],
    9104: [("D", "effect", "Music can provide comfort to someone who is feeling down.")],
    9105: [("C", "effect", "NASA floods the immediate area with water and sound when a space shuttle takes off.")],
    9106: [("B", "part_whole", "Texas has a long shoreline but not the longest of the nearby united states.")],
    9107: [("D", "has_prerequisite", "A safety law now requires all cars to have seat belts.")],
    9108: [("C", "property", "Feudal Japanese leaders despised and punished people believed to have no honor.")],
    9109: [("E", "typical_location", "A place styled like a tavern but serving no alcohol is likely a restaurant.")],
    9110: [("D", "has_prerequisite", "Sweating excessively during exercise means you need to drink water.")],
    9111: [("C", "typical_location", "The president holds the highest office in the government.")],
    9112: [("E", "property", "Forgetting is the opposite of remembering.")],
    9113: [("A", "typical_location", "A bug that preys on aphids commonly lives in a garden.")],
    9114: [("C", "effect", "Accidents involving cars affect the people involved in the collision.")],
    9115: [("A", "typical_location", "Mowing near landscaping in the front yard risks launching rocks at passing cars.")],
    9116: [("D", "typical_location", "Cheese is commonly bought at a market.")],
    9117: [("D", "part_whole", "Combined days can form a week.")],
    9118: [("E", "used_for", "A box of black and red chips from a general store is used to play checkers.")],
    9119: [("B", "typical_location", "Homeless people may go to a bus depot to try to move around.")],
}
