# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7720-7819 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_7720_7819 = {
    7720: [("B", "typical_location", "A smiling child might excitedly point out a big rainbow in the sky.")],
    7721: [("C", "typical_location", "A Menorah is lit during Jewish worship at a synagogue.")],
    7722: [("D", "motivation", "People commonly play basketball because they are having fun.")],
    7723: [("D", "typical_location", "Large shopping malls commonly have many revolving doors at their entrances.")],
    7724: [("A", "typical_location", "A business on the 110th floor is located in a skyscraper.")],
    7725: [("E", "typical_location", "Bald eagles are spotted more often in northern reaches such as British Columbia.")],
    7726: [("A", "part_whole", "A mountain is a type of hill that rises to a greater height.")],
    7727: [("E", "effect", "Ice left in the sun commonly melts and becomes water.")],
    7728: [("B", "typical_location", "Executives on the top floor typically work in an office building.")],
    7729: [("C", "used_for", "A bartender will often mix the cocktails they serve to patrons.")],
    7730: [("A", "typical_location", "A pocket is a common place to keep money on your person.")],
    7731: [("E", "property", "A sheep during its first year of life is called a lamb.")],
    7732: [("C", "effect", "People who do not eat enough food may end up suffering pain from hunger.")],
    7733: [("E", "property", "When you tie a bow it should be tied in a correct and secure way.")],
    7734: [("A", "typical_location", "A fireplace is a common heat source inside a log cabin.")],
    7735: [("A", "typical_location", "A man cave with a sofa bed is often set up in a basement.")],
    7736: [("A", "used_for", "Athletes are people who play sports as their main activity.")],
    7737: [("D", "typical_location", "You grab a doorknob to open a door and reach what is beyond the doorway.")],
    7738: [("A", "used_for", "Studying with multiple sources helps with gathering information for a project.")],
    7739: [("E", "used_for", "People who own restaurants are in the business of selling food.")],
    7740: [("E", "typical_location", "A conductor and performers singing in German are commonly seen at an opera.")],
    7741: [("D", "typical_location", "A harp player's first major performance would likely take place in a concert hall.")],
    7742: [("D", "effect", "Running is vigorous exercise that really works up a sweat.")],
    7743: [("E", "used_for", "Many birds travel long distances, especially during seasonal migration.")],
    7744: [("A", "motivation", "Faith in religion is needed because some truths are ultimately unknowable.")],
    7745: [("A", "typical_location", "A canoe needs sufficiently deep water and cannot float in water that is too shallow.")],
    7746: [("A", "cause", "Tickets that fail to arrive on time cause delays that leave a queue unmoving.")],
    7747: [("D", "used_for", "Round needlepoint work is done on a round wooden frame or hoop.")],
    7748: [("B", "typical_location", "Family photos are often stored dusty in an attic after climbing a ladder.")],
    7749: [("B", "motivation", "Having lunch is the logical thing to do when you are feeling hunger.")],
    7750: [("A", "part_whole", "Wine is an alcoholic beverage made by fermenting grapes.")],
    7751: [("D", "typical_location", "A bassoon is played in a very pleasing fashion at a symphony performance.")],
    7752: [("E", "effect", "Unequal housework and childcare stress in a marriage may lead to arguments.")],
    7753: [("D", "typical_location", "A double edged razor can be purchased at a drug store.")],
    7754: [("A", "property", "Someone who spends most of their time resting may be showing laziness.")],
    7755: [("E", "typical_location", "You are likely to see more statues on display in a museum.")],
    7756: [("C", "used_for", "Telling someone to go to sleep is a way of urging them to rest up.")],
    7757: [("E", "capability", "Hitting a bottle in a carnival game requires very good aim.")],
    7758: [("E", "typical_location", "Art books are commonly kept on shelves in a museum library or shop.")],
    7759: [("D", "typical_location", "A product on display in a store is meant to draw customers inside.")],
    7760: [("B", "typical_location", "A lizard off the ground is likely to be found on a tree trunk.")],
    7761: [("E", "effect", "Learning about the world and the good in it is likely to bring pleasure.")],
    7762: [("E", "typical_location", "Condiments are kept in separate containers so they do not combine with each other.")],
    7763: [("D", "used_for", "When coworkers get together to exchange information they are having a meeting.")],
    7764: [("A", "typical_location", "Many municipalities historically placed their cemetery in a churchyard.")],
    7765: [("A", "typical_location", "People in an interview are typically positioned facing each other.")],
    7766: [("B", "typical_location", "Silicone sealant is commonly stored and sold in a tube.")],
    7767: [("E", "used_for", "Recording on an old answering machine required inserting a cassette tape.")],
    7768: [("B", "motivation", "A common reason to play cards at a casino is to win money.")],
    7769: [("A", "effect", "Someone who does not feel empowered is likely to feel disheartened.")],
    7770: [("B", "effect", "If you hit a person with a stick they are likely to suffer pain.")],
    7771: [("D", "typical_location", "A dense urban area offers good shopping in a downtown district.")],
    7772: [("C", "effect", "While contemplating her fate Sarah could not take action until events unfolded.")],
    7773: [("B", "motivation", "Some people quit work and return to school to better themselves.")],
    7774: [("A", "used_for", "A mother who sees her child loves to learn will make effort to teach him.")],
    7775: [("D", "property", "Someone who is a stranger to others may still be a known person to you.")],
    7776: [("C", "effect", "When an animal becomes old it may begin to feel pain from aging.")],
    7777: [("D", "typical_location", "A snake can easily hide among the dense cover of a thick forest.")],
    7778: [("B", "effect", "Repeatedly falling on ice in comical ways may make someone sick of being laughed at.")],
    7779: [("B", "used_for", "Lighting a match in a dark tunnel is most likely done for illumination.")],
    7780: [("C", "typical_location", "Someone with money who wants to visit a desert may head to a casino in Las Vegas.")],
    7781: [("E", "effect", "Fire helps a cold person because it emits heat that warms the surroundings.")],
    7782: [("D", "property", "The matter inside a sealed can of soda is in a liquid state.")],
    7783: [("E", "typical_location", "Lawyers commonly lease office space in an office building.")],
    7784: [("B", "typical_location", "An employer would prefer an employee plan vacation during free time.")],
    7785: [("E", "typical_location", "Mold is commonly found in a damp cellar or basement of a house.")],
    7786: [("C", "motivation", "People having an affair may care only about their love for each other.")],
    7787: [("C", "typical_location", "Drugs passed around at a wild concert could be someone's last such outing.")],
    7788: [("B", "used_for", "A stress test is a common heart evaluation performed during a medical checkup.")],
    7789: [("C", "effect", "Sitting quietly can help a person come up with their best insights about things.")],
    7790: [("D", "effect", "Studying is the most effective way for a student to get better grades.")],
    7791: [("B", "primary_function", "A flashlight is a portable light source you can carry by hand.")],
    7792: [("A", "property", "Someone with alacrity for life's challenges may still show reluctance in relationships.")],
    7793: [("A", "used_for", "A sharp blade is used to cut through a piece of meat such as a chuck roast.")],
    7794: [("A", "effect", "Getting in shape should improve a person's health by making them feel better.")],
    7795: [("D", "effect", "Learning languages helps a person achieve better communication with others.")],
    7796: [("B", "part_whole", "A person's right-hand man is also referred to as their number one helper.")],
    7797: [("B", "typical_location", "A wonderful place to adopt a cat is the humane society.")],
    7798: [("E", "effect", "The worst possible result of long-term smoking is death.")],
    7799: [("E", "typical_location", "Soft non-slip mats that collect water are commonly found in pairs in a bathroom.")],
    7800: [("D", "typical_location", "You will find more than one door in a building with multiple rooms.")],
    7801: [("E", "effect", "Seeing old things can inspire a person to explore more and feel curiosity.")],
    7802: [("B", "typical_location", "Ficus trees are not native to California but are commonly found there as ornamentals.")],
    7803: [("B", "effect", "When love is not reciprocated the feelings involved often include pain and suffering.")],
    7804: [("D", "typical_location", "People are usually most comfortable in their own home.")],
    7805: [("A", "effect", "Telling many people about tasks you perform can come across as bragging.")],
    7806: [("C", "typical_location", "Someone owning the finest clothing store in the midwest might live in Ohio.")],
    7807: [("C", "typical_location", "When water is transferred with a fish in it the fish commonly ends up in a fish tank.")],
    7808: [("A", "typical_location", "Pennies you plan to use soon are often kept in a pocket.")],
    7809: [("C", "effect", "Cats that have found a patch of sunlight are likely to lie down and bask.")],
    7810: [("B", "typical_location", "Someone convicted of a petty crime is likely to spend time in jail.")],
    7811: [("E", "effect", "A person who works hard and achieves their goals gets to feel fulfilled.")],
    7812: [("B", "motivation", "People watch a documentary hoping to gain insight into real events.")],
    7813: [("C", "typical_location", "Geese invading a secure installation would first be spotted from a guard house.")],
    7814: [("E", "typical_location", "People commonly keep a credit card in a wallet.")],
    7815: [("B", "used_for", "After being shipwrecked Robinson relied on a huge tree to provide shelter.")],
    7816: [("D", "effect", "After cooling off to manage anger a person does not need to seek revenge.")],
    7817: [("E", "property", "Someone who appears lazy outwardly may still have a very active imagination.")],
    7818: [("D", "typical_location", "Humans can have a cup of coffee or a sandwich at a cafe.")],
    7819: [("A", "used_for", "With baked potatoes someone may not know how to prepare them properly.")],
}
