# -*- coding: utf-8 -*-
"""Batch: hand-authored v2-style KB for qids 6820-6919 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6820_6919 = {
    6820: [("D", "effect", "Going out to play commonly leads a child to being entertained.")],
    6821: [("B", "typical_location", "A phone book commonly lists names of places to stay such as hotels and motels.")],
    6822: [("D", "typical_location", "A coastal area is a geographic region commonly associated with a bay.")],
    6823: [("D", "property", "Some people prefer salty snacks while others prefer sweet ones.")],
    6824: [("D", "typical_location", "Light from the sun spreads outward through the universe as it travels away from Earth.")],
    6825: [("B", "effect", "After death, a body may be cremated as one common form of disposition.")],
    6826: [("E", "typical_location", "Aberdeen, South Dakota is a well-known United States city named Aberdeen.")],
    6827: [("B", "used_for", "Replacing ink cartridges lets you keep using pens without buying brand new ones.")],
    6828: [("E", "typical_location", "A concert hall is often located in a city where large populations can attend performances.")],
    6829: [("A", "property", "Having no money left after paying bills means you are broke.")],
    6830: [("A", "typical_location", "A ballpoint pen is commonly used at a bank when writing a check.")],
    6831: [("E", "used_for", "An electric fan circulates air to cool and ventilate a hot room.")],
    6832: [("D", "typical_location", "An electric razor may be exposed to water in a bathroom during use or cleaning.")],
    6833: [("B", "motivation", "When it is cold and snowy outside, people commonly choose to stay in.")],
    6834: [("E", "property", "Ugly is commonly considered the opposite of beautiful.")],
    6835: [("B", "effect", "Cooking produces cooked food as its direct result.")],
    6836: [("B", "typical_location", "Hell's Canyon is a famously named geologic erosion feature whose name contrasts with heaven.")],
    6837: [("B", "motivation", "People eat hamburger in order to satisfy hunger.")],
    6838: [("A", "effect", "When anger reaches a boiling point, therapists recommend taking a break to cool off.")],
    6839: [("E", "typical_location", "Rats that coexist with turtles are commonly found at a reptile farm.")],
    6840: [("A", "typical_location", "Mathematical rules are commonly found in a textbook.")],
    6841: [("A", "primary_function", "A maid is typically hired for cleaning house.")],
    6842: [("E", "typical_location", "A public garden is commonly found in a park.")],
    6843: [("D", "motivation", "A late student running in the hallway is trying to go to class.")],
    6844: [("D", "property", "Buffalo were hunted until their population numbers became sparse.")],
    6845: [("B", "effect", "Regular jogging can lead to improved health for the body.")],
    6846: [("E", "motivation", "Friends sometimes throw a party when another friend is coming home.")],
    6847: [("D", "effect", "Smoking commonly causes a persistent cough affecting the breathing organs.")],
    6848: [("A", "typical_location", "An airplane is stored indoors in a hangar.")],
    6849: [("A", "typical_location", "New York has grimy urban rivers from which seafood might be sourced controversially.")],
    6850: [("E", "used_for", "Donating a talent to a cause commonly means working for free.")],
    6851: [("E", "effect", "Not paying attention while bathing can cause someone to slip and fall.")],
    6852: [("E", "effect", "Killing someone typically ends with a funeral for the victim.")],
    6853: [("C", "used_for", "Taking many notes in class commonly requires buying a notebook.")],
    6854: [("C", "part_whole", "A tennis game can be one match within a championship tournament.")],
    6855: [("A", "cause", "A cat often comes running at the sound of a can of tuna fish being opened.")],
    6856: [("C", "effect", "People commonly feel excited when their birthday is approaching.")],
    6857: [("B", "used_for", "People at work exchange information with large groups during a meeting.")],
    6858: [("C", "typical_location", "A very small town may lack parking lots for visitors.")],
    6859: [("C", "typical_location", "Coworkers commonly sit around a table together during a meeting.")],
    6860: [("A", "typical_location", "An electrical breaker panel is commonly located in a home basement.")],
    6861: [("E", "effect", "A lead for a journalist commonly develops into a news article.")],
    6862: [("D", "typical_location", "A fine picture may serve as the background setting at an art show.")],
    6863: [("D", "property", "Helping others while expecting nothing in return is altruistic behavior.")],
    6864: [("E", "property", "A gardener is commonly said to have a green thumb for growing plants.")],
    6865: [("C", "motivation", "An athlete feeling inadequate may apply increased effort to improve competition performance.")],
    6866: [("E", "property", "The glass ceiling is a metaphor for barriers blocking advancement.")],
    6867: [("B", "effect", "Not passing a course means the student would fail.")],
    6868: [("C", "typical_location", "A booking office is commonly found inside a building.")],
    6869: [("D", "typical_location", "Adults commonly make friends at the workplace.")],
    6870: [("D", "effect", "Severe choking while eating can result in death.")],
    6871: [("B", "used_for", "A sponge is commonly used to clean dishes.")],
    6872: [("E", "typical_location", "Fans who enjoy watching competitors go around are likely heading to a race track.")],
    6873: [("D", "has_prerequisite", "A driver needs keys to start and operate a car.")],
    6874: [("D", "motivation", "He wished he had remembered to pack the tools back then before leaving.")],
    6875: [("C", "typical_location", "In a theatre, the best seating is often center and about halfway back.")],
    6876: [("A", "property", "Someone who cogitates over every little thing may be obsessive compulsive.")],
    6877: [("D", "typical_location", "Mexico is a North American country where people enthusiastically watch soccer matches.")],
    6878: [("B", "typical_location", "Florida's peninsula and panhandle create a long coast popular for vacations and retirement.")],
    6879: [("C", "has_prerequisite", "A scientific theory requires that its underlying hypothesis be supported by fact.")],
    6880: [("C", "typical_location", "Birth control pills are commonly purchased at a drug store.")],
    6881: [("C", "typical_location", "A gatehouse commonly guards the entrance to a subdivision.")],
    6882: [("D", "effect", "Depleting forests worldwide negatively affects the earth's ecosystems.")],
    6883: [("E", "typical_location", "A toy store may have electric toy trains that stop working when electricity is lost.")],
    6884: [("E", "property", "Someone who enjoys games against others likely appreciates competitiveness.")],
    6885: [("B", "part_whole", "A sentence contains just a few words compared with longer texts.")],
    6886: [("A", "part_whole", "When an uncle visits, children are told that uncle and aunty are coming.")],
    6887: [("E", "used_for", "Seeing food on a plate commonly prompts a person to eat.")],
    6888: [("A", "motivation", "Going dancing can help someone who is isolated meet people socially.")],
    6889: [("D", "typical_location", "Cloth used for sleeping such as sheets and blankets is found in a bedroom.")],
    6890: [("D", "property", "A dog lost in Copenhagen would likely be of Danish nationality or origin.")],
    6891: [("C", "motivation", "Someone who dislikes socializing may still go out simply to have fun.")],
    6892: [("D", "typical_location", "A sea anemone commonly inhabits a tide pool along the shoreline.")],
    6893: [("A", "typical_location", "Humans are what you would find moving inside a ticket office.")],
    6894: [("E", "typical_location", "The living room is commonly the first room you enter in a house.")],
    6895: [("E", "property", "Thinking the same thing your friends say indicates agreement.")],
    6896: [("C", "typical_location", "A tennis court with older refined clientele is commonly located at a health club.")],
    6897: [("C", "part_whole", "The world is known to be part of the universe.")],
    6898: [("E", "typical_location", "Light bulbs are frequently found inside a lamp.")],
    6899: [("E", "effect", "A neutral person seeing an idea become reality would likely feel satisfied.")],
    6900: [("E", "typical_location", "Montreal is a famous bilingual city where one might visit a French restaurant after hockey.")],
    6901: [("E", "typical_location", "Opened jelly should be stored in a refrigerator to prevent spoiling.")],
    6902: [("E", "used_for", "Rich kids at a parents' mountain lodge commonly go skiing to relieve boredom.")],
    6903: [("A", "property", "Humans are said to possess consciousness while dogs are often thought to lack it.")],
    6904: [("C", "part_whole", "A person's bottom is also commonly called a butt.")],
    6905: [("A", "typical_location", "Public tennis courts are commonly found in a park.")],
    6906: [("C", "typical_location", "A newspaper may land on the lawn when it misses the porch.")],
    6907: [("E", "effect", "Climbing higher commonly makes a person afraid of falling down.")],
    6908: [("D", "effect", "A person usually stops eating lunch because they feel full.")],
    6909: [("B", "effect", "Winning a baseball game commonly leads to celebration.")],
    6910: [("B", "typical_location", "Kitchen cabinets including undersink units are commonly manufactured in Mexico.")],
    6911: [("A", "property", "An incompetent real estate agent might sell a house for less than it is worth.")],
    6912: [("C", "typical_location", "A snake would be unlikely to be welcome at a petting zoo.")],
    6913: [("C", "primary_function", "The purpose of drinking water is hydration.")],
    6914: [("E", "typical_location", "A small dog that naps on the couch is typically in the living room.")],
    6915: [("E", "effect", "Resting on a couch after work commonly means relaxing.")],
    6916: [("A", "part_whole", "Alabama is one of the Gulf states that must prepare for hurricanes.")],
    6917: [("C", "property", "Bitter foods are characteristically not sweet.")],
    6918: [("B", "typical_location", "An armoire is commonly purchased at a furniture store.")],
    6919: [("B", "typical_location", "Commuters usually move quickly on a freeway during rush hour.")],
}
