# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 6320-6419 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6320_6419 = {
    6320: [("A", "property", "The bald eagle is widely recognized as a symbol of the United States of America.")],
    6321: [("C", "typical_location", "A flowering anemone is commonly kept in a flower pot so it can grow and bloom.")],
    6322: [("C", "part_whole", "When siblings fight constantly, a parent may need a rule for every family situation.")],
    6323: [("B", "primary_function", "A blade that catches the air and turns powers a windmill to create energy.")],
    6324: [("E", "used_for", "Closing your eyes is commonly the last thing you do before falling asleep.")],
    6325: [("C", "used_for", "Besides shopping, people often go to malls to meet friends.")],
    6326: [("D", "effect", "Exercise commonly causes the body to start sweating.")],
    6327: [("C", "effect", "When a winning baseball game is imminent, a team is likely celebrating.")],
    6328: [("C", "effect", "A couple who decide stopping their marriage is best commonly get divorced.")],
    6329: [("E", "typical_location", "Wine is commonly served with dinner at a French restaurant.")],
    6330: [("C", "used_for", "When hair flow gets knotted in a convertible, the driver puts the top up while stopping.")],
    6331: [("C", "used_for", "When people pray, they commonly talk to God.")],
    6332: [("D", "effect", "Writing for a long time before finishing can cause writer's cramp.")],
    6333: [("A", "typical_location", "Colorado does not border New York, which lies far to the east.")],
    6334: [("D", "effect", "Someone who entertains others commonly feels liked by the audience.")],
    6335: [("D", "typical_location", "A doctor typically trains at medical school before opening a practice.")],
    6336: [("C", "motivation", "An empty shopping center solicits stores to fill vacant retail space.")],
    6337: [("D", "effect", "Eating beans at dinner commonly causes flatulence afterward.")],
    6338: [("D", "part_whole", "Every living person has one head on top of their neck.")],
    6339: [("C", "effect", "A laid-off factory worker hearing about a changing society may feel resentment.")],
    6340: [("B", "typical_location", "On a sunny day a person can hold a cup upright under a waterfall to catch river water.")],
    6341: [("A", "motivation", "A spy listening to a target chat is on a mission of gathering information.")],
    6342: [("E", "effect", "Light passing through the air can illuminate objects in its path.")],
    6343: [("C", "typical_location", "A church is often busiest on Sunday, the day after Saturday.")],
    6344: [("D", "typical_location", "After finishing shopping, a shopping bag is commonly taken home.")],
    6345: [("D", "used_for", "Many people drink coffee while reading the newspaper.")],
    6346: [("A", "used_for", "To see a story on the big screen you must go to the movies.")],
    6347: [("E", "typical_location", "A food show visiting a pizzeria in each state commonly goes to capital cities.")],
    6348: [("D", "typical_location", "Bread and chips for a picnic are commonly taken from a walk-in pantry.")],
    6349: [("B", "cause", "A president commonly comes to office through an election.")],
    6350: [("E", "effect", "After a divorce a person's relationship status changes to having no spouse.")],
    6351: [("B", "typical_location", "Yooperland refers to the Upper Peninsula region of Michigan.")],
    6352: [("D", "used_for", "Having children wash dishes after dinner helps teach them responsibility.")],
    6353: [("C", "property", "A black dog is easier to spot than one that blends into its surroundings.")],
    6354: [("B", "typical_location", "A dentist's office seeking high visibility often sets up on main street.")],
    6355: [("A", "typical_location", "Macaroni, rice, and Hamburger Helper are grocery items found at a grocery store.")],
    6356: [("C", "cause", "A bite that breaks the skin can cause a drop of blood to fall.")],
    6357: [("D", "used_for", "Someone going to study in a library is about to read books.")],
    6358: [("B", "typical_location", "A mother is likely to put a ribbon in a girl's hair.")],
    6359: [("A", "effect", "Climbing a mountain leads to getting higher in elevation.")],
    6360: [("B", "property", "When a situation has soured, someone is likely in a negative situation.")],
    6361: [("A", "used_for", "If you cannot afford an original painting, you can get a reproduction instead.")],
    6362: [("A", "used_for", "An immoral student taking final exams without studying is likely to cheat.")],
    6363: [("E", "typical_location", "Someone who lost sunglasses can quickly buy new ones at a drugstore.")],
    6364: [("B", "used_for", "When fighting inflation people should stop spending more money.")],
    6365: [("D", "cause", "Driving is expensive largely because cars keep using gas.")],
    6366: [("B", "typical_location", "The best place to keep a dish cloth is in the kitchen where it is used.")],
    6367: [("E", "used_for", "Between each customer a waiter is sometimes required to set the table again.")],
    6368: [("C", "used_for", "A Christmas tree makes a great gift for a poor family with no December decorations.")],
    6369: [("B", "property", "When a person has to pee, their bladder is full.")],
    6370: [("D", "effect", "Ignorance between groups can cause hostility.")],
    6371: [("A", "effect", "When you play games with children you are entertaining them.")],
    6372: [("C", "effect", "If you go fishing but catch no fish, you may go home empty-handed.")],
    6373: [("E", "typical_location", "Many radio studios are located in a large city.")],
    6374: [("A", "effect", "An extra blanket on a cold night can make someone even more comfortable.")],
    6375: [("E", "used_for", "Someone with hunger in the middle of the night should have food.")],
    6376: [("A", "used_for", "When people are bored they often call friends.")],
    6377: [("E", "used_for", "Saying you typically use a travel website to book flights implies you used it in the past.")],
    6378: [("C", "effect", "When a farmer is reproducing sheep, one sheep later gives birth.")],
    6379: [("C", "typical_location", "The Llano Estacado plateau lies primarily in Texas.")],
    6380: [("D", "property", "Someone who cannot reply to you could be mute.")],
    6381: [("E", "typical_location", "People without insurance may face long waits at a walk-in clinic.")],
    6382: [("A", "used_for", "Pouring water over coffee grounds is how you make a cup of coffee.")],
    6383: [("E", "typical_location", "Most human hair is on a person's head.")],
    6384: [("D", "cause", "A dog that seems antsy and restless may have fleas.")],
    6385: [("E", "typical_location", "A public library downtown can be visited by people of any age.")],
    6386: [("A", "used_for", "When a dog is too close to the street, its owner may yell for it to come here.")],
    6387: [("C", "effect", "Listening to someone answer questions incorrectly on purpose can cause irritation.")],
    6388: [("E", "has_prerequisite", "You must fall asleep before you can dream.")],
    6389: [("C", "typical_location", "Istanbul is famous for its historic Grand Bazaar.")],
    6390: [("B", "typical_location", "A sloth that exists only in your head may appear in a bad dream.")],
    6391: [("E", "effect", "The idea of going on vacation commonly inspires pleasant thoughts.")],
    6392: [("D", "typical_location", "Away from home you can get a barbecue meal at a restaurant.")],
    6393: [("E", "typical_location", "The best place to store personal knowledge is in your head.")],
    6394: [("E", "typical_location", "Two guards checking IDs at an entryway suggest an office building.")],
    6395: [("A", "effect", "A baby who hears his mother talk for months commonly learns to speak.")],
    6396: [("D", "used_for", "Before a party, staff may need to attend a meeting.")],
    6397: [("A", "typical_location", "A catwalk above a stage with rehearsed lines and an audience describes a theatre.")],
    6398: [("A", "typical_location", "England has a queen who is a person, not an insect.")],
    6399: [("A", "motivation", "When a child has a disease keeping him from playing, his family wants him to be healthy.")],
    6400: [("E", "property", "A motorcycle is a type of bike that has an engine.")],
    6401: [("D", "effect", "Driving a car for ten straight hours commonly leads to getting tired.")],
    6402: [("E", "typical_location", "In biblical tradition a snake tempted people in the Garden of Eden.")],
    6403: [("A", "typical_location", "On vacation people may enjoy a motel swimming pool before bedtime.")],
    6404: [("B", "capability", "A modern farmer managing finances and sales needs skills common to a businessman.")],
    6405: [("A", "used_for", "Lovers who want to show affection commonly kiss each other.")],
    6406: [("A", "typical_location", "You can wet a washcloth at a sink without squatting down.")],
    6407: [("D", "motivation", "When you decide to go somewhere, you usually do it to get somewhere.")],
    6408: [("D", "used_for", "When meeting people for the first time you introduce yourself.")],
    6409: [("B", "has_prerequisite", "Someone financially unable to pay legal costs may be unable to bring suit.")],
    6410: [("D", "typical_location", "Someone filling a cart and grabbing coffee before checkout is at a grocery store.")],
    6411: [("B", "typical_location", "Characters in hats inside a dime store suggest you are watching an old movie.")],
    6412: [("C", "primary_function", "Manufacturers operate many machines to produce products.")],
    6413: [("C", "effect", "A headache is a painful condition that can make going to the opera uncomfortable.")],
    6414: [("A", "typical_location", "Liquid food is commonly stored in a jar.")],
    6415: [("B", "used_for", "A balloon bought to decorate something is commonly for a birthday party.")],
    6416: [("A", "property", "To speak up about an unfair written assignment is to be verbal about it.")],
    6417: [("A", "typical_location", "Water run-off overflow commonly ends up in a sewer.")],
    6418: [("C", "effect", "Spending too much money on beer can lead to problems.")],
    6419: [("E", "typical_location", "You would walk in a passage through a labyrinth.")],
}
