# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 5920-6019 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_5920_6019 = {
    5920: [("B", "used_for", "Friends who decide to spend their lives together in matrimony arrange a wedding.")],
    5921: [("E", "effect", "Children commonly feel boredom when taken to the opera.")],
    5922: [("C", "effect", "Too much jogging for elderly people can lead to heart attacks.")],
    5923: [("E", "effect", "Someone who thinks new movies are bad and excessive may feel fear when seeing one.")],
    5924: [("D", "typical_location", "A zoo is an unlikely place to find ice compared with hockey rinks or refrigerators.")],
    5925: [("B", "typical_location", "Without a carrying case, sunglasses can be kept in a shirt pocket.")],
    5926: [("A", "capability", "Primal animals sometimes fight each other to prove themselves.")],
    5927: [("D", "typical_location", "A trash can is commonly found near a water cooler in a workplace.")],
    5928: [("D", "effect", "Creating art that fulfills you also gives a feeling of accomplishment.")],
    5929: [("B", "used_for", "Rubbish is commonly watched on television as low-quality programming.")],
    5930: [("D", "property", "An altruistic person is willing to share a sandwich with a hungry friend.")],
    5931: [("D", "used_for", "Money given to appease clients is used to take care of proposals.")],
    5932: [("C", "cause", "Sweating during jogging commonly soaks a runner's shirt.")],
    5933: [("D", "typical_location", "Antarctica is so cold that travelers need insulation to go there.")],
    5934: [("B", "part_whole", "The Pantheon is famous for its color and its impressive columns.")],
    5935: [("B", "used_for", "People commonly wear hats to stay warm in the cold.")],
    5936: [("B", "effect", "A business that does not make profit loses money.")],
    5937: [("B", "part_whole", "The humorous bone is a nickname for a bone found in the arm.")],
    5938: [("D", "typical_location", "A tote bag filled with papers is commonly brought to school.")],
    5939: [("D", "typical_location", "A supply closet is likely to be located in a school.")],
    5940: [("C", "used_for", "A swinging hinge on both parts is used for a fancy french door.")],
    5941: [("A", "effect", "Hurting someone else means causing pain to that person.")],
    5942: [("C", "effect", "Fencing in really hot weather commonly leads to perspiration.")],
    5943: [("E", "effect", "If you cogitate on something for a long time, you can get irritated.")],
    5944: [("B", "part_whole", "Trees are an important part of the ecosphere.")],
    5945: [("A", "typical_location", "Row houses with nearby red phone booths are commonly found in England.")],
    5946: [("E", "typical_location", "Michigan is known to have many lakes.")],
    5947: [("D", "typical_location", "Large quantities of beans in crates are stored in a warehouse.")],
    5948: [("A", "typical_location", "Seats at the movies are frequently covered in popcorn and soda.")],
    5949: [("D", "used_for", "When you first wake up and head to work, you have to get dressed.")],
    5950: [("D", "typical_location", "Marmots live in North America.")],
    5951: [("E", "effect", "Terrorism caused by a few can lead to all-out war.")],
    5952: [("D", "typical_location", "An expensive wristwatch not being worn is often kept displayed in its case.")],
    5953: [("E", "part_whole", "The main part of Turkey makes up Asia Minor.")],
    5954: [("D", "motivation", "Someone may start a fire to achieve warmth.")],
    5955: [("E", "effect", "Central banks fighting inflation can push the economy toward recession.")],
    5956: [("A", "has_prerequisite", "Before something is going to die, it is likely to be sick first.")],
    5957: [("B", "motivation", "Someone uncomfortable with others may rather spend time with an animal.")],
    5958: [("E", "typical_location", "A man who needs to finish paperwork goes to the office.")],
    5959: [("B", "typical_location", "Ireland is a kingdom frequently associated with pubs.")],
    5960: [("C", "typical_location", "Blue Mountain in the Blue Ridge range is in Pennsylvania.")],
    5961: [("D", "typical_location", "People go to a state park if they want to go fishing.")],
    5962: [("D", "part_whole", "A king or queen is a member of the monarchy.")],
    5963: [("E", "motivation", "A sinner hoping a deity is forgiving ultimately seeks absolution.")],
    5964: [("B", "has_prerequisite", "A person without an outhouse has indoor plumbing.")],
    5965: [("C", "property", "A yawn is noisy breathing that does not indicate you are sick.")],
    5966: [("A", "motivation", "Competing is a way to show off one's skill.")],
    5967: [("C", "effect", "Kids visiting museums of old dinosaur bones commonly feel amazement.")],
    5968: [("D", "typical_location", "A predatory salesperson pacing for prey treats the shop as his sea.")],
    5969: [("C", "property", "A gentleman could be wearing a suit.")],
    5970: [("A", "typical_location", "Tools are often kept in a box in the garage.")],
    5971: [("D", "typical_location", "The Oklahoma Sooners play in the Big Twelve conference.")],
    5972: [("B", "used_for", "After yoga class, participants are commonly instructed to meditate quietly.")],
    5973: [("A", "motivation", "Keeping a straight face helps a person avoid showing emotion.")],
    5974: [("B", "typical_location", "The ranch house is common in Montana in the northwestern Rocky Mountains.")],
    5975: [("C", "used_for", "Chatting with friends on the clock is acceptable when exchanging information.")],
    5976: [("B", "effect", "A student who pulled an all-nighter before lecture may go to sleep upon arriving.")],
    5977: [("A", "part_whole", "A viola is heard along with three other instruments in a string quartet.")],
    5978: [("C", "typical_location", "A good place to obtain a ladder is a hardware store.")],
    5979: [("A", "typical_location", "People are likely to push a religious tract in a public place.")],
    5980: [("C", "typical_location", "A sideboard filled with serving dishes is found in the dining room.")],
    5981: [("C", "motivation", "Studying for final exams is nerve wracking if you are afraid of failure.")],
    5982: [("A", "typical_location", "You could go to a steakhouse with an ocean view in Mexico.")],
    5983: [("D", "used_for", "Parents tell kids to stop talking when they want them to go to sleep.")],
    5984: [("A", "primary_function", "A guard protects people from attack.")],
    5985: [("D", "typical_location", "If you run out of beer, you can buy more at a grocery store.")],
    5986: [("B", "motivation", "A retired person who returns to work likely needs to earn money.")],
    5987: [("C", "effect", "Answering questions correctly leads to a better grade.")],
    5988: [("C", "effect", "Indoor cats tend to live many years longer than outdoor cats.")],
    5989: [("B", "property", "A couple who copulates regularly but seems distant may show it in their faces.")],
    5990: [("E", "typical_location", "If you are getting drunk in public, you are likely at a bar.")],
    5991: [("E", "typical_location", "A grain of sand in your bathing suit can cause discomfort.")],
    5992: [("D", "typical_location", "Ancient stargazers spent much time staring into the heavens.")],
    5993: [("D", "typical_location", "Hitting toll roads on the way to the Big Apple means visiting New York.")],
    5994: [("E", "typical_location", "Someone too young to travel abroad for an illegal item may get it from the black market.")],
    5995: [("E", "motivation", "A person with troubles may ask for help when praying.")],
    5996: [("C", "typical_location", "After buying food, you should put it in a freezer for cold storage.")],
    5997: [("A", "used_for", "After someone is done helping you, you should say thank.")],
    5998: [("B", "typical_location", "You might open a desk drawer to find a bottle of glue.")],
    5999: [("C", "typical_location", "If vegetable plants need watering, get the hose out of the garden shed.")],
    6000: [("B", "effect", "When a crowd begins to panic, people might run amok.")],
    6001: [("D", "effect", "The victim of someone committing a murder will die.")],
    6002: [("C", "used_for", "Washing clothes requires more than water; you need to use soap.")],
    6003: [("D", "used_for", "Potatoes ready to be served are best placed in a plate.")],
    6004: [("C", "effect", "Analyzing information helps a person learn facts.")],
    6005: [("A", "typical_location", "A demonstration is a type of presentation that might be set up on a table.")],
    6006: [("A", "effect", "If he came to despise his sister, she may still have felt love for him.")],
    6007: [("C", "motivation", "Students may hold a bake sale for the school to buy new sports equipment.")],
    6008: [("A", "cause", "If you fall when going for a run, you most likely tripped.")],
    6009: [("C", "effect", "Reading letters when unaware of a condition can lead to realization.")],
    6010: [("D", "used_for", "A person heading overseas might board ship.")],
    6011: [("C", "motivation", "A trivia lover studies to keep increasing knowledge.")],
    6012: [("A", "property", "Music enjoyed by people from all countries is universal.")],
    6013: [("A", "effect", "Attempts to improve himself that fail can reduce a person's income.")],
    6014: [("D", "typical_location", "Southern California has many Mexican restaurants.")],
    6015: [("B", "typical_location", "A rest area usually does not have any pillow.")],
    6016: [("C", "property", "A governor may declare a raging natural fire the biggest disaster he has seen.")],
    6017: [("B", "typical_location", "Tourists seeking red telephone boxes look in London.")],
    6018: [("D", "typical_location", "Gel that must be kept cool should be put in a refrigerator.")],
    6019: [("E", "primary_function", "An oven can roast meat as it cooks.")],
}
