# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 9220-9319 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_9220_9319 = {
    9220: [("C", "typical_location", "A basement is the lowest level of a house and is highly susceptible to flooding.")],
    9221: [("B", "effect", "Police commonly arrest people who start fights while drunk in public.")],
    9222: [("E", "typical_location", "Nevada is famous for having a multitude of wedding chapels, especially in Las Vegas.")],
    9223: [("D", "typical_location", "The Lower East Side is a neighborhood in Manhattan known for nightlife including nightclubs.")],
    9224: [("A", "effect", "Returning to work after time off commonly results in earning money again.")],
    9225: [("C", "typical_location", "A public house is a traditional term for a place where people go to drink at a bar.")],
    9226: [("A", "typical_location", "A hilltop provides an elevated vantage point with a good view of surrounding scenery.")],
    9227: [("B", "has_prerequisite", "A computer program must be created by someone writing code before it can exist.")],
    9228: [("B", "used_for", "Smiling is a friendly facial expression that helps people make new friends.")],
    9229: [("B", "motivation", "Animals acting aggressively near a bucket often do so because they need to eat food inside it.")],
    9230: [("E", "effect", "Someone proven guilty of killing people commonly receives a long prison sentence.")],
    9231: [("A", "typical_location", "Dentists commonly give patients a free toothbrush after a dental visit.")],
    9232: [("A", "effect", "Drug addiction commonly causes damage to personal relationships with family and friends.")],
    9233: [("D", "typical_location", "People commonly lock their front door at night for security.")],
    9234: [("D", "typical_location", "A worker at a desk who eyes the door at day's end is likely in an office waiting to leave.")],
    9235: [("A", "typical_location", "Dance clubs are commonly found in the downtown area of a metropolitan city.")],
    9236: [("E", "effect", "Running errands around town involves gathering supplies and items needed for daily life.")],
    9237: [("B", "typical_location", "Clean plates are commonly stored in a kitchen cupboard after being washed and dried.")],
    9238: [("C", "typical_location", "A newly bought apple tree is commonly planted in a front yard where it has space to grow.")],
    9239: [("E", "typical_location", "Jellyfish are marine animals that must live in salt water to survive.")],
    9240: [("C", "has_prerequisite", "A performer typically prepares and rehearses the day before a scheduled performance.")],
    9241: [("E", "property", "A pizza crust that is broad in circumference yet crispy is characteristically thin rather than thick.")],
    9242: [("A", "typical_location", "People light candles to see better when they are in a dimly lit room.")],
    9243: [("C", "typical_location", "A fabric store sells bolts of wool material that is not made into wearable clothing.")],
    9244: [("C", "effect", "Discussing marital issues while chatting with friends commonly creates a feeling of discomfort.")],
    9245: [("A", "typical_location", "A lake is a small body of water that commonly has boats on it.")],
    9246: [("B", "typical_location", "A town commonly has parks with playgrounds where people can take their children to play.")],
    9247: [("C", "typical_location", "At a bed and breakfast, the guest room is typically just a bedroom serving as the only room.")],
    9248: [("E", "used_for", "People drinking alcohol while hearing music at a social gathering are likely to dance.")],
    9249: [("D", "property", "When flexing bare arms to carry a load of wood inside, one's grasp is full rather than empty.")],
    9250: [("C", "typical_location", "A pocket is where a person carries a small harmonica for personal use.")],
    9251: [("B", "effect", "A man who spends a romantic weekend with his girlfriend is likely to become physically intimate.")],
    9252: [("A", "motivation", "The goal of someone planning to kill another person is to take that person's life.")],
    9253: [("E", "effect", "Winning a competition with a cash prize allows the victor to cash in their winnings.")],
    9254: [("B", "property", "Talking and writing are both forms of communication used to share ideas with others.")],
    9255: [("E", "capability", "Unlike young people, older adults can gradually grow shorter as their spinal discs compress with age.")],
    9256: [("E", "property", "Knowledge gained through learning is empowering because it can open opportunities anywhere.")],
    9257: [("C", "typical_location", "Old photographs from past trips are commonly found stored in an attic among forgotten belongings.")],
    9258: [("D", "typical_location", "Mice in a house are usually found in the kitchen where food crumbs attract them.")],
    9259: [("C", "typical_location", "Blood transfusions are medical procedures that must be performed at a hospital.")],
    9260: [("C", "used_for", "To have fun, a person should partake in activities they enjoy doing.")],
    9261: [("B", "property", "A cabin in the woods that feels very large and spacious may feel more like a villa than a rustic shelter.")],
    9262: [("B", "typical_location", "Ball bearings are commonly found in skatepark equipment and areas where skateboarding takes place.")],
    9263: [("D", "capability", "Muscles attached to bones contract and pull on them, making it possible for bones to move.")],
    9264: [("B", "typical_location", "Someone who lost keys while walking outdoors would search outside along the path they walked.")],
    9265: [("A", "typical_location", "Coffee that is not needed immediately can be stored in an airtight container to stay fresh.")],
    9266: [("C", "primary_function", "A candle provides light through burning wax and does not require electricity.")],
    9267: [("E", "typical_location", "Coins that a person wants to carry while traveling are commonly kept in a purse or wallet.")],
    9268: [("A", "property", "A person who is not normal in behavior or thinking is considered unconventional.")],
    9269: [("A", "typical_location", "Litter tossed from a moving car commonly ends up along roadsides.")],
    9270: [("A", "effect", "Killing another person typically results in a criminal trial in court.")],
    9271: [("C", "typical_location", "Chicken is commonly served on a plate as a prepared meal.")],
    9272: [("C", "effect", "Easter falls in spring, which comes soon after the Christmas and winter holiday season ends.")],
    9273: [("C", "effect", "When trees change color and temperatures drop, fall has officially taken over from summer.")],
    9274: [("B", "typical_location", "A school building commonly has shelves with toys and learning materials for young students.")],
    9275: [("C", "effect", "Breathing fresh air can help a person think more clearly when making an important decision.")],
    9276: [("B", "effect", "Having fun with people you care about commonly causes you to start smiling.")],
    9277: [("C", "typical_location", "Address cards with written addresses are commonly sorted and stored in an address book.")],
    9278: [("A", "capability", "A wrestler about to be pinned should try to get free and escape the opponent's hold.")],
    9279: [("A", "typical_location", "A greenhouse commonly contains many varieties of ficus plants cultivated together.")],
    9280: [("A", "typical_location", "Students seeking higher education commonly attend a university.")],
    9281: [("C", "used_for", "When internet service stops working, a person calls their internet service company for support.")],
    9282: [("A", "property", "A manager assigns mandatory leave to nonessential personnel during emergencies or shutdowns.")],
    9283: [("C", "typical_location", "After death, a person's body is commonly placed in a coffin for burial or viewing.")],
    9284: [("E", "effect", "A crying infant in the home commonly prevents a couple from going to bed at their desired time.")],
    9285: [("E", "cause", "You do not earn money during lunch because you stop working to eat your meal.")],
    9286: [("C", "capability", "Someone who does not understand computers can still operate them by following step-by-step instructions.")],
    9287: [("D", "effect", "A performer in his nineties who continues doing shows may experience fatigue from the physical exertion.")],
    9288: [("E", "motivation", "People eat breakfast in the morning to feel satisfied and start the day without hunger.")],
    9289: [("A", "property", "Thick molasses is viscous and is not free flowing like a thin liquid.")],
    9290: [("B", "effect", "Hearing someone play violin beautifully is commonly described as inspiring to listeners.")],
    9291: [("B", "motivation", "Someone who keeps calling repeatedly is hoping to get an answer on the other end.")],
    9292: [("E", "effect", "A person found responsible for intentionally starting a fire commonly faces going to jail.")],
    9293: [("E", "typical_location", "Germany is known for chess set manufacturing and could have facilities holding many chess boards.")],
    9294: [("A", "typical_location", "A footstool placed under a desk provides leg comfort for someone working at a computer all day.")],
    9295: [("A", "typical_location", "A large university office environment could accumulate tens of thousands of paper clips across departments.")],
    9296: [("B", "typical_location", "A restaurant serves alcoholic drinks even though it is not primarily a bar.")],
    9297: [("B", "used_for", "Someone overwhelmed with love may express those feelings by singing joyful songs.")],
    9298: [("E", "typical_location", "A bald eagle soaring over mountainous terrain can see for miles in every direction.")],
    9299: [("B", "effect", "Parents going through divorce are most concerned about causing emotional distress to their children.")],
    9300: [("A", "typical_location", "Business people attend industry conventions to get updates about developments in their field.")],
    9301: [("A", "effect", "Setting a cup down on a table repeatedly can create a noticeable noise each time.")],
    9302: [("B", "has_prerequisite", "Winning a competitive ball game against another player generally requires skill.")],
    9303: [("E", "typical_location", "The Chesapeake Bay estuary between Maryland and Virginia is renowned for its blue crabs.")],
    9304: [("E", "motivation", "People may board a ship to attend a party or celebration held aboard the vessel.")],
    9305: [("C", "effect", "Eating just enough at breakfast leaves a person with a feeling of being satisfied without overeating.")],
    9306: [("A", "property", "Cardinals in the Catholic Church refer to a gathering of church leaders as a conclave.")],
    9307: [("C", "typical_location", "Kitchen cabinets with glass doors allow you to see dishes stored inside.")],
    9308: [("D", "typical_location", "Someone typing on a keyboard is commonly seen working in an office.")],
    9309: [("E", "used_for", "A spoon is dipped into a bowl of soup to scoop up a portion to eat.")],
    9310: [("E", "property", "The D in DRC stands for Democratic, as in Democratic Republic of the Congo.")],
    9311: [("B", "typical_location", "When a number of athletes are wrestling, they are at a wrestling competition.")],
    9312: [("D", "typical_location", "A neighborhood mailbox located between one house and the next block is commonly at a street corner.")],
    9313: [("D", "capability", "Humans solve problems by thinking critically through possible solutions.")],
    9314: [("E", "motivation", "An elephant is asked to recall a number because trainers test memory before rewarding it with food.")],
    9315: [("C", "typical_location", "People commonly play basketball outside at a park with outdoor courts.")],
    9316: [("C", "used_for", "An investor converts stock holdings into cash by selling shares on the market.")],
    9317: [("B", "typical_location", "A parking space in a great position near a building entrance is commonly in the front of the building.")],
    9318: [("E", "typical_location", "Insects are commonly found eating green plants in a field or meadow.")],
    9319: [("E", "typical_location", "A fancy, upscale, and expensive place to stay overnight is a hotel rather than a budget motel.")],
}
