# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 6020-6119 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6020_6119 = {
    6020: [("D", "has_prerequisite", "Chatting with friends requires having friends to talk to.")],
    6021: [("D", "has_prerequisite", "Entering tertiary education typically requires graduating from high school first.")],
    6022: [("E", "typical_location", "Adults commonly drink beer at social parties.")],
    6023: [("A", "typical_location", "Markets on weekends are crowded places where you can count on seeing other people.")],
    6024: [("D", "motivation", "First-time home buyers usually want to be careful and make sure they know what they are doing.")],
    6025: [("A", "typical_location", "A restaurant can provide dining service where patrons are treated politely like gentlemen.")],
    6026: [("A", "typical_location", "Lizards in the wild are commonly found in gardens and other outdoor natural areas.")],
    6027: [("A", "effect", "Attempting too much learning at once can cause headaches from mental strain.")],
    6028: [("A", "typical_location", "Lying on an outdoor deck and looking up means you are gazing at the sky.")],
    6029: [("B", "effect", "Sitting down in a cushy chair leads to feeling comfort.")],
    6030: [("C", "has_prerequisite", "Houses require a solid foundation to be built on.")],
    6031: [("D", "typical_location", "The master electrical control panel for a home is usually in the basement.")],
    6032: [("D", "effect", "Video games and television alone do not make somebody kill.")],
    6033: [("C", "typical_location", "Melting frozen food should be put back in the fridge to stay cold.")],
    6034: [("C", "typical_location", "People typically store a drill in the garage with other tools.")],
    6035: [("E", "has_prerequisite", "If you want to win a game, you must play it.")],
    6036: [("E", "typical_location", "Disneyland zoos in eastern Asia are places where you might see a gazelle in captivity.")],
    6037: [("B", "typical_location", "Cows commonly live in the great outdoors on farms and pastures.")],
    6038: [("E", "effect", "A spiteful child toward parents commonly responds by acting out.")],
    6039: [("C", "effect", "Entering an air-conditioned room to cool off provides relief from hot weather.")],
    6040: [("B", "typical_location", "Gazelles in the wild are commonly found on open plains.")],
    6041: [("A", "effect", "Discovering an unwanted truth can cause emotional pain.")],
    6042: [("C", "typical_location", "An audience watching a principal speak is typically seated at a school.")],
    6043: [("D", "part_whole", "A bird landing on a branch perches using its two legs.")],
    6044: [("E", "typical_location", "Flowers in a recreation area run by local government are commonly found in a state park.")],
    6045: [("A", "effect", "Summer ends when fall begins as the next season arrives.")],
    6046: [("E", "used_for", "A stapler attaches two pieces of paper together without using glue.")],
    6047: [("B", "effect", "Women expecting to begin procreating are typically awaiting pregnancy.")],
    6048: [("C", "used_for", "After baking cookies, a parent may consume the cookies they made.")],
    6049: [("B", "part_whole", "Australia is both a country and a continent.")],
    6050: [("A", "property", "Someone who goes around killing people might be described as terrible.")],
    6051: [("E", "effect", "Bad shoelaces can come untied and cause a runner to trip over.")],
    6052: [("C", "typical_location", "A violinist commonly stands on a platform in a concert hall.")],
    6053: [("C", "typical_location", "Art galleries are commonly found in a large city.")],
    6054: [("D", "has_prerequisite", "Something you do requires effort and also takes time to complete.")],
    6055: [("A", "typical_location", "People shop for new flooring at stores like Home Depot.")],
    6056: [("B", "typical_location", "Stumbling in dim light with creaky floors and a star map suggests being in an attic.")],
    6057: [("A", "capability", "Sunshine provides light that helps a lemur see its surroundings.")],
    6058: [("A", "has_prerequisite", "Breathing is a key factor in living along with eating and drinking.")],
    6059: [("C", "effect", "Crying when seeing a bill suggests feeling distraught about the cost.")],
    6060: [("C", "typical_location", "New carpeting is typically installed in a home or office.")],
    6061: [("B", "typical_location", "A snake might slither out of underbrush where it was hiding.")],
    6062: [("B", "used_for", "City-building simulation games let a player spend time constructing an entire large city.")],
    6063: [("E", "motivation", "People disappointed by something they are not entitled to must lower their expectations.")],
    6064: [("B", "typical_location", "A released balloon floats upward into the sky.")],
    6065: [("D", "typical_location", "Most people get carrots from a supermarket.")],
    6066: [("A", "used_for", "A child learning about lizards might look up the topic in an encyclopedia.")],
    6067: [("E", "typical_location", "Someone who uses a hammer and tools for work might be employed at a repair shop.")],
    6068: [("E", "effect", "Soldiers returning home after killing in war often feel remorse.")],
    6069: [("E", "property", "In chess, children sometimes mistakenly call a rook a castle.")],
    6070: [("D", "typical_location", "An old lady might hide medicine below cookies inside a jar.")],
    6071: [("A", "typical_location", "People drinking a glass of water are commonly found sitting at a table.")],
    6072: [("E", "typical_location", "A synagogue is a building associated with many books written in Hebrew.")],
    6073: [("A", "property", "A casual business meeting that breaks standard protocol is described as informal.")],
    6074: [("D", "effect", "Drinking alcohol to excess can cause a person to begin vomiting.")],
    6075: [("C", "effect", "Being very rude while expressing yourself may result in being slapped.")],
    6076: [("D", "effect", "A girl who is often ignored may feel happiness when a boy flirts with her.")],
    6077: [("E", "typical_location", "Roommates in a two-bedroom apartment may sleep on the couch when short on beds.")],
    6078: [("E", "effect", "Discovering the truth in a crime gives a policeman increased knowledge of what happened.")],
    6079: [("D", "typical_location", "A weasel may find a home inside a hollow log in the wild.")],
    6080: [("E", "effect", "Without key information, Lorna could not find the solution to her problem.")],
    6081: [("A", "property", "A democracy is a kind of country that has a government.")],
    6082: [("A", "has_prerequisite", "Farmers need farmland as a good starting resource when beginning to farm.")],
    6083: [("C", "capability", "Best friends are often good at keeping secrets for each other.")],
    6084: [("A", "typical_location", "A major convention can fill hotel rooms across an entire state like Michigan.")],
    6085: [("C", "typical_location", "A person can be paid to play a triangle in an orchestra.")],
    6086: [("E", "effect", "After killing with a blunt instrument, there may be no way to clean up the bloody mess.")],
    6087: [("E", "effect", "When years pass since someone was young, they have aged.")],
    6088: [("C", "primary_function", "Real estate agents describing homes often exaggerate features to attract buyers.")],
    6089: [("C", "typical_location", "Litter thrown from a car commonly collects along roadsides.")],
    6090: [("C", "typical_location", "A cat in a house should typically be kept safely inside a room.")],
    6091: [("D", "effect", "After running for 100 miles, a person may suffer shortness of breath from exhaustion.")],
    6092: [("B", "effect", "A building casts a shadow for roughly half of each day as the sun moves across the sky.")],
    6093: [("D", "effect", "Sitting down for a long period of time can lead to flatulence.")],
    6094: [("D", "property", "If you comfort a friend, you are being friendly.")],
    6095: [("A", "effect", "Gaining more land often leads to disputes over boundaries and ownership.")],
    6096: [("B", "typical_location", "A stack of paper not immediately needed is commonly stored in a cabinet.")],
    6097: [("A", "typical_location", "A sloth moves slowly between vines in a tropical jungle.")],
    6098: [("E", "property", "A bicycle is a popular device with children that has two wheels.")],
    6099: [("D", "typical_location", "A snake in the United Kingdom might find hiding places at Kew Gardens.")],
    6100: [("B", "typical_location", "A bowling alley often has mixed carpet and hardwood floors where friends gather for fun.")],
    6101: [("C", "typical_location", "Keeping a marmot in a cage is safer than letting it roam freely.")],
    6102: [("E", "typical_location", "Michigan is the mitten-shaped state where you might find a tennis court.")],
    6103: [("D", "typical_location", "Very high-tech computers are found aboard a space shuttle.")],
    6104: [("D", "typical_location", "Someone can spend money at a store when purchasing goods.")],
    6105: [("A", "effect", "An unexpected and confusing announcement can bring a nation to shock.")],
    6106: [("D", "effect", "Fighting inflation can help prevent a recession in some economic conditions.")],
    6107: [("E", "typical_location", "A student typically keeps a notebook in her backpack when it is not in use.")],
    6108: [("D", "used_for", "In court, hearing testimony helps satisfy curiosity about what happened.")],
    6109: [("C", "effect", "Compared with trains, airplanes tend to arrive late more often due to delays.")],
    6110: [("B", "has_prerequisite", "Before beginning work on a computer, it is necessary to sit down at a workstation.")],
    6111: [("A", "effect", "People who put in no effort in life often end up amounting to nothing.")],
    6112: [("E", "typical_location", "A dental office alongside similar providers is commonly located in a medical building.")],
    6113: [("E", "typical_location", "A personal washing machine is likely to be found in a house.")],
    6114: [("C", "typical_location", "People are likely to kick a ball on a soccer field.")],
    6115: [("D", "typical_location", "A lightning rod cable must be grounded by connecting its end to the ground.")],
    6116: [("E", "effect", "Seeing what others have that you lack commonly causes jealousy.")],
    6117: [("B", "capability", "Calculating attributes often requires mathematical skills such as those used in calculus.")],
    6118: [("A", "effect", "The legal consequence of killing is likely being imprisoned.")],
    6119: [("D", "effect", "Having a light, healthy lunch can leave you feeling satisfied without being overly full.")],
}
