# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 6920-7019 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6920_7019 = {
    6920: [("A", "typical_location", "The nursery rhyme Hey Diddle Diddle features a cow jumping over the moon.")],
    6921: [("D", "effect", "Feet kept in boots all day commonly begin to stink from sweat and bacteria.")],
    6922: [("B", "typical_location", "A library commonly contains many bookshelves holding large book collections.")],
    6923: [("D", "typical_location", "Louisiana is a Gulf Coast delta state widely known for barbecue cuisine.")],
    6924: [("D", "typical_location", "UFO catcher claw machines are commonly found at amusement parks and arcades.")],
    6925: [("A", "used_for", "A brassiere uses adjustable straps that sometimes need tightening for proper fit.")],
    6926: [("D", "typical_location", "A harmonica is a small portable instrument commonly sold at a music store.")],
    6927: [("D", "typical_location", "An unattached building on a small property can serve as a separate playroom.")],
    6928: [("D", "effect", "Forgiving others can bring a sense of new freedom from resentment and vengeance.")],
    6929: [("E", "effect", "Being punched in the nose commonly makes the eyes fill with tears.")],
    6930: [("B", "typical_location", "Casinos and nightclubs both operate late at night and offer drinks and entertainment.")],
    6931: [("D", "used_for", "Archaeologists work to preserve the ruins of lost cities rather than letting them decay.")],
    6932: [("A", "motivation", "People may claim they resist authority even when never explicitly told to obey.")],
    6933: [("A", "typical_location", "Business travelers commonly keep plane tickets and documents in a briefcase.")],
    6934: [("E", "property", "In business accounting, profit is the financial opposite of debt.")],
    6935: [("B", "typical_location", "Chocolate for baking is commonly purchased at a supermarket.")],
    6936: [("C", "effect", "A racing heart during a public outing commonly signals panic or anxiety.")],
    6937: [("D", "used_for", "People watch favorite programs by turning on the television at home.")],
    6938: [("A", "used_for", "Chess lets players control the destiny of imaginary kingdoms on a board.")],
    6939: [("A", "primary_function", "A nonprofit business is organized primarily to help people rather than maximize profit.")],
    6940: [("D", "typical_location", "A drainage ditch helps draw groundwater away from yards.")],
    6941: [("B", "used_for", "Early humans commonly drew pictures on the walls of caves.")],
    6942: [("C", "capability", "Bean plants grow well in direct sunlight.")],
    6943: [("A", "used_for", "A portable CD player is used to play disks on a portable device.")],
    6944: [("B", "effect", "A prisoner who keeps escaping is also frequently being caught again.")],
    6945: [("E", "effect", "Eating too much regularly commonly leads to gaining weight.")],
    6946: [("E", "typical_location", "Politicians in London commonly assemble in Parliament.")],
    6947: [("E", "motivation", "Constant grooming is often done to preserve one's beauty.")],
    6948: [("A", "used_for", "Students expected to recite in class must memorize sections to repeat them aloud.")],
    6949: [("A", "typical_location", "The carotid artery runs through the neck and is vulnerable to injury there.")],
    6950: [("C", "typical_location", "A ranch house with unobstructed mountain views is typically located in open countryside.")],
    6951: [("B", "typical_location", "A fire extinguisher in a single-floor home without a kitchen is commonly stored in the garage.")],
    6952: [("A", "cause", "Cloudy skies block sunlight and prevent the sun from shining through.")],
    6953: [("B", "typical_location", "A round brush used while bathing is commonly stored in the shower.")],
    6954: [("A", "effect", "Having fun is an active awake experience that cannot occur while you are asleep.")],
    6955: [("E", "primary_function", "Someone working at a distillery produces wine or spirits as their job.")],
    6956: [("D", "typical_location", "Families commonly place play mats on the living room floor in front of the TV.")],
    6957: [("C", "typical_location", "An acoustic guitar is commonly played at home during a casual birthday party.")],
    6958: [("A", "part_whole", "Flooring installed above a garage commonly creates a loft living space.")],
    6959: [("B", "typical_location", "Fresh eggs can be obtained from a henhouse instead of buying them at a supermarket.")],
    6960: [("E", "motivation", "A lonely child often wants the presence and attention of parents.")],
    6961: [("C", "part_whole", "An atlas is a book that collects many maps in one volume.")],
    6962: [("D", "property", "Poor-quality clothing is often described as cheap rather than well made.")],
    6963: [("A", "effect", "People facing difficulties commonly find they need each other for support.")],
    6964: [("B", "effect", "Playing one-armed bandit slot machines involves spending money on each spin.")],
    6965: [("E", "typical_location", "Leaves for a collection are commonly gathered from trees in a forest.")],
    6966: [("A", "typical_location", "Western Texas is a large southern region of the United States with many venomous snakes.")],
    6967: [("B", "typical_location", "Someone refusing to pick a side between friends typically stands in between them.")],
    6968: [("E", "typical_location", "Staplers and index cards are commonly purchased at an office supply store.")],
    6969: [("E", "typical_location", "People may spend long hours playing video games at an internet cafe.")],
    6970: [("C", "property", "Despite technological progress, all people remain fundamentally human.")],
    6971: [("E", "typical_location", "Barefoot walking on pavement heated by sunshine is commonly done on a street.")],
    6972: [("C", "part_whole", "Modern high-rise buildings are often largely made of glass windows.")],
    6973: [("A", "typical_location", "Bees are popular pollinators across gardens throughout the United States.")],
    6974: [("B", "typical_location", "Beautiful cars are commonly displayed at car shows.")],
    6975: [("D", "typical_location", "A sofa bed is a practical guest sleeping option for a living room with frequent visitors.")],
    6976: [("B", "capability", "Elderly people commonly have weaker immune systems and get illnesses more often.")],
    6977: [("A", "effect", "Contraceptive devices are designed to prevent the creation of a new person.")],
    6978: [("B", "motivation", "A person who studies constantly may be trying to know everything.")],
    6979: [("E", "cause", "Operating a vehicle through driving is what causes a car to move.")],
    6980: [("A", "typical_location", "Water flowing through a hydroelectric dam turns turbines to generate electricity.")],
    6981: [("B", "used_for", "Two people sharing a common goal can accomplish it by working together.")],
    6982: [("E", "typical_location", "Work-from-home software is installed on a computer for remote use.")],
    6983: [("B", "typical_location", "Actors in a theater may pretend to be action figures during a performance without selling toys.")],
    6984: [("B", "typical_location", "Candy stays fresh longer when stored in a sealed jar.")],
    6985: [("A", "typical_location", "Children commonly deposit coins into a piggy bank kept in their room.")],
    6986: [("E", "property", "Mathematics is often considered a purer subject than applied science.")],
    6987: [("D", "typical_location", "A nearby grocery store means the store is in your neighborhood.")],
    6988: [("B", "property", "Randomly fiddling a fiddle produces unpredictable song choices.")],
    6989: [("E", "motivation", "Social people often view socializing as a way of having fun.")],
    6990: [("E", "part_whole", "A tissue holder requested at a dealership is installed in a car.")],
    6991: [("D", "typical_location", "Beavers build lodges and call wooded stream areas their home.")],
    6992: [("E", "effect", "Waiting until the last minute to buy Christmas presents commonly causes stress.")],
    6993: [("E", "effect", "Live show producers often worry whether the performance will broadcast properly.")],
    6994: [("C", "typical_location", "Gazelles run and jump across open steppe terrain to escape predators.")],
    6995: [("A", "property", "Someone avoiding tight clothes would refuse close fitting garments that show curves.")],
    6996: [("B", "used_for", "A cashier tells customers they must spend money to buy food.")],
    6997: [("E", "typical_location", "Cinderella is a classic character found in fairy tales.")],
    6998: [("A", "property", "Cutting yourself on a sharp object despite warnings suggests being unobservant.")],
    6999: [("C", "used_for", "Having lunch means eating food during the midday meal.")],
    7000: [("E", "effect", "Standing in a lit room causes a person's body to cast a shadow.")],
    7001: [("C", "effect", "A tough judge in a court case may sentence a guilty defendant to go to jail.")],
    7002: [("A", "typical_location", "People flee an opera house when someone shouts fire during a performance.")],
    7003: [("B", "typical_location", "Most people eat the majority of their meals at home.")],
    7004: [("B", "used_for", "An archaeologist puzzled by artifacts begins thinking through possible explanations.")],
    7005: [("A", "motivation", "Jogging faster and faster is commonly done to improve cardiovascular fitness.")],
    7006: [("E", "part_whole", "Casino slot machines often have card slots for member loyalty points.")],
    7007: [("E", "has_prerequisite", "Employees struggling at work attend meetings to improve their understanding of tasks.")],
    7008: [("B", "effect", "Satisfied customers commonly smile after being served well.")],
    7009: [("A", "typical_location", "Old clothes can be stored in a large rectangular trunk to keep moths away.")],
    7010: [("D", "motivation", "Curiosity about what is on television leads someone to watch their favorite show.")],
    7011: [("A", "typical_location", "Washington state borders the Pacific Ocean and offers coastal condominium locations.")],
    7012: [("A", "typical_location", "Someone finding a hide-a-bed uncomfortable may choose to stay at a hotel instead.")],
    7013: [("D", "property", "A bulky older blanket feels cumbersome compared with a lighter blanket.")],
    7014: [("C", "effect", "Admiring an opponent's score while losing a competition commonly triggers jealousy.")],
    7015: [("C", "used_for", "Married couples commonly conceive children by making love.")],
    7016: [("C", "effect", "Friends advise a new church member to get in shape so they will feel better.")],
    7017: [("E", "has_prerequisite", "Becoming great at fiddling requires extensive practice over time.")],
    7018: [("A", "typical_location", "Clothes purchased at stores are commonly carried home in a shopping bag from a retail store.")],
    7019: [("A", "typical_location", "Clothing bought at a store is commonly placed in a shopping bag at a retail store.")],
}
