# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7520-7619 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_7520_7619 = {
    7520: [("E", "typical_location", "After a party, the dining room often needs cleaning from spilled food and dishes.")],
    7521: [("D", "property", "Films are a popular form of entertainment enjoyed before bedtime.")],
    7522: [("A", "typical_location", "A classroom is where schoolchildren gather during the school day.")],
    7523: [("C", "has_prerequisite", "An organism requires food consumed to sustain life and continue living.")],
    7524: [("D", "used_for", "Children often make each other laugh by tickling one another.")],
    7525: [("A", "property", "Finding a needle in a haystack is proverbially very difficult.")],
    7526: [("A", "effect", "Rain water falling from the sky is generally welcomed by people and plants.")],
    7527: [("D", "typical_location", "Football stadiums have bleachers where spectators watch large athletes run.")],
    7528: [("E", "typical_location", "A small appointment book is commonly carried in a pocket.")],
    7529: [("B", "typical_location", "A city cat often lives in a back alley near buildings.")],
    7530: [("E", "typical_location", "Salt is commonly kept on the table during meals.")],
    7531: [("D", "used_for", "A man might give a penny to a communal pot before another person takes one.")],
    7532: [("D", "effect", "First sexual experience is often described as painful for some girls.")],
    7533: [("C", "typical_location", "England is famously foggy, associated with tea culture, and ruled by a monarch.")],
    7534: [("C", "typical_location", "A sofa in a bedroom provides a place to relax besides the bed.")],
    7535: [("B", "part_whole", "A handsome prince is a stock character common to fairy tales.")],
    7536: [("B", "effect", "A child taken against its will is taken away from its parents.")],
    7537: [("A", "typical_location", "People find milk for sale at a supermarket.")],
    7538: [("A", "typical_location", "Chairs are typically set on the floor surface.")],
    7539: [("E", "effect", "When a child reaches their late teens they typically become an adult.")],
    7540: [("D", "property", "Idle children sitting around without activity often appear bored.")],
    7541: [("A", "capability", "Pregnancy shows that someone can create new life, surprising those who felt destructive.")],
    7542: [("E", "effect", "Getting a cold leads to illness that people dread.")],
    7543: [("C", "typical_location", "Canned goods are commonly kept behind a cupboard door in kitchens.")],
    7544: [("A", "effect", "Pulling a muscle is an unwanted outcome, not a reason to go running.")],
    7545: [("D", "typical_location", "A group of bungalows in a small area forms a neighborhood.")],
    7546: [("C", "typical_location", "Ballparks are known for selling peanuts and Cracker Jack at games.")],
    7547: [("B", "part_whole", "Asia is an example of a continent on Earth.")],
    7548: [("E", "effect", "Viewing pastoral scene paintings in a museum can evoke a feeling of peace.")],
    7549: [("B", "part_whole", "The human body contains organs that are biological, not musical instruments.")],
    7550: [("A", "typical_location", "A senior looking to take a year off is likely in highschool or college.")],
    7551: [("C", "typical_location", "Most buildings are located above ground rather than underground.")],
    7552: [("E", "typical_location", "In a courtroom the person beside you may carry a briefcase and you may stand accused.")],
    7553: [("D", "used_for", "Filling up a shopping cart means purchasing items at a store.")],
    7554: [("A", "used_for", "Pronouns can function as objects of prepositions referring to someone.")],
    7555: [("D", "effect", "Playing the violin often stirs up feelings in a person.")],
    7556: [("E", "typical_location", "A bucket raised from a well comes up empty when the well has run dry.")],
    7557: [("A", "typical_location", "A drawing room is a central feature located in a mansion or palatial estate.")],
    7558: [("D", "typical_location", "Supermarket delivery trucks commonly carry food containers for unloading.")],
    7559: [("E", "effect", "Achieving something commonly makes a person feel proud.")],
    7560: [("B", "used_for", "Having lunch always involves eating food.")],
    7561: [("A", "used_for", "Film studios spend large amounts of money producing movies.")],
    7562: [("B", "has_prerequisite", "When ending a marriage you often need a lawyer.")],
    7563: [("C", "effect", "Ending painful family phone calls can stem from feeling too much regret.")],
    7564: [("C", "motivation", "People spend money in order to buy things.")],
    7565: [("C", "typical_location", "People normally leave a home through the front door rather than a window.")],
    7566: [("A", "effect", "Standing in a queue means waiting for your turn.")],
    7567: [("B", "typical_location", "Seattle is a city famously known for frequent rain.")],
    7568: [("E", "typical_location", "Patrons leaving during a film because of broken AC are exiting a movie theatre.")],
    7569: [("D", "used_for", "Ball bearings are commonly used in machines to allow smooth movement.")],
    7570: [("D", "effect", "Successfully cashing a check often brings great joy.")],
    7571: [("A", "used_for", "Being able to buy a house is one way children please their parents.")],
    7572: [("B", "effect", "Reading newspapers nowadays can lead to aggravation over distressing news.")],
    7573: [("D", "typical_location", "A fish market is a specialty location to buy large quantities of crab.")],
    7574: [("E", "capability", "A bird scoops up more air by spreading its wings.")],
    7575: [("C", "typical_location", "An unused ottoman with no room elsewhere is often stored in the basement.")],
    7576: [("E", "effect", "Without a father's help a person would likely feel disappointed.")],
    7577: [("E", "used_for", "Buying something at a busy store often requires waiting in line.")],
    7578: [("D", "effect", "Someone without gardening skill often finds plants die despite efforts to grow them.")],
    7579: [("B", "property", "Going out often and talking to many people indicates an active social life.")],
    7580: [("A", "used_for", "Knowing what to do to achieve dreams leads a person to spring into action.")],
    7581: [("C", "typical_location", "A sixteen-year-old on a football team likely plays on a high school field.")],
    7582: [("A", "typical_location", "A fraternity gymnasium is most likely located on a college campus.")],
    7583: [("E", "used_for", "A potato can be eaten topped with sour cream and cheese.")],
    7584: [("A", "typical_location", "Train tickets are commonly bought in person at a ticket booth.")],
    7585: [("B", "effect", "After the initial shock passes a person typically settles and feels calm.")],
    7586: [("B", "typical_location", "A coffeepot hitting the ground can spill hot liquid when its handle breaks.")],
    7587: [("B", "typical_location", "Fungus may be studied and found in a university biology laboratory.")],
    7588: [("C", "property", "Being chosen to go on stage after an audition suggests you have talent.")],
    7589: [("C", "typical_location", "A garden would be extremely valuable for food and shade in a desert.")],
    7590: [("E", "effect", "Seeing an idea become reality after years of work calls for celebration.")],
    7591: [("A", "property", "Covering wood thinly with gold metal is called gilding.")],
    7592: [("C", "cause", "Loss of soldiers' lives in a general's apology typically occurs during war.")],
    7593: [("C", "typical_location", "Local fans showcase athletes at their home stadium.")],
    7594: [("C", "used_for", "The opposite of dissociating from someone is to join with them.")],
    7595: [("A", "part_whole", "Most people wear shoes and socks on their feet.")],
    7596: [("A", "typical_location", "Columbia is a city in the state of South Carolina.")],
    7597: [("D", "motivation", "Putting on soft music at the end of the day helps a person relax.")],
    7598: [("B", "typical_location", "Medics help soldiers in the middle of fighting on the battlefield.")],
    7599: [("A", "typical_location", "Someone might learn about a piccolo in a music class.")],
    7600: [("A", "primary_function", "A police officer may direct traffic when power outages disable signals.")],
    7601: [("A", "effect", "Completing art to satisfaction can bring a feeling of enlightenment.")],
    7602: [("E", "typical_location", "A frisbee in play is most likely flying through the air.")],
    7603: [("A", "used_for", "Ball projectiles are historically shot from a cannon.")],
    7604: [("B", "used_for", "Seeing a friend nearby commonly prompts a person to wave.")],
    7605: [("C", "effect", "Quietly biting nails often signals that someone is experiencing anxiety.")],
    7606: [("D", "typical_location", "An excavation site may be located near a quarry where earth is removed.")],
    7607: [("E", "typical_location", "Fairgrounds are known for selling lots of fried foods on sticks.")],
    7608: [("D", "effect", "After four years of study a student is finally able to graduate.")],
    7609: [("D", "property", "Thick sunscreen helps make skin sun-resistant for those sensitive to sunlight.")],
    7610: [("C", "typical_location", "Casinos are the most likely places to find many gamblers.")],
    7611: [("B", "motivation", "A person dressed as a clown hopes to make others happy.")],
    7612: [("C", "used_for", "Someone who needs to eat should be getting food.")],
    7613: [("A", "used_for", "People in love commonly kiss when they are alone together.")],
    7614: [("A", "effect", "An unripe sugary banana bite can taste overly sweet and cloy on the palate.")],
    7615: [("A", "typical_location", "Large cuts of meat needing hours of cooking are placed in an oven.")],
    7616: [("B", "effect", "Better understanding of people around you can lead to deeper compassion.")],
    7617: [("D", "used_for", "A thirsty person should drink water.")],
    7618: [("A", "used_for", "A friend already at the fishing spot surprises you by saying he is catching fish.")],
    7619: [("C", "used_for", "Someone with hair long enough for a ponytail heads to a salon to have it cut.")],
}
