# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 8320-8419 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8320_8419 = {
    8320: [("B", "effect", "Going public about a controversial issue is likely to bring consequences from critics and supporters.")],
    8321: [("E", "has_prerequisite", "Proving you own a home may require showing a deed or mortgage document.")],
    8322: [("D", "used_for", "Reports are commonly printed by loading paper into a computer printer.")],
    8323: [("E", "effect", "An overbearing parent who makes a child earn their value can leave the child feeling worthlessness.")],
    8324: [("B", "effect", "A fisherman who waits a long time without getting bites is likely to feel boredom.")],
    8325: [("D", "motivation", "After a day at work, people commonly take a bus to go home.")],
    8326: [("B", "typical_location", "A curling iron is commonly used in the bathroom near a mirror and electrical outlet.")],
    8327: [("B", "part_whole", "Many vacuums store collected dirt inside an internal container or bag.")],
    8328: [("B", "used_for", "Motion capture with human performers is commonly used when producing movies with animated characters.")],
    8329: [("E", "typical_location", "A snake seeking warmth next to a camper may crawl into a sleeping bag.")],
    8330: [("E", "typical_location", "A taxiplane is an obscure aircraft concept, not a place where you would normally find a taxi.")],
    8331: [("D", "effect", "When people feel anger toward each other, they sometimes fight.")],
    8332: [("C", "used_for", "To hear music in a car, a person can listen to the radio.")],
    8333: [("A", "property", "Sexual acts a partner agrees to may be described as fine if that is what you're into.")],
    8334: [("D", "typical_location", "Potatoes ordered by a chef are commonly prepared and placed on a customer's plate.")],
    8335: [("D", "typical_location", "Colorado is a mile-high state where a marmoset would only be found in a zoo.")],
    8336: [("C", "typical_location", "Mammoth remains are commonly found during archaeological excavations.")],
    8337: [("D", "typical_location", "A bowling alley produces loud impact noises that are hard to drown out with a radio.")],
    8338: [("A", "used_for", "Coal is commonly used as fuel to light and sustain a fire.")],
    8339: [("A", "effect", "If a spouse abandons you, the marriage has effectively stopped.")],
    8340: [("A", "typical_location", "Someone charged with killing people is likely to end up going to jail.")],
    8341: [("D", "effect", "Farting in public away from home may cause public disapproval from nearby people.")],
    8342: [("B", "effect", "A museum visitor who realizes an object is missing is likely to feel shock.")],
    8343: [("C", "typical_location", "People commonly keep a television in the bedroom for watching before retiring at night.")],
    8344: [("E", "capability", "A balloon uses heated or lighter-than-air gas to float through the air.")],
    8345: [("B", "property", "Someone thought to be mean may actually turn out to be nice once you know them better.")],
    8346: [("E", "has_prerequisite", "To pass a class you typically must finish all homework assignments completed away from school.")],
    8347: [("C", "typical_location", "A small dog that envies sled dogs pulling people through snow likely lives in Canada.")],
    8348: [("D", "typical_location", "Before a farmer collects them, eggs are commonly found in a chicken coop.")],
    8349: [("B", "typical_location", "The closest place in a home to find a potato is commonly a kitchen cupboard.")],
    8350: [("A", "effect", "After eating some turkey, a person is likely to be full.")],
    8351: [("D", "effect", "Losing a soccer game commonly causes a player to feel anger.")],
    8352: [("C", "primary_function", "A priest who cannot speak can still pray silently as part of religious devotion.")],
    8353: [("C", "effect", "Running after a ball on a hot summer day commonly causes a person's body to start sweating.")],
    8354: [("C", "effect", "People commonly express audibly that they are having fun through laughter.")],
    8355: [("B", "effect", "Becoming inebriated from alcohol leads to a state of drunkenness.")],
    8356: [("C", "used_for", "After learning about science, people often conduct an experiment to test what they learned.")],
    8357: [("E", "used_for", "People who love chatting with friends use all sorts of communication methods to keep in touch.")],
    8358: [("E", "typical_location", "Someone who does math at work commonly keeps a calculator open on their desktop.")],
    8359: [("B", "typical_location", "A horse and buggy rental offers a unique way to see Central Park.")],
    8360: [("E", "typical_location", "Excavation at a construction site begins with establishing a good foundation.")],
    8361: [("D", "motivation", "Going to a club euphemistically may mean wanting to get down and dance.")],
    8362: [("C", "typical_location", "A school bell commonly signals the end of a scheduled class period.")],
    8363: [("E", "primary_function", "The usual purpose of a vehicle is to carry people or goods so they can travel.")],
    8364: [("B", "effect", "A person in jail commonly receives letters from loved ones on the outside.")],
    8365: [("D", "typical_location", "Melted cheese is commonly found on a hot pizza fresh from the oven.")],
    8366: [("D", "used_for", "You use a television show or video player to see a clip on screen.")],
    8367: [("B", "used_for", "An easy way to make a potato soft is to boil it in a cooking pot.")],
    8368: [("B", "property", "Fine-tuning an important measurement often requires making only a slight increase.")],
    8369: [("E", "capability", "Children who play cards often cannot remember the original rules and invent their own.")],
    8370: [("E", "typical_location", "Uniformed officials commonly search travelers for terrorists at an airport security checkpoint.")],
    8371: [("B", "used_for", "A backpack with a pet compartment is a good way to carry a small dog.")],
    8372: [("D", "used_for", "Standing in queue at a store gives you time to look around at your surroundings.")],
    8373: [("E", "part_whole", "A hand-carved pawn is a fine piece belonging to a chess set.")],
    8374: [("D", "effect", "Someone involved in a precarious rescue can get hurt if conditions turn dangerous.")],
    8375: [("D", "capability", "A boat is a wet vehicle that you steer with a wheel or tiller on the water.")],
    8376: [("A", "effect", "When people are honest, they tend to tell the truth rather than lie.")],
    8377: [("E", "effect", "Climbing for a long time commonly causes painful blisters to form on the hands.")],
    8378: [("C", "used_for", "Adults commonly dress themselves without needing help putting on clothing.")],
    8379: [("E", "typical_location", "A curious ferret will often crawl up a person's trouser leg.")],
    8380: [("E", "effect", "Anger builds up emotional tension inside you that may release energy when expressed.")],
    8381: [("E", "effect", "Learning about science commonly leads to increased knowledge about how things work.")],
    8382: [("A", "typical_location", "A railing installed on a home deck can block the view when you sit outside on it.")],
    8383: [("A", "part_whole", "A terrace planned to be covered in green plants completes the dream garden.")],
    8384: [("B", "primary_function", "Teachers play many roles, but they get the most fulfillment from simply teaching children.")],
    8385: [("E", "cause", "Children may run out of a house quickly if they smell smoke indicating fire.")],
    8386: [("D", "part_whole", "Arkansas is a state located within the United States.")],
    8387: [("B", "property", "In Paris you can expect to see a French wine list at restaurants.")],
    8388: [("B", "used_for", "A broadcast host adjusts his microphone so the audience can hear clearly.")],
    8389: [("B", "typical_location", "Someone in a drawing room may go to a studio to have an architectural draft completed.")],
    8390: [("B", "used_for", "One of the best ways to improve at wrestling is to take lessons from a coach.")],
    8391: [("D", "property", "Religious parents may find it wrong when a child stops being married to an ex-spouse.")],
    8392: [("A", "effect", "Someone celebrating with way too many beers may still succeed in having fun.")],
    8393: [("B", "cause", "Someone may not want to sit down next to you if you smell bad.")],
    8394: [("B", "typical_location", "Hair gel is commonly stored in the bathroom near where you shower and get clean.")],
    8395: [("B", "effect", "If you decide to go somewhere an hour away, you would be arriving there in about an hour.")],
    8396: [("D", "typical_location", "You could see a moving weasel that is not real in an animated film.")],
    8397: [("A", "used_for", "People commonly dance when listening to upbeat music.")],
    8398: [("D", "effect", "An idea becoming reality can sometimes bring pain instead of the expected joy.")],
    8399: [("C", "primary_function", "Taking a phone call is a form of communication that connects distant people.")],
    8400: [("C", "typical_location", "A child's first violin is commonly purchased at a music store.")],
    8401: [("E", "typical_location", "A can of food is commonly stored in a kitchen cabinet at home.")],
    8402: [("E", "typical_location", "If you need to find where a committee meets, you would start by locating the boardroom.")],
    8403: [("D", "part_whole", "Fully loaded cars still have spacious trunks for additional storage.")],
    8404: [("D", "effect", "Someone farting silently may have gotten away with it without making noise.")],
    8405: [("B", "has_prerequisite", "A person who has run all day and feels tired needs time to rest.")],
    8406: [("E", "property", "A house is commonly owned by a person and may have a second floor.")],
    8407: [("E", "effect", "A stingy boss may push down or reject an employee's request for a raise.")],
    8408: [("E", "typical_location", "Feather-stuffed pillows are less common because many people are allergic to feathers.")],
    8409: [("D", "typical_location", "A can of corn is commonly kept in the pantry with other canned goods.")],
    8410: [("C", "typical_location", "You might find an imaginary blue apple tree illustrated in a coloring book.")],
    8411: [("A", "typical_location", "Someone who breaks a musical triangle may go to a music shop for a replacement.")],
    8412: [("A", "typical_location", "Most birds lay and keep their eggs in a nest.")],
    8413: [("B", "typical_location", "Index cards on display at a museum may be featured in a library-themed exhibit.")],
    8414: [("D", "motivation", "A sick person with a project to finish may choose to work at home rather than go in.")],
    8415: [("B", "typical_location", "You can buy a bugle at a music store and take it home with you.")],
    8416: [("D", "primary_function", "A lawn mower has a spinning blade that cuts living grass plants.")],
    8417: [("A", "property", "When a plate is thrown through the air, the space inside its arc is filled with air.")],
    8418: [("A", "typical_location", "The best place to keep ice cream from melting is a freezer.")],
    8419: [("C", "capability", "A toddling child who is learning about the world is gaining greater mobility.")],
}
