# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 8020-8119 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8020_8119 = {
    8020: [("A", "typical_location", "A county's elected representative carries local influence to Washington, D.C.")],
    8021: [("E", "typical_location", "Antarctica is the coldest place where a balcony would leave someone chilled.")],
    8022: [("D", "effect", "When two people compete against each other, one winner typically emerges.")],
    8023: [("B", "cause", "Drinking alcohol causes disorientation that impairs driving and leads to crashes.")],
    8024: [("A", "part_whole", "Bookends are sold and used as a matching pair to support books on a shelf.")],
    8025: [("A", "typical_location", "A football field drawing over a hundred thousand fans is often the most popular spot on a college campus.")],
    8026: [("D", "effect", "After doing wrong and sensing judgment from others, a person commonly begins feeling guilty.")],
    8027: [("E", "typical_location", "Indian restaurants are commonly found throughout many large cities around the world.")],
    8028: [("B", "effect", "Working hard commonly improves a person's situation and leads to a better life.")],
    8029: [("C", "typical_location", "The back yard is the lawn people care about less because visitors rarely see it.")],
    8030: [("A", "typical_location", "A bedroom has pillows on the bed that may be hidden from view depending on where you stand.")],
    8031: [("B", "typical_location", "A gentleman may own a big house and go inside it as his residence.")],
    8032: [("C", "property", "Dogs are omnivores, meaning they consume both plants and meat.")],
    8033: [("B", "typical_location", "An expert in hieroglyphics would excavate at archaeological sites in Egypt.")],
    8034: [("A", "effect", "Successfully fighting inflation can eventually lead to lower prices appearing at stores.")],
    8035: [("D", "typical_location", "A mother reads a bedtime story to a child from a book of stories.")],
    8036: [("E", "effect", "Spending too much time intensely jogging can strain the heart and cause heart attacks.")],
    8037: [("A", "typical_location", "A cow that does not exist appears only in a fictional story book.")],
    8038: [("C", "used_for", "Television broadcasts programs that deliver information through both audio and video.")],
    8039: [("C", "effect", "Watching your team lose a game commonly causes feelings of stress.")],
    8040: [("D", "typical_location", "A newspaper delivery boy tosses the paper onto the homeowner's porch.")],
    8041: [("D", "used_for", "A doctor uses an armband blood-pressure cuff to check readings and may prescribe medicine to lower blood pressure.")],
    8042: [("B", "typical_location", "A battle in a video game is simulated combat, not a real armed conflict.")],
    8043: [("E", "used_for", "Reading books on a subject is a common way to further knowledge about it.")],
    8044: [("E", "typical_location", "When the kitchen sink is clogged, dishes can be washed in another sink such as the laundry room.")],
    8045: [("C", "typical_location", "Keeping one hand on the wall is the simplest way to avoid backtracking in a labyrinth.")],
    8046: [("E", "motivation", "With a broken oven and microwave, Billy needed money so he could buy food.")],
    8047: [("C", "typical_location", "A bachelor living alone commonly has an unclean sink in his apartment.")],
    8048: [("D", "typical_location", "A patient waits in a dentist's office before getting an x-ray of the jaw.")],
    8049: [("B", "effect", "A drunken person who passes out often shows vomiting as a sign of sickness beforehand.")],
    8050: [("A", "typical_location", "People in densely populated areas commonly live in small spaces such as an apartment.")],
    8051: [("A", "typical_location", "Children often drop a coin into a wishing well on weekend outings.")],
    8052: [("D", "typical_location", "Without his own screwdriver, John would take his lawnmower to a repair shop.")],
    8053: [("B", "effect", "A pet that its owner does not care for commonly suffers from neglect.")],
    8054: [("E", "effect", "Mosquitoes about to be swatted will fly away to survive.")],
    8055: [("D", "effect", "An outfit that cleaning cannot salvage is already ruined beyond repair.")],
    8056: [("C", "typical_location", "A dog playing outside can get completely dirty from mud and dirt.")],
    8057: [("A", "effect", "A drunk person with an unsteady stride is commonly staggering while walking.")],
    8058: [("A", "motivation", "When you comfort a friend, you feel care and concern for them.")],
    8059: [("D", "typical_location", "Monks in a monastery who are not blood relatives often call each other brother.")],
    8060: [("E", "typical_location", "Boxes of products are stored in bulk at a warehouse.")],
    8061: [("E", "typical_location", "A Canadian traveling in the American southwest might visit New Mexico.")],
    8062: [("D", "property", "A chemise is a flapper-era garment with thin shoulder straps.")],
    8063: [("E", "typical_location", "Hunting guns are sold at a sporting goods store.")],
    8064: [("B", "used_for", "The internet is a fairly new way to access information compared with books and libraries.")],
    8065: [("A", "typical_location", "A snake's nest is likely to contain a nest full of babies.")],
    8066: [("A", "capability", "A computer programmed to think autonomously can theoretically make decisions on its own.")],
    8067: [("A", "effect", "Having many errands and very little time commonly causes stress.")],
    8068: [("D", "typical_location", "Employees usually work for a company that hires and pays them.")],
    8069: [("C", "used_for", "A person uses their hand to hold and write with a steel pen.")],
    8070: [("B", "capability", "Remembering facts on a test demonstrates the knowledge a student has acquired.")],
    8071: [("B", "typical_location", "Someone wanting a new ottoman would shop at a furniture store.")],
    8072: [("E", "effect", "A person who yawns and paces while waiting is likely feeling boredom.")],
    8073: [("B", "typical_location", "Knives you plan to bring outside are commonly packed in a backpack.")],
    8074: [("A", "typical_location", "When not in use, an automobile is commonly parked in a garage.")],
    8075: [("B", "typical_location", "Manhattan is a dense island where skyscrapers blend into a panoramic cityscape.")],
    8076: [("A", "part_whole", "Measuring from each edge helps locate the dead center of an object.")],
    8077: [("C", "typical_location", "Outside of a zoo, marmosets are native to tropical regions such as Venezuela.")],
    8078: [("A", "typical_location", "A cemetery surrounded by many houses and businesses is located in a city.")],
    8079: [("D", "typical_location", "If you need marble and have none, you can buy it at a store.")],
    8080: [("B", "has_prerequisite", "Going to market requires traveling to reach the shopping destination.")],
    8081: [("E", "effect", "Being taken somewhere against your will means you get somewhere involuntarily.")],
    8082: [("E", "used_for", "Someone seeking information about adopted parents must ask questions of records or relatives.")],
    8083: [("A", "typical_location", "Michigan is the glove-shaped state where you can eat at a delicatessen.")],
    8084: [("E", "used_for", "On a second and final attempt, a high jumper is trying to break a record.")],
    8085: [("C", "effect", "Standing in line accomplishes waiting your turn for service.")],
    8086: [("D", "typical_location", "Toilet water is contaminated and should not be drunk.")],
    8087: [("D", "typical_location", "An active soldier on deployment is likely to sleep in a tent.")],
    8088: [("B", "typical_location", "A jellyfish is not likely to be found alive in a retail store.")],
    8089: [("C", "effect", "Dying from suffocation means the body has no more air to breathe.")],
    8090: [("D", "typical_location", "A pilot is most easily found at or near an airplane.")],
    8091: [("C", "effect", "People competing for scarce resources commonly experience aggression.")],
    8092: [("B", "typical_location", "Marbles bought in a bag are commonly kept stored in a jar at home.")],
    8093: [("E", "motivation", "You want to have food when you are hungry.")],
    8094: [("E", "effect", "Placing a napkin under a cup on a table helps avoid leaving a water mark.")],
    8095: [("B", "used_for", "Many different building materials are needed to construct a house for people.")],
    8096: [("C", "typical_location", "Quebec in Canada is known for excellent French restaurants outside the United States.")],
    8097: [("E", "property", "Getting wet means your clothes or body are not dry.")],
    8098: [("B", "part_whole", "Bones must be removed from a fish before serving a fillet.")],
    8099: [("D", "motivation", "Some students drop out of school to gain more leisure time.")],
    8100: [("B", "typical_location", "Water in the sky comes from rain clouds that form from evaporated moisture.")],
    8101: [("C", "typical_location", "Someone hungry enough to eat a whole cow might go to a butcher shop.")],
    8102: [("D", "effect", "Students learning difficult science material often show frustration on their faces.")],
    8103: [("A", "effect", "After winning a race, competitors commonly celebrate their victory.")],
    8104: [("E", "typical_location", "Non-perishable food at home is commonly stored in the pantry.")],
    8105: [("C", "typical_location", "Captured elephants are kept on display at a zoo.")],
    8106: [("C", "typical_location", "After returning from travel, a person commonly puts luggage away in a closet.")],
    8107: [("B", "part_whole", "Many fingers are found together on a hand.")],
    8108: [("C", "typical_location", "A road passing residences, stores, and public buildings runs through a town.")],
    8109: [("D", "typical_location", "A ventilation system should be closed in a hospital to prevent spread of airborne illness.")],
    8110: [("C", "typical_location", "Grapes for wine are often grown at a winery that produces an intoxicating beverage.")],
    8111: [("C", "used_for", "Exercise is widely considered the best way to release pent-up energy.")],
    8112: [("E", "motivation", "Hunger is an effective motivator for having lunch.")],
    8113: [("D", "used_for", "Friends in elementary school commonly play together during recess activities like jump rope.")],
    8114: [("B", "effect", "After only ten seconds in an ice bath, an athlete quickly develops chills.")],
    8115: [("A", "typical_location", "The audience of a Broadway show claps inside the theatre.")],
    8116: [("D", "typical_location", "A young person without a job commonly goes to school instead of work.")],
    8117: [("B", "typical_location", "Keeping up with the Joneses by maintaining a perfect lawn is a classic suburban habit in suburbia.")],
    8118: [("D", "used_for", "Waitresses commonly refill a customer's cup during a meal.")],
    8119: [("D", "typical_location", "A marmoset would be out of place in an indoor shopping mall.")],
}
