# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 8920-9019 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8920_9019 = {
    8920: [("E", "typical_location", "A creature too large to fit through doorways would remain stuck outside.")],
    8921: [("A", "typical_location", "Leftovers from cooking are commonly stored in a refrigerator to keep them fresh.")],
    8922: [("B", "property", "A flashy new car is a common way to show that someone can afford expensive things.")],
    8923: [("A", "typical_location", "Cincinnati is a city located in the state of Ohio.")],
    8924: [("B", "typical_location", "Most adult Americans divide their weekday time between home and work.")],
    8925: [("B", "typical_location", "Many of the world's most famous ancient temples are located in the Middle East.")],
    8926: [("A", "typical_location", "Hospital waiting rooms are places where sadness is often present.")],
    8927: [("C", "typical_location", "A piano owned for personal use is commonly kept in a music room at home.")],
    8928: [("D", "motivation", "Dogs that want to play often try to go outside.")],
    8929: [("A", "typical_location", "A receptionist in a lobby is the person visitors ask for directions.")],
    8930: [("E", "effect", "Filing a lawsuit against a rival commonly increases tensions between the parties.")],
    8931: [("D", "effect", "Eating breakfast in bed risks spills that can dirty clean sheets.")],
    8932: [("B", "property", "A purse carried by many women is also commonly called a handbag.")],
    8933: [("C", "motivation", "Couples may seek divorce partly to keep their children from suffering in a bad marriage.")],
    8934: [("C", "motivation", "A competitive person who likes games usually aims to win.")],
    8935: [("B", "motivation", "Most people play games primarily for entertainment.")],
    8936: [("E", "effect", "Steam exposed to cold air quickly condenses and disappears from view.")],
    8937: [("B", "typical_location", "Living with at least two other people often follows getting married and sharing a household.")],
    8938: [("C", "typical_location", "An adult collector of toy cars typically keeps them at their own home.")],
    8939: [("C", "typical_location", "A bean bag chair placed in a family room can be used by everyone in the household.")],
    8940: [("B", "typical_location", "Children commonly throw a ball around on a playground.")],
    8941: [("B", "typical_location", "A nature preserve is a protected area that safeguards animals such as the bald eagle.")],
    8942: [("D", "typical_location", "Washington State in the Pacific Northwest is known for its many apple orchards.")],
    8943: [("B", "part_whole", "Just as a forward comes before an essay, an afterword comes at the end of it.")],
    8944: [("A", "part_whole", "A bicycle uses a chain to drive the rear wheel.")],
    8945: [("D", "typical_location", "Someone who lives by the shore most likely lives in a seaside town.")],
    8946: [("C", "used_for", "To eat lunch at home you first need to get food from the kitchen.")],
    8947: [("C", "typical_location", "The base of a stack of cubes rests on the floor.")],
    8948: [("B", "property", "Sunshine and warmth are weather conditions commonly associated with summer.")],
    8949: [("C", "typical_location", "A mouse in a densely populated area may seek shelter in abandoned houses.")],
    8950: [("B", "typical_location", "An alley party is a setting where illegal drug use is sometimes associated.")],
    8951: [("C", "typical_location", "Pleasure gardens are a tradition often traced to English courtyard design.")],
    8952: [("E", "property", "When the cost of a purchase outweighs its benefit, the expense is not worthwhile.")],
    8953: [("A", "typical_location", "A restaurant known for fresh grilled food is often a local favorite dining spot.")],
    8954: [("A", "effect", "Animals that eat well and take mud baths in the sun commonly feel pleasure.")],
    8955: [("C", "typical_location", "Safety lights are commonly installed at concerts to help the audience see.")],
    8956: [("B", "used_for", "A lawyer states the case so spectators understand the legal issues at stake.")],
    8957: [("E", "effect", "If everyone understood each other better, it would help bring about peace.")],
    8958: [("D", "effect", "Older people struggling with computers often experience stress from simple tasks.")],
    8959: [("A", "typical_location", "Stores such as K Mart sell electric razors to customers who need one.")],
    8960: [("A", "typical_location", "Seattle is a city known for frequent rain that makes carrying an umbrella useful.")],
    8961: [("D", "typical_location", "A committee that someone ran for office to join may meet in a boardroom.")],
    8962: [("A", "typical_location", "Peanuts sold during the fourth inning are being sold at a ballpark.")],
    8963: [("C", "typical_location", "Linoleum flooring is commonly preferred on kitchen floors.")],
    8964: [("C", "motivation", "When people believe government wrongdoing has occurred, they often demand justice.")],
    8965: [("A", "effect", "Killing people does not usually lead to joy for those involved.")],
    8966: [("E", "effect", "Eating only hamburgers over time is likely to lead to getting fat.")],
    8967: [("A", "typical_location", "A dishonest salesman is a stereotype sometimes associated with a used car lot.")],
    8968: [("A", "typical_location", "Walking up to a second-floor bedroom means you are inside a house.")],
    8969: [("D", "typical_location", "A water-tight vessel inspected on a dock is likely headed next to the ocean.")],
    8970: [("E", "property", "Animals are living species other than humans that also have blood.")],
    8971: [("D", "effect", "Celebrating an occasion for hours on end commonly leaves a person becoming tired.")],
    8972: [("E", "typical_location", "A piano kept at home is commonly placed in a music room.")],
    8973: [("A", "typical_location", "An artist creating an elaborate wood carving for a spiritual location may work at a synagogue.")],
    8974: [("E", "typical_location", "A hot dog cart often sells best in a park where many active people gather.")],
    8975: [("D", "typical_location", "Humans travel in space to destinations such as the International Space Station.")],
    8976: [("D", "typical_location", "Pat Roberts is a U.S. senator representing the state of Kansas.")],
    8977: [("B", "motivation", "People may change their plans after watching the morning news about outdoor conditions such as hiking weather.")],
    8978: [("D", "typical_location", "Schools are places where young people use pencils for writing and learning.")],
    8979: [("B", "typical_location", "Retail chains such as Sears have historically sold hardware and home supplies.")],
    8980: [("C", "effect", "People feeling a lot of excitement often express it by dancing.")],
    8981: [("A", "has_prerequisite", "A dog must drink water daily to stay alive.")],
    8982: [("B", "typical_location", "A chef famous for grilling is most likely working at a restaurant.")],
    8983: [("C", "typical_location", "Students commonly use an eraser while doing schoolwork at schools.")],
    8984: [("C", "property", "Even beneficial substances can act like poison when consumed in excessive doses as nutrients.")],
    8985: [("A", "effect", "Cotton clothing that gets wet may suffer shrinkage when it dries.")],
    8986: [("D", "typical_location", "The rural general store is a classic staple of small-town America.")],
    8987: [("A", "typical_location", "A jellyfish that does not actually exist may appear only in a cartoon.")],
    8988: [("A", "effect", "When a washing cycle finishes, the clothes inside are still wet clothes.")],
    8989: [("D", "used_for", "In a dressing room someone evaluates how clothing looks and fits before buying.")],
    8990: [("D", "typical_location", "An office building on a city block may have a deli on its ground floor.")],
    8991: [("C", "property", "Clothing is generally meant to be worn by a person rather than an animal.")],
    8992: [("C", "typical_location", "After getting home, people often put spare coins into a jar for storage.")],
    8993: [("D", "motivation", "Children who enjoy playing pretend together mainly do it to have fun with friends.")],
    8994: [("B", "typical_location", "A pianist playing a note for others to copy is likely with a symphony orchestra.")],
    8995: [("A", "motivation", "Voters who choose an outsider often hope the change will bring welcome change.")],
    8996: [("A", "typical_location", "Direction signs are commonly seen on a freeway where traffic moves fast.")],
    8997: [("A", "motivation", "Lowering expectations can help a person avoid feeling like a failure.")],
    8998: [("D", "effect", "Someone who cannot fall asleep suffers from wakefulness.")],
    8999: [("E", "typical_location", "Someone with a cold who asks for a tissue holder may be at a doctor's office.")],
    9000: [("A", "property", "Without glasses a driver may misjudge oncoming cars as being close when they are not.")],
    9001: [("E", "typical_location", "A dirty plate from a meal is commonly placed in the dishwasher to be cleaned.")],
    9002: [("E", "used_for", "When buying something a person is using money from their wallet.")],
    9003: [("C", "effect", "A child who does chores while a parent is away is being helpful.")],
    9004: [("B", "motivation", "A politician who promises money may be hoping to increase power through support.")],
    9005: [("B", "motivation", "When a novelist backs a plot into a corner, they must not give up on the story.")],
    9006: [("C", "typical_location", "Glue is well used in an art room for crafts and school projects.")],
    9007: [("A", "typical_location", "India is a country in southern Asia, not the island homeland of wild lemurs.")],
    9008: [("B", "motivation", "An adult in love is likely to marry their partner.")],
    9009: [("B", "typical_location", "A diver underwater must monitor how much oxygen remains in their supply.")],
    9010: [("D", "cause", "A group may all drink poison and die because everybody believed the same fatal instruction.")],
    9011: [("B", "property", "A person who does something bad by accident and then apologizes is being sincere.")],
    9012: [("B", "property", "An aircraft needs a lightweight skeleton so that it can fly.")],
    9013: [("B", "motivation", "A student who hates school and wants a job may choose to drop out of school.")],
    9014: [("A", "effect", "An entertaining person who makes others feel good hopes to bring lasting happiness to them.")],
    9015: [("C", "used_for", "Friends who are apart can communicate by writing a letter.")],
    9016: [("B", "typical_location", "A traveler from out of town who loses a room key is likely at a hotel.")],
    9017: [("E", "typical_location", "Gasoline can end up in the water when it leaks or spills from a boat.")],
    9018: [("B", "used_for", "A well-sealed container helps keep food fresh inside a refrigerator.")],
    9019: [("A", "typical_location", "A dentist office is commonly found alongside other medical providers at a medical center.")],
}
