# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 5720-5819 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_5720_5819 = {
    5720: [("B", "typical_location", "A business lobby is where visitors commonly find the reception desk.")],
    5721: [("C", "used_for", "Praising opponents is one activity a coach might do while separately critiquing his own team's execution.")],
    5722: [("A", "typical_location", "A lounge lizard stereotypically hangs out at jazz clubs and nightlife venues.")],
    5723: [("E", "motivation", "Growing your own food is often the cheapest way to obtain it.")],
    5724: [("A", "property", "Questioning something because you are unsure reflects doubt.")],
    5725: [("C", "typical_location", "Someone seeking to learn from teachers commonly attends school.")],
    5726: [("E", "typical_location", "A car engine produces heat while running and can serve as a mobile heat source.")],
    5727: [("C", "typical_location", "A grocery store sells both fresh fruit such as apples and frozen treats such as ice cream.")],
    5728: [("E", "motivation", "People dive through underwater caves to travel from one side to the other.")],
    5729: [("E", "typical_location", "Texas is famously associated with genuine Western steakhouses.")],
    5730: [("E", "typical_location", "Snakes are commonly found in the swamps of Louisiana.")],
    5731: [("B", "typical_location", "Sitting down to read a menu and place an order commonly happens at a cafe.")],
    5732: [("D", "property", "Brown is a common horse color that might remind people of chocolate.")],
    5733: [("B", "property", "Texas is stereotyped as a state where cattle are known for bold attitudes.")],
    5734: [("B", "property", "The area between oceans and continents spans a very wide distance.")],
    5735: [("B", "has_prerequisite", "Therapists often say couples must work on communication as a first step.")],
    5736: [("A", "typical_location", "Food is digested primarily in the stomach.")],
    5737: [("D", "typical_location", "The freshest tomatoes are commonly found at a market.")],
    5738: [("D", "effect", "Standing in line all day commonly causes a person to get tired.")],
    5739: [("B", "effect", "Inflation erodes purchasing power, causing saved money to lose value over time.")],
    5740: [("C", "typical_location", "A fox wearing silly clothes on paper is likely drawn in a storybook illustration.")],
    5741: [("C", "motivation", "After improving a mile time, athletes often feel pride and tell many people about it.")],
    5742: [("B", "typical_location", "Personal silverware washed at home is commonly stored in a kitchen drawer.")],
    5743: [("E", "effect", "Having sex without protection commonly leads to unwanted pregnancy.")],
    5744: [("D", "typical_location", "Bookshops specializing in course texts are commonly located near or in a student union.")],
    5745: [("B", "typical_location", "Lasers used for research are commonly found in a university laboratory.")],
    5746: [("E", "effect", "Fighting inflation often brings dissatisfaction to the public facing higher costs.")],
    5747: [("C", "used_for", "Fiddling on a violin means using the instrument to make music.")],
    5748: [("C", "effect", "An evening spent remembering the past often leads to feelings of nostalgia.")],
    5749: [("A", "used_for", "Getting drunk requires drinking booze containing alcohol.")],
    5750: [("D", "typical_location", "People commonly hang curtains in their house to block light on a television.")],
    5751: [("C", "property", "Nice weather can change quickly and unpredictably.")],
    5752: [("E", "typical_location", "If you lack a bean, a food store is where you go to obtain one.")],
    5753: [("D", "used_for", "Hiking utilizes physical exercise as its main form of exertion.")],
    5754: [("A", "used_for", "Firebreak lines dug by workers help fight spreading wildfires.")],
    5755: [("D", "typical_location", "Workers at a warehouse commonly collect cardboard for recycling.")],
    5756: [("A", "motivation", "Students take unpaid memberships to gain work experience.")],
    5757: [("E", "motivation", "People who enjoy learning about science seek to gain information.")],
    5758: [("E", "used_for", "A fruit basket is a common way to give grapes as a gift.")],
    5759: [("D", "typical_location", "Expensive antique lanterns are commonly found in an antique shop.")],
    5760: [("A", "capability", "Differentiating between reality and lies requires telling truth from falsehood.")],
    5761: [("A", "used_for", "A sick person commonly takes medicine to recover from illness.")],
    5762: [("A", "typical_location", "Someone searching for a shirt at home commonly pulls open a closet.")],
    5763: [("B", "used_for", "Saving money like humans requires learning about banking.")],
    5764: [("A", "motivation", "Seeking information for one's own understanding is a common personal priority.")],
    5765: [("B", "typical_location", "A computer mouse is commonly found in a box at a computer store.")],
    5766: [("E", "used_for", "Playing a piano is one way to play music.")],
    5767: [("B", "property", "Critics sometimes claim government wants to control everything.")],
    5768: [("E", "property", "Blemish-free, flowing skin is typical of a person in good health.")],
    5769: [("D", "used_for", "A needlepoint frame holds the fabric taut while stitching.")],
    5770: [("A", "typical_location", "Policemen commonly patrol streets in their assigned area.")],
    5771: [("D", "typical_location", "Hosts apologize for offering only a sofa bed in the guest room.")],
    5772: [("E", "effect", "Skipping dinner and sleeping early makes it easier to attend a meeting rescheduled to before lunch.")],
    5773: [("C", "used_for", "Wood can be carved to change its shape.")],
    5774: [("A", "typical_location", "After paying, customers take purchased magazines home from a bookstore.")],
    5775: [("B", "property", "Professors expect straightforward answers rather than convoluted ones to simple questions.")],
    5776: [("E", "effect", "Learning about science can inspire a sense of wonder in someone.")],
    5777: [("C", "motivation", "Cats looking longingly at an aquarium are likely wanting to eat the fish.")],
    5778: [("D", "typical_location", "People visit a cemetery to see monuments to deceased loved ones.")],
    5779: [("A", "typical_location", "Travelers often sleep in chairs while waiting for vehicles at an airport.")],
    5780: [("E", "effect", "Waging war commonly leads to widespread suffering.")],
    5781: [("E", "capability", "Someone who is on the move cannot stay still in one place.")],
    5782: [("E", "used_for", "Some people prefer to bluntly state facts rather than lie.")],
    5783: [("E", "typical_location", "A music store carries a wide selection of oboe brands.")],
    5784: [("B", "typical_location", "Blowfish in zoos are kept in tanks filled with sea water.")],
    5785: [("E", "typical_location", "A sealed drink meant to travel with you is commonly placed in a backpack.")],
    5786: [("E", "effect", "Actions that make life harder for someone amount to making trouble for them.")],
    5787: [("E", "property", "Despite reports of bad weather, a gorgeous wedding day makes the weather look beautiful.")],
    5788: [("D", "typical_location", "Pennsylvania has a long history of coal mining in the United States.")],
    5789: [("D", "motivation", "Obsessed children may try to squeeze all the fun out of every experience.")],
    5790: [("C", "typical_location", "Cheap watches shoplifted by thieves are commonly taken from a department store.")],
    5791: [("E", "typical_location", "Graduate classes are taken at a university where you might ride a bicycle.")],
    5792: [("B", "typical_location", "Contraceptive devices are commonly obtained at a pharmacy.")],
    5793: [("E", "typical_location", "Fans banging on the glass in the front row are a staple at a hockey game.")],
    5794: [("C", "effect", "Promising to fight an enemy over a transgression may extend even to the death.")],
    5795: [("B", "typical_location", "Customers can shop outdoors at a market.")],
    5796: [("E", "effect", "Waking from a nightmare commonly leaves a person in shock.")],
    5797: [("C", "typical_location", "Pretty flowers growing in the ground are commonly found in a park.")],
    5798: [("B", "effect", "Chatting with friends about old memories often leads someone to laugh.")],
    5799: [("E", "typical_location", "Families keep a favorite comforter for cuddling on the couch in the living room.")],
    5800: [("D", "used_for", "To bring home fish from a boat you must go fishing on the water.")],
    5801: [("C", "used_for", "Banks use account books to keep track of financial records.")],
    5802: [("D", "typical_location", "Teenagers discussing a poet through Socratic dialogue commonly do so in a classroom.")],
    5803: [("B", "property", "Government, planned cities, workers, and record keeping are hallmarks of civilization.")],
    5804: [("D", "typical_location", "Discovery Channel features television programs such as those starring sharks.")],
    5805: [("A", "typical_location", "A singing human performing music is commonly found in a band.")],
    5806: [("A", "effect", "Falling down is what puts a person on the ground.")],
    5807: [("A", "effect", "A person found guilty of stabbing someone to death in Washington State likely faces imprisonment.")],
    5808: [("C", "used_for", "Pretending and wasting hours often means spending time day dreaming.")],
    5809: [("C", "typical_location", "Tourists are often happiest capturing pictures of snow on mountain peaks.")],
    5810: [("C", "effect", "Stress commonly makes remembering information more difficult for people.")],
    5811: [("C", "typical_location", "Bald eagles prefer countryside habitats over big cities.")],
    5812: [("C", "typical_location", "Someone seeking solitude and peace may go to the top of a mountain.")],
    5813: [("C", "has_prerequisite", "Finishing a job requires having enough supplies on hand.")],
    5814: [("E", "typical_location", "A crushed paper coffee cup belongs in the trash.")],
    5815: [("B", "used_for", "Sitting down in a locker room bathroom commonly means using the toilet to pee.")],
    5816: [("E", "property", "Earth is the third planet from the sun where minerals are found.")],
    5817: [("D", "typical_location", "People are likely to sing during a performance at the opera.")],
    5818: [("E", "effect", "Someone scared of skiing after an accident wants to avoid broken legs.")],
    5819: [("D", "property", "Waging war is often considered an evil act.")],
}
