# -*- coding: utf-8 -*-
"""Rest KB for qids 6620-6719 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6620_6719 = {
    6620: [("A", "typical_location", "A ticket booth is commonly placed outside the entrance of a train station.")],
    6621: [("A", "part_whole", "Two eyes are normally found on a person's face.")],
    6622: [("A", "effect", "A person who hurts someone else is likely to feel remorse afterward.")],
    6623: [("D", "typical_location", "When city populations declined, many Detroit residents moved to the suburbs.")],
    6624: [("A", "typical_location", "Lincoln is the capital city of Nebraska.")],
    6625: [("E", "effect", "A customer is likely to be satisfied when an auto shop meets their expectations.")],
    6626: [("B", "typical_location", "Clouds are visible in the sky above the ground.")],
    6627: [("B", "property", "Refusing to move means staying put in the same place.")],
    6628: [("A", "typical_location", "Rocks are commonly found on the ground in many outdoor settings.")],
    6629: [("C", "property", "Glass should be handled with care because it breaks easily.")],
    6630: [("B", "motivation", "All humans generally want to feel comfortable in their own home.")],
    6631: [("D", "typical_location", "Bald eagles and redwood trees are both found in northern California.")],
    6632: [("C", "typical_location", "Peanut butter is commonly stored in and taken out of a jar.")],
    6633: [("D", "effect", "Discovering the truth after much worry commonly brings relief.")],
    6634: [("A", "typical_location", "The Shenandoah Valley is located in West Virginia.")],
    6635: [("A", "motivation", "Politicians commonly compete by running for president in a major election.")],
    6636: [("E", "primary_function", "Asking questions is an effective way to learn new things from someone else.")],
    6637: [("C", "primary_function", "Living things continue their species by procreating and reproducing.")],
    6638: [("A", "used_for", "Rollerblades have blades that let a person roll from one place to another.")],
    6639: [("C", "typical_location", "A map where water covers more than half of the area is likely a map of an ocean.")],
    6640: [("D", "typical_location", "A bald eagle often perches on high places to get a lay of the land.")],
    6641: [("B", "typical_location", "Dirt commonly gets trapped under a person's fingernails.")],
    6642: [("E", "typical_location", "Chocolate is commonly purchased at a supermarket.")],
    6643: [("B", "typical_location", "Mouthwash is usually stored in a bottle.")],
    6644: [("D", "has_prerequisite", "A person with good credit can usually get a car loan at a great interest rate.")],
    6645: [("B", "typical_location", "Large numbers of apartment buildings are typically found in an urban area.")],
    6646: [("E", "typical_location", "A row of apple trees is commonly planted in fields on a farm or orchard.")],
    6647: [("B", "property", "Buildings in downtown New York are not small; they are typically very tall.")],
    6648: [("D", "typical_location", "A balloon purchased along with weekly household essentials was likely bought at a grocery store.")],
    6649: [("B", "used_for", "When children are not playing outside, they commonly play video games indoors.")],
    6650: [("E", "typical_location", "Jellyfish live in bodies of water such as a pond or the sea.")],
    6651: [("E", "typical_location", "A child's schoolwork is commonly displayed on the wall of a classroom.")],
    6652: [("D", "typical_location", "The Bermuda Triangle is famous for stories of mysterious disappearances.")],
    6653: [("A", "typical_location", "A beaver is unlikely to be found in a strip club.")],
    6654: [("B", "effect", "An out-of-control fire that is not stopped can harm someone.")],
    6655: [("D", "typical_location", "A catwalk in a theater may be quiet when no performance is underway.")],
    6656: [("C", "motivation", "A digital artist may modify a copy of a famous picture to make it unique.")],
    6657: [("B", "typical_location", "Many colonial kingdoms originated in European nations that established overseas empires.")],
    6658: [("E", "effect", "Short-term forgetfulness is an early sign of memory problems in aging.")],
    6659: [("E", "primary_function", "A mother who punishes her children may raise her voice to yell at them.")],
    6660: [("E", "effect", "In a war, a person is likely to have to kill another person.")],
    6661: [("C", "has_prerequisite", "A young bird still in the nest needs to learn to fly before it can leave.")],
    6662: [("A", "typical_location", "A cannon is commonly found at a fort on land.")],
    6663: [("E", "typical_location", "A human goes to an airport to be lifted into the air and carried off by airplane.")],
    6664: [("B", "used_for", "Children with vivid imaginations can use almost anything to play games.")],
    6665: [("A", "typical_location", "A fairgrounds ride or heat can leave a person feeling nauseous or dizzy while drinking lemonade.")],
    6666: [("D", "motivation", "Someone who goes dancing without caring about talking to others is mainly there for having fun.")],
    6667: [("C", "typical_location", "Games are commonly purchased at a toy store.")],
    6668: [("B", "has_prerequisite", "Reaching an advantage in anything requires hard work and determination.")],
    6669: [("E", "property", "Using television when one has much to do may indicate laziness.")],
    6670: [("D", "effect", "Bringing a lawsuit against a family member commonly creates tensions with the rest of the family.")],
    6671: [("E", "typical_location", "Members of the Jewish community gather in a temple to worship according to Old Testament tradition.")],
    6672: [("D", "typical_location", "A goalie who blocks a ball and feels blood on his face was playing in a soccer game.")],
    6673: [("E", "typical_location", "A ferret would feel most free when allowed to roam outdoors.")],
    6674: [("A", "primary_function", "Without a remote control, a person must manually switch on a television.")],
    6675: [("A", "typical_location", "A table designed for gambling should be placed in a card room.")],
    6676: [("A", "property", "A person who did not see a sharp object falling in front of them was unobservant.")],
    6677: [("E", "typical_location", "A father and child go to a toy store to pick out a stuffed animal.")],
    6678: [("D", "motivation", "During self-improvement, a person works to better himself.")],
    6679: [("E", "has_prerequisite", "A person who tosses and turns without rest may need to get comfortable in order to sleep.")],
    6680: [("E", "property", "Someone whose mind is far away still has a body that is physically present.")],
    6681: [("B", "effect", "Creating art that not everyone agrees with can cause controversy.")],
    6682: [("B", "typical_location", "A group of beavers commonly builds a dam across a river or stream.")],
    6683: [("D", "effect", "Motion sickness is one of the many hazards a person may face while traveling.")],
    6684: [("B", "motivation", "A person who wants to go to college is seeking further education.")],
    6685: [("A", "property", "Hostility between two sides can be too much to abide even when someone pleads for peace.")],
    6686: [("B", "property", "It is often healthy to eat the skin of certain fruits such as apples.")],
    6687: [("C", "used_for", "A handshake is a common gesture given when meeting people.")],
    6688: [("C", "used_for", "A teacher may suggest that a student practice writing by composing a letter about people he knows.")],
    6689: [("D", "typical_location", "A pencil is commonly carried in a shirt pocket.")],
    6690: [("E", "typical_location", "Someone who lost an appointment book during a medical checkup would first look at the doctor's office.")],
    6691: [("D", "effect", "Watching someone open a gift you bought commonly gives the giver a sense of joy.")],
    6692: [("D", "property", "Receiving something for no cost means getting it for free.")],
    6693: [("C", "property", "A trainer who disregards a disability focuses on the client's potential rather than limitations.")],
    6694: [("B", "effect", "When you change a contract, it is revised to reflect the new terms.")],
    6695: [("E", "used_for", "Cassettes can be used in a player to listen to recorded music.")],
    6696: [("E", "effect", "When lying becomes a habit between close friends, it can become a betrayal of trust.")],
    6697: [("D", "used_for", "Someone who likes rubbing hair but cannot cut it might get a pet mammal to stroke.")],
    6698: [("E", "typical_location", "A student who needs more knowledge and has a truancy problem should attend more class.")],
    6699: [("C", "typical_location", "A dental office is commonly found in an office building.")],
    6700: [("E", "typical_location", "A hiring agent at a seated interview may retrieve a contract and pen from a briefcase.")],
    6701: [("D", "motivation", "Many people say they want to feel loved more than anything else.")],
    6702: [("B", "typical_location", "A cat wandering outside is likely to be found in a residential area.")],
    6703: [("C", "property", "Dogs are generally friendly toward people.")],
    6704: [("A", "property", "Energy from the sun arrives on Earth primarily in the form of light.")],
    6705: [("C", "typical_location", "A homeowner who wants new flooring installed typically wants it in their house.")],
    6706: [("B", "typical_location", "A parking lot is a good public place to leave a car.")],
    6707: [("B", "capability", "Driving cars is an activity that only humans are capable of doing among the listed options.")],
    6708: [("E", "typical_location", "A car with its turn signal on is commonly stopped at a street corner before turning.")],
    6709: [("C", "effect", "Rain will wet your clothes if you do not have an umbrella.")],
    6710: [("C", "property", "A customer may leave a restaurant if the person at the front is not polite.")],
    6711: [("C", "property", "Resources in an area that is not thick with them are sparse.")],
    6712: [("B", "effect", "Instituting a civil action means starting a court case.")],
    6713: [("E", "primary_function", "The primary duty of a chef is to prepare food.")],
    6714: [("D", "property", "Eating simple green ingredients means avoiding heavily processed foods.")],
    6715: [("E", "typical_location", "A large personal apple tree is commonly planted in a backyard.")],
    6716: [("D", "effect", "After cashing in chips at a casino, a person is typically about to leave.")],
    6717: [("B", "property", "Something bad is unlikely to be described as virtuous by anyone.")],
    6718: [("D", "motivation", "People commonly go hiking to enjoy nature.")],
    6719: [("E", "typical_location", "A special box where someone keeps a return ticket likely holds keepsakes and mementos.")],
}
