# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 8220-8319 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8220_8319 = {
    8220: [("B", "typical_location", "A blowfish kept as a pet is commonly housed at a pet shop before going home.")],
    8221: [("A", "property", "Cats share four legs with most other mammals.")],
    8222: [("B", "typical_location", "Natural light from stars and other sources originates in the universe.")],
    8223: [("E", "typical_location", "An advertisement opened after reading a subject line is typically an email.")],
    8224: [("B", "used_for", "Someone far away may whistle to get your attention while you stand in a queue.")],
    8225: [("A", "used_for", "Important precious cargo is often delivered as quickly as possible by aeroplane.")],
    8226: [("D", "primary_function", "Flat rocks stacked between pond levels are used to create a waterfall.")],
    8227: [("B", "typical_location", "A marmoset on display in a zoo may be found in a Colorado zoo exhibit.")],
    8228: [("B", "used_for", "To use a television after getting cable you plug in the power cord.")],
    8229: [("A", "effect", "Children who experience aging eventually become adults.")],
    8230: [("E", "used_for", "A college freshman determined to make friends does lots of talking with others.")],
    8231: [("B", "typical_location", "Toothpaste is normally kept in the bathroom at home.")],
    8232: [("A", "typical_location", "Brother Dan sitting in a holding chair in a circle talking to peers suggests a meeting hall.")],
    8233: [("D", "used_for", "Shopping at a shop commonly ends with payment at a cash register.")],
    8234: [("C", "has_prerequisite", "A witness oath requires the person not to lie when testifying.")],
    8235: [("A", "typical_location", "A front yard is generally filled with grass.")],
    8236: [("A", "property", "A significant event in someone's life is something that is not ignorable.")],
    8237: [("B", "has_prerequisite", "When answering questions you only get credit if your answer is correct.")],
    8238: [("C", "has_prerequisite", "Exercising daily requires a great deal of mental discipline.")],
    8239: [("E", "property", "People who follow God are usually mortal human beings.")],
    8240: [("D", "typical_location", "A large post office is likely to be found in a business district.")],
    8241: [("D", "typical_location", "A bar is a business that serves alcoholic refreshment.")],
    8242: [("A", "property", "A large body of water often appears blue to the eye.")],
    8243: [("D", "used_for", "To make something to put peanut butter and jelly on you bake bread.")],
    8244: [("C", "typical_location", "A state's supreme courthouse is typically located in the capital city.")],
    8245: [("E", "used_for", "To analyse a subject at great length you must think about it carefully.")],
    8246: [("E", "motivation", "A teacher who sees unrealized potential may try to encourage the student.")],
    8247: [("E", "typical_location", "A koala far from Australia may be seen at the San Diego Zoo in an English-speaking country.")],
    8248: [("C", "typical_location", "A former wrestler might donate a new main wrestling mat to a school.")],
    8249: [("B", "used_for", "Enjoying newspapers enough to pay regularly means buying a subscription.")],
    8250: [("D", "typical_location", "An old coffee table book is commonly found at an antique store.")],
    8251: [("B", "typical_location", "A bald eagle would avoid something irrelevant like soup.")],
    8252: [("C", "property", "Players in a drawing game can identify an item when it is common enough to recognize.")],
    8253: [("B", "motivation", "People with punishing physical jobs often want to avoid additional exercise.")],
    8254: [("E", "typical_location", "The area of land next to the ocean is called a beach.")],
    8255: [("C", "typical_location", "If you need a cavity filled you go to a dentist.")],
    8256: [("B", "used_for", "When you are traveling you must be going somewhere.")],
    8257: [("E", "motivation", "People read gossip magazines to be entertained.")],
    8258: [("D", "typical_location", "A runner who prefers the forest over the city drives to the countryside each morning.")],
    8259: [("E", "typical_location", "A child skipping pebbles in nature is likely at a pond.")],
    8260: [("A", "typical_location", "Gamblers who watch four-legged animals commonly gather at a race track.")],
    8261: [("B", "typical_location", "Children go to kindergarten class before they start primary school.")],
    8262: [("D", "typical_location", "Very fresh fruit is most likely still on the tree.")],
    8263: [("E", "used_for", "People communicate by talking to each other.")],
    8264: [("C", "typical_location", "A good place for a person to put green beans when eating is the mouth.")],
    8265: [("A", "effect", "Two individuals experiencing fear who cannot agree may separate from each other.")],
    8266: [("E", "property", "The only solution Sam found to stop the Crimson King permanently was temporary.")],
    8267: [("C", "typical_location", "Late at night with no lamp nearby the entire building can seem pitch black.")],
    8268: [("C", "typical_location", "An automobile involved in an accident is likely taken to a repair shop.")],
    8269: [("D", "effect", "Like most activities, practice at chess helps build your skill at it.")],
    8270: [("C", "motivation", "A very vain person in a crowd loves to draw attention to themselves.")],
    8271: [("E", "capability", "A competent person at work is able to solve problems effectively.")],
    8272: [("B", "used_for", "After staring at a computer all day you can relieve strain by closing your eyes.")],
    8273: [("A", "typical_location", "A house often has multiple personal televisions in different rooms.")],
    8274: [("A", "motivation", "Pain can quickly change the ways of people who put off having a checkup.")],
    8275: [("E", "capability", "When you love someone you can forgive them easily.")],
    8276: [("D", "typical_location", "A human wishing to explore our galaxy might start with the solar system.")],
    8277: [("B", "typical_location", "A container full of rice is commonly kept in the pantry.")],
    8278: [("D", "motivation", "If attending a meeting is your priority you need to get a good result from it.")],
    8279: [("B", "effect", "Practicing answering questions can lead to a better grade.")],
    8280: [("C", "typical_location", "North America has winter at the start of the year because it lies in the northern hemisphere.")],
    8281: [("A", "typical_location", "If you are in the southern United States eating crab you are likely in South Carolina.")],
    8282: [("C", "typical_location", "Dressing formally with stereotypical viewing glasses and buying tickets suggests an opera house.")],
    8283: [("B", "motivation", "Someone careful to eat a healthy dinner wants to experience living longer.")],
    8284: [("B", "typical_location", "Tourists on hikes often take pictures at a waterfall.")],
    8285: [("D", "has_prerequisite", "Playing tennis requires at least one opponent, a ball, and a tennis racket.")],
    8286: [("D", "typical_location", "Fans filing in for a big game will soon fill a sports stadium.")],
    8287: [("E", "effect", "Even though she implored a reply the email recipient chose to ignore it.")],
    8288: [("E", "typical_location", "Coin-operated machines and toys that fire projectile balls are found in an arcade.")],
    8289: [("C", "motivation", "After quitting cigarettes Sarah took long drives for relaxation.")],
    8290: [("C", "typical_location", "A tin likely to have food in it is sold at a grocery store.")],
    8291: [("B", "motivation", "He seemed to believe success was the only way to please parents and earn their love.")],
    8292: [("B", "typical_location", "Someone who loves flying kites might look for one at a toy store.")],
    8293: [("A", "effect", "Seeing artifacts he had lost long ago while reading brought up painful memories.")],
    8294: [("A", "used_for", "To make a vertical company more horizontal you branch out into new areas.")],
    8295: [("B", "typical_location", "If you do not speak French or Italian you may encounter confusion at the opera.")],
    8296: [("B", "effect", "When a bully said mean words the effect on others was to hurt people.")],
    8297: [("C", "property", "Einstein decided that energy was related to matter.")],
    8298: [("C", "used_for", "Choosing meat and bread from an employee's question means having a ham sandwich.")],
    8299: [("A", "typical_location", "Sam lost his tickets because he did not want a night of singing at the opera.")],
    8300: [("C", "typical_location", "Everybody wants to be the frontman or play guitar in a rock band.")],
    8301: [("D", "typical_location", "Searching a place many times for a hole suggests scouring a golf course.")],
    8302: [("D", "motivation", "Someone cleans their house of pollen to reduce allergies.")],
    8303: [("A", "property", "An annoying person who always has a comment may think he must know everything.")],
    8304: [("E", "property", "The belief that we do not choose what happens in life is called predetermination.")],
    8305: [("C", "typical_location", "James could find a heavy chain wrap for tires at a hardware store.")],
    8306: [("A", "effect", "Someone becomes a lover by falling in love.")],
    8307: [("C", "used_for", "During time off from work people often take trips.")],
    8308: [("D", "effect", "Learning through a long difficult process increases a person's knowledge.")],
    8309: [("B", "typical_location", "You can put a ruler either on top of a desk or into its drawer.")],
    8310: [("B", "typical_location", "Cats peeking at birds often hug the ground or windowsill near the ground.")],
    8311: [("E", "property", "Typing is a form of communication.")],
    8312: [("C", "typical_location", "A satellite that zipped past the moon was heading deeper into the universe.")],
    8313: [("C", "typical_location", "John could hunt blowfish in Hawaiian waters without leaving America.")],
    8314: [("A", "typical_location", "You can get a trumpet to take home at a music store.")],
    8315: [("E", "typical_location", "Salesmen commonly work in a shop selling goods.")],
    8316: [("E", "used_for", "An archery target is something you could hang on a building.")],
    8317: [("C", "used_for", "Removing dirt from a carpet while doing housework requires vacuuming.")],
    8318: [("C", "effect", "After surgery even drinking was difficult because he had trouble swallowing.")],
    8319: [("B", "property", "Five years after becoming a parent most people have a school-age child.")],
}
