# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7620-7719 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_7620_7719 = {
    7620: [("B", "typical_location", "Salmon commonly spawn in rivers where they lay eggs in freshwater.")],
    7621: [("A", "typical_location", "A ring binder containing budgets is commonly kept in an office.")],
    7622: [("C", "typical_location", "After eating at a restaurant one leaves dirty plates for staff to collect.")],
    7623: [("E", "typical_location", "A bookend on a shelf is commonly found in a school library.")],
    7624: [("B", "typical_location", "Dog owners often lay newspaper on the floor for puppies to use.")],
    7625: [("D", "typical_location", "A squirrel may run across a roof to move between gutters on adjoining buildings.")],
    7626: [("B", "typical_location", "Wild gazelle are commonly found on open plains in Africa.")],
    7627: [("A", "used_for", "Bleach is added to well water to disinfect it during a bacteria scare.")],
    7628: [("C", "typical_location", "Portuguese is spoken in Brazil, part of the Amazon basin where sloths live.")],
    7629: [("E", "capability", "Someone who understands the world mainly through sound may lack vision.")],
    7630: [("A", "typical_location", "On a business trip you take a bath in a hotel room.")],
    7631: [("E", "effect", "Walking a dog for a long time commonly leads to tiredness.")],
    7632: [("E", "has_prerequisite", "Aspiring writers commonly study literature in college.")],
    7633: [("C", "effect", "A short-distance runner who attempts long distances is likely to get tired.")],
    7634: [("E", "effect", "Being exposed as a liar commonly causes a person to feel humiliated.")],
    7635: [("C", "motivation", "The main goal of work outside the home is to earn money.")],
    7636: [("B", "typical_location", "An encyclopedia is a reference collection where you can look up what a sloth is.")],
    7637: [("D", "typical_location", "When ink costs more than a new printer, the expense hits a home office hardest.")],
    7638: [("E", "motivation", "Birds in August may be looking to reproduce before winter.")],
    7639: [("B", "typical_location", "Lemonade kept in a refrigerator stays cold and most refreshing.")],
    7640: [("A", "used_for", "Writing a letter is a less aggressive way to express anger than physical confrontation.")],
    7641: [("C", "typical_location", "A moving airplane is commonly seen in the sky.")],
    7642: [("C", "typical_location", "A worker standing in a kitchen for a whole shift is likely at a restaurant.")],
    7643: [("E", "property", "A person who is well off is said to be affluent.")],
    7644: [("D", "property", "Rain is a type of weather.")],
    7645: [("B", "typical_location", "An airport attracts a large diverse crowd from many places suitable for distributing tracts.")],
    7646: [("B", "used_for", "He used a metal detector to find the ring he lost while pulling weeds.")],
    7647: [("A", "effect", "Drinking alcohol always leads to inebriation to some degree.")],
    7648: [("D", "typical_location", "A conductor flails his arms while facing an orchestra.")],
    7649: [("A", "effect", "An audience that enjoys a performance commonly shows smiles.")],
    7650: [("A", "effect", "After going to bed you might dream, which can be good or bad.")],
    7651: [("D", "effect", "Someone who does not want to be spoken to may show an adverse reaction to a talkative person.")],
    7652: [("C", "property", "A guilty conscience can make someone imagine they still hear a victim's heart beating.")],
    7653: [("E", "property", "In many animal species the males are the dominant ones.")],
    7654: [("E", "typical_location", "A broken keyboard is commonly found discarded or replaced in an office.")],
    7655: [("C", "capability", "A computer can process information but cannot believe in god.")],
    7656: [("C", "typical_location", "Koalas cannot survive in Siberia's cold climate.")],
    7657: [("B", "typical_location", "Food that does not need refrigeration is commonly kept on a shelf inside a cupboard.")],
    7658: [("B", "has_prerequisite", "Someone who learns music by ear may never have seen it written on paper.")],
    7659: [("A", "effect", "Stabbing a buck badly would leave blood bleeding everywhere.")],
    7660: [("E", "motivation", "Parents encourage kids to play baseball because it is fun to play.")],
    7661: [("D", "typical_location", "A bungalow overlooking a sidewalk is located in a neighborhood.")],
    7662: [("E", "capability", "A person with a head has the ability to point at things.")],
    7663: [("C", "typical_location", "Loose foot rails on a bar are often fixed with a screwdriver kept behind the bar.")],
    7664: [("C", "typical_location", "Decorative saucers not in daily use are often displayed in a china cabinet.")],
    7665: [("B", "motivation", "When talking you are hoping for a conversation with another person.")],
    7666: [("A", "has_prerequisite", "The first step in starting a crop is to till the soil.")],
    7667: [("D", "effect", "Taking a hill to gain advantage commonly leads to victory.")],
    7668: [("B", "property", "A genius is likely to be exceptional in all subjects.")],
    7669: [("C", "used_for", "Sliced and fried potatoes are commonly made into french fries.")],
    7670: [("D", "property", "A very happy person is likely to have joyfulness.")],
    7671: [("E", "effect", "Achieving a savings goal commonly brings great satisfaction.")],
    7672: [("A", "typical_location", "School bathrooms are cleaned daily but often wet and messy by morning from heavy student use.")],
    7673: [("A", "motivation", "An ugly girl may wish to become beautiful.")],
    7674: [("B", "effect", "A victim of a random punch may find a bruise on their body.")],
    7675: [("E", "effect", "Watering planted seeds helps plants grow.")],
    7676: [("D", "property", "Bears in the wild are very dangerous and require caution.")],
    7677: [("C", "typical_location", "A delicatessen is a specific type of shop selling prepared meats and sandwiches.")],
    7678: [("D", "property", "Some video games are educational as well as entertaining for kids.")],
    7679: [("E", "typical_location", "Plants usually start growing in the ground.")],
    7680: [("E", "used_for", "Someone reading the Bible before meeting a priest may be preparing for confession.")],
    7681: [("E", "effect", "After summer ends children go back to school.")],
    7682: [("A", "typical_location", "Canada is a northern country where bald eagle preserves can be found.")],
    7683: [("C", "effect", "When friends do not respect you, you may suffer contempt at their hands.")],
    7684: [("C", "property", "A bad real estate agent is commonly described as incompetent.")],
    7685: [("A", "effect", "A hurricane plowing through a city can create a disaster.")],
    7686: [("B", "typical_location", "Fish can be found living in a stream in nature.")],
    7687: [("D", "typical_location", "An automobile that has broken down is commonly found on the side of the road.")],
    7688: [("C", "typical_location", "As a compromise a disliked rug might be placed under a table.")],
    7689: [("C", "typical_location", "A pond surrounded by tall buildings is unlikely to be in the countryside.")],
    7690: [("E", "motivation", "A host who lights up when the doorbell rings is obviously ready to welcome guests.")],
    7691: [("A", "typical_location", "Las Vegas has many dental offices where you could visit hundreds of dentists.")],
    7692: [("C", "typical_location", "A circus performance features lions, elephants, and acrobats.")],
    7693: [("C", "effect", "Eating a hamburger too fast without swallowing can cause choking.")],
    7694: [("C", "effect", "James changed his tune about violence when it was being done against him.")],
    7695: [("D", "motivation", "Some children wish they were grown ups so they could do anything they want.")],
    7696: [("E", "typical_location", "Spirits are said to haunt outside locations such as a cemetery.")],
    7697: [("E", "effect", "The opposite of consequences from lying constantly is earning rewards through honesty.")],
    7698: [("D", "effect", "When job applications receive no callbacks it can lead to frustration.")],
    7699: [("E", "used_for", "You can use a stick to swat at grass growing in a field.")],
    7700: [("C", "typical_location", "Computers are used for sorting mail at a post office.")],
    7701: [("D", "typical_location", "Alabama comes before Tennessee alphabetically and has many fiddle players.")],
    7702: [("D", "used_for", "You might say please when asking someone to entertain you.")],
    7703: [("A", "effect", "Standing in line for hours may cause pain in your feet.")],
    7704: [("A", "typical_location", "A cat typically enjoys a warm place to rest.")],
    7705: [("C", "typical_location", "A fire pit in a backyard is commonly burned for warmth or cooking.")],
    7706: [("A", "effect", "Eating hamburgers in excess can lead to health problems long term.")],
    7707: [("E", "typical_location", "John went to the farmers market to get grapes.")],
    7708: [("A", "typical_location", "A referee tells racers to line up at the start.")],
    7709: [("A", "typical_location", "Getting a paper back marked with corrections usually happens in a classroom.")],
    7710: [("A", "typical_location", "Many stars are visible in the night sky.")],
    7711: [("E", "typical_location", "A ball is commonly used for exercise in a gymnasium.")],
    7712: [("C", "effect", "Eating beans at breakfast may cause gas.")],
    7713: [("B", "used_for", "The last thing to do when replying is to send your response.")],
    7714: [("E", "has_prerequisite", "Sarah did not want to do bad but felt she had no choice.")],
    7715: [("D", "typical_location", "A ranch house stereotype makes people think of cowboys in Texas.")],
    7716: [("A", "motivation", "Going to bed at eleven at night means looking to fall asleep.")],
    7717: [("C", "typical_location", "Mouthwash in a little paper cup is commonly given at a dentist's office.")],
    7718: [("C", "typical_location", "Someone in an apartment might need a small table for limited space.")],
    7719: [("D", "effect", "The flu is likely to result in illness throughout the body.")],
}
