# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 8420-8519 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8420_8519 = {
    8420: [("E", "typical_location", "A freezer with food in it is usually found in your own home.")],
    8421: [("B", "cause", "A thunderstorm causes water to come out of the sky as rain.")],
    8422: [("B", "typical_location", "Disneyland is a popular west coast attraction with a lot of water nearby.")],
    8423: [("E", "typical_location", "If you need an eraser, you would go to an office supply store.")],
    8424: [("D", "typical_location", "A shop gets the sand dollars it sells from the ocean floor.")],
    8425: [("B", "typical_location", "Hotels have reception areas where guests may spend twenty-four hours.")],
    8426: [("B", "typical_location", "Hot dogs are extremely expensive at Disneyland despite all the walking.")],
    8427: [("A", "typical_location", "You wait on a bench for something on tracks at a train station.")],
    8428: [("E", "capability", "A group of horses is likely to be seen running in a herd together.")],
    8429: [("B", "motivation", "When a person has lost all hope, they tend to expect miracles.")],
    8430: [("B", "part_whole", "A human has two arms, unlike a dog.")],
    8431: [("E", "motivation", "A person who likes school also enjoys learning.")],
    8432: [("C", "typical_location", "You could put a clock on the floor in your own bedroom.")],
    8433: [("B", "typical_location", "The best way to keep tomatoes fresh is in a refrigerator.")],
    8434: [("A", "typical_location", "While shopping for greeting cards, your child would like to be at a toy store.")],
    8435: [("D", "typical_location", "A hotel room is likely to have a small kitchenette.")],
    8436: [("E", "motivation", "To get recognition at work you need to work hard.")],
    8437: [("A", "typical_location", "If his bathroom would not flush on Saturdays, John was forced to poop at a neighbor's house.")],
    8438: [("A", "property", "A box labeled stuff could contain anything.")],
    8439: [("E", "typical_location", "You would find a pot being used by someone at a restaurant.")],
    8440: [("B", "effect", "Living in a humid climate leads to a lot of perspiration.")],
    8441: [("B", "typical_location", "If you are Greek and see a shark in the wild, you are likely in the Mediterranean Sea.")],
    8442: [("D", "typical_location", "To get paint for a project, go to a hardware store.")],
    8443: [("A", "typical_location", "Clean linen is important at a hospital where John might work.")],
    8444: [("C", "motivation", "To gain the most profits, focus on cutting down waste.")],
    8445: [("E", "typical_location", "She needed cabbage and make-up, so she went to a supermarket to buy both.")],
    8446: [("C", "motivation", "An academic seeking the truth in pursuit of learning will do anything to further knowledge.")],
    8447: [("A", "effect", "If Danny eats what he likes despite food not loving him back, he often develops gas.")],
    8448: [("E", "typical_location", "Robbers who want the big load of money in a bank target the bank vault.")],
    8449: [("C", "typical_location", "When traveling, people usually do not worry about medical emergencies because hospitals are in every state.")],
    8450: [("A", "primary_function", "Science explains the art found in nature.")],
    8451: [("A", "part_whole", "Sex is often referred to as part of the human experience for everyone.")],
    8452: [("B", "used_for", "Sally brought a ball when visiting Scott so they could play with it.")],
    8453: [("D", "effect", "Someone running away from a big animal feels frightened.")],
    8454: [("A", "typical_location", "Jelly put into a tube is bound for donuts.")],
    8455: [("B", "property", "If someone is sharp and highly qualifies for a job, their qualifications may be called above board.")],
    8456: [("E", "used_for", "When a teacher gives you a command, you should follow it.")],
    8457: [("D", "typical_location", "After lasagna has been cooked, look for it on a plate.")],
    8458: [("C", "typical_location", "When darkness came, she was prompted to go to bed.")],
    8459: [("E", "effect", "One fun result of farting is a loud noise.")],
    8460: [("E", "typical_location", "Lights used for a safe landing are installed on a plane.")],
    8461: [("E", "typical_location", "A famous basketball court is in Los Angeles.")],
    8462: [("A", "effect", "When a play starts in an auditorium, the lights tend to fade out.")],
    8463: [("A", "used_for", "It is usually difficult to forgive your spouse if they have sex with someone else.")],
    8464: [("E", "typical_location", "A car show can cause excitement from things that can move but are not moving.")],
    8465: [("E", "used_for", "A couple in a canoe might row about with each other.")],
    8466: [("B", "typical_location", "You might find a bald eagle in the western state of Colorado.")],
    8467: [("C", "motivation", "If people are informed of an imminent war, they hope for peace.")],
    8468: [("B", "motivation", "At her mother's death bed, her mother reassured her to be happy and fight her issues.")],
    8469: [("B", "used_for", "When meeting a friend, one generally says hi at first.")],
    8470: [("D", "property", "When passion fades and someone shows no emotion, they have demonstrated coldness toward the other.")],
    8471: [("B", "part_whole", "Running targets the regular muscles in the legs.")],
    8472: [("C", "typical_location", "John would go to a flower shop to get a blue anemone for Laura's birthday.")],
    8473: [("E", "motivation", "When finding information about manners, you hope to know how to act.")],
    8474: [("B", "property", "People consider chatting with friends when there is work to do as silliness.")],
    8475: [("B", "typical_location", "The night table with hand cream is in homes.")],
    8476: [("A", "typical_location", "A student without a dictionary at the dorm would go to the library.")],
    8477: [("D", "property", "Loose lips sink ships, so surprise party planners must be very discreet.")],
    8478: [("A", "motivation", "Someone brings home fish because they are hungry.")],
    8479: [("D", "typical_location", "You could find thousands of chairs in a school room.")],
    8480: [("D", "typical_location", "A brownstone apartment away from the center of town is in a subdivision.")],
    8481: [("C", "part_whole", "After hearing it for so long he finally gave in and began talking to the voice.")],
    8482: [("C", "motivation", "People write things down so they will not forget.")],
    8483: [("A", "effect", "Driving along a scenic highway can have a calming effect of relaxation.")],
    8484: [("A", "used_for", "When people drive they usually listen to the radio to ward off boredom.")],
    8485: [("D", "property", "A man with loose morals was always faithful to his wife.")],
    8486: [("B", "typical_location", "A merchant who sells produce has a market.")],
    8487: [("A", "effect", "If people work hard and save their money, they are likely to gain wealth.")],
    8488: [("E", "typical_location", "Soldiers are trained to use explosive devices during war.")],
    8489: [("C", "used_for", "To memorialize his favorite horse permanently, he commissioned an engraving.")],
    8490: [("A", "typical_location", "Tens of thousands of people playing baseball could be found in America.")],
    8491: [("B", "motivation", "If someone comes in while you are cooking, they are hoping to get food.")],
    8492: [("B", "part_whole", "Ribs are a popular pork barbecue dish.")],
    8493: [("C", "property", "When people get older their hair becomes very thin.")],
    8494: [("D", "used_for", "A magnet is used in a speaker to make something vibrate.")],
    8495: [("B", "typical_location", "When you feed food to animals, you are at a petting zoo.")],
    8496: [("E", "part_whole", "An artist using a stylus on a pad kept a very steady hand.")],
    8497: [("A", "typical_location", "You are likely to find an artisan market in a town.")],
    8498: [("D", "motivation", "Some people will only have sex for the first time if they love another.")],
    8499: [("E", "capability", "People claim that God has the gift to work miracles for people.")],
    8500: [("C", "typical_location", "To keep a turkey unspoiled, the full name of a useful implement is a refrigerator.")],
    8501: [("B", "part_whole", "You can get yellow fungus on your toenails.")],
    8502: [("A", "motivation", "If someone wants to travel, they want to go somewhere.")],
    8503: [("B", "effect", "Someone takes up exercising to improve their physical fitness.")],
    8504: [("D", "has_prerequisite", "A robot needs energy to be working.")],
    8505: [("B", "typical_location", "A cup is a good place to keep many a pencil.")],
    8506: [("A", "typical_location", "Living on the top floor means nobody is above you in the apartment building.")],
    8507: [("D", "effect", "The dog always made the stick come back after it was thrown away.")],
    8508: [("A", "property", "Putting on a professional stage play requires serious effort.")],
    8509: [("D", "typical_location", "A shopping arcade with a lot of foot traffic is located in a busy city.")],
    8510: [("C", "typical_location", "If you find liquid water, you are likely on planet Earth.")],
    8511: [("A", "used_for", "A student with reading difficulties furrows his brow while concentrating on a line of the book.")],
    8512: [("A", "effect", "When giving assistance to people in need, you are likely to see smiles on their faces.")],
    8513: [("E", "used_for", "When a union shop decides to go off strike, they return to work.")],
    8514: [("E", "property", "If you asked a friend to write you a response, you might be looking for an answer.")],
    8515: [("A", "part_whole", "A shoreline separates a bay from the open water.")],
    8516: [("A", "property", "A sad tune someone fiddles is likely about troubles.")],
    8517: [("B", "typical_location", "A good place to see an apple tree is Oregon.")],
    8518: [("B", "property", "Sam called tech support because he was sure a reason exists for his stuck computer.")],
    8519: [("E", "used_for", "A student who wants to recall information from class later is taking notes.")],
}
