# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7320-7419 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_7320_7419 = {
    7320: [("B", "typical_location", "A desk drawer commonly holds small office supplies such as paper clips.")],
    7321: [("A", "typical_location", "A closet stores clothing and can also hold a book kept near fabric items you wear.")],
    7322: [("D", "effect", "Getting in shape commonly makes clothing fit better and look better on a person.")],
    7323: [("C", "effect", "Rain makes streets wet and slippery, creating dangerous conditions for travel.")],
    7324: [("A", "part_whole", "A saw is commonly one of the tools included in a tool kit.")],
    7325: [("E", "motivation", "Having prior knowledge of something makes it easier to remember related information.")],
    7326: [("B", "typical_location", "Stage lights are mounted high in the rafters above an auditorium stage.")],
    7327: [("D", "typical_location", "A dish is commonly used when serving or eating food at a table.")],
    7328: [("D", "effect", "The unpleasant odor of flatulence is what people dislike most about farting.")],
    7329: [("C", "effect", "When a counterweight rises on a mine elevator, the elevator car descends.")],
    7330: [("D", "effect", "Standing in a queue with no alternative means you will have to wait.")],
    7331: [("E", "typical_location", "A jewelry store sells chains and other chain accessories.")],
    7332: [("D", "effect", "Eating undercooked hamburger meat can cause food poisoning.")],
    7333: [("E", "property", "Music that makes people want to dance is typically enjoyable for them.")],
    7334: [("B", "typical_location", "A man often keeps sunglasses in a shirt pocket for quick access.")],
    7335: [("C", "typical_location", "A city commonly has multiple ticket offices for trains, theaters, and other venues.")],
    7336: [("D", "typical_location", "Household window cleaner can damage a computer monitor screen.")],
    7337: [("D", "motivation", "When a friend needs help moving, a supportive response is to offer to help.")],
    7338: [("E", "typical_location", "A barber at a barber shop regularly uses a comb when cutting hair.")],
    7339: [("B", "typical_location", "A finished board game is commonly stored on a shelf at home.")],
    7340: [("B", "used_for", "Sharing knowledge with others is commonly done by teaching another person.")],
    7341: [("C", "has_prerequisite", "Finding information requires time in addition to research materials.")],
    7342: [("C", "typical_location", "A head at a morgue belongs to a deceased person who cannot move.")],
    7343: [("E", "effect", "Eating an unhealthy lunch can cause heartburn afterward.")],
    7344: [("C", "typical_location", "A restaurant that serves spirits appropriately relies on spirits supplied from a brewery.")],
    7345: [("D", "typical_location", "Finding bread inside a car would seem odd in most everyday situations.")],
    7346: [("E", "motivation", "After a workplace injury, a coworker may advise paying more attention to safety.")],
    7347: [("B", "typical_location", "When a computer will not boot, people often buy a replacement at a computer store.")],
    7348: [("A", "typical_location", "New York City is a famous filming location that audiences often recognize on screen.")],
    7349: [("C", "motivation", "Someone new to a city who practices communication skills is likely planning on making friends.")],
    7350: [("C", "typical_location", "A post office provides both mailboxes and stamps for sending mail.")],
    7351: [("A", "effect", "When many siblings keep having children, the extended family grows into a larger family.")],
    7352: [("B", "part_whole", "Iron ore is the mineral dug from the earth and smelted to produce iron.")],
    7353: [("B", "typical_location", "Air conditioners are more commonly used in the hot southern United States.")],
    7354: [("E", "typical_location", "A marmoset feels safest in a sheltered burrow away from predators.")],
    7355: [("E", "typical_location", "A television can be stored and hidden inside a cabinet when not in use.")],
    7356: [("D", "effect", "Surprising a baby during peek-a-boo commonly causes laughter.")],
    7357: [("C", "typical_location", "Astronauts in a space shuttle receive instructions from ground control by radio.")],
    7358: [("C", "typical_location", "A man getting a divorce may leave his marital home and stay at a relative's house such as his aunt's house.")],
    7359: [("E", "used_for", "Ice can be carved with tools to give it a desired artistic shape.")],
    7360: [("A", "effect", "Jumping rope is vigorous exercise that makes a person active.")],
    7361: [("B", "effect", "Mold growing on carpet can produce a foul odor and make a room smell bad.")],
    7362: [("C", "effect", "Tickling someone near a very ticklish spot commonly produces giggling.")],
    7363: [("E", "typical_location", "Peanuts are commonly stored or served from a jar.")],
    7364: [("A", "used_for", "To reach a store visible across the street, a person must cross the road.")],
    7365: [("D", "property", "An odd new trend that becomes widespread is often described as the new normal.")],
    7366: [("B", "effect", "Waking up in the middle of the night can cause irritability the next day.")],
    7367: [("D", "property", "Puppies are commonly described as cute.")],
    7368: [("C", "typical_location", "An unused old refrigerator is often stored in a garage.")],
    7369: [("D", "motivation", "Many young people enjoy driving a car because it lets them have fun.")],
    7370: [("D", "used_for", "To remember facts for a test, a student must memorize them while studying.")],
    7371: [("B", "capability", "Running after a ball quickly requires having legs to move fast.")],
    7372: [("D", "effect", "Listening to someone play violin can bring relaxation to the listener.")],
    7373: [("A", "used_for", "Parents often encourage bored children to read a book.")],
    7374: [("C", "effect", "Being drunk commonly causes stumbling and difficulty walking in a straight line.")],
    7375: [("B", "motivation", "People commonly create art to express themselves.")],
    7376: [("B", "used_for", "Eating fruit is a common way to satisfy a craving for something sweet and healthy.")],
    7377: [("B", "effect", "Learning answers to troubling questions can give a person a free mind.")],
    7378: [("B", "typical_location", "A hotel room away from home often includes a small kitchenette.")],
    7379: [("B", "property", "The tortoise traveled slowly yet steadily, which allowed it to win the race.")],
    7380: [("A", "used_for", "Setting a cup on the table means putting it down as requested.")],
    7381: [("A", "property", "Attending church and praying are examples of religiosity.")],
    7382: [("E", "used_for", "People commonly trade for services or goods by using money.")],
    7383: [("E", "typical_location", "Children commonly stand in lines with other children at school.")],
    7384: [("E", "effect", "Drinking alcohol commonly leads to frequent urination, sending people to the bathroom.")],
    7385: [("D", "effect", "Winning a game commonly brings a feeling of satisfaction.")],
    7386: [("B", "capability", "A young bird still in the nest will soon need to learn to fly.")],
    7387: [("D", "typical_location", "In many Asian restaurants, food is served and eaten in a bowl.")],
    7388: [("D", "typical_location", "When not dining out, the closest place to eat is usually your own house.")],
    7389: [("D", "property", "Floating disembodied lips could hypnotize someone through their surreal motion.")],
    7390: [("D", "motivation", "Someone who does not want to move where they live is often said to want to stay put.")],
    7391: [("D", "used_for", "Two people wrestling for fun are typically playing around together.")],
    7392: [("A", "typical_location", "Someone removes a ring before bathing so it will not get wet in the bath tub.")],
    7393: [("B", "effect", "People commonly get angry when they are in a fight.")],
    7394: [("A", "typical_location", "Jumping insects propel themselves through the air between surfaces.")],
    7395: [("A", "effect", "Too many people driving on the roads commonly causes traffic jams.")],
    7396: [("A", "effect", "Couples sometimes say they started falling in love at first sight.")],
    7397: [("E", "typical_location", "A child can get a wagon at a toy store.")],
    7398: [("D", "effect", "A director tells an extra to step aside because the cameras have moved to a new position.")],
    7399: [("C", "effect", "A panicked babysitter receiving an unexpected call may abruptly hang up.")],
    7400: [("D", "property", "Guns are restricted in some areas because they are deadly in the wrong hands.")],
    7401: [("B", "typical_location", "Nearly all humans live on planet Earth.")],
    7402: [("E", "effect", "Serious heart problems in a living thing can ultimately lead to death.")],
    7403: [("A", "effect", "When a train leaves the station it begins to accelerate down the tracks.")],
    7404: [("B", "property", "Religious spiritual life is often not acknowledged in a secular worldview.")],
    7405: [("D", "effect", "A chemical solution becoming warm is an expected consequence of an increase of temperature.")],
    7406: [("A", "property", "Something done sometimes but not often is described as occurring only occasionally.")],
    7407: [("A", "used_for", "Conglomerates reaching a tentative agreement typically plan to do business together.")],
    7408: [("E", "typical_location", "Dust commonly accumulates underneath carpet fibers on the floor.")],
    7409: [("D", "part_whole", "If the world consists of materials, it is made of the substances of the physical world.")],
    7410: [("A", "effect", "Trembling hands while holding a cup make someone worry they will end up breaking the cup.")],
    7411: [("C", "typical_location", "Popcorn is a crunchy snack commonly eaten at a movie theater.")],
    7412: [("B", "effect", "If too much payroll tax is withheld, the IRS may issue a refund.")],
    7413: [("C", "motivation", "People attend a self-help lecture hoping to accomplish gaining knowledge.")],
    7414: [("A", "property", "Someone who creates art is often described as very inspired.")],
    7415: [("D", "effect", "Instead of speaking eloquently, a nervous person may end up stuttering over their words.")],
    7416: [("A", "effect", "When friends ditch you, you are likely to feel let down.")],
    7417: [("D", "typical_location", "Most household plumbing runs inside the walls behind fixtures.")],
    7418: [("D", "effect", "People often tape a television show to watch again because they enjoyed it the first time.")],
    7419: [("D", "effect", "When a couple drinks alcohol together, it may lower inhibitions and lead to having sex.")],
}
