# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 8820-8919 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8820_8919 = {
    8820: [("B", "typical_location", "A house commonly has artificial light sources such as lamps and ceiling fixtures.")],
    8821: [("D", "effect", "Eating spicy food commonly causes heartburn in many people.")],
    8822: [("B", "effect", "Dogs with no intruders to guard against commonly sleep soundly.")],
    8823: [("B", "typical_location", "A department store sells both purses and televisions.")],
    8824: [("A", "typical_location", "Bowling alleys have gutters that keep balls from rolling off the lane.")],
    8825: [("B", "motivation", "A horse that wins many major races hopes to achieve the triple crown.")],
    8826: [("B", "used_for", "People bowing before a statue are likely worshipping idols.")],
    8827: [("E", "typical_location", "A sporting goods store sells jerseys and other uniform tops.")],
    8828: [("D", "motivation", "Being tired makes people realize they need to have rest.")],
    8829: [("A", "used_for", "Bringing suit is a legal expression meaning going to court.")],
    8830: [("A", "typical_location", "A streaming box connected to a TV lets someone use it like a computer.")],
    8831: [("D", "typical_location", "Many rivers flow into and out of a lake.")],
    8832: [("E", "motivation", "A scientist analyses compiled lab data to gain better understanding.")],
    8833: [("C", "property", "All known science says traveling faster than light is impossible.")],
    8834: [("D", "effect", "Wearing shoes that are too tight while jogging commonly causes blisters on the feet.")],
    8835: [("C", "typical_location", "A dirt highway is commonly found out in the countryside.")],
    8836: [("D", "has_prerequisite", "Birds lay eggs after having a mate.")],
    8837: [("C", "typical_location", "Washington state has a Columbia County and lies furthest west among the listed places.")],
    8838: [("D", "typical_location", "Someone hiding from a tornado might find a snake in a ditch.")],
    8839: [("A", "used_for", "Someone crafty with needles may enjoy sewing along with needlepoint and crocheting.")],
    8840: [("E", "cause", "Fatigue commonly causes a person to stop driving and rest at a hotel.")],
    8841: [("B", "typical_location", "The information superhighway is a metaphor for cyberspace.")],
    8842: [("D", "property", "A shy person at a school dance often ends up as a wallflower.")],
    8843: [("A", "typical_location", "Books are a good place to find many fictional words.")],
    8844: [("D", "property", "A strict school dress code may require girls to wear a long skirt.")],
    8845: [("D", "typical_location", "Illness is a common way a stay ends for an elderly resident of a nursing home.")],
    8846: [("B", "effect", "Watching a frightening horror film like Saw commonly causes fear.")],
    8847: [("E", "effect", "The government may take money through penalties if you fail to file taxes.")],
    8848: [("D", "used_for", "After losing a primary, a caring candidate may still advocate for the opponent.")],
    8849: [("A", "typical_location", "A homeless person can go to a homeless shelter for food.")],
    8850: [("B", "part_whole", "The motherboard is the part of a computer that holds memory and processing chips.")],
    8851: [("C", "effect", "Staying healthy commonly helps a person live a long life.")],
    8852: [("B", "property", "The hands of someone who does not do manual labor tend to be soft.")],
    8853: [("A", "motivation", "People commonly want to feel amusement while playing cards.")],
    8854: [("C", "typical_location", "An amusement park is a good place to purchase a toy balloon.")],
    8855: [("D", "typical_location", "Clothes being donated to charity are commonly folded and placed into a bag.")],
    8856: [("B", "typical_location", "Millions of marmosets sit in trees across Latin America.")],
    8857: [("C", "typical_location", "With a cold, a tissue holder belongs in a bathroom or bedroom while staying inside.")],
    8858: [("A", "effect", "Radio communication often produces static on the other end of the line.")],
    8859: [("A", "typical_location", "Months worth of canned food is commonly kept in a pantry.")],
    8860: [("B", "typical_location", "An unused weapon is likely stored in an army bunker.")],
    8861: [("D", "effect", "After a hard day, someone overcome by fatigue may fall to the earth during a break.")],
    8862: [("D", "effect", "Using complicated words and technical language is likely to draw blank stares from an audience.")],
    8863: [("B", "cause", "People often want to stop being married because of trouble in the relationship.")],
    8864: [("E", "typical_location", "Food packaged for sale is bound for a shop.")],
    8865: [("D", "typical_location", "You would get an upright piano from a music store if you do not already have one.")],
    8866: [("E", "property", "Someone who believes in God yet kills a divine entity would be considered horrible.")],
    8867: [("B", "motivation", "Someone hungry with nothing in the house must buy food.")],
    8868: [("D", "effect", "A dangerous rescue may endanger those attempting it.")],
    8869: [("E", "typical_location", "A beautiful thunderstorm is commonly viewed across an open plain.")],
    8870: [("D", "effect", "A kid commonly cries when riding a bike after falling off.")],
    8871: [("A", "typical_location", "A saw that is too big may not fit with wrenches and screwdrivers in a metal toolbox.")],
    8872: [("A", "typical_location", "Millions of ficus plants can be found at an arboretum.")],
    8873: [("C", "typical_location", "A drawer is a good place in a home to keep an extra eyeglasses case.")],
    8874: [("B", "property", "A bedroom should be in darkness before sleeping.")],
    8875: [("E", "used_for", "A telephone lets you hear other people and be heard yourself.")],
    8876: [("B", "typical_location", "In an abandoned house, a stride through dust leaves a clear path on the ground.")],
    8877: [("D", "typical_location", "A snowflake is quite beautiful when it is falling through the air.")],
    8878: [("E", "effect", "A lying employee is likely to end up being fired.")],
    8879: [("D", "has_prerequisite", "Being able to cogitate means a person clearly must have a brain.")],
    8880: [("E", "typical_location", "The Gideons place Bibles in night table drawers at hotels.")],
    8881: [("C", "used_for", "Learning to dance is one way to put excitement into a routine.")],
    8882: [("A", "used_for", "A horse rider who wants to find foxes should participate in an English hunt.")],
    8883: [("D", "effect", "Running while dehydrated in humid heat commonly causes leg cramps.")],
    8884: [("D", "used_for", "Someone contemplating a choice will likely spend the following day deciding.")],
    8885: [("C", "effect", "Smoking during pregnancy is linked to birth defects in growing families.")],
    8886: [("D", "typical_location", "A shelf would fit well in the corner of a room.")],
    8887: [("B", "effect", "A business spending beyond its means may face bankruptcy and make a declaration.")],
    8888: [("B", "typical_location", "Scissors you will not need soon belong in a cabinet for storage.")],
    8889: [("E", "effect", "Getting drunk and losing inhibitions commonly leads to slurred speech.")],
    8890: [("D", "typical_location", "A terrace overlooking a section of the Grand River is likely located in Michigan.")],
    8891: [("D", "effect", "When two people love each other, they commonly experience happiness.")],
    8892: [("A", "used_for", "The customary thing to say when someone sneezes is bless you.")],
    8893: [("A", "effect", "Someone excited about meeting close family is likely feeling love.")],
    8894: [("C", "used_for", "To have fun at a winter party outside, you should wrap up warmly.")],
    8895: [("B", "effect", "When a curtain closes, the show is over.")],
    8896: [("E", "typical_location", "Mats are usually placed in a doorway of a house.")],
    8897: [("E", "typical_location", "A skylight is most likely installed on the roof of a building.")],
    8898: [("B", "effect", "Adults watching TV quietly hope the baby will fall asleep.")],
    8899: [("B", "typical_location", "A student commonly keeps and finds pens in a backpack.")],
    8900: [("D", "capability", "A human is adapted to handle diverse situations.")],
    8901: [("E", "effect", "People commonly feel fatigue after travelling a long distance.")],
    8902: [("E", "typical_location", "An advertising company is a business, not a place where you find an office building.")],
    8903: [("D", "used_for", "Having sex is one way two people communicate that they are in love.")],
    8904: [("E", "used_for", "Rather than talk in class, a student should be silent and pay attention.")],
    8905: [("E", "motivation", "Killing people because they are bad is commonly called vengeance.")],
    8906: [("D", "typical_location", "Scientific instruments are used in a laboratory.")],
    8907: [("D", "effect", "Learning about the world and how it works can cause a loss of innocence.")],
    8908: [("A", "typical_location", "Someone dressed in costume about to go on stage is likely about to be in a play.")],
    8909: [("C", "part_whole", "A saw is not necessary for car repair and would not be included in a basic tool kit.")],
    8910: [("E", "typical_location", "A house is a place that could have one back garden.")],
    8911: [("B", "effect", "Movement happens while someone is going somewhere.")],
    8912: [("C", "motivation", "A person who wants to be successful often has an end goal to acquire wealth.")],
    8913: [("C", "used_for", "Metal is smelted out of minerals in the countryside.")],
    8914: [("E", "used_for", "A human can get around by taking a bus.")],
    8915: [("C", "property", "People who are lying to one another are behaving deceptively.")],
    8916: [("D", "typical_location", "Potato chips are commonly bought at a supermarket.")],
    8917: [("C", "used_for", "Curious kids who want to check the weather outside should open the door.")],
    8918: [("E", "effect", "When a 1940s radio show pretended Earth was invaded by Martians, many people believed it.")],
    8919: [("A", "used_for", "After a long hard day of work, it is time for sitting down and relaxing.")],
}
