# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 6520-6619 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6520_6619 = {
    6520: [("D", "effect", "Moving a car without looking is dangerous and commonly leads to accidents.")],
    6521: [("D", "property", "To enlarge a backyard you extend the boundaries of the property.")],
    6522: [("C", "typical_location", "An apple orchard has fruit on tall trees that may require a ladder to reach.")],
    6523: [("C", "typical_location", "Sailing in the Caribbean evokes pirate lore and the search for a treasure chest.")],
    6524: [("A", "typical_location", "A garage is a good place to store a work wagon.")],
    6525: [("B", "motivation", "Someone enjoying city life but still searching is often looking for happiness.")],
    6526: [("C", "motivation", "After hard work people commonly watch television to be entertained.")],
    6527: [("A", "part_whole", "A physiologist examining bones would be looking at a skeleton.")],
    6528: [("C", "used_for", "Reading a book is a good way to relieve boredom.")],
    6529: [("D", "effect", "A longer reach can help a boxer achieve victory over an opponent.")],
    6530: [("E", "typical_location", "A place setting with a plate flanked by silverware is commonly on a table.")],
    6531: [("C", "used_for", "After receiving a passing sentence, a defendant may pursue appeals.")],
    6532: [("D", "motivation", "Someone in a hurry to bake bread may say they do not have all day because they are hungry.")],
    6533: [("A", "effect", "Kissing often can lead to arousal between partners.")],
    6534: [("E", "typical_location", "Marmosets may be found in a protected national park in South America.")],
    6535: [("A", "typical_location", "An attic typically has a ceiling that is closer to the floor than most rooms.")],
    6536: [("E", "property", "Remembering every answer on a test likely demonstrates strong knowledge.")],
    6537: [("D", "property", "A garden is usually at its most beautiful when flowers are in full bloom.")],
    6538: [("D", "effect", "Successfully competing against a worthy adversary commonly makes a person feel pride.")],
    6539: [("D", "property", "Something scary seen in an entrance hall might turn out to be just a person.")],
    6540: [("C", "typical_location", "An indoor ficus needs water and should be placed near a sunny window.")],
    6541: [("B", "effect", "When someone is not in their right mind, their brain can play tricks on them.")],
    6542: [("D", "typical_location", "People normally take a bath in their own home.")],
    6543: [("B", "typical_location", "When heading home from a trip, airports often have gift shops for last-minute souvenirs.")],
    6544: [("C", "typical_location", "A home bread machine is typically kept in the house.")],
    6545: [("E", "effect", "Ice can help a person cool off on a hot day.")],
    6546: [("A", "typical_location", "Money not carried in a wallet is commonly kept in a bank account.")],
    6547: [("A", "typical_location", "Athletes may feel chills walking through a central passage into an arena.")],
    6548: [("E", "typical_location", "The baboon is a monkey species native to the African continent.")],
    6549: [("E", "used_for", "Talking to others is a typical way people try to make friends.")],
    6550: [("D", "used_for", "Seeing his team and sizing up opponents, he was about to compete against them.")],
    6551: [("A", "property", "A station refusing censorship may aim to remain neutral on contested issues.")],
    6552: [("B", "motivation", "People want to get warm when cold because it helps them feel comfortable.")],
    6553: [("B", "typical_location", "Someone sitting on a folding chair in a big room with a stage may be in an auditorium.")],
    6554: [("C", "used_for", "When you do not want something, you reject it.")],
    6555: [("E", "property", "People who unwind by listening to music often find it relaxing.")],
    6556: [("B", "typical_location", "Someone searching for human ancestors might look at a gravesite.")],
    6557: [("B", "property", "A careless mistake can sometimes leave someone in an advantageous position.")],
    6558: [("A", "typical_location", "Students do most of their learning in a classroom.")],
    6559: [("A", "typical_location", "At work someone might keep an eyeglasses case in a drawer.")],
    6560: [("B", "typical_location", "On a computer you view a window showing your current task on the screen.")],
    6561: [("A", "property", "Mediocre performance suggests habits that are not distinguished.")],
    6562: [("E", "typical_location", "A towel in a cardboard box gives a kitten a warm place to rest.")],
    6563: [("E", "effect", "Someone focused on learning science will gain scientific knowledge.")],
    6564: [("C", "typical_location", "Humans are kept in large numbers in small spaces in a prison.")],
    6565: [("B", "typical_location", "Many random citizens use an entrance hall to enter a public building.")],
    6566: [("C", "used_for", "Someone who enjoys fabric as a medium often expresses creativity by sewing.")],
    6567: [("E", "effect", "A very cheap company may fail to pay employees fairly.")],
    6568: [("D", "used_for", "A detective searching through lies aims to find facts.")],
    6569: [("B", "typical_location", "A small dog would be very happy at a gathering at grandma's house.")],
    6570: [("D", "used_for", "People with strong feelings for each other may kiss and also embrace.")],
    6571: [("A", "typical_location", "Someone seeking shelter in a city may go to a homeless shelter.")],
    6572: [("E", "property", "A stuffy feeling in a shirt may lead someone to unfasten a button-up shirt.")],
    6573: [("D", "typical_location", "An antique pirate artifact might be stored in a locked drawer.")],
    6574: [("A", "property", "Fatalism contrasts with a strong belief in free will.")],
    6575: [("C", "used_for", "Contestants on American Idol wait their turn to sing.")],
    6576: [("C", "typical_location", "Someone saving for a bass guitar would go to a music store to get it.")],
    6577: [("E", "typical_location", "Seeing a shark near Tahiti means you are in the South Pacific.")],
    6578: [("D", "capability", "A soldier is expected to be able to follow instructions.")],
    6579: [("D", "motivation", "Tinder encourages meeting people to help users make new friends.")],
    6580: [("E", "typical_location", "A farmer working on a wet terrace may be in a rice paddy.")],
    6581: [("E", "used_for", "People trying to stop a parade may set up a roadblock.")],
    6582: [("A", "typical_location", "A small dog wearing a white coat might be found in a laboratory.")],
    6583: [("D", "property", "Someone gawking at diamonds likely thinks they are pretty.")],
    6584: [("B", "used_for", "Reading a book can help someone have fun when bored.")],
    6585: [("D", "cause", "Living where many people gather can make it hard to move around because of commotion.")],
    6586: [("A", "typical_location", "A doctor may recommend a health centre spa for recovery from a torn ankle.")],
    6587: [("E", "has_prerequisite", "To eat lunch you need to have time for it.")],
    6588: [("A", "effect", "Drinking alcohol too fast commonly leads to intoxication.")],
    6589: [("A", "typical_location", "Someone waiting for a wife arriving from France might be at the airport.")],
    6590: [("A", "effect", "Someone who dislikes authority figures does not like being ordered around.")],
    6591: [("E", "effect", "Driving a car too fast is likely to result in a speeding ticket.")],
    6592: [("C", "used_for", "A college student wanting to meet people may dislike going to parties.")],
    6593: [("A", "motivation", "An idealist who gives away computers often does so to help people.")],
    6594: [("D", "typical_location", "A specialty store is a good place to get a gift for someone with specific tastes.")],
    6595: [("D", "effect", "A kid wanting to play outside is sick of doing nothing indoors.")],
    6596: [("B", "effect", "Someone with beef allergies may suffer gas after eating a hamburger.")],
    6597: [("E", "typical_location", "Students commonly keep rubber bands in the classroom.")],
    6598: [("B", "part_whole", "In a battleship fleet the smaller warship may be called a corvette.")],
    6599: [("C", "primary_function", "A sump pump is used to move water out of a flooded room.")],
    6600: [("A", "used_for", "Taking pictures at an event helps you remember it later.")],
    6601: [("D", "used_for", "In a soccer game players commonly use their head on the ball.")],
    6602: [("E", "capability", "Someone skilled at thinking who applies it broadly ends up solving problems.")],
    6603: [("D", "used_for", "A customer often calls an electric company to pay bills.")],
    6604: [("E", "used_for", "A person might use a cloth to remove a drop of blood from a surface.")],
    6605: [("C", "effect", "A parent's concern may be met with indifference from a teacher.")],
    6606: [("A", "typical_location", "You can see people who use a puck professionally at a hockey rink.")],
    6607: [("A", "used_for", "After recording something and having it transcribed you may need a spell checker.")],
    6608: [("B", "typical_location", "A laundry room used by only a few people may be in the basement of an apartment building.")],
    6609: [("A", "typical_location", "A bicycle is likely to be stolen when left on a street.")],
    6610: [("E", "effect", "Someone staying in bed without moving at all may simply doze.")],
    6611: [("D", "used_for", "Large groups claiming to change society often demonstrate in public.")],
    6612: [("D", "typical_location", "A waiter brings water to customers at a restaurant.")],
    6613: [("C", "primary_function", "Police are likely to conduct an investigation in a killing.")],
    6614: [("A", "typical_location", "A sailor on a voyage may stow a suitcase in the cargo hold.")],
    6615: [("C", "typical_location", "A child who never saw a jellyfish in real life may have only seen one in a tank.")],
    6616: [("C", "property", "Fish make good entry-level pets because they are relatively easy to care for.")],
    6617: [("E", "property", "Someone wanting to feel safe again may have been in a harmful relationship.")],
    6618: [("C", "effect", "When someone is snoring they produce a loud noise.")],
    6619: [("A", "used_for", "A coach teaching respect does not want players to belittle opponents.")],
}
