# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 5820-5919 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_5820_5919 = {
    5820: [("D", "typical_location", "Geography is the science class that studies the earth and its physical features.")],
    5821: [("C", "typical_location", "A person gives a dog a bone reward by placing it in the dog's mouth.")],
    5822: [("A", "motivation", "Someone procreating without wanting sex with a man may seek a reproductive partner through a clinic.")],
    5823: [("E", "property", "Big is the opposite of little in size.")],
    5824: [("D", "typical_location", "Someone heading to a meeting often keeps related literature in a bag.")],
    5825: [("A", "effect", "Getting what you want in life commonly brings a little bit of happiness.")],
    5826: [("A", "property", "A contrarian demographer might dismiss an important anomaly as trivial.")],
    5827: [("E", "used_for", "To sort a pile of stuff you must start by separating things into groups.")],
    5828: [("E", "typical_location", "Food you want to eat right now is commonly placed on a plate.")],
    5829: [("D", "motivation", "People with money who want things tend to buy and own objects.")],
    5830: [("D", "typical_location", "Flame-broiled hamburgers are commonly served at a fast food restaurant.")],
    5831: [("B", "used_for", "Getting married is a common way to start living life together with someone else.")],
    5832: [("C", "effect", "Medication that relieves symptoms can take away a person's pain.")],
    5833: [("C", "typical_location", "Safety laws require a fire extinguisher in every public building.")],
    5834: [("D", "effect", "Eating vegetables as a doctor advises commonly helps a person lose weight.")],
    5835: [("A", "property", "Unconventional describes traits or behavior that mean the opposite of normal.")],
    5836: [("E", "typical_location", "You buy a replacement screw for a loose drawer knob at a hardware store.")],
    5837: [("E", "capability", "The living have experiences that the dead cannot have.")],
    5838: [("C", "typical_location", "A leader with nothing to lead needs a company or group to lead.")],
    5839: [("A", "cause", "Viruses cause both the flu and the common cold.")],
    5840: [("E", "typical_location", "Some monkeys originated in South Africa, a place with borders and many people.")],
    5841: [("B", "typical_location", "On a pool table you hit a ball with a stick into other balls.")],
    5842: [("D", "used_for", "You fit one piece with another piece when assembling a jigsaw puzzle.")],
    5843: [("E", "effect", "Studying too intensely can cause headaches.")],
    5844: [("A", "typical_location", "During the week a teacher speaks with school children more than anyone else.")],
    5845: [("D", "typical_location", "A woman who wants to bring a writing instrument with her often keeps it in a purse.")],
    5846: [("E", "used_for", "When thirsty, a person uses their hands to pick up a cup and drink.")],
    5847: [("D", "used_for", "A pioneer bought salt at a general store for food preservation.")],
    5848: [("C", "effect", "Agreeing with someone commonly helps people become closer.")],
    5849: [("A", "typical_location", "A researcher studying apes in the wild may live in isolation for months.")],
    5850: [("B", "effect", "A frustrated customer at a busy restaurant may wait in line for service.")],
    5851: [("A", "motivation", "A serious pragmatic person drives a car primarily for transportation.")],
    5852: [("C", "property", "Minnesota is a state whose name many people find difficult to spell.")],
    5853: [("D", "motivation", "A student's broad goal is often to improve in every aspect of life.")],
    5854: [("A", "effect", "Seeing a horrible sight at an area of elevation may make you feel disgust.")],
    5855: [("A", "typical_location", "The kitchen is the best place in a home to make food.")],
    5856: [("D", "typical_location", "Extra sheets of paper are commonly stored in a cabinet.")],
    5857: [("E", "effect", "Remembering a happy wedding day can cause a person to experience pleasure.")],
    5858: [("D", "effect", "Finding a long lost painting would bring an artist great relief.")],
    5859: [("D", "used_for", "When tomatoes are dying, a gardener should water the garden.")],
    5860: [("A", "typical_location", "People commonly borrow a cup of sugar from a neighbor's house.")],
    5861: [("B", "typical_location", "A human can find body coverings such as clothes at a clothing store.")],
    5862: [("A", "used_for", "When there is no agenda, friends commonly like to hang out together.")],
    5863: [("E", "effect", "Two people without initial attraction can grow to love another over time.")],
    5864: [("E", "property", "Music is usually considered a beautiful sound.")],
    5865: [("E", "has_prerequisite", "You can use a television without opening your eyes, though open eyes let you see it.")],
    5866: [("D", "property", "Anxiety about performing in front of others is called stage fright.")],
    5867: [("A", "capability", "A mosquito collects many a drop of blood when it bites people or animals.")],
    5868: [("E", "typical_location", "A dictionary is commonly found in a classroom where young people get lessons.")],
    5869: [("C", "capability", "Even a mean person can sometimes show kindness to others.")],
    5870: [("C", "typical_location", "A hotel room contains a bed that has been used by many different people.")],
    5871: [("B", "effect", "Without a return ticket a traveler commonly misses their plane home.")],
    5872: [("D", "property", "Something whose weight is not light is heavy.")],
    5873: [("D", "typical_location", "You can buy an electric fan at a hardware store.")],
    5874: [("E", "typical_location", "You can buy a night table to take home at a furniture store.")],
    5875: [("C", "typical_location", "A table next to a side chair makes a nice place to read and drink coffee.")],
    5876: [("A", "typical_location", "You use a changing room at the gym before working out.")],
    5877: [("C", "used_for", "Someone hiding sobs may disguise crying by laughing instead.")],
    5878: [("E", "typical_location", "A marmot in California might be seen in the Sierra Nevada mountains.")],
    5879: [("B", "typical_location", "A small village outside a city is generally located in the countryside.")],
    5880: [("A", "typical_location", "You can see a religious statue at a church.")],
    5881: [("E", "typical_location", "A restaurant often has tables set with silverware rolled into displayed napkins.")],
    5882: [("C", "typical_location", "People commonly encounter many escalators when visiting a mall.")],
    5883: [("E", "effect", "Many cats dislike being bathed more than most other unpleasant activities.")],
    5884: [("D", "typical_location", "A post office is always located inside a building.")],
    5885: [("D", "typical_location", "You bring your flight bag to the airport when traveling by air.")],
    5886: [("C", "primary_function", "Computers use ones and zeroes to do arithmetic and process information.")],
    5887: [("A", "used_for", "While attending a lecture in an auditorium students should take notes.")],
    5888: [("B", "motivation", "Someone running from an assailant runs to move fast and escape danger.")],
    5889: [("D", "motivation", "A person frustrated online usually desires to find information they could not locate.")],
    5890: [("C", "property", "The world stays in motion even when a person is being still.")],
    5891: [("A", "effect", "Brave actions are worthy of admiration even when you disdain the person.")],
    5892: [("E", "typical_location", "Ferrets are found out of doors in the wild before they are captured.")],
    5893: [("C", "part_whole", "A wobbly chair often has four legs that are uneven.")],
    5894: [("C", "has_prerequisite", "Using soap is necessary for a thorough bath.")],
    5895: [("E", "typical_location", "Trees are likely to be protected within a state park.")],
    5896: [("E", "used_for", "In the middle of the night it is hard to communicate using only a whisper.")],
    5897: [("B", "motivation", "Striving for happier circumstances is called seeking a better life.")],
    5898: [("C", "effect", "Going to work with a boss you dislike commonly sets in stress.")],
    5899: [("C", "capability", "A person uses a contraceptive device to prevent pregnancy.")],
    5900: [("B", "typical_location", "Farmland away from the city is located in the countryside.")],
    5901: [("A", "typical_location", "A liquid that should be stored and not easily consumed goes in a jar.")],
    5902: [("C", "used_for", "Bringing suit against someone means going to court over a legal dispute.")],
    5903: [("C", "effect", "Looking at other people's artwork commonly inspires an artist to create.")],
    5904: [("D", "typical_location", "After a puppy is housebroken it may sleep in a bed indoors.")],
    5905: [("D", "typical_location", "A final exam is often given at the end of each semester.")],
    5906: [("C", "effect", "Someone beginning work they really want to do likely feels excitement.")],
    5907: [("A", "effect", "Driving a car causes air pollution from exhaust emissions.")],
    5908: [("A", "typical_location", "After hours on the road a driver longingly eyes the seats at a rest area.")],
    5909: [("C", "typical_location", "When getting dressed a person often checks a mirror in the bedroom.")],
    5910: [("C", "typical_location", "Roses used across America are also shipped north to Canada.")],
    5911: [("A", "used_for", "To find a bus arrival time a person reads the text on the station schedule.")],
    5912: [("D", "has_prerequisite", "Criminals often arm themselves before robbing a bank.")],
    5913: [("D", "motivation", "A sailor is typically most excited for the destination of coming home.")],
    5914: [("B", "used_for", "Someone listening to music may sing along for enjoyment.")],
    5915: [("C", "used_for", "A turkey needed for cooking is commonly placed in an oven.")],
    5916: [("D", "part_whole", "A country that spans the entire breadth of a landmass lies on a continent.")],
    5917: [("B", "effect", "When you gain someone's trust they will do what you want because you have persuaded them.")],
    5918: [("A", "property", "A diss track is a rap song directed at someone as an insult.")],
    5919: [("D", "used_for", "A mechanic is commonly asked to fix problems with machine parts.")],
}
