# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 8120-8219 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8120_8219 = {
    8120: [("A", "typical_location", "Children commonly go to school to learn reading, math, and other subjects.")],
    8121: [("D", "used_for", "A winch on an off-road vehicle uses strong steel cable to pull or recover stuck vehicles.")],
    8122: [("C", "typical_location", "A non-slip bath mat is often chosen to match the colors of a bathroom.")],
    8123: [("A", "primary_function", "A candle emits light when its wick is lit during a power outage.")],
    8124: [("E", "effect", "Washing hands with water immediately makes them become wet.")],
    8125: [("A", "typical_location", "Munitions loaded onto a launch platform are commonly found at Cape Canaveral.")],
    8126: [("A", "property", "A person who is overly drunk often seems disoriented to others.")],
    8127: [("C", "typical_location", "A restaurant located at a hotel may allow guests to sleep there after dining.")],
    8128: [("D", "used_for", "Many companies communicate advertisements directly to consumers through email.")],
    8129: [("C", "effect", "Water from a leaky faucet commonly dribbles out in drops rather than flowing steadily.")],
    8130: [("C", "property", "An annoying neighbor who bothers others is often considered a bore.")],
    8131: [("D", "property", "Each cough and noise is amplified during the silence of a softly hummed hymn.")],
    8132: [("A", "used_for", "Couples preparing to copulate often begin foreplay by kissing each other.")],
    8133: [("E", "typical_location", "A religious community bake sale commonly takes place in the basement of a church.")],
    8134: [("C", "part_whole", "Purchasing a bass drum is one step toward assembling a complete drum set.")],
    8135: [("E", "effect", "Seeing how old things were created long ago is likely to cause nostalgia.")],
    8136: [("A", "used_for", "Dogs commonly like to chew and eat bones as a treat.")],
    8137: [("B", "capability", "A nimble person who is not yet skilled at climbing may still have good dexterity.")],
    8138: [("B", "typical_location", "An airport passageway is a crowded corridor where many people walk together.")],
    8139: [("A", "motivation", "Some people fart playfully in order to get attention from others.")],
    8140: [("C", "used_for", "The old song about twisting tells listeners to twist and shout.")],
    8141: [("A", "property", "A bright green ficus plant is often a sign of good health.")],
    8142: [("B", "effect", "When you meet interesting people your contacts list is likely to grow.")],
    8143: [("D", "used_for", "Climbing a hill can give you a good vantage point to survey the landscape.")],
    8144: [("B", "typical_location", "Ten or a hundred attached homes are commonly found in an apartment building.")],
    8145: [("D", "typical_location", "People compete to see who is quicker at a race track.")],
    8146: [("E", "motivation", "Someone who always spends money may list going shopping as a favorite hobby.")],
    8147: [("E", "effect", "Riding a horse for a long time can cause stiffness and pain in the legs.")],
    8148: [("B", "effect", "A person who picks at their skin may develop open sores over time.")],
    8149: [("A", "part_whole", "Pointed ears are a visible part of a dog that you can see.")],
    8150: [("A", "property", "Soccer matches among major athletic competitions often generate intense excitement.")],
    8151: [("C", "typical_location", "Humans in cities go to a park when they want to be in nature.")],
    8152: [("A", "effect", "An animal that does not eat will eventually die from starvation.")],
    8153: [("B", "effect", "A tired couple communicating about apartments may still have misunderstandings between them.")],
    8154: [("A", "primary_function", "A vacuum cleaner pulls dirt in by sucking rather than blowing air outward.")],
    8155: [("E", "typical_location", "A small island surrounded by flowing liquid water sits in a body of water.")],
    8156: [("E", "effect", "Fencing with sharp blades can cause small cuts if you are not careful.")],
    8157: [("A", "property", "Listening to music means consuming sound vibrations through your ears.")],
    8158: [("B", "motivation", "A military leader issues commands to his force in order to win a battle.")],
    8159: [("A", "effect", "People caught in severe weather who lose their balance while traveling may experience pain.")],
    8160: [("E", "typical_location", "Young people must follow the rules at school during the day.")],
    8161: [("C", "part_whole", "An injury can happen to any living thing with a body.")],
    8162: [("A", "part_whole", "Meningitis is an illness that affects the brain and its surrounding membranes.")],
    8163: [("A", "property", "Scars on a person's body may indicate they tried committing suicide.")],
    8164: [("E", "typical_location", "After finishing work a pilot commonly goes home to rest.")],
    8165: [("B", "typical_location", "People focused on exercise at a swimming pool are often at a YMCA.")],
    8166: [("D", "effect", "A broken air conditioner may blow hard regardless of how low the dial is set.")],
    8167: [("A", "typical_location", "California is known for sunshine and the Disneyland theme park.")],
    8168: [("B", "typical_location", "A person may blush after slamming a door loudly at a neighbor's house.")],
    8169: [("A", "motivation", "When it is chilly outdoors at night you need warmth to raise your body temperature.")],
    8170: [("C", "typical_location", "Someone who lost an appointment book can buy a new one at an office supply store.")],
    8171: [("B", "typical_location", "A side chair in a bedroom helps when putting on or taking off shoes.")],
    8172: [("C", "effect", "Lightning commonly follows the sound of thunder during a storm.")],
    8173: [("A", "typical_location", "Stamps for a trip are commonly kept inside a suitcase while traveling.")],
    8174: [("A", "motivation", "Drowsiness is a common reason someone decides on going to bed.")],
    8175: [("B", "typical_location", "Shirts with a favorite team's logo are commonly sold at a sporting goods store.")],
    8176: [("B", "property", "A tetrahedron carved and sanded smooth has four equal triangular faces.")],
    8177: [("B", "property", "Something nonessential contrasts with what is essential and truly needed.")],
    8178: [("B", "effect", "Faith in a high power is said to provide solace in times of despair.")],
    8179: [("B", "effect", "Powers fighting inflation aim to avoid economic instability.")],
    8180: [("C", "effect", "The best horse in a competition commonly wins a trophy.")],
    8181: [("E", "typical_location", "People normally apply sunblock to bare skin at the beach.")],
    8182: [("B", "effect", "Overindulging when eating breakfast commonly leaves a person feeling fullness.")],
    8183: [("A", "cause", "A boy may cry because something hurt him.")],
    8184: [("E", "motivation", "A person at work commonly wants to be treated with respect.")],
    8185: [("A", "motivation", "A child going to play is likely to feel they will have fun.")],
    8186: [("B", "typical_location", "Placing a potato in an exhaust pipe can block gases and cause an explosion.")],
    8187: [("E", "property", "A studio-quality stereo system comes with all the bells and whistles.")],
    8188: [("B", "has_prerequisite", "You must breathe in order to live life.")],
    8189: [("A", "used_for", "Waiting tables involves the simple task of having to serve food to customers.")],
    8190: [("C", "used_for", "A western movie production often uses more than one horse for filming.")],
    8191: [("C", "effect", "Prisoners who play cards together do so partly to avoid being bored.")],
    8192: [("A", "property", "A person with a good sense of humor is often called witty.")],
    8193: [("B", "typical_location", "A fox lost among many trees is likely in a dense forest.")],
    8194: [("A", "property", "Someone who is not massive in size may be described as a dwarf.")],
    8195: [("A", "part_whole", "You talk into the mouthpiece of a telephone when making a call.")],
    8196: [("B", "typical_location", "If you raise vegetables at home you would put a shed in the backyard.")],
    8197: [("A", "typical_location", "People who want to go on vacation may visit a national park.")],
    8198: [("B", "typical_location", "A gallery placed in the middle of town can be an equal distance from everyone.")],
    8199: [("C", "used_for", "When washing hands you should wet them, use soap, and then rinse.")],
    8200: [("E", "typical_location", "Using scuba gear in the ocean means you are underwater.")],
    8201: [("C", "effect", "Elementary school students commonly wait in line when going into class.")],
    8202: [("D", "property", "A snake is separated from many other reptiles because it has no legs.")],
    8203: [("A", "effect", "Watching a good television show after a long workday can help a person relax.")],
    8204: [("D", "effect", "Jumping rope for a sustained period is an effect that leads to becoming tired.")],
    8205: [("C", "effect", "Celebrating by drinking too much alcohol is likely to cause hangovers.")],
    8206: [("B", "typical_location", "Someone can likely use more than one washing machine at a laundromat.")],
    8207: [("B", "used_for", "People can best have a conversation when they face each other.")],
    8208: [("E", "effect", "When rain falls outside, stuff left outdoors becomes wet things.")],
    8209: [("B", "typical_location", "The Kentucky Derby is a single prestigious race on the path toward a championship goal.")],
    8210: [("B", "effect", "A man with an injury that limits movement may always quit trying to learn a physical game.")],
    8211: [("D", "effect", "Driving to work while running late commonly causes stress when walking through the door.")],
    8212: [("C", "property", "A piano is heavy and difficult to move without help.")],
    8213: [("C", "typical_location", "You mix ingredients on a counter in a kitchen.")],
    8214: [("D", "effect", "A father who does not want his son to be soft may always be firm on him.")],
    8215: [("B", "typical_location", "Milk that you pour into a container cup commonly comes out of a cow.")],
    8216: [("B", "typical_location", "People who want to hold a demonstration commonly choose a public place.")],
    8217: [("A", "typical_location", "A good place to keep an eyeglasses case while in traffic is the car.")],
    8218: [("A", "effect", "After eating a large dinner and exercising, a person is likely to become tired.")],
    8219: [("E", "used_for", "Eating eggs is something many people do early in the day.")],
}
