# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7920-8019 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_7920_8019 = {
    7920: [("C", "used_for", "People who lack a car often take the bus to commute to work or other regular destinations.")],
    7921: [("D", "typical_location", "Medical instruments are used primarily in an operating room during surgical procedures.")],
    7922: [("C", "typical_location", "A bowling alley commonly has seating behind the scoreboard where spectators watch indoor play.")],
    7923: [("A", "typical_location", "Food that must stay cold is commonly stored on a shelf inside a refrigerator.")],
    7924: [("A", "typical_location", "The Spanish phrase arbol de manzana for apple tree is heard in Spain.")],
    7925: [("B", "used_for", "Fresh fish brought home from a market can be used to make sushi.")],
    7926: [("B", "typical_location", "Most terrestrial snakes are not likely to spend time in open water.")],
    7927: [("E", "effect", "When people successfully learn a lesson they gain knowledge from the experience.")],
    7928: [("D", "typical_location", "A stationery store sells letter openers along with high-quality writing instruments.")],
    7929: [("B", "used_for", "Companies that work well together often decide to extend their working contract.")],
    7930: [("A", "property", "An exotic dress is unusual and attention-getting rather than plain.")],
    7931: [("C", "effect", "Reading a book about an unfamiliar topic helps you learn things about that subject.")],
    7932: [("E", "motivation", "A worried parent at a child's competition may be told to stop worrying.")],
    7933: [("E", "typical_location", "A living room commonly contains coffee tables for seating areas.")],
    7934: [("A", "property", "A puppy's fur often feels soft after it has been bathed and dried.")],
    7935: [("D", "typical_location", "A wine cellar is commonly built in a basement where it stays cool and dark.")],
    7936: [("A", "motivation", "House cats hovering by an exit are often ready to go outside.")],
    7937: [("B", "property", "Someone with bad posture rarely stands straight with proper alignment.")],
    7938: [("E", "typical_location", "A popular delicatessen is likely to be found in a large city.")],
    7939: [("C", "effect", "An archaeologist who recognizes fake artifacts may feel angry at the deception.")],
    7940: [("B", "used_for", "A construction manager briefing financiers is commonly updating them on building progress.")],
    7941: [("D", "typical_location", "If you need a mailbox and do not have one, you can obtain one at a post office.")],
    7942: [("C", "property", "A flirty person is commonly known for playful behavior toward others.")],
    7943: [("E", "typical_location", "People can buy junk food and play games at a carnival.")],
    7944: [("A", "typical_location", "Dairy products are commonly kept in a plastic container in the refrigerator.")],
    7945: [("B", "typical_location", "Drivers on a long trip commonly stop at a rest area to use the bathroom.")],
    7946: [("A", "cause", "An order to rise for a night strike is commonly given at sundown.")],
    7947: [("E", "typical_location", "To breathe while sleeping at home, air must be present inside the house.")],
    7948: [("B", "typical_location", "A steak house seeking a quaint setting may open in a small town.")],
    7949: [("E", "typical_location", "Pressing a button on a handle and taking a sip describes using a water fountain.")],
    7950: [("C", "effect", "Riding a horse at high speed for the first time commonly makes a beginner feel fear.")],
    7951: [("A", "cause", "Committing perjury while testifying under oath can result in jail time.")],
    7952: [("E", "typical_location", "If you run out of coffee at home you might borrow some from a friend's house.")],
    7953: [("A", "typical_location", "A pet fish is commonly kept in an aquarium rather than an open body of water.")],
    7954: [("D", "capability", "Someone who fiddles skillfully with small objects likely has good dexterity.")],
    7955: [("E", "typical_location", "On family road trips children commonly sit in the back seat of a car.")],
    7956: [("B", "motivation", "Some people avoid working in an office because it causes frustration.")],
    7957: [("A", "effect", "A doctor may recommend jogging to cause an increased heart rate during exercise.")],
    7958: [("B", "motivation", "To exercise regularly you often need to deliberately make time in your schedule.")],
    7959: [("E", "used_for", "A spectator at a movie theater is there to watch a show on the screen.")],
    7960: [("D", "used_for", "People who want to have fun may go swimming as a recreational activity.")],
    7961: [("B", "typical_location", "A tourniquet is commonly applied temporarily in an ambulance during emergency care.")],
    7962: [("A", "typical_location", "Important papers are commonly stored in a drawer for safekeeping.")],
    7963: [("C", "primary_function", "A vending machine can dispense food when you need a quick snack.")],
    7964: [("C", "used_for", "When household plumbing is broken you typically need to show the problem to a plumber.")],
    7965: [("D", "effect", "One immediate result of eating a meal is becoming full.")],
    7966: [("D", "typical_location", "A lit cigarette left unattended is commonly placed in an ashtray.")],
    7967: [("C", "typical_location", "A well-loved piece of furniture from college might be re-homed at a friend's house.")],
    7968: [("D", "effect", "Music can open a philosopher's thoughts and bring them closer to enlightenment.")],
    7969: [("D", "typical_location", "A human entering a condo is likely to be in a residential area.")],
    7970: [("C", "part_whole", "A dog with floppy ears is commonly petted on those soft ears.")],
    7971: [("A", "typical_location", "A condom for sex is commonly kept within reach on a bedside table.")],
    7972: [("E", "effect", "Someone very drunk who lies down on a bench may pass out afterward.")],
    7973: [("A", "typical_location", "New York City in America is widely known for its theaters.")],
    7974: [("A", "typical_location", "A student who does not understand triangles may take a class in trigonometry.")],
    7975: [("B", "effect", "On a warm day moisture that drops from clouds is rain water.")],
    7976: [("A", "effect", "On an average day going to work can leave a person feeling good about being productive.")],
    7977: [("B", "motivation", "When you feel cold your likely goal is to get warm.")],
    7978: [("C", "motivation", "People often do housework themselves because hiring help at low pay is not affordable.")],
    7979: [("E", "motivation", "Some people point a transistor radio toward the sky hoping to hear transmissions from a UFO.")],
    7980: [("E", "typical_location", "A small dog may ride in a basket instead of walking a long distance.")],
    7981: [("A", "typical_location", "An American weasel may live in wild areas such as Michigan.")],
    7982: [("B", "typical_location", "A real estate business can fail when buyers cannot obtain money to purchase property.")],
    7983: [("C", "motivation", "If you are bored sitting at a friend's home you should go somewhere else.")],
    7984: [("E", "used_for", "Creating art is one way people try to make money from their talents.")],
    7985: [("B", "effect", "A drunk person leaving a bar after closing may throw up from excessive drinking.")],
    7986: [("C", "typical_location", "Travelers who want to see the countryside may depart from a train station.")],
    7987: [("A", "effect", "If perjury evidence was obtained illegally the trial may end in a mistrial.")],
    7988: [("A", "has_prerequisite", "To ensure accuracy in a term paper you must do research on your topic.")],
    7989: [("E", "typical_location", "If you are thirsty you can drink from a water fountain connected to plumbing.")],
    7990: [("D", "used_for", "An intelligent person may choose to study Greek as an intellectual pursuit.")],
    7991: [("C", "property", "Someone with noble goals may still use ignoble methods to pursue them.")],
    7992: [("D", "typical_location", "Medical papers clipped together with a paper clip are commonly handled in a hospital.")],
    7993: [("C", "motivation", "A person whose family was destroyed may kill others out of vengeance.")],
    7994: [("E", "effect", "Repeated lies that cause problems may leave a person feeling guilty.")],
    7995: [("E", "used_for", "When someone is happy that you improved yourself they may invite you to celebrate.")],
    7996: [("A", "cause", "A soggy ceiling commonly suggests that the roof has a leak.")],
    7997: [("A", "typical_location", "If you need an armchair you would go to a furniture store to buy one.")],
    7998: [("E", "typical_location", "Kobe beef served at a steak house originates from Japan.")],
    7999: [("C", "property", "People going to a party are likely to be in a mood of happiness.")],
    8000: [("A", "motivation", "Many people want to get in shape so they can feel good about themselves.")],
    8001: [("C", "typical_location", "Horseradish is a tangy sauce that might drip onto furniture while eating.")],
    8002: [("D", "effect", "Committing murder commonly brings great sorrow to the murdered person's family.")],
    8003: [("C", "capability", "People who nearly drowned are convinced they will live when they begin to breathe again.")],
    8004: [("D", "typical_location", "A free-range cow farm supplying the Bay Area is likely in northern California.")],
    8005: [("B", "property", "A daughter who absolutely adores a pop band wants very much to see them perform.")],
    8006: [("B", "effect", "After people reproduce they commonly have children.")],
    8007: [("C", "typical_location", "Someone watching a Mardi Gras parade from a balcony is most likely in New Orleans.")],
    8008: [("B", "typical_location", "A talking bee is a fictional creature found in a story book.")],
    8009: [("B", "typical_location", "Michigan is a state that is likely to have a county highway.")],
    8010: [("E", "typical_location", "A small clock is commonly kept on a desk for easy time checking.")],
    8011: [("B", "property", "A statistician who wants more information about an attribute may seek a description.")],
    8012: [("D", "typical_location", "Tourists commonly see the Eiffel Tower while on a tour in Paris.")],
    8013: [("D", "typical_location", "Extra bathroom towels are commonly stored in a linen closet.")],
    8014: [("D", "typical_location", "A herding dog with ample room to run and play would love life on a farmyard.")],
    8015: [("B", "part_whole", "A cat's whiskers are characteristically long sensory hairs on its face.")],
    8016: [("A", "used_for", "Catholic people under stress may cross themselves as a religious gesture.")],
    8017: [("D", "primary_function", "A watering can is a handled tool used to make plants wet.")],
    8018: [("B", "typical_location", "A loose feather from a pet bird is commonly found in its bird cage.")],
    8019: [("C", "effect", "Eating breakfast helps start metabolism for the day ahead.")],
}
