# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7220-7319 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_7220_7319 = {
    7220: [("A", "property", "Being too square and too old suggests Jerry was likely in his fifties.")],
    7221: [("B", "effect", "A person who does good to others commonly garners admiration in their reputation.")],
    7222: [("D", "effect", "Exercising when stressed commonly helps a person feel relaxation afterward.")],
    7223: [("C", "effect", "When an unpopular change in how things are done occurs, the public often reacts with moral outrage.")],
    7224: [("D", "used_for", "Children commonly use cards to play games.")],
    7225: [("C", "typical_location", "A chimney is an unlikely place for footprints because people rarely walk there.")],
    7226: [("E", "motivation", "To see Prague a person would travel to Europe where the city is located.")],
    7227: [("D", "effect", "Garbage put into a landfill commonly begins to smell bad as it decomposes.")],
    7228: [("C", "effect", "Starting a car can set off an attached alarm or tracking device.")],
    7229: [("D", "typical_location", "A bowl of fruit on a table commonly holds grapes in a ceramic container.")],
    7230: [("A", "effect", "Drinking too much alcohol commonly causes headaches the next day.")],
    7231: [("E", "motivation", "Companies commonly respect customers who spend money on their products.")],
    7232: [("B", "property", "Shallow is the opposite of deep.")],
    7233: [("A", "typical_location", "A snake might drop from a tree where it was resting on branches.")],
    7234: [("A", "property", "Many republics have a form of government based on democracy.")],
    7235: [("D", "typical_location", "North Carolina in the eastern United States is known for barbecue rather than apple orchards.")],
    7236: [("B", "used_for", "Winding an old mechanical clock is how you reset and keep its time.")],
    7237: [("B", "typical_location", "A nightclub is a place where teenagers can go to hear music and be entertained.")],
    7238: [("A", "used_for", "Fencing around property provides protection for what is inside.")],
    7239: [("C", "effect", "A hurricane characteristically brings destruction to the areas it hits.")],
    7240: [("E", "used_for", "An incinerator destroys refuse so it no longer exists.")],
    7241: [("C", "effect", "A pilot who earns a medal for quick thinking likely handled a plane catching on fire.")],
    7242: [("B", "effect", "Flying off the rails is an idiom meaning things go badly like a train wreck.")],
    7243: [("D", "typical_location", "A concrete jungle is an urban area not known for apple trees.")],
    7244: [("E", "motivation", "If Billy wanted to return home, his mother telling him to go away would keep him from doing so.")],
    7245: [("C", "property", "Shark Tank is a popular reality television show.")],
    7246: [("C", "property", "A teacher may keep an eye on a student with a reputation for trouble even when he is being good.")],
    7247: [("B", "effect", "Without double spacing or line breaks it is hard to tell where one paragraph ends and the next begins.")],
    7248: [("A", "motivation", "People commonly try to avoid suffering pain.")],
    7249: [("A", "motivation", "Someone who rejects fate may believe people control events themselves.")],
    7250: [("E", "effect", "Jogging all day is likely to leave a person being tired.")],
    7251: [("B", "motivation", "When feeling lost, people often need someone to listen and make them feel understood.")],
    7252: [("D", "effect", "Hurting someone else can lead to a sense of bad karma even when one is not caught.")],
    7253: [("E", "motivation", "Some graduates choose not to keep attending school later because of much work.")],
    7254: [("C", "typical_location", "Discarded tin cans may remain in a landfill essentially forever because metal does not quickly decompose.")],
    7255: [("C", "effect", "A couple copulating repeatedly may eventually have babies as a result.")],
    7256: [("E", "motivation", "Choosing to fly in an airplane normally means you have to go far to your destination.")],
    7257: [("C", "typical_location", "A kitchen is not a place likely to organize items with a card catalog.")],
    7258: [("E", "effect", "Watching a horror movie might leave a person feeling fearful.")],
    7259: [("E", "typical_location", "A child can learn about the adventures of a talking monkey in a story book.")],
    7260: [("A", "property", "One hundred centavos make one Mexican peso.")],
    7261: [("E", "typical_location", "A mother deeply involved in schooling might aspire to be president of the PTA.")],
    7262: [("B", "used_for", "A sports fan commonly watches a sporting event.")],
    7263: [("E", "used_for", "Paying by phone instead of paper money removes the need to make physical change.")],
    7264: [("D", "typical_location", "Footprints form as an impression on the ground where someone walked.")],
    7265: [("C", "typical_location", "Many kinds of soup can be purchased at a supermarket.")],
    7266: [("B", "effect", "After cashing in from overtime a person might celebrate with unhealthy binge drinking.")],
    7267: [("E", "used_for", "After brewing coffee with hot water and grounds you pour it into a coffee cup.")],
    7268: [("E", "property", "Restaurant is another name for an eatery.")],
    7269: [("B", "typical_location", "Illness happens within a person's body.")],
    7270: [("B", "property", "A new world traveler from the homogeneous suburbs may be shocked by the plethora of food varieties abroad.")],
    7271: [("E", "primary_function", "A rotor that moves a lot of air enables a helicopter to lift straight up.")],
    7272: [("A", "motivation", "An artist may feel his work must evoke strong emotion rather than merely depict a picture.")],
    7273: [("E", "motivation", "A drive full of obstacles requires a driver to pay attention carefully.")],
    7274: [("E", "typical_location", "Birds seen above someone hiking in a desert were likely in the sky.")],
    7275: [("C", "property", "An expert may find a product first rate despite numerous bad public reviews.")],
    7276: [("E", "effect", "After an earthquake someone on the water should watch for tidal waves.")],
    7277: [("A", "used_for", "When experiencing boredom millennials commonly surf the net for entertainment.")],
    7278: [("A", "part_whole", "When a printer runs out of paper the IT staff commonly fetches another ream of paper.")],
    7279: [("E", "effect", "Over time people become old as they age.")],
    7280: [("A", "motivation", "A father tired of a lazy son would encourage hard work.")],
    7281: [("D", "typical_location", "A basement where children play is commonly found in one's own house.")],
    7282: [("B", "typical_location", "When not staying at home you keep your shirt packed in a suitcase.")],
    7283: [("B", "property", "Joyful is about as far as one can get from unhappy on the emotional spectrum.")],
    7284: [("A", "used_for", "Spending time with friends and acquaintances is called socializing.")],
    7285: [("A", "typical_location", "An actual wild weasel can be found in the great outdoors.")],
    7286: [("A", "effect", "Taking a phone call always involves communication between callers.")],
    7287: [("A", "effect", "Good sex commonly results in orgasm for the participants.")],
    7288: [("D", "effect", "Grooming oneself is known to increase satisfaction by boosting self-esteem.")],
    7289: [("D", "typical_location", "Delicate electronics like an iPod should not be taken near water.")],
    7290: [("E", "typical_location", "Someone looking for a job is likely to find a computer at a library.")],
    7291: [("E", "typical_location", "A bald eagle likes to fly over open country where it can hunt.")],
    7292: [("C", "effect", "A computer that stops working despite troubleshooting may have suffered a crash.")],
    7293: [("B", "effect", "Eating too much lunch too often can lead to obesity over time.")],
    7294: [("D", "motivation", "Susan might attend a KKK meeting without sharing its cause in order to get information.")],
    7295: [("B", "typical_location", "A fireplace is likely to serve as a heat source in a home.")],
    7296: [("E", "used_for", "Teaching can help someone who needs assistance with answering questions.")],
    7297: [("E", "effect", "Someone falling into broken glass would fear lacerations from the sharp glass.")],
    7298: [("C", "used_for", "Silk is used to make high quality garments such as clothing and gowns.")],
    7299: [("B", "motivation", "Enslaved workers were commonly forced to keep working even when one dropped dead.")],
    7300: [("D", "property", "Wood floats because it is less dense than water.")],
    7301: [("B", "used_for", "With dodge balls children commonly throw things at each other in games.")],
    7302: [("B", "effect", "Rock music that stirs strong emotions may evoke ardor in a listener.")],
    7303: [("C", "used_for", "Many animals eat plants as part of their diet.")],
    7304: [("C", "typical_location", "Despite being advertised as pet friendly an apartment complex may still refuse a small dog.")],
    7305: [("A", "property", "Water from a household faucet is commonly at room temperature.")],
    7306: [("C", "property", "The bald eagle serves as the national emblem of America.")],
    7307: [("D", "typical_location", "Someone who wants to be a star often moves to Hollywood.")],
    7308: [("D", "used_for", "A student sitting in a quiet classroom with paper in front of them is likely completing a test.")],
    7309: [("A", "motivation", "A father who goofs around when a child complains of boredom aims to entertain the child.")],
    7310: [("B", "effect", "Feeling pride looking at a report card suggests the student managed to pass class.")],
    7311: [("D", "typical_location", "People usually feel the most comfortable in their own house.")],
    7312: [("C", "typical_location", "A stereotypical bum like John often lives near a train station.")],
    7313: [("A", "typical_location", "A job is commonly done at a workplace.")],
    7314: [("B", "typical_location", "To keep jewelry safe in a hotel room a guest can use a safe deposit box.")],
    7315: [("A", "typical_location", "To legally obtain a new night table you would visit a furniture store.")],
    7316: [("C", "cause", "Attraction commonly causes people to initially begin flirting.")],
    7317: [("D", "has_prerequisite", "You must have money before you can go on vacation.")],
    7318: [("B", "typical_location", "John would go to an office supply store to buy a writing instrument and paperclips.")],
    7319: [("A", "typical_location", "A family owned barber shop is likely found in a neighborhood.")],
}
