# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 7020-7119 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_7020_7119 = {
    7020: [("C", "typical_location", "Rock musicians sometimes smash their guitars on stage at the end of a concert.")],
    7021: [("D", "typical_location", "An altar is commonly the focal point of a religious or formal ceremony.")],
    7022: [("A", "typical_location", "A drug dealer convicted of a felony is likely sent to prison.")],
    7023: [("D", "property", "Regular working out makes a person's muscles hard despite a gentle temperament.")],
    7024: [("B", "typical_location", "Famous pictures are commonly displayed for public viewing at an art show.")],
    7025: [("B", "used_for", "Gentlemen who need to talk commonly hold a meeting to discuss matters.")],
    7026: [("D", "has_prerequisite", "Combustion engines require oil for lubrication and proper operation.")],
    7027: [("E", "capability", "Jumping rope develops a sense of rhythm through timed bouncing.")],
    7028: [("D", "property", "Most modern farms operate as industrial agricultural businesses rather than small family plots.")],
    7029: [("A", "used_for", "A dog house shelters a puppy so it can sleep comfortably outside.")],
    7030: [("B", "typical_location", "Beavers are native to North America and are not found living wild in Australia.")],
    7031: [("B", "typical_location", "Watching men kick a black and white ball while drinking beer describes a soccer game.")],
    7032: [("D", "typical_location", "Vegetarian restaurants can be found in most cities around the world.")],
    7033: [("A", "effect", "When wind shifts from one heading to another, it changes direction.")],
    7034: [("A", "typical_location", "A military base commonly has guns and personnel in uniform.")],
    7035: [("D", "typical_location", "Sports equipment for an away game is brought into the arena where the team plays.")],
    7036: [("D", "part_whole", "A house commonly has a ground floor as its lowest level.")],
    7037: [("E", "typical_location", "A bee can get stuck easily while moving among flowers in a field of flowers.")],
    7038: [("D", "typical_location", "Dust accumulates over time in most buildings.")],
    7039: [("C", "typical_location", "California is known for mudslides, wildfires, earthquakes, and strict zoning codes.")],
    7040: [("D", "effect", "Ending a marriage to someone who takes everything may leave a person facing bankruptcy.")],
    7041: [("E", "motivation", "The biological purpose of eating breakfast is to gain energy for the day.")],
    7042: [("C", "used_for", "A farmer scoops eyes from potatoes to plant them in the ground.")],
    7043: [("B", "effect", "Regular jogging helps prevent heart attacks through cardiovascular exercise.")],
    7044: [("C", "typical_location", "Workers eat together at dining tables in a cafeteria at their workplace.")],
    7045: [("C", "typical_location", "A snake might hide inside a hollow log for shelter.")],
    7046: [("A", "typical_location", "A beaver on a Pacific beach is likely located in Washington state.")],
    7047: [("C", "typical_location", "Elephants originate from Africa, where they evolved and still live in the wild.")],
    7048: [("C", "property", "Music downloaded without paying for it has been stolen.")],
    7049: [("A", "typical_location", "A child is likely to keep a wagon in the backyard at home.")],
    7050: [("E", "primary_function", "A newspaper is a traditional way to inform the public about events.")],
    7051: [("D", "typical_location", "At a university, a residence hall is commonly called a dormitory.")],
    7052: [("E", "typical_location", "A gentleman may go to a restaurant to relax and enjoy a meal.")],
    7053: [("E", "effect", "A blind person cannot suffer eye strain from using a computer.")],
    7054: [("C", "property", "A zoo worker who is very well organized might be described as put together.")],
    7055: [("A", "typical_location", "A concert that requires passing through a ticket booth is held at a venue.")],
    7056: [("E", "motivation", "Nations explore all avenues to maintain peace and avoid war.")],
    7057: [("C", "effect", "Unprotected sex is likely to result in pregnancy.")],
    7058: [("D", "typical_location", "Air held down by gravity forms the atmosphere covering the surface of earth.")],
    7059: [("E", "typical_location", "A person keeps a night table in each of the homes they have lived in.")],
    7060: [("A", "motivation", "People form a line outside a hot-dog stand to wait their turn.")],
    7061: [("A", "part_whole", "Paperwork and research make up the bulk of a lawyer's work.")],
    7062: [("A", "motivation", "Being overweight commonly motivates a person to lose weight at the gym.")],
    7063: [("C", "typical_location", "Peanuts sold near a ferris wheel are being sold at a carnival.")],
    7064: [("C", "typical_location", "Drivers enter a grocery store parking lot from the street.")],
    7065: [("C", "property", "An awful bitter taste suggests that food has gone rotten.")],
    7066: [("C", "typical_location", "Environmental activists known as tree huggers are associated with San Francisco.")],
    7067: [("E", "effect", "Working out too hard when getting in shape commonly causes pain.")],
    7068: [("B", "motivation", "A cold and wet person should go back home to warm up and dry off.")],
    7069: [("B", "capability", "An ultrasound can reveal whether an unborn baby is a boy or girl.")],
    7070: [("E", "motivation", "Punishment is a common but harmful reason people hurt someone else.")],
    7071: [("C", "effect", "Blocking someone in a driveway means failing to move one's car out of the way.")],
    7072: [("B", "typical_location", "A gentleman might visit a church for social or spiritual gatherings.")],
    7073: [("C", "typical_location", "A windshield on a motorboat protects against spray and wind on the water.")],
    7074: [("B", "effect", "After heavy exercise the day before, a person commonly stretches upon waking.")],
    7075: [("B", "typical_location", "A policeman patrolling outdoors without stopping cars is likely on the street.")],
    7076: [("B", "typical_location", "A newspaper office employs many writers for a daily publication.")],
    7077: [("E", "effect", "A profound question from a teacher makes students stop and think.")],
    7078: [("B", "typical_location", "Top secret government facilities in New Mexico have hosted sensitive research programs.")],
    7079: [("A", "typical_location", "Audiences cheer for athletes at a sporting event.")],
    7080: [("A", "typical_location", "A nightclub in a prime downtown area location can thrive despite poor management.")],
    7081: [("D", "capability", "A television lets viewers take in audio as well as visual information.")],
    7082: [("A", "typical_location", "Chicago is widely known for its amazing pizzerias.")],
    7083: [("D", "used_for", "A tree offers shelter to people or animals in the woods.")],
    7084: [("E", "typical_location", "A koala that cannot find its usual haunts may make its home in a gum tree.")],
    7085: [("E", "used_for", "To dissolve a marriage through divorce, one should speak with a lawyer.")],
    7086: [("B", "typical_location", "A furnace is commonly located in the basement of a house.")],
    7087: [("E", "effect", "Kissing outside in cool weather can leave a person feeling cold.")],
    7088: [("C", "effect", "Eating too much without exercising enough commonly leads to obesity.")],
    7089: [("C", "typical_location", "Wine and cheese are served after viewing exhibits and installations at an art show.")],
    7090: [("C", "typical_location", "A tired traveler seeking accommodations may pull into a motel.")],
    7091: [("D", "typical_location", "A student is likely to use a notebook in the classroom.")],
    7092: [("D", "property", "A caregiver who is bad at her job is often indifferent to the needs of seniors.")],
    7093: [("D", "typical_location", "The professional Detroit Tigers play baseball in Detroit.")],
    7094: [("C", "property", "In architecture, all buildings refers collectively to structures in the built environment.")],
    7095: [("D", "motivation", "Lonely people often buy a cat to have company at home.")],
    7096: [("C", "used_for", "A leash is used to control a dog and stop it from biting nearby people.")],
    7097: [("C", "motivation", "Talking about bad behavior is the first step toward changing behavior.")],
    7098: [("E", "effect", "Drinking a lot of alcohol leads to drunkenness.")],
    7099: [("A", "effect", "Making something grow leads to growth over time.")],
    7100: [("A", "property", "Someone who appears calm but was up all night was likely anxious.")],
    7101: [("D", "motivation", "A person seeking a promotion at work wants to gain respect from colleagues.")],
    7102: [("A", "property", "An orthodox person contrasts with a roommate who is very liberal.")],
    7103: [("E", "typical_location", "Supplies for stringing a bass guitar are sold at a music shop.")],
    7104: [("D", "typical_location", "A personal telephone directory is commonly kept on a desk.")],
    7105: [("C", "part_whole", "A bone found in food probably belonged to a cow.")],
    7106: [("E", "effect", "When a patient is losing consciousness, death may seem inevitable to frantic medics.")],
    7107: [("E", "typical_location", "An apple tree standing alone is likely found in open fields.")],
    7108: [("E", "typical_location", "A patio is an outdoor space unlikely to have a doormat for wiping feet.")],
    7109: [("C", "typical_location", "During finals week a student may hang a do not disturb sign on a doorway.")],
    7110: [("E", "typical_location", "A dog that fetches the newspaper from the driveway lives in its own house.")],
    7111: [("C", "typical_location", "Day traders on the exchange floor often celebrate at a steak house in New York.")],
    7112: [("E", "capability", "Intelligence is key to a student's ability to learn effectively.")],
    7113: [("B", "used_for", "Careful thinking is the best way to understand a theory better.")],
    7114: [("C", "effect", "People commonly panic when facing a crisis.")],
    7115: [("C", "typical_location", "Students in school often stick gum under or around a water fountain.")],
    7116: [("B", "motivation", "A person who is not social may decide to stay home instead of attending a party.")],
    7117: [("C", "effect", "Focusing only on fighting inflation without other concerns can cause a recession.")],
    7118: [("E", "effect", "Children who like to play can easily have fun.")],
    7119: [("B", "effect", "A bridge blocks sunlight and casts a shadow on the ground below.")],
}
