# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 6220-6319 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6220_6319 = {
    6220: [("D", "typical_location", "A theater near home on a military base is commonly surrounded by servicemen.")],
    6221: [("B", "effect", "A pet abandoned at a shelter may join a new adoptive family.")],
    6222: [("C", "motivation", "Someone focused on the bottom line often wants to make money.")],
    6223: [("D", "property", "A motivational speaker may describe a disability as his greatest strength.")],
    6224: [("C", "effect", "When you are driving you are moving from place to place.")],
    6225: [("C", "used_for", "A written sex contract may specify consent before a partner performs oral acts.")],
    6226: [("E", "typical_location", "Two doors on opposite sides of a room are commonly at the front and back.")],
    6227: [("E", "typical_location", "When home electricity is cut off, people often go to a laundromat to wash clothes.")],
    6228: [("D", "property", "Wildly erratic results toward either end make the average result uncommon.")],
    6229: [("B", "has_prerequisite", "Learning a foreign language is difficult without exposure to that language.")],
    6230: [("D", "effect", "Answering questions that are not interesting commonly causes boredom.")],
    6231: [("E", "typical_location", "A shared living room helps a house feel like a home.")],
    6232: [("A", "part_whole", "If an aircraft hub is not tightened, the propeller assembly may come loose.")],
    6233: [("B", "typical_location", "A department store sells both clothing and household appliances.")],
    6234: [("B", "has_prerequisite", "A child learns to ride a bike without training wheels through practice.")],
    6235: [("C", "effect", "People may dislike machines that fail to work reliably.")],
    6236: [("D", "motivation", "Someone who feels being in love is vital may need it to live life fully.")],
    6237: [("A", "motivation", "Love often leads people to fully live life with commitment.")],
    6238: [("B", "typical_location", "An alto sax player trying to be heard over ruckus is often in a marching band.")],
    6239: [("C", "effect", "An unhappy person suffering greatly may attempt suicide to end pain.")],
    6240: [("B", "has_prerequisite", "Getting drunk requires the consumption of alcohol.")],
    6241: [("A", "effect", "Commentators discussing fighting inflation often mention raising interest rates.")],
    6242: [("E", "primary_function", "A soldier directed by a higher-status officer must follow orders.")],
    6243: [("D", "used_for", "A suit meant for outside water use is worn for swimming.")],
    6244: [("E", "motivation", "Someone very hungry may eat at almost anywhere besides McDonald's.")],
    6245: [("B", "typical_location", "Travelers sometimes leave baggage on a platform at a train station.")],
    6246: [("B", "typical_location", "A woman often stores a train ticket in her purse.")],
    6247: [("E", "effect", "Physical intimacy that begins with touch may lead a person toward pleasure.")],
    6248: [("E", "used_for", "Children who want to cool off on a hot day commonly go swimming.")],
    6249: [("E", "typical_location", "People often set screen savers showing sunshine on a desktop computer.")],
    6250: [("B", "effect", "Someone who cannot smile may still appear to frown even while doing acrobatics.")],
    6251: [("A", "typical_location", "Paying bills and registering to vote are services offered in a public building.")],
    6252: [("C", "typical_location", "After buying a telephone, people commonly place it on a desktop at home.")],
    6253: [("B", "effect", "After anger is talked down, a person is much more calm.")],
    6254: [("D", "effect", "Explicit fantasies during sleep in males can lead to erections.")],
    6255: [("C", "used_for", "A speaker commonly gives a demonstration when introducing a new product.")],
    6256: [("E", "property", "A very religious person may view ending a marriage as wrong.")],
    6257: [("C", "property", "Living with an uncle is different from how most families are arranged.")],
    6258: [("A", "used_for", "A human wears a wet suit when surfing in cold water.")],
    6259: [("E", "effect", "Spending money one does not have commonly leads to debt.")],
    6260: [("B", "part_whole", "A bearing contains small balls that help it rotate efficiently.")],
    6261: [("C", "typical_location", "Slippery moss from constant moisture is often found near a waterfall.")],
    6262: [("D", "cause", "Someone forced to labor for years without freedom may have endured slavery.")],
    6263: [("B", "typical_location", "Sears was a store that seemed to sell almost everything including sports equipment.")],
    6264: [("C", "typical_location", "A ferret can hide easily inside a wood pile.")],
    6265: [("E", "motivation", "In stories a cat may go to a castle to see the king.")],
    6266: [("B", "typical_location", "Kuwait and neighboring countries are located in the Middle East.")],
    6267: [("D", "property", "A real estate agent who oversells home features may always exaggerate.")],
    6268: [("D", "effect", "An insurance adjuster who finds a claim incorrect will deny it.")],
    6269: [("A", "part_whole", "A person has blood and parents as part of being human.")],
    6270: [("A", "effect", "A tired worker who has begun the day may respond by sitting down.")],
    6271: [("E", "typical_location", "Old scale models of vehicles such as boats are often made of wood.")],
    6272: [("C", "typical_location", "A map on an outside wall is commonly found at a highway rest area.")],
    6273: [("B", "typical_location", "Someone struggling up steep slopes may wish to be on flat ground.")],
    6274: [("B", "cause", "Asthma attacks are a common cause of difficulty in breathing.")],
    6275: [("B", "effect", "When snow on a mountain becomes heavy it can trigger avalanches.")],
    6276: [("E", "typical_location", "A spare wooden rod may be kept with cleaning supplies in a broom closet.")],
    6277: [("E", "motivation", "Catch-and-release fishing is often done to have fun without keeping fish.")],
    6278: [("B", "capability", "Bluebirds are known to sing songs.")],
    6279: [("E", "typical_location", "An altar in danger of vandalism should be placed in a sanctuary.")],
    6280: [("E", "effect", "When things fall apart an ongoing activity may stop.")],
    6281: [("E", "typical_location", "Tap dance practice on hard tile in a bathroom can make a lot of noise.")],
    6282: [("E", "effect", "Watching a horror film commonly causes a person to experience fear.")],
    6283: [("C", "effect", "Helping others is likely to give someone good feelings.")],
    6284: [("A", "typical_location", "A marmot is most commonly found in the wild.")],
    6285: [("D", "motivation", "Someone getting in shape typically wants to achieve good health.")],
    6286: [("A", "effect", "Playing games for a long time commonly leads to fatigue.")],
    6287: [("B", "typical_location", "People often ride bicycles beside canals in the Netherlands.")],
    6288: [("B", "effect", "A human who is smiling and whistling is likely in a good mood.")],
    6289: [("A", "used_for", "Beavers chew up trees in American forests to build dams.")],
    6290: [("C", "property", "Employer contributions to retirement plans are often optional rather than mandatory.")],
    6291: [("C", "effect", "A selfish person at a potluck may take food but not bring any.")],
    6292: [("C", "typical_location", "Bleachers full of hooligans with chants and smoke bombs describe a soccer game.")],
    6293: [("D", "motivation", "During meditation someone contemplating may strive for clear thought.")],
    6294: [("C", "typical_location", "A robin at the end of summer may be found in a bird's nest instead of as a blue egg.")],
    6295: [("E", "effect", "A lonely mentally disturbed person may begin to talk to himself for conversation.")],
    6296: [("A", "typical_location", "Cows commonly graze in a green field.")],
    6297: [("B", "typical_location", "Many homes and businesses are expected in a big city.")],
    6298: [("E", "typical_location", "A coworker who needs a pen may borrow one kept in a leather briefcase.")],
    6299: [("A", "effect", "A teacher may give punishment when a boy leaves line for disobeying orders.")],
    6300: [("B", "effect", "A sick boy receiving many supportive letters may feel happiness.")],
    6301: [("A", "typical_location", "A hermit's bedroom and kitchen are rooms in his dwelling on a hill.")],
    6302: [("A", "part_whole", "A landing is the flat area at the top of a stairwell you walk up.")],
    6303: [("A", "typical_location", "A tennis court at someone's home may be part of a country club membership.")],
    6304: [("D", "typical_location", "Washer and dryer sets are displayed in the showroom of an appliance store.")],
    6305: [("E", "primary_function", "A master of a trade is expected to teach all related skills.")],
    6306: [("B", "motivation", "Someone noticing skewed lines forming a trapezoid may be interested in geometry.")],
    6307: [("B", "cause", "Having rest usually means you worked all day or exerted yourself earlier.")],
    6308: [("D", "property", "Swiss cheese always has holes throughout the cheese.")],
    6309: [("D", "typical_location", "Steakhouses in Maine can offer fresh-caught lobster from nearby waters.")],
    6310: [("B", "cause", "Insomnia prevents someone from going to bed and falling asleep.")],
    6311: [("A", "motivation", "A child going out to play is likely hoping to have fun.")],
    6312: [("E", "effect", "Eating a light breakfast helps avoid going to work with a full stomach.")],
    6313: [("C", "effect", "A person who is dying may show skin that begins to change color.")],
    6314: [("D", "effect", "After people perform a concert the audience commonly responds with applause.")],
    6315: [("D", "effect", "A common biggest fear when opening a business is failure.")],
    6316: [("C", "effect", "Kissing outdoors in cold November weather may cause someone to catch cold.")],
    6317: [("C", "effect", "Someone who is learning will often end up knowing more over time.")],
    6318: [("D", "capability", "Plants that cannot move may reproduce asexually to continue their lineage.")],
    6319: [("B", "part_whole", "When reviewing photos a detective may struggle to pick a suspect out among many faces.")],
}
