# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 8620-8719 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_8620_8719 = {
    8620: [("A", "motivation", "Being tired is a common reason someone might not feel like starting to dance.")],
    8621: [("B", "used_for", "A photograph is a good way to preserve memories of a beloved pet after it is gone.")],
    8622: [("B", "typical_location", "A cold shark would likely seek warmer tropical waters.")],
    8623: [("C", "effect", "Working out and releasing energy all day commonly leads to exhaustion.")],
    8624: [("D", "typical_location", "Artillery refers to heavy weaponry that is stocked for military use.")],
    8625: [("E", "typical_location", "Florida has a long coastline along the Gulf of Mexico where condominiums are found.")],
    8626: [("B", "typical_location", "Lizards are commonly found living in sunny gardens.")],
    8627: [("A", "used_for", "A jogger wears headphones to listen to music from a device such as an iPod.")],
    8628: [("D", "primary_function", "An actor's job while performing is to pretend to be another character.")],
    8629: [("C", "typical_location", "A greenhouse commonly holds pots with living plants growing inside them.")],
    8630: [("E", "typical_location", "A shopping mall often has food kiosks and electronics stores that benefit from foot traffic.")],
    8631: [("E", "effect", "After being indoors all day, breathing fresh air commonly leaves a person feeling refreshed.")],
    8632: [("D", "effect", "After an excavation is finished, there is typically a pile of dirt left behind.")],
    8633: [("E", "effect", "Driving while sleep deprived can cause as many deadly accidents as driving while drunk.")],
    8634: [("A", "typical_location", "A colorful pebble that falls on a goldfish would be in an aquarium.")],
    8635: [("B", "has_prerequisite", "Before a child can be adopted, the biological parent must give away legal custody.")],
    8636: [("B", "property", "Skepticism is a mindset that can prevent someone from accepting something they want to believe.")],
    8637: [("D", "effect", "Skating is a physical activity that increases a person's heart rate.")],
    8638: [("C", "primary_function", "When someone does not reply to a question, they are ignoring it.")],
    8639: [("E", "cause", "Being restrained can prevent a person from walking forward.")],
    8640: [("A", "typical_location", "A stadium is primarily built for sports and is an unlikely place for a concert hall.")],
    8641: [("E", "typical_location", "A student who climbs out a window to avoid listening for an hour was likely in a classroom.")],
    8642: [("D", "typical_location", "An office supply store is where someone can buy more clipboards.")],
    8643: [("A", "effect", "A bedridden patient must be moved regularly to avoid developing bed sores.")],
    8644: [("B", "typical_location", "A cat prefers to relieve itself in a sand box or litter box.")],
    8645: [("D", "used_for", "A wooden rod bought for woodworking is kept to connect pieces of wood.")],
    8646: [("E", "effect", "Standing in a queue for a long time commonly leads to impatience.")],
    8647: [("D", "property", "Bacteria in water often form slimy colonies or films.")],
    8648: [("A", "typical_location", "Many households kept a telephone directory in the kitchen near stored food.")],
    8649: [("B", "typical_location", "An amusement park parking lot is typically full only during daytime visiting hours.")],
    8650: [("D", "typical_location", "To get a potato as close to the source as possible, one would go to a farmer's field.")],
    8651: [("A", "typical_location", "Unwanted advertisements are often delivered to a home through the mail box.")],
    8652: [("A", "property", "Someone not caught for killing another person would not have a conviction.")],
    8653: [("D", "typical_location", "Apple trees can commonly be found growing in the woods.")],
    8654: [("E", "typical_location", "A sofabed for overnight guests is commonly placed in a spare room.")],
    8655: [("B", "effect", "A speed bump is designed to cause vehicles to slow down.")],
    8656: [("B", "effect", "Listening to loud music over time can gradually cause a person to become deaf.")],
    8657: [("D", "motivation", "People often groom themselves in a mirror before leaving to look their best for beauty.")],
    8658: [("A", "primary_function", "A waiter waiting tables must listen to and serve customers.")],
    8659: [("A", "typical_location", "Someone checking emails might paste a favorite picture on their computer desktop.")],
    8660: [("C", "primary_function", "A cowboy is known for riding horses as part of ranch work.")],
    8661: [("D", "typical_location", "An amphitheatre traditionally provides a stage in an outdoor environment.")],
    8662: [("A", "property", "In a group where everyone is in a relationship except one person, that person is single.")],
    8663: [("B", "effect", "An anti-inflation bill may fail to force companies into lowering prices.")],
    8664: [("A", "typical_location", "Car manufacturing at a factory creates enough noise that workers wear earplugs.")],
    8665: [("E", "used_for", "People with mental health issues often need someone to talk to for support.")],
    8666: [("C", "typical_location", "During a harvest, potatoes are dug up one after another in a farmer's field.")],
    8667: [("D", "effect", "A beginner violinist quickly notices calluses developing on the fingers from pressing strings.")],
    8668: [("A", "effect", "Discovering a partner lied about seeing someone else commonly causes a broken heart.")],
    8669: [("D", "typical_location", "A funeral is the gathering of loved ones that follows a person's final birthday.")],
    8670: [("D", "effect", "A landmine is an explosive weapon that can kill innocents long after a war ends.")],
    8671: [("D", "typical_location", "A saucepan that is not in use is commonly stored in a kitchen cupboard.")],
    8672: [("E", "property", "Household stoves are commonly available in gas or electric types.")],
    8673: [("C", "typical_location", "A bench on a curb is typically found at a street corner.")],
    8674: [("D", "motivation", "People in love commonly buy presents for each other on birthdays.")],
    8675: [("C", "has_prerequisite", "Going for a long walk requires comfortable shoes.")],
    8676: [("E", "cause", "When a person hits their hand on something, their own carelessness or stupidity often caused it.")],
    8677: [("B", "primary_function", "A dog commonly communicates with another dog by barking.")],
    8678: [("A", "effect", "Staying in bed too long without moving can cause bedsores.")],
    8679: [("B", "part_whole", "A small group of three or four musicians playing together is called a band.")],
    8680: [("A", "typical_location", "A waterfall is a water feature with a pool at the bottom.")],
    8681: [("D", "effect", "Someone drunk who causes a public disturbance may be arrested for public intoxication.")],
    8682: [("A", "property", "An old man jumping rope would likely look silly to onlookers.")],
    8683: [("D", "property", "History is commonly classified into periods such as ancient, medieval, and modern.")],
    8684: [("D", "effect", "Falling on gravel while running can cause cuts that require stitches.")],
    8685: [("B", "typical_location", "A bald eagle often builds its nest on a high cliff that is hard to reach.")],
    8686: [("C", "primary_function", "When someone is typing, they are communicating through written text.")],
    8687: [("D", "part_whole", "Much like a bicycle, a chain on a motorbike drives the back wheel.")],
    8688: [("D", "effect", "When living beings are nervous, they commonly begin to perspire.")],
    8689: [("E", "typical_location", "Old clothes stored for later use are commonly kept down in the attic.")],
    8690: [("C", "effect", "A new grandmother often says a newborn grandchild brings joy to her life.")],
    8691: [("B", "effect", "Someone having a hard time writing a term paper is likely to feel frustration.")],
    8692: [("D", "typical_location", "A roadblock sign commonly causes a long line of cars to form behind it.")],
    8693: [("D", "used_for", "To make up hours lost at work, an employee may pick up extra shifts.")],
    8694: [("D", "typical_location", "A cable for electronics can be purchased at a store such as Radio Shack.")],
    8695: [("D", "used_for", "A driveway filled with snow must be cleared through shovelling.")],
    8696: [("D", "effect", "Someone having a heart attack may panic from fear of death.")],
    8697: [("A", "typical_location", "Marmosets are small primates usually found in rainforest habitats.")],
    8698: [("E", "typical_location", "A bus is a large over-the-road transport where passengers may choose a window seat.")],
    8699: [("C", "effect", "Cancer has the potential to spread through the body and result in death.")],
    8700: [("C", "capability", "Deep breathing techniques require great control over bringing air into the lungs.")],
    8701: [("B", "property", "Stockings are leg coverings for women commonly made of nylon.")],
    8702: [("C", "motivation", "After a long day, someone relaxing with a book wants to get comfortable.")],
    8703: [("E", "typical_location", "A church is a religious building found in nearly every town.")],
    8704: [("A", "typical_location", "Beer is commonly sold and consumed from a bottle as its medium container.")],
    8705: [("C", "typical_location", "An evening meal at a sit-down restaurant is typically served on a plate.")],
    8706: [("B", "typical_location", "A hotel passageway such as a lobby corridor is mainly used by visitors.")],
    8707: [("B", "typical_location", "Business calls on the phone most often take place in an office.")],
    8708: [("C", "typical_location", "A movie house is a place where people quietly eat popcorn while watching a film.")],
    8709: [("B", "primary_function", "A football coach begs a receiver who keeps dropping the ball to make a catch.")],
    8710: [("A", "typical_location", "A musician playing alone with no audience might be found at a subway station.")],
    8711: [("A", "property", "When commanding someone, you may need to know whether that person will obey.")],
    8712: [("A", "primary_function", "When Ryan answered the call, the person on the other end began to talk.")],
    8713: [("A", "used_for", "Knitting with a group of friends is a great way to enjoy relaxation.")],
    8714: [("B", "has_prerequisite", "To reach something on the other side of a body of water, people must cross the river.")],
    8715: [("B", "has_prerequisite", "Buying a house typically requires saving enough money for a down payment.")],
    8716: [("E", "typical_location", "Placing a coffee mug on a desktop risks ruining papers if the mug spills.")],
    8717: [("C", "cause", "A climber who suffers a brain injury most commonly got it from a falling accident.")],
    8718: [("E", "cause", "Doing housework can stir up dust and allergens that make a person sick with allergies.")],
    8719: [("D", "used_for", "A dictionary is where you can look up what an animal such as a lemur is.")],
}
