# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 9320-9419 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_9320_9419 = {
    9320: [("A", "used_for", "A judge passes sentence on a guilty party after a trial.")],
    9321: [("B", "motivation", "A go-getter who enjoys company often has a desire to advance.")],
    9322: [("A", "motivation", "Someone with empty cupboards must work to earn money for food.")],
    9323: [("E", "effect", "Watching a beloved dog die on screen commonly makes viewers cry.")],
    9324: [("E", "typical_location", "Sheep are exhibited at agricultural shows held at fairgrounds.")],
    9325: [("D", "effect", "Someone just starting work has not yet begun accomplishing tasks.")],
    9326: [("B", "property", "Creating an unusual animal like a platypus shows imagination.")],
    9327: [("E", "used_for", "Vinyl music is listened to by playing record albums.")],
    9328: [("B", "property", "Not every cat develops cancer during its lifetime.")],
    9329: [("D", "typical_location", "A book kept for bedtime reading is commonly placed on a bedside table.")],
    9330: [("C", "property", "Faith is often defined as belief held without complete knowledge.")],
    9331: [("C", "typical_location", "Stamp collections are commonly stored in a drawer at home.")],
    9332: [("D", "effect", "Chronic excessive drinking commonly leads to serious illness.")],
    9333: [("D", "property", "Someone unconcerned with small details may be described as carefree.")],
    9334: [("C", "motivation", "Listening to music is a common way to have fun.")],
    9335: [("B", "motivation", "A person who begins exercising often seeks to live well.")],
    9336: [("A", "used_for", "Learning every animal taxonomic name requires memorizing many names.")],
    9337: [("A", "property", "A fragile human body should be cared for because you only get one body.")],
    9338: [("B", "effect", "Parents worried about infant sleep safety fear sudden infant death.")],
    9339: [("E", "motivation", "People commonly use computers to achieve increased efficiency.")],
    9340: [("A", "effect", "Regularly eating oversized meals commonly causes a person to gain weight.")],
    9341: [("E", "typical_location", "Someone who answers phones and takes messages for a living works in an office.")],
    9342: [("D", "typical_location", "Highways connect cities such as San Diego, Omaha, and Atlanta across the United States.")],
    9343: [("E", "typical_location", "A waiting room often has many couches with people sitting on them.")],
    9344: [("E", "typical_location", "A person looking at an altar is likely standing in a temple.")],
    9345: [("E", "typical_location", "A home breaker box is commonly located in the basement.")],
    9346: [("C", "used_for", "Books require a light source to be read in the dark.")],
    9347: [("B", "typical_location", "A number is the usual answer to a math problem.")],
    9348: [("D", "effect", "Watching others play a game he once loved can stir feelings of longing.")],
    9349: [("A", "has_prerequisite", "Watching a film requires opening your eyes to see the screen.")],
    9350: [("A", "cause", "A car crash may leave someone unable to drive and prompt taking the bus.")],
    9351: [("A", "property", "Someone traveling in cold weather should stay warm.")],
    9352: [("D", "motivation", "Many people hope to fall in love with someone of the opposite sex.")],
    9353: [("E", "used_for", "Bringing home fish usually means you went fishing.")],
    9354: [("B", "typical_location", "Sports teams traditionally enter an arena through a central passage.")],
    9355: [("E", "effect", "Loving another person commonly brings happiness.")],
    9356: [("B", "effect", "Typing excessively for long periods can cause carpal tunnel syndrome.")],
    9357: [("B", "typical_location", "A crowded motorway is likely found in a city.")],
    9358: [("C", "effect", "A body commonly sweats after jogging.")],
    9359: [("D", "capability", "A throat injury can prevent someone from being able to make sound.")],
    9360: [("D", "cause", "A headache can stop someone from analysing information.")],
    9361: [("B", "typical_location", "Fabric is cut to order at a tailor shop.")],
    9362: [("E", "typical_location", "A dustbin in active use is commonly found in the kitchen.")],
    9363: [("B", "typical_location", "A grocery store has many shelves covered with food items.")],
    9364: [("C", "property", "Milk is plentiful in calcium, which helps bone development.")],
    9365: [("C", "typical_location", "A receptionist with a long commute likely lives far from the office park.")],
    9366: [("C", "effect", "A player should try to avoid injury while playing ball.")],
    9367: [("B", "typical_location", "Sugar can be found in nearly every home in a town.")],
    9368: [("D", "typical_location", "Revolving doors are commonly found in a hotel lobby.")],
    9369: [("E", "property", "The opposite of being dead is being alive.")],
    9370: [("B", "typical_location", "A small dog can compete in a dog show.")],
    9371: [("C", "typical_location", "A forgotten tuning fork can be retrieved from a music store.")],
    9372: [("A", "used_for", "A TV personality dressed as a weasel might play a children's song.")],
    9373: [("C", "typical_location", "A teakettle is a classic souvenir from merry old England.")],
    9374: [("E", "motivation", "Some people drink alcohol to seek relaxation.")],
    9375: [("E", "typical_location", "A bottle used to feed a newborn is commonly found in a nursery.")],
    9376: [("A", "typical_location", "A picture is commonly hung on a wall.")],
    9377: [("C", "property", "A parent may reassure a child that everyone is different.")],
    9378: [("B", "motivation", "A principal encouraging students to try hard wants them to do well.")],
    9379: [("E", "motivation", "A younger risky investor typically aims to gain wealth.")],
    9380: [("C", "property", "Someone wanting neither bad nor excellent service seeks adequate service.")],
    9381: [("D", "effect", "Long-term medication can allow a mental illness to be effectively treated.")],
    9382: [("D", "typical_location", "Buildings are likely to be small in a town.")],
    9383: [("E", "typical_location", "A beaver gathers dam-building materials in a wooded area.")],
    9384: [("C", "property", "A person working fourteen hours a day has very little spare time.")],
    9385: [("B", "used_for", "Piano is often taught as the best introduction to learn music.")],
    9386: [("A", "part_whole", "A stone found in the body that is not a kidney stone may be in the gallbladder.")],
    9387: [("C", "typical_location", "Small grapes are commonly found in wine country.")],
    9388: [("C", "used_for", "Someone bored and hungry may go grocery shopping.")],
    9389: [("A", "effect", "A vision experienced before bed may occur while falling asleep.")],
    9390: [("B", "typical_location", "Driving a road toward a river often passes through a valley.")],
    9391: [("E", "motivation", "An adult with a family often aims to own a home.")],
    9392: [("B", "property", "Wealth is often inferred from the valuable things a person owns.")],
    9393: [("C", "effect", "A stray dog may never recover from being abandoned.")],
    9394: [("A", "used_for", "A tired person can be refreshed by resting in bed.")],
    9395: [("E", "typical_location", "A pub sells alcohol and often serves food as well.")],
    9396: [("B", "typical_location", "A captured bald eagle spends the rest of its life in captivity.")],
    9397: [("C", "part_whole", "A control knob that switches channels is on a television.")],
    9398: [("B", "typical_location", "A comb kept near a mirror is often found in a medicine cabinet.")],
    9399: [("A", "typical_location", "A thoroughfare lined with skyscrapers runs through a city.")],
    9400: [("A", "effect", "Someone who stayed home from work for a week due to illness likely felt malaise.")],
    9401: [("D", "property", "Diving into the deep dark ocean is both dangerous and high risk.")],
    9402: [("A", "typical_location", "Saying king me is a checkers phrase, not used in a scrabble game.")],
    9403: [("A", "part_whole", "Painting only the lips on a canvas produces part of a human face.")],
    9404: [("A", "typical_location", "A government bureau may be in charge within the French government.")],
    9405: [("A", "property", "Someone already skinny may still feel compelled to lose more weight.")],
    9406: [("D", "typical_location", "A mammoth has never existed as a real animal in a movie.")],
    9407: [("C", "typical_location", "Food on a space shuttle is normally freeze dried or dehydrated.")],
    9408: [("A", "primary_function", "A container is something that holds food or other items.")],
    9409: [("E", "used_for", "An adult woman getting ready for work will dress herself.")],
    9410: [("B", "typical_location", "A strip mall seeking heavy traffic is often built in a city.")],
    9411: [("A", "used_for", "Someone may stop being a lover by choosing to distance themselves.")],
    9412: [("E", "typical_location", "A bathroom is wet and steamy right after a hot shower.")],
    9413: [("D", "has_prerequisite", "After finding the right shoe, a person still needs socks.")],
    9414: [("B", "typical_location", "Shareholders gather in a building to hold meetings.")],
    9415: [("C", "motivation", "People learn in order to increase knowledge.")],
    9416: [("B", "effect", "A creative person visiting a museum often gains inspiration.")],
    9417: [("B", "typical_location", "A nightclub is likely located in a downtown area.")],
    9418: [("A", "property", "The Blowfish, who make music for their lead singer, are a rock band.")],
    9419: [("E", "effect", "Spending a long time walking a dog commonly leads to tiredness.")],
}
