# -*- coding: utf-8 -*-
"""Batch: hand-authored rest KB for qids 6720-6819 (100 questions, 1 fact each)."""

KNOWLEDGE_REST_6720_6819 = {
    6720: [("C", "used_for", "A baseball bat is held by the handle when a player swings it in front of a watching crowd.")],
    6721: [("D", "typical_location", "Ann Arbor is a city in the state of Michigan.")],
    6722: [("B", "typical_location", "Birth control pills are commonly taken in the bedroom as part of a private routine.")],
    6723: [("B", "property", "Shopping local means preferring domestic goods over foreign products.")],
    6724: [("A", "effect", "Exercising continuously for three hours commonly causes exhaustion.")],
    6725: [("C", "motivation", "Studying the stock market can be a way to pursue wealth without physical labor or face-to-face sales.")],
    6726: [("C", "typical_location", "A man commonly keeps spare change in his pocket when he plans to spend it soon.")],
    6727: [("C", "has_prerequisite", "Remembering requires prior knowledge of the things being recalled.")],
    6728: [("A", "effect", "A highly elastic ball thrown at a wall will bounce back off the surface.")],
    6729: [("B", "effect", "A roller skater who loses balance and cannot recover will fall down.")],
    6730: [("E", "effect", "An active imagination commonly produces vivid wild dreams during sleep.")],
    6731: [("C", "typical_location", "A zoo typically keeps a lemur in a cage or enclosed habitat.")],
    6732: [("D", "typical_location", "A home spa is commonly installed in the backyard for privacy and access.")],
    6733: [("D", "primary_function", "A farmer's main goal is to raise crops on the land.")],
    6734: [("A", "property", "Preferring someone healthy rather than thick suggests a preference for a slim build.")],
    6735: [("C", "used_for", "Meditation is a practice people use to calm themselves into a trance-like state.")],
    6736: [("D", "cause", "Drunk driving after becoming inebriated can destroy a car in a crash.")],
    6737: [("A", "effect", "Getting drunk results in a state of intoxication.")],
    6738: [("B", "used_for", "Someone who loves horses commonly plays with them each time they visit a farm.")],
    6739: [("A", "typical_location", "A tissue is commonly kept in a pants pocket for convenient access.")],
    6740: [("E", "has_prerequisite", "Becoming like Michael Phelps requires learning to swim as a first step.")],
    6741: [("C", "typical_location", "A president commonly meets others and addresses the public at a press conference.")],
    6742: [("D", "typical_location", "Marmots use their hands to climb to the top of a rocky hillside in high places.")],
    6743: [("E", "effect", "Loving someone who does not love you back commonly causes heartache.")],
    6744: [("C", "typical_location", "A hardware store sells pails, nails, and hammers together.")],
    6745: [("A", "typical_location", "A blank sheet of paper ready for use commonly sits in a printer.")],
    6746: [("A", "capability", "Most lizards move by walking on four legs.")],
    6747: [("B", "typical_location", "A cat does not belong in a swimming pool because cats typically avoid water.")],
    6748: [("D", "typical_location", "A soccer stadium has rows of seats surrounding the playing court.")],
    6749: [("A", "motivation", "A failing student should try to achieve a better grade.")],
    6750: [("D", "typical_location", "A marmoset would be unable to breathe underground where air is limited.")],
    6751: [("E", "motivation", "A bodybuilder eats large amounts of food to gain weight and build muscle.")],
    6752: [("B", "used_for", "Clean clothes taken from the dryer are commonly folded before being put away.")],
    6753: [("B", "primary_function", "The intended biological function of sex is to reproduce.")],
    6754: [("D", "effect", "Snoring while resting can disturb and affect other people nearby.")],
    6755: [("B", "part_whole", "A shareholder owns a portion of a large company through their shares.")],
    6756: [("E", "used_for", "Most people in Canada converse by speaking English.")],
    6757: [("D", "typical_location", "Lemurs naturally live in a rain forest environment.")],
    6758: [("E", "has_prerequisite", "Returning to work requires getting out of bed as the first step of the day.")],
    6759: [("C", "effect", "Creating art commonly gives the artist a sense of pleasure.")],
    6760: [("A", "property", "Electric storms are most likely to occur during hot summer weather.")],
    6761: [("D", "typical_location", "Extra folding chairs for unexpected guests are commonly placed in a room of the house.")],
    6762: [("B", "capability", "A good musician with a keen ear picks up much more detail when they hear sounds.")],
    6763: [("E", "typical_location", "A cat often hesitates at the front door about whether to come in or go out.")],
    6764: [("B", "typical_location", "Without a shirt pocket, sunglasses are commonly carried in a bag.")],
    6765: [("D", "typical_location", "A museum gift shop commonly sells replicas of paintings on display.")],
    6766: [("B", "property", "The saying pairs inevitable taxes with death as equally unavoidable.")],
    6767: [("E", "typical_location", "A populated area is a bad place for a cemetery due to space and health concerns.")],
    6768: [("D", "capability", "Wendy believes she can repair her destroyed favorite toy rather than grieve.")],
    6769: [("B", "typical_location", "Protected forests are commonly found within national parks.")],
    6770: [("C", "used_for", "A dictionary is a reference book used to find the meaning of a word.")],
    6771: [("C", "typical_location", "Long-term storage boxes of old toys are commonly kept in the basement.")],
    6772: [("E", "typical_location", "A yo-yo can be purchased at a toy store.")],
    6773: [("B", "typical_location", "A clean plate is commonly put away in a kitchen cupboard.")],
    6774: [("A", "effect", "Family members of someone who committed suicide commonly feel deep sorrow.")],
    6775: [("D", "typical_location", "More than a drop of blood is commonly spilled on a battlefield.")],
    6776: [("D", "typical_location", "A saw not needed soon is commonly stored in a toolbox in a single-floor home.")],
    6777: [("B", "used_for", "Taking pictures is a common way to share memories of visiting a museum.")],
    6778: [("D", "typical_location", "New Hampshire is a state in the New England region where horses can be found.")],
    6779: [("C", "motivation", "People commonly listen to music for personal enjoyment.")],
    6780: [("B", "used_for", "China transports cargo by sea using very large boats.")],
    6781: [("E", "property", "Keeping lines tied tight means avoiding any slack in the rope.")],
    6782: [("C", "effect", "Confessing to a forgiving person commonly leaves the confessor feeling great relief.")],
    6783: [("E", "motivation", "A lazy person often watches television simply because they are bored.")],
    6784: [("E", "typical_location", "Hell and Christmas are small towns in Michigan connected by a bus route.")],
    6785: [("E", "used_for", "A lawyer may plan to produce evidence to engage a witness who has been difficult to locate.")],
    6786: [("B", "used_for", "People commonly kneel down while praying in addition to clasping their hands.")],
    6787: [("B", "property", "Special is commonly considered the opposite of ordinary.")],
    6788: [("A", "typical_location", "A screwdriver for home repairs is commonly found in a toolkit.")],
    6789: [("A", "used_for", "Saying wherever is a common reply when deferring a dinner choice to someone else.")],
    6790: [("B", "typical_location", "A very large amount of air is found at the surface of the earth in the atmosphere.")],
    6791: [("C", "typical_location", "An auditorium without students is commonly found in a theater venue.")],
    6792: [("C", "typical_location", "People go to zoos to see animals on display.")],
    6793: [("D", "used_for", "Rainwater collected in a large container is commonly used to water a garden.")],
    6794: [("B", "effect", "Having to obtain lunch at a restaurant results in spending money.")],
    6795: [("D", "used_for", "During discovery, a lawyer is required to produce evidence for the opposing side.")],
    6796: [("E", "effect", "Once work gets going, a person often works best when they have momentum.")],
    6797: [("B", "typical_location", "A beaver would not feel free inside a cage.")],
    6798: [("C", "typical_location", "A telephone booth almost always has a telephone book because a phone is right there.")],
    6799: [("E", "typical_location", "Gruber excavation is associated with Montana as its place of origin.")],
    6800: [("D", "effect", "Prolonged tickling causing dizziness and spinning can also lead to nausea.")],
    6801: [("B", "typical_location", "Because people die, graveyards are commonly found in every town.")],
    6802: [("B", "part_whole", "The spine is located in the back of the human body.")],
    6803: [("C", "effect", "Driving in heavy traffic commonly puts a person in a state of stress.")],
    6804: [("D", "effect", "After a tennis game has started, a match is underway.")],
    6805: [("D", "effect", "Getting drunk and crashing a car commonly results in injury.")],
    6806: [("B", "primary_function", "Maintaining rosebushes in a lawn is part of landscaping work.")],
    6807: [("A", "typical_location", "A yard commonly sits next to a driveway on a property.")],
    6808: [("C", "typical_location", "After a disaster preparedness video, people become conscious of door materials in a building.")],
    6809: [("D", "used_for", "Some people use love as part of choosing to procreate and start a family.")],
    6810: [("D", "typical_location", "Well-crafted Chesterfield furniture originates from Derbyshire in England.")],
    6811: [("C", "capability", "Making the right decision often requires a person to trust himself and his judgment.")],
    6812: [("C", "effect", "Most people aged nineteen have already completed high school.")],
    6813: [("C", "typical_location", "An apartment complex, a collection of small dwellings, normally has a nearby parking area.")],
    6814: [("E", "property", "Cuddling in bed after sex is a pleasant way to spend time with a loved one.")],
    6815: [("D", "effect", "After a good dance, a person is likely to say they are happy.")],
    6816: [("B", "typical_location", "A laboratory handling preserved specimens is equipped with cold storage.")],
    6817: [("A", "typical_location", "Someone without time to cook might go to restaurants for a baked potato.")],
    6818: [("D", "typical_location", "Shoppers leaving a department store commonly carry plastic bags from purchases.")],
    6819: [("B", "typical_location", "The president usually lays his head to rest at the White House.")],
}
